import 'package:dart2esm/src/diagnostics/unsupported_kernel_node.dart';
import 'package:dart2esm/src/pipeline/compiler_pipeline.dart';
import 'package:kernel/kernel.dart' as k;
import 'package:test/test.dart';

void main() {
  test('routes Kernel through explicit compiler stages', () {
    final libraryUri = Uri.parse('package:sample/main.dart');
    final library = k.Library(libraryUri, fileUri: libraryUri);
    final main = _procedure('main');
    library.addProcedure(main);
    final component = k.Component(libraries: [library]);
    component.setMainMethodAndMode(main.reference, true);

    final result = Dart2EsmCompilerPipeline(
      options: const Dart2EsmPipelineOptions(runMain: false),
    ).compile(component);

    expect(result.kernel.component, same(component));
    expect(result.kernel.main, same(main));
    expect(result.semantic.kernel, same(result.kernel));
    expect(result.semantic.model.component, same(component));
    expect(result.semantic.model.main, same(main));
    expect(result.codegen.code, same(result.code));
    expect(result.codegen.diagnostics, same(result.diagnostics));
    expect(result.code, contains('// Generated by dart2esm.'));
    expect(result.code, contains('export function main()'));
    expect(result.code, isNot(contains('main();')));
  });

  test('rejects components without a main method in the frontend stage', () {
    final pipeline = Dart2EsmCompilerPipeline(
      options: const Dart2EsmPipelineOptions(runMain: true),
    );

    expect(
      () => pipeline.compile(k.Component()),
      throwsA(isA<UnsupportedKernelNode>()),
    );
  });
}

k.Procedure _procedure(String name) {
  return k.Procedure(
    k.Name(name),
    k.ProcedureKind.Method,
    k.FunctionNode(k.Block([])),
    fileUri: Uri.parse('memory:$name.dart'),
    isStatic: true,
  );
}
