import 'dart:io';

import 'package:dart2esm/src/codegen/esm_codegen.dart';
import 'package:dart2esm/src/compiler.dart';
import 'package:dart2esm/src/component.dart';
import 'package:dart2esm/src/parser/kernel_parser.dart';
import 'package:dart2esm/src/ast/esm_ast.dart';
import 'package:dart2esm/src/lowering/kernel_to_esm_ast.dart';
import 'package:dart2esm/src/foundation/diagnostics/unsupported_compiler_feature.dart';
import 'package:dart2esm/src/transformer/helpers/helper_loader.dart';
import 'package:dart2esm/src/transformer/helpers/runtime_helpers.dart';
import 'package:dart2esm/src/semantic/semantic.dart';
import 'package:dart2esm/src/semantic/semantic_builder.dart';
import 'package:dart2esm/src/transformer/module_transformer.dart';
import 'package:dart2esm/src/foundation/diagnostics/unsupported_kernel_node.dart';
import 'package:kernel/kernel.dart' as k;
import 'package:test/test.dart';

void main() {
  test('compiler components expose the ordered component contract', () {
    expect(
      compilerComponentOrder,
      compilerComponentContracts.map((contract) => contract.id).toList(),
    );
    expect(compilerComponentContracts.map((contract) => contract.id), [
      CompilerComponentId.parser,
      CompilerComponentId.semantic,
      CompilerComponentId.lowerer,
      CompilerComponentId.transformer,
      CompilerComponentId.codegen,
    ]);
    expect(const KernelParser().parse, isA<Function>());
    expect(const SemanticBuilder().build, isA<Function>());
    expect(const Lowerer().lower, isA<Function>());
    expect(const Transformer().transform, isA<Function>());
    expect(const HelperLoader().load, isA<Function>());
    expect(const Codegen().generate, isA<Function>());
    expect(
      compilerComponentContractFor(CompilerComponentId.parser).output,
      'ParserReturn',
    );
    expect(
      compilerComponentContractFor(
        CompilerComponentId.lowerer,
      ).allowsRuntimeHelperReference,
      isTrue,
    );
    expect(
      compilerComponentContractFor(
        CompilerComponentId.codegen,
      ).allowsKernelAccess,
      isFalse,
    );
  });

  test('compiles supported Kernel through the compiler components', () {
    final libraryUri = Uri.parse('package:sample/main.dart');
    final library = k.Library(libraryUri, fileUri: libraryUri);
    final helperParameter = k.VariableDeclaration('value');
    final helper = _procedure(
      'helper',
      body: k.Block([k.ReturnStatement(k.VariableGet(helperParameter))]),
      positionalParameters: [helperParameter],
    );
    final message = k.VariableDeclaration(
      'message',
      initializer: k.StringLiteral('ok'),
      isFinal: true,
    );
    final main = _procedure(
      'main',
      body: k.Block([
        message,
        k.ExpressionStatement(
          k.StaticInvocation(helper, k.Arguments([k.VariableGet(message)])),
        ),
      ]),
    );
    library.addProcedure(helper);
    library.addProcedure(main);
    final component = k.Component(libraries: [library]);
    component.setMainMethodAndMode(main.reference, true);

    final result = Compiler(
      options: const CompilerOptions(runMain: true),
    ).compile(component);

    expect(result.completedComponents, compilerComponentOrder);
    expect(result.kernel.component, same(component));
    expect(result.semantic?.semantic.main, same(main));
    expect(result.lowering?.module.items, hasLength(3));
    expect(result.lowering?.runtimeHelpers, isEmpty);
    expect(result.transform?.lowering, same(result.lowering));
    expect(result.transform?.runtimeHelpers, isEmpty);
    expect(result.transform?.linkedHelpers, isEmpty);
    expect(result.transform?.invalidatesSemantic, isFalse);
    expect(result.codegen?.code, same(result.code));
    expect(result.code, '''
// Generated by dart2esm.

export function helper(value) {
  return value;
}

export function main() {
  const message = "ok";
  helper(message);
}

main();
''');
  });

  test('codegen parenthesizes expression callees', () {
    const module = EsmModule(
      items: [
        EsmExpressionStatement(
          EsmCall(
            callee: EsmArrowFunction(
              parameters: [EsmIdentifierParameter(name: 'value')],
              body: EsmIdentifier('value'),
            ),
            arguments: [EsmStringLiteral('ok')],
          ),
        ),
      ],
    );

    expect(const Codegen().generate(module).code, '''
// Generated by dart2esm.

((value) => value)("ok");
''');
  });

  test('codegen parenthesizes arrow functions in nullish coalescing', () {
    const module = EsmModule(
      items: [
        EsmExpressionStatement(
          EsmNullishCoalesce(
            left: EsmIdentifier('compare'),
            right: EsmArrowFunction(
              parameters: [
                EsmIdentifierParameter(name: 'left'),
                EsmIdentifierParameter(name: 'right'),
              ],
              body: EsmNumberLiteral(0),
            ),
          ),
        ),
      ],
    );

    expect(const Codegen().generate(module).code, '''
// Generated by dart2esm.

(compare ?? ((left, right) => 0));
''');
  });

  test('codegen emits arrow array binding parameters structurally', () {
    const module = EsmModule(
      items: [
        EsmExpressionStatement(
          EsmCall(
            callee: EsmArrowFunction(
              parameters: [
                EsmArrayPatternParameter(
                  elements: [
                    EsmIdentifierParameter(name: 'key'),
                    EsmIdentifierParameter(name: 'value'),
                  ],
                ),
              ],
              body: EsmIdentifier('key'),
            ),
            arguments: [
              EsmArrayLiteral([
                EsmStringLiteral('left'),
                EsmStringLiteral('right'),
              ]),
            ],
          ),
        ),
      ],
    );

    expect(const Codegen().generate(module).code, '''
// Generated by dart2esm.

(([key, value]) => key)(["left", "right"]);
''');
  });

  test('codegen emits object literal properties from key AST', () {
    const module = EsmModule(
      items: [
        EsmVariableDeclaration(
          binding: EsmIdentifierBinding('object'),
          mutable: false,
          initializer: EsmObjectLiteral([
            EsmObjectLiteralProperty(
              key: EsmStaticPropertyKey('alpha'),
              value: EsmNumberLiteral(1),
            ),
            EsmObjectLiteralProperty(
              key: EsmStaticPropertyKey('not-valid'),
              value: EsmNumberLiteral(2),
            ),
            EsmObjectLiteralProperty(
              key: EsmComputedPropertyKey(EsmIdentifier('dynamicKey')),
              value: EsmNumberLiteral(3),
            ),
          ]),
        ),
      ],
    );

    expect(const Codegen().generate(module).code, '''
// Generated by dart2esm.

const object = { alpha: 1, "not-valid": 2, [dynamicKey]: 3 };
''');
  });

  test('codegen emits variable declarations from binding AST', () {
    const module = EsmModule(
      items: [
        EsmVariableDeclaration(
          binding: EsmArrayBindingPattern(
            elements: [
              EsmIdentifierBinding('first'),
              EsmIdentifierBinding('second'),
            ],
          ),
          initializer: EsmIdentifier('pair'),
          mutable: false,
        ),
        EsmVariableDeclaration(
          binding: EsmObjectBindingPattern(
            bindings: [
              EsmObjectPatternBinding(
                property: 'alpha',
                name: 'value',
                defaultValue: EsmNumberLiteral(1),
              ),
            ],
          ),
          initializer: EsmIdentifier('source'),
          mutable: true,
        ),
      ],
    );

    expect(const Codegen().generate(module).code, '''
// Generated by dart2esm.

const [first, second] = pair;
let { alpha: value = 1 } = source;
''');
  });

  test('codegen preserves nested binary expression semantics', () {
    const module = EsmModule(
      items: [
        EsmFunction(
          name: 'main',
          export: true,
          parameters: [],
          body: [
            EsmVariableDeclaration(
              binding: EsmIdentifierBinding('value'),
              mutable: true,
              initializer: EsmNumberLiteral(10),
            ),
            EsmExpressionStatement(
              EsmAssignment(
                target: EsmIdentifier('value'),
                value: EsmBinary(
                  left: EsmIdentifier('value'),
                  operator: EsmBinaryOperator.subtract,
                  right: EsmBinary(
                    left: EsmIdentifier('oldPosition'),
                    operator: EsmBinaryOperator.subtract,
                    right: EsmIdentifier('newPosition'),
                  ),
                ),
              ),
            ),
          ],
        ),
      ],
    );

    expect(const Codegen().generate(module).code, '''
// Generated by dart2esm.

export function main() {
  let value = 10;
  value = value - (oldPosition - newPosition);
}
''');
  });

  test('codegen emits binary and unary operator AST', () {
    const module = EsmModule(
      items: [
        EsmExpressionStatement(
          EsmBinary(
            left: EsmUnary(
              operator: EsmUnaryOperator.typeOf,
              operand: EsmIdentifier('value'),
            ),
            operator: EsmBinaryOperator.strictEquals,
            right: EsmStringLiteral('string'),
          ),
        ),
        EsmExpressionStatement(
          EsmUnary(
            operator: EsmUnaryOperator.logicalNot,
            operand: EsmBinary(
              left: EsmIdentifier('value'),
              operator: EsmBinaryOperator.instanceOf,
              right: EsmIdentifier('Box'),
            ),
          ),
        ),
      ],
    );

    expect(const Codegen().generate(module).code, '''
// Generated by dart2esm.

typeof value === "string";
!(value instanceof Box);
''');
  });

  test('codegen emits import meta as a structured meta property', () {
    const module = EsmModule(
      items: [
        EsmExpressionStatement(
          EsmPropertyAccess(receiver: EsmImportMeta(), property: 'url'),
        ),
      ],
    );

    expect(const Codegen().generate(module).code, '''
// Generated by dart2esm.

import.meta.url;
''');
  });

  test('codegen emits class superclass as an expression', () {
    const module = EsmModule(
      items: [
        EsmClass(
          name: 'Derived',
          export: true,
          superclass: EsmCall(
            callee: EsmIdentifier('mixin'),
            arguments: [EsmIdentifier('Base')],
          ),
          constructor: null,
          methods: [],
        ),
      ],
    );

    expect(const Codegen().generate(module).code, '''
// Generated by dart2esm.

export class Derived extends mixin(Base) {
}
''');
  });

  test('codegen emits class method keys from property key AST', () {
    const module = EsmModule(
      items: [
        EsmClass(
          name: 'Box',
          export: true,
          superclass: null,
          constructor: null,
          methods: [
            EsmClassMethod(
              key: EsmStaticPropertyKey('not-valid'),
              kind: EsmClassMethodKind.method,
              isStatic: false,
              parameters: [],
              body: [],
            ),
            EsmClassMethod(
              key: EsmComputedPropertyKey(EsmIdentifier('dynamicKey')),
              kind: EsmClassMethodKind.method,
              isStatic: true,
              parameters: [],
              body: [],
            ),
          ],
        ),
      ],
    );

    expect(const Codegen().generate(module).code, '''
// Generated by dart2esm.

export class Box {
  "not-valid"() {
  }
  static [dynamicKey]() {
  }
}
''');
  });

  test('codegen emits catch parameters as binding AST', () {
    const module = EsmModule(
      items: [
        EsmTryStatement(
          body: [EsmThrowStatement(EsmStringLiteral('boom'))],
          catchParameter: EsmIdentifierParameter(name: 'error'),
          catchBody: [
            EsmExpressionStatement(
              EsmCall(
                callee: EsmIdentifier('handle'),
                arguments: [EsmIdentifier('error')],
              ),
            ),
          ],
          finallyBody: null,
        ),
      ],
    );

    expect(const Codegen().generate(module).code, '''
// Generated by dart2esm.

try {
  throw "boom";
} catch (error) {
  handle(error);
}
''');
  });

  test('module transformer prunes empty module artifacts', () {
    const marker = EsmExpressionStatement(
      EsmCall(callee: EsmIdentifier('sideEffect'), arguments: const []),
    );
    const module = EsmModule(
      items: [
        EsmRawModuleItem('  \n'),
        EsmBlockStatement([]),
        EsmFunction(
          name: 'main',
          export: true,
          parameters: [],
          body: [EsmBlockStatement([]), marker],
        ),
        EsmClass(
          name: 'Box',
          export: true,
          superclass: null,
          constructor: EsmClassConstructor(
            parameters: [],
            body: [EsmBlockStatement([])],
          ),
          methods: [
            EsmClassMethod(
              key: EsmStaticPropertyKey('read'),
              kind: EsmClassMethodKind.method,
              isStatic: false,
              parameters: [],
              body: [
                EsmBlockStatement([]),
                EsmReturnStatement(EsmNumberLiteral(1)),
              ],
            ),
          ],
        ),
      ],
    );

    final result = const Transformer().transform(_loweringForModule(module));

    expect(result.changed, isTrue);
    expect(result.invalidatesSemantic, isFalse);
    expect(result.module.items, hasLength(2));
    final main = result.module.items.first as EsmFunction;
    expect(main.body, hasLength(1));
    expect(main.body.single, same(marker));
    final box = result.module.items.last as EsmClass;
    expect(box.constructor?.body, isEmpty);
    expect(box.methods.single.body, [isA<EsmReturnStatement>()]);
  });

  test('helper loader resolves helper declarations before codegen', () {
    const module = EsmModule(
      items: [
        EsmFunction(
          name: 'main',
          export: true,
          parameters: [],
          body: [
            EsmExpressionStatement(
              EsmCall(
                callee: EsmIdentifier('__dartPrint'),
                arguments: [EsmStringLiteral('linked')],
              ),
            ),
          ],
        ),
      ],
    );

    final linked = const HelperLoader().load(
      module: module,
      helpers: const [EsmRuntimeHelper.print],
    );

    expect(linked.helpers, [
      EsmRuntimeHelper.print,
      EsmRuntimeHelper.stringify,
    ]);
    expect(linked.module.items, hasLength(3));
    final helper = linked.module.items.first;
    expect(helper, isA<EsmFunction>());
    expect((helper as EsmFunction).name, '__dartPrint');
    expect(helper.export, isFalse);
    expect(const Codegen().generate(linked.module).code, '''
// Generated by dart2esm.

function __dartPrint(value) {
  console.log(__dartStr(value));
}

function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}

export function main() {
  __dartPrint("linked");
}
''');
  });

  test('semantic reserves compiler-provided generated global names', () {
    final libraryUri = Uri.parse('package:sample/main.dart');
    final library = k.Library(libraryUri, fileUri: libraryUri);
    final helperCollision = k.Procedure(
      k.Name('__dartPrint', library),
      k.ProcedureKind.Method,
      k.FunctionNode(k.EmptyStatement()),
      fileUri: Uri.parse('memory:__dartPrint.dart'),
      isStatic: true,
    );
    final main = _procedure(
      'main',
      body: k.ExpressionStatement(
        k.StaticInvocation(helperCollision, k.Arguments([])),
      ),
    );
    library.addProcedure(helperCollision);
    library.addProcedure(main);
    final component = k.Component(libraries: [library]);
    component.setMainMethodAndMode(main.reference, true);

    final result = Compiler(
      options: const CompilerOptions(runMain: false),
    ).compile(component);

    final collisionSymbol = result.semantic!.semantic.symbolForRequired(
      helperCollision,
    );
    expect(collisionSymbol.name, '__dartPrint_1');
  });

  test('semantic folds anonymous mixin superclass edges', () {
    final libraryUri = Uri.parse('package:sample/main.dart');
    final library = k.Library(libraryUri, fileUri: libraryUri);
    final base = k.Class(name: 'Base', fileUri: libraryUri);
    final mixin = k.Class(name: 'Mixin', fileUri: libraryUri);
    final mixinMethod = k.Procedure(
      k.Name('label'),
      k.ProcedureKind.Method,
      k.FunctionNode(k.ReturnStatement(k.StringLiteral('mixin'))),
      fileUri: Uri.parse('memory:mixin_label.dart'),
    );
    final mixinApplication = k.Class(
      name: r'_Derived&Base&Mixin',
      isAnonymousMixin: true,
      supertype: k.Supertype(base, const []),
      mixedInType: k.Supertype(mixin, const []),
      fileUri: libraryUri,
    );
    mixinApplication.addProcedure(mixinMethod);
    final derived = k.Class(
      name: 'Derived',
      supertype: k.Supertype(mixinApplication, const []),
      fileUri: libraryUri,
    );
    final main = _procedure('main', body: k.EmptyStatement());
    library.addClass(base);
    library.addClass(mixin);
    library.addClass(mixinApplication);
    library.addClass(derived);
    library.addProcedure(main);
    final component = k.Component(libraries: [library]);
    component.setMainMethodAndMode(main.reference, true);

    final semantic = const SemanticBuilder().build(
      ParserReturn(component: component, main: main),
    );

    expect(
      semantic.semantic.classes.map((klass) => klass.node),
      isNot(contains(mixinApplication)),
    );
    final derivedSymbol = semantic.semantic.classSymbolFor(derived);
    expect(derivedSymbol, isNotNull);
    expect(derivedSymbol!.jsSuperclass, same(base));
    expect(derivedSymbol.interfaceMarkerClasses, contains(mixin));
    final loweredMixinMethod = semantic.semantic.instanceProcedureSymbolFor(
      mixinMethod,
    );
    expect(loweredMixinMethod, isNotNull);
    expect(loweredMixinMethod!.name, 'label');
    expect(loweredMixinMethod.emit, isTrue);
    expect(derivedSymbol.procedures, contains(same(loweredMixinMethod)));
  });

  test('compiles switch continue through the compiler components', () async {
    final result = Compiler(
      options: const CompilerOptions(runMain: false),
    ).compile(_componentWithSwitchContinue());

    expect(result.completedComponents, compilerComponentOrder);

    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm_compiler_test_',
    );
    addTearDown(() => tempDir.delete(recursive: true));

    File('${tempDir.path}/main.mjs').writeAsStringSync(result.code);
    final consumer = File('${tempDir.path}/consumer.mjs')
      ..writeAsStringSync('''
import { main } from './main.mjs';
console.log(main());
''');
    final nodeResult = await Process.run('node', [consumer.path]);

    expect(
      nodeResult.exitCode,
      0,
      reason: '${nodeResult.stdout}\n${nodeResult.stderr}',
    );
    expect(nodeResult.stdout, 'target\n');
    expect(nodeResult.stderr, isEmpty);
  });

  test('rejects unsupported Kernel in the compiler components', () {
    final component = _componentWithYieldStatement();

    final compiler = Compiler(options: const CompilerOptions(runMain: true));

    expect(
      () => compiler.compile(component),
      throwsA(isA<UnsupportedCompilerFeature>()),
    );
  });

  test('rejects components without a main method in the parser component', () {
    final compiler = Compiler(options: const CompilerOptions(runMain: true));

    expect(
      () => compiler.compile(k.Component()),
      throwsA(isA<UnsupportedKernelNode>()),
    );
  });
}

k.Component _componentWithSwitchContinue() {
  final libraryUri = Uri.parse('package:sample/main.dart');
  final library = k.Library(libraryUri, fileUri: libraryUri);
  final result = k.VariableDeclaration(
    'result',
    initializer: k.StringLiteral('start'),
  );
  final target = k.SwitchCase(
    [k.IntLiteral(0)],
    [k.TreeNode.noOffset],
    k.ExpressionStatement(k.VariableSet(result, k.StringLiteral('target'))),
  );
  final main = _procedure(
    'main',
    body: k.Block([
      result,
      k.SwitchStatement(k.IntLiteral(1), [
        target,
        k.SwitchCase(
          [k.IntLiteral(1)],
          [k.TreeNode.noOffset],
          k.Block([k.ContinueSwitchStatement(target)]),
        ),
      ]),
      k.ReturnStatement(k.VariableGet(result)),
    ]),
  );
  library.addProcedure(main);
  final component = k.Component(libraries: [library]);
  component.setMainMethodAndMode(main.reference, true);
  return component;
}

k.Component _componentWithYieldStatement() {
  final libraryUri = Uri.parse('package:sample/main.dart');
  final library = k.Library(libraryUri, fileUri: libraryUri);
  final main = _procedure(
    'main',
    body: k.Block([k.YieldStatement(k.IntLiteral(1))]),
  );
  library.addProcedure(main);
  final component = k.Component(libraries: [library]);
  component.setMainMethodAndMode(main.reference, true);
  return component;
}

k.Procedure _procedure(
  String name, {
  required k.Statement body,
  List<k.VariableDeclaration> positionalParameters = const [],
}) {
  return k.Procedure(
    k.Name(name),
    k.ProcedureKind.Method,
    k.FunctionNode(body, positionalParameters: positionalParameters),
    fileUri: Uri.parse('memory:$name.dart'),
    isStatic: true,
  );
}

LowererReturn _loweringForModule(
  EsmModule module, {
  Iterable<EsmRuntimeHelper> runtimeHelpers = const [],
}) {
  final libraryUri = Uri.parse('package:sample/main.dart');
  final library = k.Library(libraryUri, fileUri: libraryUri);
  final main = _procedure('main', body: k.EmptyStatement());
  library.addProcedure(main);
  final component = k.Component(libraries: [library]);
  component.setMainMethodAndMode(main.reference, true);
  final kernel = ParserReturn(component: component, main: main);
  final semantic = SemanticBuilderReturn(
    kernel: kernel,
    semantic: Semantic(
      component: component,
      main: main,
      classes: const [],
      extensionTypes: const [],
      fields: const [],
      procedures: [
        EsmProcedureSymbol(
          node: main,
          name: 'main',
          export: true,
          kind: EsmProcedureKind.method,
        ),
      ],
    ),
  );
  return LowererReturn(
    semantic: semantic,
    items: module.items,
    runtimeHelpers: runtimeHelpers,
  );
}
