import 'package:dart2esm/src/compiler/codegen/esm_codegen.dart';
import 'package:dart2esm/src/compiler/pipeline.dart';
import 'package:dart2esm/src/compiler/stage.dart';
import 'package:dart2esm/src/compiler/frontend/kernel_frontend.dart';
import 'package:dart2esm/src/compiler/ir_builder/esm_ir_builder.dart';
import 'package:dart2esm/src/compiler/ir/esm_ir.dart';
import 'package:dart2esm/src/compiler/lowering/kernel_to_esm_ir.dart';
import 'package:dart2esm/src/compiler/unsupported.dart';
import 'package:dart2esm/src/compiler/runtime/runtime_helpers.dart';
import 'package:dart2esm/src/compiler/runtime/runtime_linker.dart';
import 'package:dart2esm/src/compiler/semantic/semantic_world.dart';
import 'package:dart2esm/src/compiler/transform/module_normalizer.dart';
import 'package:dart2esm/src/foundation/diagnostics/unsupported_kernel_node.dart';
import 'package:kernel/kernel.dart' as k;
import 'package:test/test.dart';

void main() {
  test('compiler core exposes the ordered stage contract', () {
    expect(
      dart2EsmCompilerStageOrder,
      dart2EsmCompilerStageContracts
          .map((contract) => contract.stageId)
          .toList(),
    );
    expect(dart2EsmCompilerStageContracts.map((contract) => contract.stageId), [
      Dart2EsmCompilerStageId.kernelFrontend,
      Dart2EsmCompilerStageId.semanticWorld,
      Dart2EsmCompilerStageId.dartLowering,
      Dart2EsmCompilerStageId.esmIrBuilder,
      Dart2EsmCompilerStageId.moduleNormalizer,
      Dart2EsmCompilerStageId.runtimeLinker,
      Dart2EsmCompilerStageId.esmCodegen,
    ]);
    expect(const KernelFrontendStage().stageId, dart2EsmCompilerStageOrder[0]);
    expect(const SemanticWorldStage().stageId, dart2EsmCompilerStageOrder[1]);
    expect(
      const KernelToEsmIrLoweringStage().stageId,
      dart2EsmCompilerStageOrder[2],
    );
    expect(const EsmIrBuilderStage().stageId, dart2EsmCompilerStageOrder[3]);
    expect(
      const ModuleNormalizerStage().stageId,
      dart2EsmCompilerStageOrder[4],
    );
    expect(const RuntimeLinkerStage().stageId, dart2EsmCompilerStageOrder[5]);
    expect(const EsmCodegenStage().stageId, dart2EsmCompilerStageOrder[6]);
    expect(
      dart2EsmStageContractFor(Dart2EsmCompilerStageId.kernelFrontend).output,
      'KernelFrontendResult',
    );
    expect(
      dart2EsmStageContractFor(
        Dart2EsmCompilerStageId.dartLowering,
      ).allowsRuntimeHelperReference,
      isTrue,
    );
    expect(
      dart2EsmStageContractFor(
        Dart2EsmCompilerStageId.esmCodegen,
      ).allowsKernelAccess,
      isFalse,
    );
  });

  test('compiles supported Kernel through the new compiler core', () {
    final libraryUri = Uri.parse('package:sample/main.dart');
    final library = k.Library(libraryUri, fileUri: libraryUri);
    final helperParameter = k.VariableDeclaration('value');
    final helper = _procedure(
      'helper',
      body: k.Block([k.ReturnStatement(k.VariableGet(helperParameter))]),
      positionalParameters: [helperParameter],
    );
    final message = k.VariableDeclaration(
      'message',
      initializer: k.StringLiteral('ok'),
      isFinal: true,
    );
    final main = _procedure(
      'main',
      body: k.Block([
        message,
        k.ExpressionStatement(
          k.StaticInvocation(helper, k.Arguments([k.VariableGet(message)])),
        ),
      ]),
    );
    library.addProcedure(helper);
    library.addProcedure(main);
    final component = k.Component(libraries: [library]);
    component.setMainMethodAndMode(main.reference, true);

    final result = Dart2EsmCompilerPipeline(
      options: const Dart2EsmPipelineOptions(runMain: true),
    ).compile(component);

    expect(result.completedStages, dart2EsmCompilerStageOrder);
    expect(result.kernel.component, same(component));
    expect(result.semantic?.world.main, same(main));
    expect(result.lowering?.items, hasLength(3));
    expect(result.irBuild?.module.items, hasLength(3));
    expect(result.lowering?.runtimeHelpers, isEmpty);
    expect(result.irBuild?.runtimeHelpers, isEmpty);
    expect(result.normalization?.irBuild, same(result.irBuild));
    expect(result.normalization?.runtimeHelpers, isEmpty);
    expect(result.normalization?.invalidatesSemanticWorld, isFalse);
    expect(result.runtime?.linkedHelpers, isEmpty);
    expect(result.codegen?.code, same(result.code));
    expect(result.code, '''
// Generated by dart2esm.

export function helper(value) {
  return value;
}

export function main() {
  const message = "ok";
  helper(message);
}

main();
''');
  });

  test('codegen parenthesizes expression callees', () {
    const module = EsmModuleIr(
      items: [
        EsmExpressionStatementIr(
          EsmCallIr(
            callee: EsmArrowFunctionIr(
              parameters: [EsmIdentifierParameterIr(name: 'value')],
              body: EsmIdentifierIr('value'),
            ),
            arguments: [EsmStringLiteralIr('ok')],
          ),
        ),
      ],
    );

    expect(const EsmCodegenStage().emit(module).code, '''
// Generated by dart2esm.

((value) => value)("ok");
''');
  });

  test('codegen parenthesizes arrow functions in nullish coalescing', () {
    const module = EsmModuleIr(
      items: [
        EsmExpressionStatementIr(
          EsmNullishCoalesceIr(
            left: EsmIdentifierIr('compare'),
            right: EsmArrowFunctionIr(
              parameters: [
                EsmIdentifierParameterIr(name: 'left'),
                EsmIdentifierParameterIr(name: 'right'),
              ],
              body: EsmNumberLiteralIr(0),
            ),
          ),
        ),
      ],
    );

    expect(const EsmCodegenStage().emit(module).code, '''
// Generated by dart2esm.

(compare ?? ((left, right) => 0));
''');
  });

  test('codegen emits arrow array binding parameters structurally', () {
    const module = EsmModuleIr(
      items: [
        EsmExpressionStatementIr(
          EsmCallIr(
            callee: EsmArrowFunctionIr(
              parameters: [
                EsmArrayPatternParameterIr(
                  elements: [
                    EsmIdentifierParameterIr(name: 'key'),
                    EsmIdentifierParameterIr(name: 'value'),
                  ],
                ),
              ],
              body: EsmIdentifierIr('key'),
            ),
            arguments: [
              EsmArrayLiteralIr([
                EsmStringLiteralIr('left'),
                EsmStringLiteralIr('right'),
              ]),
            ],
          ),
        ),
      ],
    );

    expect(const EsmCodegenStage().emit(module).code, '''
// Generated by dart2esm.

(([key, value]) => key)(["left", "right"]);
''');
  });

  test('codegen emits object literal properties from key IR', () {
    const module = EsmModuleIr(
      items: [
        EsmVariableDeclarationIr(
          binding: EsmIdentifierBindingIr('object'),
          mutable: false,
          initializer: EsmObjectLiteralIr([
            EsmObjectLiteralPropertyIr(
              key: EsmStaticPropertyKeyIr('alpha'),
              value: EsmNumberLiteralIr(1),
            ),
            EsmObjectLiteralPropertyIr(
              key: EsmStaticPropertyKeyIr('not-valid'),
              value: EsmNumberLiteralIr(2),
            ),
            EsmObjectLiteralPropertyIr(
              key: EsmComputedPropertyKeyIr(EsmIdentifierIr('dynamicKey')),
              value: EsmNumberLiteralIr(3),
            ),
          ]),
        ),
      ],
    );

    expect(const EsmCodegenStage().emit(module).code, '''
// Generated by dart2esm.

const object = { alpha: 1, "not-valid": 2, [dynamicKey]: 3 };
''');
  });

  test('codegen emits variable declarations from binding IR', () {
    const module = EsmModuleIr(
      items: [
        EsmVariableDeclarationIr(
          binding: EsmArrayBindingPatternIr(
            elements: [
              EsmIdentifierBindingIr('first'),
              EsmIdentifierBindingIr('second'),
            ],
          ),
          initializer: EsmIdentifierIr('pair'),
          mutable: false,
        ),
        EsmVariableDeclarationIr(
          binding: EsmObjectBindingPatternIr(
            bindings: [
              EsmObjectPatternBindingIr(
                property: 'alpha',
                name: 'value',
                defaultValue: EsmNumberLiteralIr(1),
              ),
            ],
          ),
          initializer: EsmIdentifierIr('source'),
          mutable: true,
        ),
      ],
    );

    expect(const EsmCodegenStage().emit(module).code, '''
// Generated by dart2esm.

const [first, second] = pair;
let { alpha: value = 1 } = source;
''');
  });

  test('codegen preserves nested binary expression semantics', () {
    const module = EsmModuleIr(
      items: [
        EsmFunctionIr(
          name: 'main',
          export: true,
          parameters: [],
          body: [
            EsmVariableDeclarationIr(
              binding: EsmIdentifierBindingIr('value'),
              mutable: true,
              initializer: EsmNumberLiteralIr(10),
            ),
            EsmExpressionStatementIr(
              EsmAssignmentIr(
                target: EsmIdentifierIr('value'),
                value: EsmBinaryIr(
                  left: EsmIdentifierIr('value'),
                  operator: EsmBinaryOperatorIr.subtract,
                  right: EsmBinaryIr(
                    left: EsmIdentifierIr('oldPosition'),
                    operator: EsmBinaryOperatorIr.subtract,
                    right: EsmIdentifierIr('newPosition'),
                  ),
                ),
              ),
            ),
          ],
        ),
      ],
    );

    expect(const EsmCodegenStage().emit(module).code, '''
// Generated by dart2esm.

export function main() {
  let value = 10;
  value = value - (oldPosition - newPosition);
}
''');
  });

  test('codegen emits binary and unary operator IR', () {
    const module = EsmModuleIr(
      items: [
        EsmExpressionStatementIr(
          EsmBinaryIr(
            left: EsmUnaryIr(
              operator: EsmUnaryOperatorIr.typeOf,
              operand: EsmIdentifierIr('value'),
            ),
            operator: EsmBinaryOperatorIr.strictEquals,
            right: EsmStringLiteralIr('string'),
          ),
        ),
        EsmExpressionStatementIr(
          EsmUnaryIr(
            operator: EsmUnaryOperatorIr.logicalNot,
            operand: EsmBinaryIr(
              left: EsmIdentifierIr('value'),
              operator: EsmBinaryOperatorIr.instanceOf,
              right: EsmIdentifierIr('Box'),
            ),
          ),
        ),
      ],
    );

    expect(const EsmCodegenStage().emit(module).code, '''
// Generated by dart2esm.

typeof value === "string";
!(value instanceof Box);
''');
  });

  test('codegen emits import meta as a structured meta property', () {
    const module = EsmModuleIr(
      items: [
        EsmExpressionStatementIr(
          EsmPropertyAccessIr(receiver: EsmImportMetaIr(), property: 'url'),
        ),
      ],
    );

    expect(const EsmCodegenStage().emit(module).code, '''
// Generated by dart2esm.

import.meta.url;
''');
  });

  test('codegen emits class superclass as an expression', () {
    const module = EsmModuleIr(
      items: [
        EsmClassIr(
          name: 'Derived',
          export: true,
          superclass: EsmCallIr(
            callee: EsmIdentifierIr('mixin'),
            arguments: [EsmIdentifierIr('Base')],
          ),
          constructor: null,
          methods: [],
        ),
      ],
    );

    expect(const EsmCodegenStage().emit(module).code, '''
// Generated by dart2esm.

export class Derived extends mixin(Base) {
}
''');
  });

  test('codegen emits class method keys from property key IR', () {
    const module = EsmModuleIr(
      items: [
        EsmClassIr(
          name: 'Box',
          export: true,
          superclass: null,
          constructor: null,
          methods: [
            EsmClassMethodIr(
              key: EsmStaticPropertyKeyIr('not-valid'),
              kind: EsmClassMethodKindIr.method,
              isStatic: false,
              parameters: [],
              body: [],
            ),
            EsmClassMethodIr(
              key: EsmComputedPropertyKeyIr(EsmIdentifierIr('dynamicKey')),
              kind: EsmClassMethodKindIr.method,
              isStatic: true,
              parameters: [],
              body: [],
            ),
          ],
        ),
      ],
    );

    expect(const EsmCodegenStage().emit(module).code, '''
// Generated by dart2esm.

export class Box {
  "not-valid"() {
  }
  static [dynamicKey]() {
  }
}
''');
  });

  test('codegen emits catch parameters as binding IR', () {
    const module = EsmModuleIr(
      items: [
        EsmTryStatementIr(
          body: [EsmThrowStatementIr(EsmStringLiteralIr('boom'))],
          catchParameter: EsmIdentifierParameterIr(name: 'error'),
          catchBody: [
            EsmExpressionStatementIr(
              EsmCallIr(
                callee: EsmIdentifierIr('handle'),
                arguments: [EsmIdentifierIr('error')],
              ),
            ),
          ],
          finallyBody: null,
        ),
      ],
    );

    expect(const EsmCodegenStage().emit(module).code, '''
// Generated by dart2esm.

try {
  throw "boom";
} catch (error) {
  handle(error);
}
''');
  });

  test('module normalizer prunes empty module artifacts', () {
    const marker = EsmExpressionStatementIr(
      EsmCallIr(callee: EsmIdentifierIr('sideEffect'), arguments: const []),
    );
    const module = EsmModuleIr(
      items: [
        EsmRawModuleItemIr('  \n'),
        EsmBlockStatementIr([]),
        EsmFunctionIr(
          name: 'main',
          export: true,
          parameters: [],
          body: [EsmBlockStatementIr([]), marker],
        ),
        EsmClassIr(
          name: 'Box',
          export: true,
          superclass: null,
          constructor: EsmClassConstructorIr(
            parameters: [],
            body: [EsmBlockStatementIr([])],
          ),
          methods: [
            EsmClassMethodIr(
              key: EsmStaticPropertyKeyIr('read'),
              kind: EsmClassMethodKindIr.method,
              isStatic: false,
              parameters: [],
              body: [
                EsmBlockStatementIr([]),
                EsmReturnStatementIr(EsmNumberLiteralIr(1)),
              ],
            ),
          ],
        ),
      ],
    );

    final result = const ModuleNormalizerStage().normalize(
      _normalizationForModule(module).irBuild,
    );

    expect(result.changed, isTrue);
    expect(result.invalidatesSemanticWorld, isFalse);
    expect(result.module.items, hasLength(2));
    final main = result.module.items.first as EsmFunctionIr;
    expect(main.body, hasLength(1));
    expect(main.body.single, same(marker));
    final box = result.module.items.last as EsmClassIr;
    expect(box.constructor?.body, isEmpty);
    expect(box.methods.single.body, [isA<EsmReturnStatementIr>()]);
  });

  test('runtime linker resolves helper declarations before codegen', () {
    const module = EsmModuleIr(
      items: [
        EsmFunctionIr(
          name: 'main',
          export: true,
          parameters: [],
          body: [
            EsmExpressionStatementIr(
              EsmCallIr(
                callee: EsmIdentifierIr('__dartPrint'),
                arguments: [EsmStringLiteralIr('linked')],
              ),
            ),
          ],
        ),
      ],
    );

    final linked = const RuntimeLinkerStage().link(
      _normalizationForModule(
        module,
        runtimeHelpers: const [EsmRuntimeHelper.print],
      ),
    );

    expect(linked.linkedHelpers, [
      EsmRuntimeHelper.print,
      EsmRuntimeHelper.stringify,
    ]);
    expect(linked.normalization.runtimeHelpers, [EsmRuntimeHelper.print]);
    expect(linked.module.items, hasLength(3));
    final helper = linked.module.items.first;
    expect(helper, isA<EsmFunctionIr>());
    expect((helper as EsmFunctionIr).name, '__dartPrint');
    expect(helper.export, isFalse);
    expect(const EsmCodegenStage().emit(linked.module).code, '''
// Generated by dart2esm.

function __dartPrint(value) {
  console.log(__dartStr(value));
}

function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}

export function main() {
  __dartPrint("linked");
}
''');
  });

  test('semantic world reserves pipeline-provided generated global names', () {
    final libraryUri = Uri.parse('package:sample/main.dart');
    final library = k.Library(libraryUri, fileUri: libraryUri);
    final helperCollision = k.Procedure(
      k.Name('__dartPrint', library),
      k.ProcedureKind.Method,
      k.FunctionNode(k.EmptyStatement()),
      fileUri: Uri.parse('memory:__dartPrint.dart'),
      isStatic: true,
    );
    final main = _procedure(
      'main',
      body: k.ExpressionStatement(
        k.StaticInvocation(helperCollision, k.Arguments([])),
      ),
    );
    library.addProcedure(helperCollision);
    library.addProcedure(main);
    final component = k.Component(libraries: [library]);
    component.setMainMethodAndMode(main.reference, true);

    final result = Dart2EsmCompilerPipeline(
      options: const Dart2EsmPipelineOptions(runMain: false),
    ).compile(component);

    final collisionSymbol = result.semantic!.world.symbolForRequired(
      helperCollision,
    );
    expect(collisionSymbol.name, '__dartPrint_1');
  });

  test('semantic world folds anonymous mixin superclass edges', () {
    final libraryUri = Uri.parse('package:sample/main.dart');
    final library = k.Library(libraryUri, fileUri: libraryUri);
    final base = k.Class(name: 'Base', fileUri: libraryUri);
    final mixin = k.Class(name: 'Mixin', fileUri: libraryUri);
    final mixinMethod = k.Procedure(
      k.Name('label'),
      k.ProcedureKind.Method,
      k.FunctionNode(k.ReturnStatement(k.StringLiteral('mixin'))),
      fileUri: Uri.parse('memory:mixin_label.dart'),
    );
    final mixinApplication = k.Class(
      name: r'_Derived&Base&Mixin',
      isAnonymousMixin: true,
      supertype: k.Supertype(base, const []),
      mixedInType: k.Supertype(mixin, const []),
      fileUri: libraryUri,
    );
    mixinApplication.addProcedure(mixinMethod);
    final derived = k.Class(
      name: 'Derived',
      supertype: k.Supertype(mixinApplication, const []),
      fileUri: libraryUri,
    );
    final main = _procedure('main', body: k.EmptyStatement());
    library.addClass(base);
    library.addClass(mixin);
    library.addClass(mixinApplication);
    library.addClass(derived);
    library.addProcedure(main);
    final component = k.Component(libraries: [library]);
    component.setMainMethodAndMode(main.reference, true);

    final semantic = const SemanticWorldStage().build(
      KernelFrontendResult(component: component, main: main),
    );

    expect(
      semantic.world.classes.map((klass) => klass.node),
      isNot(contains(mixinApplication)),
    );
    final derivedSymbol = semantic.world.classSymbolFor(derived);
    expect(derivedSymbol, isNotNull);
    expect(derivedSymbol!.jsSuperclass, same(base));
    expect(derivedSymbol.interfaceMarkerClasses, contains(mixin));
    final loweredMixinMethod = semantic.world.instanceProcedureSymbolFor(
      mixinMethod,
    );
    expect(loweredMixinMethod, isNotNull);
    expect(loweredMixinMethod!.name, 'label');
    expect(loweredMixinMethod.emit, isTrue);
    expect(derivedSymbol.procedures, contains(same(loweredMixinMethod)));
  });

  test('compiles switch continue through the new compiler core', () {
    final result = Dart2EsmCompilerPipeline(
      options: const Dart2EsmPipelineOptions(runMain: true),
    ).compile(_componentWithSwitchContinue());

    expect(result.completedStages, dart2EsmCompilerStageOrder);
    expect(result.code, contains(r'$switchTarget'));
    expect(result.code, contains(r'continue $switchLoop;'));
  });

  test('rejects unsupported Kernel in the compiler core', () {
    final component = _componentWithYieldStatement();

    final pipeline = Dart2EsmCompilerPipeline(
      options: const Dart2EsmPipelineOptions(runMain: true),
    );

    expect(
      () => pipeline.compile(component),
      throwsA(isA<NewCompilerUnsupported>()),
    );
  });

  test('rejects components without a main method in the frontend stage', () {
    final pipeline = Dart2EsmCompilerPipeline(
      options: const Dart2EsmPipelineOptions(runMain: true),
    );

    expect(
      () => pipeline.compile(k.Component()),
      throwsA(isA<UnsupportedKernelNode>()),
    );
  });
}

k.Component _componentWithSwitchContinue() {
  final libraryUri = Uri.parse('package:sample/main.dart');
  final library = k.Library(libraryUri, fileUri: libraryUri);
  final target = k.SwitchCase(
    [k.IntLiteral(0)],
    [k.TreeNode.noOffset],
    k.EmptyStatement(),
  );
  final main = _procedure(
    'main',
    body: k.Block([
      k.SwitchStatement(k.IntLiteral(0), [
        target,
        k.SwitchCase(
          [k.IntLiteral(1)],
          [k.TreeNode.noOffset],
          k.Block([k.ContinueSwitchStatement(target)]),
        ),
      ]),
    ]),
  );
  library.addProcedure(main);
  final component = k.Component(libraries: [library]);
  component.setMainMethodAndMode(main.reference, true);
  return component;
}

k.Component _componentWithYieldStatement() {
  final libraryUri = Uri.parse('package:sample/main.dart');
  final library = k.Library(libraryUri, fileUri: libraryUri);
  final main = _procedure(
    'main',
    body: k.Block([k.YieldStatement(k.IntLiteral(1))]),
  );
  library.addProcedure(main);
  final component = k.Component(libraries: [library]);
  component.setMainMethodAndMode(main.reference, true);
  return component;
}

k.Procedure _procedure(
  String name, {
  required k.Statement body,
  List<k.VariableDeclaration> positionalParameters = const [],
}) {
  return k.Procedure(
    k.Name(name),
    k.ProcedureKind.Method,
    k.FunctionNode(body, positionalParameters: positionalParameters),
    fileUri: Uri.parse('memory:$name.dart'),
    isStatic: true,
  );
}

NormalizationResult _normalizationForModule(
  EsmModuleIr module, {
  Iterable<EsmRuntimeHelper> runtimeHelpers = const [],
}) {
  final libraryUri = Uri.parse('package:sample/main.dart');
  final library = k.Library(libraryUri, fileUri: libraryUri);
  final main = _procedure('main', body: k.EmptyStatement());
  library.addProcedure(main);
  final component = k.Component(libraries: [library]);
  component.setMainMethodAndMode(main.reference, true);
  final kernel = KernelFrontendResult(component: component, main: main);
  final semantic = SemanticWorldResult(
    kernel: kernel,
    world: EsmSemanticWorld(
      component: component,
      main: main,
      classes: const [],
      extensionTypes: const [],
      fields: const [],
      procedures: [
        EsmProcedureSymbol(
          node: main,
          name: 'main',
          export: true,
          kind: EsmProcedureKind.method,
        ),
      ],
    ),
  );
  return NormalizationResult(
    irBuild: EsmIrBuildResult(
      lowering: LoweringResult(
        semantic: semantic,
        items: module.items,
        runtimeHelpers: runtimeHelpers,
      ),
      module: module,
    ),
    module: module,
    changed: false,
    invalidatesSemanticWorld: false,
  );
}
