import 'package:dart2esm/src/compiler_core/compiler_pipeline.dart';
import 'package:dart2esm/src/compiler_core/new_compiler_unsupported.dart';
import 'package:dart2esm/src/diagnostics/unsupported_kernel_node.dart';
import 'package:kernel/kernel.dart' as k;
import 'package:test/test.dart';

void main() {
  test('compiles supported Kernel through the new compiler core', () {
    final libraryUri = Uri.parse('package:sample/main.dart');
    final library = k.Library(libraryUri, fileUri: libraryUri);
    final helperParameter = k.VariableDeclaration('value');
    final helper = _procedure(
      'helper',
      body: k.Block([k.ReturnStatement(k.VariableGet(helperParameter))]),
      positionalParameters: [helperParameter],
    );
    final message = k.VariableDeclaration(
      'message',
      initializer: k.StringLiteral('ok'),
      isFinal: true,
    );
    final main = _procedure(
      'main',
      body: k.Block([
        message,
        k.ExpressionStatement(
          k.StaticInvocation(helper, k.Arguments([k.VariableGet(message)])),
        ),
      ]),
    );
    library.addProcedure(helper);
    library.addProcedure(main);
    final component = k.Component(libraries: [library]);
    component.setMainMethodAndMode(main.reference, true);

    final result = Dart2EsmCompilerPipeline(
      options: const Dart2EsmPipelineOptions(runMain: true),
    ).compile(component);

    expect(result.path, Dart2EsmCompilerPath.newCore);
    expect(result.usedLegacyOracle, isFalse);
    expect(result.kernel.component, same(component));
    expect(result.semantic?.world.main, same(main));
    expect(result.lowering?.module.items, hasLength(3));
    expect(result.normalization?.invalidatesSemanticWorld, isFalse);
    expect(result.codegen?.code, same(result.code));
    expect(result.code, '''
// Generated by dart2esm.

export function helper(value) {
  return value;
}

export function main() {
  const message = "ok";
  helper(message);
}

main();
''');
  });

  test('can reject unsupported Kernel without invoking the legacy oracle', () {
    final libraryUri = Uri.parse('package:sample/main.dart');
    final library = k.Library(libraryUri, fileUri: libraryUri);
    final main = _procedure(
      'main',
      body: k.Block([
        k.IfStatement(k.BoolLiteral(true), k.EmptyStatement(), null),
      ]),
    );
    library.addProcedure(main);
    final component = k.Component(libraries: [library]);
    component.setMainMethodAndMode(main.reference, true);

    final pipeline = Dart2EsmCompilerPipeline(
      options: const Dart2EsmPipelineOptions(
        runMain: true,
        allowLegacyOracle: false,
      ),
    );

    expect(
      () => pipeline.compile(component),
      throwsA(isA<NewCompilerUnsupported>()),
    );
  });

  test('rejects components without a main method in the frontend stage', () {
    final pipeline = Dart2EsmCompilerPipeline(
      options: const Dart2EsmPipelineOptions(runMain: true),
    );

    expect(
      () => pipeline.compile(k.Component()),
      throwsA(isA<UnsupportedKernelNode>()),
    );
  });
}

k.Procedure _procedure(
  String name, {
  required k.Statement body,
  List<k.VariableDeclaration> positionalParameters = const [],
}) {
  return k.Procedure(
    k.Name(name),
    k.ProcedureKind.Method,
    k.FunctionNode(body, positionalParameters: positionalParameters),
    fileUri: Uri.parse('memory:$name.dart'),
    isStatic: true,
  );
}
