import 'dart:io';

import 'package:dart2esm/dart2esm.dart';
import 'package:dart2esm/src/compiler.dart';
import 'package:test/test.dart';

void main() {
  test('exposes package version', () {
    expect(packageVersion, '0.0.0');
  });

  test('compiles Dart input through Kernel before backend lowering', () async {
    final tempDir = await Directory.systemTemp.createTemp('dart2esm-test-');
    addTearDown(() => tempDir.deleteSync(recursive: true));

    final input = File('${tempDir.path}/main.dart')
      ..writeAsStringSync("void main() => print('hello');\n");
    final output = File('${tempDir.path}/main.mjs');

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: input.path,
        outputPath: output.path,
        workingDirectory: tempDir,
      ),
    );

    expect(result.success, isFalse);
    expect(
      result.diagnostics,
      contains(startsWith('Kernel input accepted: format 130')),
    );
    expect(output.readAsStringSync(), contains('Generated by dart2esm'));
  });
}
