import 'dart:convert';
import 'dart:io';

import 'package:dart2esm/src/compiler_core/compiler_pipeline.dart';
import 'package:dart2esm/src/cli.dart';
import 'package:dart2esm/src/compiler.dart';
import 'package:kernel/kernel.dart' as kernel;
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

void main() {
  final fixtureDir = Directory('test/fixtures/specs');

  test('CLI version matches package metadata', () async {
    final tempDir = await Directory.systemTemp.createTemp('dart2esm-version-');
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final stdoutLog = File(p.join(tempDir.path, 'stdout.log')).openWrite();
    final stderrLog = File(p.join(tempDir.path, 'stderr.log')).openWrite();

    final exitCode = await runDart2Esm(
      ['--version'],
      stdoutSink: stdoutLog,
      stderrSink: stderrLog,
    );
    await stdoutLog.close();
    await stderrLog.close();

    final pubspec = File('pubspec.yaml').readAsStringSync();
    final version = RegExp(
      r'^version: (.+)$',
      multiLine: true,
    ).firstMatch(pubspec)!.group(1);
    expect(exitCode, ExitCode.success);
    expect(
      File(p.join(tempDir.path, 'stdout.log')).readAsStringSync(),
      'dart2esm $version\n',
    );
    expect(
      File(p.join(tempDir.path, 'stderr.log')).readAsStringSync(),
      isEmpty,
    );
  });

  test('compiles Dart input through Kernel to runnable ESM', () async {
    final fixture = File(
      p.join(fixtureDir.path, 'functions', 'basic_functions.dart'),
    );
    final tempDir = await Directory.systemTemp.createTemp('dart2esm-test-');
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final output = File(p.join(tempDir.path, 'main.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: fixture.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.diagnostics, hasLength(2));
    expect(
      result.diagnostics.first,
      matches(
        RegExp(r'^Kernel input accepted: format 130, SDK hash [0-9a-f]+\.$'),
      ),
    );
    expect(
      output.readAsStringSync(),
      File(
        p.join(fixtureDir.path, 'functions', 'basic_functions.mjs'),
      ).readAsStringSync(),
    );
    await _expectSameDartAndNodeOutput(fixture, output);
  });

  test('reads CFE Kernel component libraries and main procedure', () async {
    final tempDir = await Directory.systemTemp.createTemp('dart2esm-reader-');
    addTearDown(() => tempDir.deleteSync(recursive: true));

    final input = File(p.join(tempDir.path, 'main.dart'))
      ..writeAsStringSync(
        File(
          p.join(fixtureDir.path, 'functions', 'basic_functions.dart'),
        ).readAsStringSync(),
      );
    final dill = File(p.join(tempDir.path, 'main.dill'));
    final result = await Process.run(Platform.resolvedExecutable, [
      'compile',
      'kernel',
      '--no-link-platform',
      '--embed-sources',
      '-o',
      dill.path,
      input.path,
    ], workingDirectory: tempDir.path);

    expect(result.exitCode, 0, reason: '${result.stdout}\n${result.stderr}');

    final component = kernel.loadComponentFromBytes(dill.readAsBytesSync());
    expect(component.libraries.map((library) => library.fileUri).toList(), [
      input.uri,
    ]);
    expect(component.mainMethod?.name.text, 'main');
    expect(component.mainMethod?.function.body, isNotNull);
  });

  test('compiles simple real Dart through the new compiler core', () async {
    final tempDir = await Directory.systemTemp.createTemp('dart2esm-new-core-');
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final input = File(p.join(tempDir.path, 'main.dart'))
      ..writeAsStringSync('''
String echo(String value) {
  return value;
}

void main() {
  final value = echo('ready');
  echo(value);
}
''');
    final output = File(p.join(tempDir.path, 'main.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: input.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        runMain: false,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), '''
// Generated by dart2esm.

export function echo(value) {
  return value;
}

export function main() {
  const value = echo("ready");
  echo(value);
}
''');

    final nodeResult = await Process.run('node', [
      '--input-type=module',
      '-e',
      "import { echo } from ${jsonEncode(output.uri.toString())}; console.log(echo('js'));",
    ]);
    expect(
      nodeResult.exitCode,
      0,
      reason: '${nodeResult.stdout}\n${nodeResult.stderr}',
    );
    expect((nodeResult.stdout as String).trim(), 'js');
  });

  test('compiles print through the new runtime helper', () async {
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-print-core-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final input = File(p.join(tempDir.path, 'main.dart'))
      ..writeAsStringSync('''
void main() {
  final target = 'core';
  print('new \$target');
}
''');
    final output = File(p.join(tempDir.path, 'main.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: input.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), '''
// Generated by dart2esm.

function __dartPrint(value) {
  console.log(value);
}

export function main() {
  const target = "core";
  __dartPrint(`new \${target}`);
}

main();
''');

    final nodeResult = await Process.run('node', [output.path]);
    expect(
      nodeResult.exitCode,
      0,
      reason: '${nodeResult.stdout}\n${nodeResult.stderr}',
    );
    expect((nodeResult.stdout as String).trim(), 'new core');
  });

  test(
    'compiles top-level field reads and writes through the new core',
    () async {
      final tempDir = await Directory.systemTemp.createTemp(
        'dart2esm-static-fields-core-',
      );
      addTearDown(() => tempDir.deleteSync(recursive: true));
      final input = File(p.join(tempDir.path, 'main.dart'))
        ..writeAsStringSync('''
int counter = 1;
final seed = 3;

void bump() {
  counter = counter + seed;
}

void main() {
  bump();
  print('counter \$counter');
}
''');
      final output = File(p.join(tempDir.path, 'main.mjs'));

      final result = await compileDartToEsm(
        Dart2EsmOptions(
          inputPath: input.path,
          outputPath: output.path,
          workingDirectory: Directory.current,
          allowLegacyOracle: false,
        ),
      );

      expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
      expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
      expect(output.readAsStringSync(), '''
// Generated by dart2esm.

function __dartPrint(value) {
  console.log(value);
}

export let counter = 1;
export const seed = 3;
export function bump() {
  counter = counter + seed;
}

export function main() {
  bump();
  __dartPrint(`counter \${counter}`);
}

main();
''');

      final nodeResult = await Process.run('node', [output.path]);
      expect(
        nodeResult.exitCode,
        0,
        reason: '${nodeResult.stdout}\n${nodeResult.stderr}',
      );
      expect((nodeResult.stdout as String).trim(), 'counter 4');
    },
  );

  test('compiles top-level getters and setters through the new core', () async {
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-accessors-core-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final input = File(p.join(tempDir.path, 'main.dart'))
      ..writeAsStringSync('''
int backing = 1;

int get _computed {
  print('get computed');
  return backing + 2;
}

set _computed(int value) {
  print('set computed \$value');
  backing = value;
}

void main() {
  final first = _computed;
  _computed = 10;
  print('values \$first \$_computed \$backing');
}
''');
    final output = File(p.join(tempDir.path, 'main.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: input.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), '''
// Generated by dart2esm.

function __dartPrint(value) {
  console.log(value);
}

export let backing = 1;
function _computed() {
  __dartPrint("get computed");
  return backing + 2;
}

function _computed_1(value) {
  __dartPrint(`set computed \${value}`);
  backing = value;
}

export function main() {
  const first = _computed();
  _computed_1(10);
  __dartPrint(`values \${first} \${_computed()} \${backing}`);
}

main();
''');

    final nodeResult = await Process.run('node', [output.path]);
    expect(
      nodeResult.exitCode,
      0,
      reason: '${nodeResult.stdout}\n${nodeResult.stderr}',
    );
    expect(
      (nodeResult.stdout as String).trim(),
      'get computed\nset computed 10\nget computed\nvalues 3 12 10',
    );
  });

  test('compiles basic classes through the new core', () async {
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-class-core-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final input = File(p.join(tempDir.path, 'main.dart'))
      ..writeAsStringSync('''
class Counter {
  int value;

  Counter(this.value);

  void add(int amount) {
    value = value + amount;
  }

  int get doubled => value * 2;
}

void main() {
  final counter = Counter(3);
  counter.add(4);
  print('value \${counter.value}');
  print('double \${counter.doubled}');
}
''');
    final output = File(p.join(tempDir.path, 'main.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: input.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), '''
// Generated by dart2esm.

function __dartPrint(value) {
  console.log(value);
}

export class Counter {
  constructor(value) {
    this.value = value;
  }
  add(amount) {
    this.value = this.value + amount;
  }
  get doubled() {
    return this.value * 2;
  }
}

export function main() {
  const counter = new Counter(3);
  counter.add(4);
  __dartPrint(`value \${counter.value}`);
  __dartPrint(`double \${counter.doubled}`);
}

main();
''');

    final nodeResult = await Process.run('node', [output.path]);
    expect(
      nodeResult.exitCode,
      0,
      reason: '${nodeResult.stdout}\n${nodeResult.stderr}',
    );
    expect((nodeResult.stdout as String).trim(), 'value 7\ndouble 14');
  });

  test('compiles inheritance through the new core', () async {
    final source = File(p.join(fixtureDir.path, 'classes', 'inheritance.dart'));
    final expected = File(
      p.join(fixtureDir.path, 'classes', 'inheritance.mjs'),
    );
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-inheritance-core-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final output = File(p.join(tempDir.path, 'main.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: source.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), expected.readAsStringSync());

    final nodeResult = await Process.run('node', [output.path]);
    expect(
      nodeResult.exitCode,
      0,
      reason: '${nodeResult.stdout}\n${nodeResult.stderr}',
    );
    expect(
      (nodeResult.stdout as String).trim(),
      'animal Rex dog 4\n'
      'animal Rex dog 5\n'
      'animal Ada\n'
      'animal Ada dog 5\n'
      'animal true\n'
      'dog true',
    );
  });

  test('compiles interfaces through the new core', () async {
    final source = File(p.join(fixtureDir.path, 'classes', 'interfaces.dart'));
    final expected = File(p.join(fixtureDir.path, 'classes', 'interfaces.mjs'));
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-interfaces-core-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final output = File(p.join(tempDir.path, 'main.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: source.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), expected.readAsStringSync());

    final nodeResult = await Process.run('node', [output.path]);
    expect(
      nodeResult.exitCode,
      0,
      reason: '${nodeResult.stdout}\n${nodeResult.stderr}',
    );
    expect((nodeResult.stdout as String).trim(), 'ada person:ada true');
  });

  test('compiles static members through the new core', () async {
    final source = File(
      p.join(fixtureDir.path, 'classes', 'static_members.dart'),
    );
    final expected = File(
      p.join(fixtureDir.path, 'classes', 'static_members.mjs'),
    );
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-static-members-core-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final output = File(p.join(tempDir.path, 'main.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: source.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), expected.readAsStringSync());

    final nodeResult = await Process.run('node', [output.path]);
    expect(
      nodeResult.exitCode,
      0,
      reason: '${nodeResult.stdout}\n${nodeResult.stderr}',
    );
    expect(
      (nodeResult.stdout as String).trim(),
      'offset 3\n'
      'init total\n'
      'first 10\n'
      'bump 17\n'
      'instance 25\n'
      'double 50\n'
      'init readonly\n'
      'readonly 40\n'
      'count 2',
    );
  });

  test('compiles named constructors through the new core', () async {
    final source = File(
      p.join(fixtureDir.path, 'classes', 'named_constructors.dart'),
    );
    final expected = File(
      p.join(fixtureDir.path, 'classes', 'named_constructors.mjs'),
    );
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-named-constructors-core-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final output = File(p.join(tempDir.path, 'main.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: source.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), expected.readAsStringSync());

    final nodeResult = await Process.run('node', [output.path]);
    expect(
      nodeResult.exitCode,
      0,
      reason: '${nodeResult.stdout}\n${nodeResult.stderr}',
    );
    expect(
      (nodeResult.stdout as String).trim(),
      'origin!:0,0\n'
      'square:4,4\n'
      'point:2,3\n'
      'token alpha',
    );
  });

  test('compiles named constructor inheritance through the new core', () async {
    final source = File(
      p.join(fixtureDir.path, 'classes', 'named_constructor_inheritance.dart'),
    );
    final expected = File(
      p.join(fixtureDir.path, 'classes', 'named_constructor_inheritance.mjs'),
    );
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-named-constructor-inheritance-core-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final output = File(p.join(tempDir.path, 'main.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: source.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), expected.readAsStringSync());

    final nodeResult = await Process.run('node', [output.path]);
    expect(
      nodeResult.exitCode,
      0,
      reason: '${nodeResult.stdout}\n${nodeResult.stderr}',
    );
    expect(
      (nodeResult.stdout as String).trim(),
      'animal Rex named dog! 4\n'
      'animal Ada dog 2\n'
      'animal Mia cat 9',
    );
  });

  test('compiles named super constructors through the new core', () async {
    final source = File(
      p.join(fixtureDir.path, 'classes', 'named_super_constructors.dart'),
    );
    final expected = File(
      p.join(fixtureDir.path, 'classes', 'named_super_constructors.mjs'),
    );
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-named-super-constructors-core-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final output = File(p.join(tempDir.path, 'main.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: source.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), expected.readAsStringSync());

    final nodeResult = await Process.run('node', [output.path]);
    expect(
      nodeResult.exitCode,
      0,
      reason: '${nodeResult.stdout}\n${nodeResult.stderr}',
    );
    expect(
      (nodeResult.stdout as String).trim(),
      'named animal! Rex dog! 4\n'
      'named animal! Mia cat black!\n'
      'named animal! Tiny dog! 1 toy ball',
    );
  });

  test(
    'compiles unnamed redirecting constructors through the new core',
    () async {
      final source = File(
        p.join(
          fixtureDir.path,
          'classes',
          'unnamed_redirecting_constructors.dart',
        ),
      );
      final expected = File(
        p.join(
          fixtureDir.path,
          'classes',
          'unnamed_redirecting_constructors.mjs',
        ),
      );
      final tempDir = await Directory.systemTemp.createTemp(
        'dart2esm-unnamed-redirecting-constructors-core-',
      );
      addTearDown(() => tempDir.deleteSync(recursive: true));
      final output = File(p.join(tempDir.path, 'main.mjs'));

      final result = await compileDartToEsm(
        Dart2EsmOptions(
          inputPath: source.path,
          outputPath: output.path,
          workingDirectory: Directory.current,
          allowLegacyOracle: false,
        ),
      );

      expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
      expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
      expect(output.readAsStringSync(), expected.readAsStringSync());

      final nodeResult = await Process.run('node', [output.path]);
      expect(
        nodeResult.exitCode,
        0,
        reason: '${nodeResult.stdout}\n${nodeResult.stderr}',
      );
      expect(
        (nodeResult.stdout as String).trim(),
        'default:0,1\n'
        'animal Rex dog! 4',
      );
    },
  );

  test('compiles redirecting constructors through the new core', () async {
    final source = File(
      p.join(fixtureDir.path, 'classes', 'redirecting_constructors.dart'),
    );
    final expected = File(
      p.join(fixtureDir.path, 'classes', 'redirecting_constructors.mjs'),
    );
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-redirecting-constructors-core-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final output = File(p.join(tempDir.path, 'main.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: source.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), expected.readAsStringSync());

    final nodeResult = await Process.run('node', [output.path]);
    expect(
      nodeResult.exitCode,
      0,
      reason: '${nodeResult.stdout}\n${nodeResult.stderr}',
    );
    expect(
      (nodeResult.stdout as String).trim(),
      'point:0,0\n'
      'alias:4,5\n'
      'default:0,1\n'
      'mirror:5,5\n'
      '0..10\n'
      '5..15\n'
      'default:1:true\n'
      'from:2:true\n'
      'off:3:false\n'
      'animal Rex dog! 4\n'
      'animal Tiny dog! 1 toy ball\n'
      'point:0,0 red\n'
      'default:0,1 wrapped',
    );
  });

  test(
    'compiles redirecting factory constructors through the new core',
    () async {
      final source = File(
        p.join(
          fixtureDir.path,
          'classes',
          'redirecting_factory_constructors.dart',
        ),
      );
      final expected = File(
        p.join(
          fixtureDir.path,
          'classes',
          'redirecting_factory_constructors.mjs',
        ),
      );
      final tempDir = await Directory.systemTemp.createTemp(
        'dart2esm-redirecting-factory-constructors-core-',
      );
      addTearDown(() => tempDir.deleteSync(recursive: true));
      final output = File(p.join(tempDir.path, 'main.mjs'));

      final result = await compileDartToEsm(
        Dart2EsmOptions(
          inputPath: source.path,
          outputPath: output.path,
          workingDirectory: Directory.current,
          allowLegacyOracle: false,
        ),
      );

      expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
      expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
      expect(output.readAsStringSync(), expected.readAsStringSync());

      final nodeResult = await Process.run('node', [output.path]);
      expect(
        nodeResult.exitCode,
        0,
        reason: '${nodeResult.stdout}\n${nodeResult.stderr}',
      );
      expect(
        (nodeResult.stdout as String).trim(),
        'square:2\n'
        'named:3\n'
        'named:4\n'
        'square:5\n'
        'default:8\n'
        'options:9\n'
        'custom:6\n'
        'button:button\n'
        'button:primary',
      );

      final module = File(p.join(tempDir.path, 'module.mjs'));
      final consumer = File(p.join(tempDir.path, 'consumer.mjs'))
        ..writeAsStringSync(
          "import { Shape, Widget } from './module.mjs';\n"
          "console.log(Shape.named(3) instanceof Shape);\n"
          "console.log(Widget.named('primary') instanceof Widget);\n",
        );
      final moduleResult = await compileDartToEsm(
        Dart2EsmOptions(
          inputPath: source.path,
          outputPath: module.path,
          workingDirectory: Directory.current,
          runMain: false,
          allowLegacyOracle: false,
        ),
      );

      expect(
        moduleResult.success,
        isTrue,
        reason: moduleResult.diagnostics.join('\n'),
      );
      expect(moduleResult.compilerPath, Dart2EsmCompilerPath.newCore);
      expect(
        module.readAsStringSync(),
        _withoutMainCall(expected.readAsStringSync()),
      );

      final importResult = await Process.run('node', [
        consumer.path,
      ], workingDirectory: tempDir.path);
      expect(
        importResult.exitCode,
        0,
        reason: '${importResult.stdout}\n${importResult.stderr}',
      );
      expect((importResult.stdout as String).trim(), 'true\ntrue');
    },
  );

  test('compiles function parameters through the new core', () async {
    final source = File(
      p.join(fixtureDir.path, 'functions', 'parameters.dart'),
    );
    final expected = File(
      p.join(fixtureDir.path, 'functions', 'parameters.mjs'),
    );
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-function-parameters-core-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final output = File(p.join(tempDir.path, 'main.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: source.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), expected.readAsStringSync());

    final nodeResult = await Process.run('node', [output.path]);
    expect(
      nodeResult.exitCode,
      0,
      reason: '${nodeResult.stdout}\n${nodeResult.stderr}',
    );
    expect(
      (nodeResult.stdout as String).trim(),
      'a!\n'
      'b?b?\n'
      'item:3:x\n'
      'custom:4:y\n'
      '[z]\n'
      '(z)',
    );
  });

  test('compiles Function.apply through the new core', () async {
    final source = File(
      p.join(fixtureDir.path, 'functions', 'function_apply.dart'),
    );
    final expected = File(
      p.join(fixtureDir.path, 'functions', 'function_apply.mjs'),
    );
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-function-apply-core-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final output = File(p.join(tempDir.path, 'main.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: source.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), expected.readAsStringSync());

    final nodeResult = await Process.run('node', [output.path]);
    expect(
      nodeResult.exitCode,
      0,
      reason: '${nodeResult.stdout}\n${nodeResult.stderr}',
    );
    expect(
      (nodeResult.stdout as String).trim(),
      'positional 5\n'
      'named ADA:3\n'
      'local 9\n'
      'forward dart:2',
    );
  });

  test('compiles function values through the new core', () async {
    final source = File(
      p.join(fixtureDir.path, 'functions', 'function_values.dart'),
    );
    final expected = File(
      p.join(fixtureDir.path, 'functions', 'function_values.mjs'),
    );
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-function-values-core-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final output = File(p.join(tempDir.path, 'main.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: source.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), expected.readAsStringSync());

    final nodeResult = await Process.run('node', [output.path]);
    expect(
      nodeResult.exitCode,
      0,
      reason: '${nodeResult.stdout}\n${nodeResult.stderr}',
    );
    expect((nodeResult.stdout as String).trim(), '7\n10\n3\n8');
  });

  test('compiles if/else control flow through the new core', () async {
    final tempDir = await Directory.systemTemp.createTemp('dart2esm-if-core-');
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final input = File(p.join(tempDir.path, 'main.dart'))
      ..writeAsStringSync('''
void main() {
  final enabled = true;
  if (enabled) {
    print('then');
  } else {
    print('else');
  }
}
''');
    final output = File(p.join(tempDir.path, 'main.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: input.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), '''
// Generated by dart2esm.

function __dartPrint(value) {
  console.log(value);
}

export function main() {
  const enabled = true;
  if (enabled) {
    __dartPrint("then");
  } else {
    __dartPrint("else");
  }
}

main();
''');

    final nodeResult = await Process.run('node', [output.path]);
    expect(
      nodeResult.exitCode,
      0,
      reason: '${nodeResult.stdout}\n${nodeResult.stderr}',
    );
    expect((nodeResult.stdout as String).trim(), 'then');
  });

  test('compiles while control flow through the new core', () async {
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-while-core-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final input = File(p.join(tempDir.path, 'main.dart'))
      ..writeAsStringSync('''
void main() {
  var i = 0;
  while (i < 3) {
    print('i \$i');
    i = i + 1;
  }
}
''');
    final output = File(p.join(tempDir.path, 'main.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: input.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), '''
// Generated by dart2esm.

function __dartPrint(value) {
  console.log(value);
}

export function main() {
  let i = 0;
  while (i < 3) {
    __dartPrint(`i \${i}`);
    i = i + 1;
  }
}

main();
''');

    final nodeResult = await Process.run('node', [output.path]);
    expect(
      nodeResult.exitCode,
      0,
      reason: '${nodeResult.stdout}\n${nodeResult.stderr}',
    );
    expect((nodeResult.stdout as String).trim(), 'i 0\ni 1\ni 2');
  });

  test('compiles for control flow through the new core', () async {
    final tempDir = await Directory.systemTemp.createTemp('dart2esm-for-core-');
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final input = File(p.join(tempDir.path, 'main.dart'))
      ..writeAsStringSync('''
void main() {
  var total = 0;
  for (var i = 0; i < 4; i = i + 1) {
    total = total + i;
  }
  print('total \$total');
}
''');
    final output = File(p.join(tempDir.path, 'main.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: input.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), '''
// Generated by dart2esm.

function __dartPrint(value) {
  console.log(value);
}

export function main() {
  let total = 0;
  for (let i = 0; i < 4; i = i + 1) {
    total = total + i;
  }
  __dartPrint(`total \${total}`);
}

main();
''');

    final nodeResult = await Process.run('node', [output.path]);
    expect(
      nodeResult.exitCode,
      0,
      reason: '${nodeResult.stdout}\n${nodeResult.stderr}',
    );
    expect((nodeResult.stdout as String).trim(), 'total 6');
  });

  test('compiles do control flow through the new core', () async {
    final tempDir = await Directory.systemTemp.createTemp('dart2esm-do-core-');
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final input = File(p.join(tempDir.path, 'main.dart'))
      ..writeAsStringSync('''
void main() {
  var i = 0;
  do {
    print('do \$i');
    i = i + 1;
  } while (i < 2);
}
''');
    final output = File(p.join(tempDir.path, 'main.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: input.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), '''
// Generated by dart2esm.

function __dartPrint(value) {
  console.log(value);
}

export function main() {
  let i = 0;
  do {
    __dartPrint(`do \${i}`);
    i = i + 1;
  } while (i < 2);
}

main();
''');

    final nodeResult = await Process.run('node', [output.path]);
    expect(
      nodeResult.exitCode,
      0,
      reason: '${nodeResult.stdout}\n${nodeResult.stderr}',
    );
    expect((nodeResult.stdout as String).trim(), 'do 0\ndo 1');
  });

  test('compiles loop break and continue through the new core', () async {
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-loop-jumps-core-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final input = File(p.join(tempDir.path, 'main.dart'))
      ..writeAsStringSync('''
void main() {
  var i = 0;
  while (i < 5) {
    i = i + 1;
    if (i < 3) {
      continue;
    }
    if (i > 3) {
      break;
    }
    print('hit \$i');
  }
  print('done \$i');
}
''');
    final output = File(p.join(tempDir.path, 'main.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: input.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), '''
// Generated by dart2esm.

function __dartPrint(value) {
  console.log(value);
}

export function main() {
  let i = 0;
  label: {
    while (i < 5) {
      label_1: {
        i = i + 1;
        if (i < 3) {
          break label_1;
        }
        if (i > 3) {
          break label;
        }
        __dartPrint(`hit \${i}`);
      }
    }
  }
  __dartPrint(`done \${i}`);
}

main();
''');

    final nodeResult = await Process.run('node', [output.path]);
    expect(
      nodeResult.exitCode,
      0,
      reason: '${nodeResult.stdout}\n${nodeResult.stderr}',
    );
    expect((nodeResult.stdout as String).trim(), 'hit 3\ndone 4');
  });

  test('compiles switch control flow through the new core', () async {
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-switch-core-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final input = File(p.join(tempDir.path, 'main.dart'))
      ..writeAsStringSync('''
void main() {
  var value = 2;
  switch (value) {
    case 1:
      print('one');
      break;
    case 2:
    case 3:
      print('two/three');
      break;
    default:
      print('other \$value');
  }
}
''');
    final output = File(p.join(tempDir.path, 'main.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: input.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), '''
// Generated by dart2esm.

function __dartPrint(value) {
  console.log(value);
}

export function main() {
  let value = 2;
  label: {
    switch (value) {
      case 1:
        __dartPrint("one");
        break label;
      case 2:
      case 3:
        __dartPrint("two/three");
        break label;
      default:
        __dartPrint(`other \${value}`);
    }
  }
}

main();
''');

    final nodeResult = await Process.run('node', [output.path]);
    expect(
      nodeResult.exitCode,
      0,
      reason: '${nodeResult.stdout}\n${nodeResult.stderr}',
    );
    expect((nodeResult.stdout as String).trim(), 'two/three');
  });

  test(
    'reports unsupported real switch continue when oracle is disabled',
    () async {
      final tempDir = await Directory.systemTemp.createTemp(
        'dart2esm-no-oracle-',
      );
      addTearDown(() => tempDir.deleteSync(recursive: true));
      final input = File(p.join(tempDir.path, 'main.dart'))
        ..writeAsStringSync('''
void main() {
  switch (0) {
    target:
    case 0:
      continue target;
  }
}
''');
      final output = File(p.join(tempDir.path, 'main.mjs'));

      final result = await compileDartToEsm(
        Dart2EsmOptions(
          inputPath: input.path,
          outputPath: output.path,
          workingDirectory: Directory.current,
          allowLegacyOracle: false,
        ),
      );

      expect(result.success, isFalse);
      expect(result.compilerPath, isNull);
      expect(
        result.diagnostics.single,
        contains('New compiler core does not support statement lowering'),
      );
      expect(output.existsSync(), isFalse);
    },
  );

  test('compiles type tests through the new core', () async {
    final source = File(p.join(fixtureDir.path, 'syntax', 'type_tests.dart'));
    final expected = File(p.join(fixtureDir.path, 'syntax', 'type_tests.mjs'));
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-type-tests-core-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final output = File(p.join(tempDir.path, 'type_tests.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: source.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), expected.readAsStringSync());
    await _expectSameDartAndNodeOutput(source, output);
  });

  test('compiles control operators through the new core', () async {
    final source = File(
      p.join(fixtureDir.path, 'syntax', 'control_operators.dart'),
    );
    final expected = File(
      p.join(fixtureDir.path, 'syntax', 'control_operators.mjs'),
    );
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-control-operators-core-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final output = File(p.join(tempDir.path, 'control_operators.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: source.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), expected.readAsStringSync());
    await _expectSameDartAndNodeOutput(source, output);
  });

  test('compiles const collections through the new core', () async {
    final source = File(
      p.join(fixtureDir.path, 'syntax', 'const_collections.dart'),
    );
    final expected = File(
      p.join(fixtureDir.path, 'syntax', 'const_collections.mjs'),
    );
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-const-collections-core-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final output = File(p.join(tempDir.path, 'const_collections.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: source.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), expected.readAsStringSync());
    await _expectSameDartAndNodeOutput(source, output);
  });

  test('compiles const value objects through the new core', () async {
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-const-values-core-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));

    for (final id in const [
      'classes/callable_classes',
      'classes/constructor_tearoffs',
      'records/basic_records',
      'syntax/type_symbol_literals',
    ]) {
      final source = File(p.join(fixtureDir.path, '$id.dart'));
      final expected = File(p.join(fixtureDir.path, '$id.mjs'));
      final output = File(
        p.join(tempDir.path, '${id.replaceAll('/', '_')}.mjs'),
      );

      final result = await compileDartToEsm(
        Dart2EsmOptions(
          inputPath: source.path,
          outputPath: output.path,
          workingDirectory: Directory.current,
          allowLegacyOracle: false,
        ),
      );

      expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
      expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
      expect(output.readAsStringSync(), expected.readAsStringSync());
      await _expectSameDartAndNodeOutput(source, output);
    }
  });

  test('compiles local library imports through the new core', () async {
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-local-imports-core-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));

    for (final id in const [
      'imports/exports_api',
      'imports/reexport_api',
      'imports/parts',
      'imports/relative_imports',
    ]) {
      final source = File(p.join(fixtureDir.path, '$id.dart'));
      final expected = File(p.join(fixtureDir.path, '$id.mjs'));
      final output = File(p.join(tempDir.path, '${p.basename(id)}.mjs'));

      final result = await compileDartToEsm(
        Dart2EsmOptions(
          inputPath: source.path,
          outputPath: output.path,
          workingDirectory: Directory.current,
          allowLegacyOracle: false,
        ),
      );

      expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
      expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
      expect(output.readAsStringSync(), expected.readAsStringSync());
      await _expectSameDartAndNodeOutput(source, output);
    }

    await _expectLocalImportSurface(fixtureDir, tempDir);
  });

  test('can emit an ESM module without running main', () async {
    final fixture = _GoldenFixture(
      root: fixtureDir,
      source: File(
        p.join(fixtureDir.path, 'functions', 'basic_functions.dart'),
      ),
      expectedEsm: File(
        p.join(fixtureDir.path, 'functions', 'basic_functions.mjs'),
      ),
    );
    final tempDir = await Directory.systemTemp.createTemp('dart2esm-no-main-');
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final output = File(p.join(tempDir.path, 'basic_functions.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: fixture.source.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        runMain: false,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), _withoutMainCall(fixture.expectedCode));
  });

  test('CLI --no-run-main omits the main invocation', () async {
    final fixture = _GoldenFixture(
      root: fixtureDir,
      source: File(
        p.join(fixtureDir.path, 'functions', 'basic_functions.dart'),
      ),
      expectedEsm: File(
        p.join(fixtureDir.path, 'functions', 'basic_functions.mjs'),
      ),
    );
    final tempDir = await Directory.systemTemp.createTemp('dart2esm-cli-');
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final output = File(p.join(tempDir.path, 'basic_functions.mjs'));
    final stdoutLog = File(p.join(tempDir.path, 'stdout.log')).openWrite();
    final stderrLog = File(p.join(tempDir.path, 'stderr.log')).openWrite();

    final exitCode = await runDart2Esm(
      [fixture.source.path, '-o', output.path, '--no-run-main'],
      stdoutSink: stdoutLog,
      stderrSink: stderrLog,
    );
    await stdoutLog.close();
    await stderrLog.close();

    expect(exitCode, ExitCode.success);
    expect(output.readAsStringSync(), _withoutMainCall(fixture.expectedCode));
  });

  test('CLI --metrics prints generated ESM size metrics', () async {
    final fixture = _GoldenFixture(
      root: fixtureDir,
      source: File(
        p.join(fixtureDir.path, 'functions', 'basic_functions.dart'),
      ),
      expectedEsm: File(
        p.join(fixtureDir.path, 'functions', 'basic_functions.mjs'),
      ),
    );
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-cli-metrics-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final output = File(p.join(tempDir.path, 'basic_functions.mjs'));
    final stdoutLog = File(p.join(tempDir.path, 'stdout.log')).openWrite();
    final stderrLog = File(p.join(tempDir.path, 'stderr.log')).openWrite();

    final exitCode = await runDart2Esm(
      [fixture.source.path, '-o', output.path, '--no-run-main', '--metrics'],
      stdoutSink: stdoutLog,
      stderrSink: stderrLog,
    );
    await stdoutLog.close();
    await stderrLog.close();

    expect(exitCode, ExitCode.success);
    expect(output.readAsStringSync(), _withoutMainCall(fixture.expectedCode));
    expect(
      File(p.join(tempDir.path, 'stdout.log')).readAsStringSync(),
      matches(
        RegExp(
          r'^Metrics \(dart2esm\): raw=\d+ bytes; gzip=\d+ bytes; lines=\d+; helpers=\d+\.\n$',
        ),
      ),
    );
  });

  test('compile options pass environment defines to CFE', () async {
    final fixture = File(
      p.join(fixtureDir.path, 'libraries', 'environment.dart'),
    );
    final tempDir = await Directory.systemTemp.createTemp('dart2esm-env-');
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final output = File(p.join(tempDir.path, 'environment.mjs'));

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: fixture.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        environmentDefines: const [
          'dart2esm.feature=true',
          'dart2esm.answer=42',
          'dart2esm.label=defined',
        ],
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    final nodeRun = await Process.run('node', [
      output.path,
    ], workingDirectory: tempDir.path);
    expect(nodeRun.exitCode, 0, reason: '${nodeRun.stdout}\n${nodeRun.stderr}');
    expect(nodeRun.stdout, 'env true true 42 defined\n');
    expect(nodeRun.stderr, isEmpty);
  });

  test('CLI -D passes environment defines to CFE', () async {
    final fixture = File(
      p.join(fixtureDir.path, 'libraries', 'environment.dart'),
    );
    final tempDir = await Directory.systemTemp.createTemp('dart2esm-cli-env-');
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final output = File(p.join(tempDir.path, 'environment.mjs'));
    final stdoutLog = File(p.join(tempDir.path, 'stdout.log')).openWrite();
    final stderrLog = File(p.join(tempDir.path, 'stderr.log')).openWrite();

    final exitCode = await runDart2Esm(
      [
        fixture.path,
        '-o',
        output.path,
        '-Ddart2esm.feature=true,dart2esm.answer=43',
        '--define=dart2esm.label=cli',
      ],
      stdoutSink: stdoutLog,
      stderrSink: stderrLog,
    );
    await stdoutLog.close();
    await stderrLog.close();

    expect(exitCode, ExitCode.success);
    expect(
      File(p.join(tempDir.path, 'stdout.log')).readAsStringSync(),
      isEmpty,
    );
    final nodeRun = await Process.run('node', [
      output.path,
    ], workingDirectory: tempDir.path);
    expect(nodeRun.exitCode, 0, reason: '${nodeRun.stdout}\n${nodeRun.stderr}');
    expect(nodeRun.stdout, 'env true true 43 cli\n');
    expect(nodeRun.stderr, isEmpty);
  });

  test(
    'no-run-main import exposes initialized top-level ESM bindings',
    () async {
      final fixture = _GoldenFixture(
        root: fixtureDir,
        source: File(
          p.join(fixtureDir.path, 'variables', 'top_level_variables.dart'),
        ),
        expectedEsm: File(
          p.join(fixtureDir.path, 'variables', 'top_level_variables.mjs'),
        ),
      );
      final tempDir = await Directory.systemTemp.createTemp('dart2esm-var-');
      addTearDown(() => tempDir.deleteSync(recursive: true));
      final output = File(p.join(tempDir.path, 'vars.mjs'));
      final consumer = File(p.join(tempDir.path, 'consumer.mjs'))
        ..writeAsStringSync(
          "import { assignFirst, finalValue } from './vars.mjs';\n"
          "console.log('values ' + assignFirst + ' ' + finalValue);\n",
        );

      final result = await compileDartToEsm(
        Dart2EsmOptions(
          inputPath: fixture.source.path,
          outputPath: output.path,
          workingDirectory: Directory.current,
          runMain: false,
        ),
      );

      expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
      expect(output.readAsStringSync(), _withoutMainCall(fixture.expectedCode));

      final nodeRun = await Process.run('node', [
        consumer.path,
      ], workingDirectory: tempDir.path);
      expect(
        nodeRun.exitCode,
        0,
        reason: '${nodeRun.stdout}\n${nodeRun.stderr}',
      );
      expect(
        nodeRun.stdout,
        'init readFirst\n'
        'init assignFirst\n'
        'init finalValue\n'
        'values 20 30\n',
      );
      expect(nodeRun.stderr, isEmpty);
    },
  );

  test('direct named ESM import reads primitive top-level variables', () async {
    final fixture = _GoldenFixture(
      root: fixtureDir,
      source: File(
        p.join(fixtureDir.path, 'variables', 'primitive_exports.dart'),
      ),
      expectedEsm: File(
        p.join(fixtureDir.path, 'variables', 'primitive_exports.mjs'),
      ),
    );
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-import-var-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final output = File(p.join(tempDir.path, 'a.mjs'));
    final consumer = File(p.join(tempDir.path, 'b.mjs'))
      ..writeAsStringSync("import { c } from './a.mjs';\nconsole.log(c);\n");

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: fixture.source.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        runMain: false,
        allowLegacyOracle: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(result.compilerPath, Dart2EsmCompilerPath.newCore);
    expect(output.readAsStringSync(), _withoutMainCall(fixture.expectedCode));

    final nodeRun = await Process.run('node', [
      consumer.path,
    ], workingDirectory: tempDir.path);
    expect(nodeRun.exitCode, 0, reason: '${nodeRun.stdout}\n${nodeRun.stderr}');
    expect(nodeRun.stdout, '1\n');
    expect(nodeRun.stderr, isEmpty);
  });

  test('direct class imports preserve interface instanceof checks', () async {
    final fixture = _GoldenFixture(
      root: fixtureDir,
      source: File(p.join(fixtureDir.path, 'classes', 'interfaces.dart')),
      expectedEsm: File(p.join(fixtureDir.path, 'classes', 'interfaces.mjs')),
    );
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-import-interface-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final output = File(p.join(tempDir.path, 'interfaces.mjs'));
    final consumer = File(p.join(tempDir.path, 'consumer.mjs'))
      ..writeAsStringSync(
        "import { NamedThing, Person } from './interfaces.mjs';\n"
        "const person = new Person('ada');\n"
        "console.log(person.name);\n"
        "console.log(person.describe());\n"
        "console.log(person instanceof NamedThing);\n",
      );

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: fixture.source.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        runMain: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(output.readAsStringSync(), _withoutMainCall(fixture.expectedCode));

    final nodeRun = await Process.run('node', [
      consumer.path,
    ], workingDirectory: tempDir.path);
    expect(nodeRun.exitCode, 0, reason: '${nodeRun.stdout}\n${nodeRun.stderr}');
    expect(
      nodeRun.stdout,
      'ada\n'
      'person:ada\n'
      'true\n',
    );
    expect(nodeRun.stderr, isEmpty);
  });

  test('direct extension type imports expose an ESM class facade', () async {
    final fixture = _GoldenFixture(
      root: fixtureDir,
      source: File(p.join(fixtureDir.path, 'classes', 'extension_types.dart')),
      expectedEsm: File(
        p.join(fixtureDir.path, 'classes', 'extension_types.mjs'),
      ),
    );
    final tempDir = await Directory.systemTemp.createTemp(
      'dart2esm-import-extension-type-',
    );
    addTearDown(() => tempDir.deleteSync(recursive: true));
    final output = File(p.join(tempDir.path, 'extension_types.mjs'));
    final consumer = File(p.join(tempDir.path, 'consumer.mjs'))
      ..writeAsStringSync(
        "import { UserId } from './extension_types.mjs';\n"
        "const id = new UserId(5);\n"
        "console.log(id.value);\n"
        "console.log(id.plus(2));\n"
        "console.log(id.doubled);\n"
        "id.observed = 1;\n"
        "console.log(id.value);\n"
        "console.log(id instanceof UserId);\n"
        "const parsed = UserId.parse('9');\n"
        "console.log(parsed.value);\n"
        "console.log(UserId.zeroValue);\n"
        "console.log(UserId.defaultValue);\n"
        "console.log(UserId.current.value);\n"
        "UserId.current = UserId.parse('6');\n"
        "console.log(UserId.current.value);\n"
        "console.log(UserId.zero().value);\n"
        "console.log(id['+'](3).value);\n",
      );

    final result = await compileDartToEsm(
      Dart2EsmOptions(
        inputPath: fixture.source.path,
        outputPath: output.path,
        workingDirectory: Directory.current,
        runMain: false,
      ),
    );

    expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
    expect(output.readAsStringSync(), _withoutMainCall(fixture.expectedCode));

    final nodeRun = await Process.run('node', [
      consumer.path,
    ], workingDirectory: tempDir.path);
    expect(nodeRun.exitCode, 0, reason: '${nodeRun.stdout}\n${nodeRun.stderr}');
    expect(
      nodeRun.stdout,
      '5\n'
      '7\n'
      '10\n'
      '5\n'
      'true\n'
      '9\n'
      '0\n'
      '12\n'
      '1\n'
      '6\n'
      '0\n'
      '8\n',
    );
    expect(nodeRun.stderr, isEmpty);
  });

  for (final fixture in _goldenFixtures(fixtureDir)) {
    test('matches ${fixture.id} ESM golden and runtime behavior', () async {
      await _expectGoldenFixture(fixture);
    });
  }
}

Future<void> _expectLocalImportSurface(
  Directory fixtureDir,
  Directory tempDir,
) async {
  final exportsSource = File(
    p.join(fixtureDir.path, 'imports', 'exports_api.dart'),
  );
  final exportsExpected = File(
    p.join(fixtureDir.path, 'imports', 'exports_api.mjs'),
  );
  final exportsModule = File(p.join(tempDir.path, 'exports_module.mjs'));
  final exportsResult = await compileDartToEsm(
    Dart2EsmOptions(
      inputPath: exportsSource.path,
      outputPath: exportsModule.path,
      workingDirectory: Directory.current,
      runMain: false,
      allowLegacyOracle: false,
    ),
  );

  expect(
    exportsResult.success,
    isTrue,
    reason: exportsResult.diagnostics.join('\n'),
  );
  expect(exportsResult.compilerPath, Dart2EsmCompilerPath.newCore);
  expect(
    exportsModule.readAsStringSync(),
    _withoutMainCall(exportsExpected.readAsStringSync()),
  );

  final reexportSource = File(
    p.join(fixtureDir.path, 'imports', 'reexport_api.dart'),
  );
  final reexportExpected = File(
    p.join(fixtureDir.path, 'imports', 'reexport_api.mjs'),
  );
  final reexportModule = File(p.join(tempDir.path, 'reexport_module.mjs'));
  final reexportResult = await compileDartToEsm(
    Dart2EsmOptions(
      inputPath: reexportSource.path,
      outputPath: reexportModule.path,
      workingDirectory: Directory.current,
      runMain: false,
      allowLegacyOracle: false,
    ),
  );

  expect(
    reexportResult.success,
    isTrue,
    reason: reexportResult.diagnostics.join('\n'),
  );
  expect(reexportResult.compilerPath, Dart2EsmCompilerPath.newCore);
  expect(
    reexportModule.readAsStringSync(),
    _withoutMainCall(reexportExpected.readAsStringSync()),
  );

  final consumer = File(p.join(tempDir.path, 'consumer.mjs'))
    ..writeAsStringSync('''
const exportsApi = await import('./exports_module.mjs');
console.log([
  Object.hasOwn(exportsApi, 'ExportedThing'),
  Object.hasOwn(exportsApi, 'exportedValue'),
  Object.hasOwn(exportsApi, 'HiddenThing'),
  Object.hasOwn(exportsApi, 'hiddenValue'),
].join(' '));
const reexportApi = await import('./reexport_module.mjs');
console.log([
  Object.hasOwn(reexportApi, 'BarrelThing'),
  Object.hasOwn(reexportApi, 'LeafThing'),
  Object.hasOwn(reexportApi, 'leafValue'),
  Object.hasOwn(reexportApi, 'HiddenLeafThing'),
  Object.hasOwn(reexportApi, 'barrelValue'),
].join(' '));
''');
  final importResult = await Process.run('node', [
    consumer.path,
  ], workingDirectory: tempDir.path);

  expect(
    importResult.exitCode,
    0,
    reason: '${importResult.stdout}\n${importResult.stderr}',
  );
  expect(
    importResult.stdout,
    'true true false false\n'
    'true true true false false\n',
  );
  expect(importResult.stderr, isEmpty);
}

String _withoutMainCall(String code) {
  const mainCall = '\nmain();\n';
  expect(code.endsWith(mainCall), isTrue);
  final withoutMain = code.substring(0, code.length - mainCall.length);
  return code.startsWith('// Generated by dart2esm.')
      ? withoutMain
      : '$withoutMain\n';
}

List<_GoldenFixture> _goldenFixtures(Directory fixtureDir) {
  final sources =
      fixtureDir
          .listSync(recursive: true)
          .whereType<File>()
          .where((file) => file.path.endsWith('.dart'))
          .where((file) => File(p.setExtension(file.path, '.mjs')).existsSync())
          .toList()
        ..sort((left, right) => left.path.compareTo(right.path));
  return [
    for (final source in sources)
      _GoldenFixture(
        root: fixtureDir,
        source: source,
        expectedEsm: File(p.setExtension(source.path, '.mjs')),
      ),
  ];
}

Future<void> _expectGoldenFixture(_GoldenFixture fixture) async {
  final tempDir = await Directory.systemTemp.createTemp('dart2esm-golden-');
  addTearDown(() => tempDir.deleteSync(recursive: true));

  final output = File(p.join(tempDir.path, '${fixture.name}.mjs'));
  final result = await compileDartToEsm(
    Dart2EsmOptions(
      inputPath: fixture.source.path,
      outputPath: output.path,
      workingDirectory: Directory.current,
    ),
  );
  expect(result.success, isTrue, reason: result.diagnostics.join('\n'));
  expect(output.readAsStringSync(), fixture.expectedEsm.readAsStringSync());
  if (fixture.id == 'libraries/concurrent') {
    await _expectNodeOutput(output, 'concurrent 42\n');
    return;
  }
  if (fixture.id == 'libraries/html') {
    await _expectNodeOutputWithPrelude(output, '''
class ElementStub {
  constructor(tagName) {
    this.tagName = tagName;
    this.id = "";
    this.textContent = "";
    this.children = [];
  }
  append(node) {
    this.children.push(node);
    this.textContent += node.textContent ?? "";
    return node;
  }
  appendChild(node) {
    return this.append(node);
  }
}
const store = new Map();
const elementsById = new Map();
globalThis.Element = ElementStub;
globalThis.Node = ElementStub;
globalThis.document = {
  title: "",
  body: new ElementStub("body"),
  createElement: tagName => new ElementStub(tagName),
  querySelector: selector => selector.startsWith("#") ? elementsById.get(selector.slice(1)) ?? null : null,
};
const appendToBody = globalThis.document.body.append.bind(globalThis.document.body);
globalThis.document.body.append = node => {
  if (node.id) elementsById.set(node.id, node);
  return appendToBody(node);
};
globalThis.document.body.appendChild = globalThis.document.body.append;
globalThis.window = {
  localStorage: {
    getItem: key => store.has(String(key)) ? store.get(String(key)) : null,
    setItem: (key, value) => { store.set(String(key), String(value)); },
  },
};
''', 'html true ok root hello child true root\n');
    return;
  }
  if (fixture.id == 'libraries/indexed_db') {
    await _expectNodeOutputWithPrelude(output, '''
function makeRequest(result) {
  const listeners = new Map();
  return {
    result,
    error: null,
    addEventListener(type, callback) { listeners.set(type, callback); },
    dispatch(type) {
      const event = { target: this };
      listeners.get(type)?.(event);
      this["on" + type]?.(event);
    },
  };
}
class MemoryObjectStore {
  constructor() { this.data = new Map(); }
  put(value, key) {
    const request = makeRequest(key);
    queueMicrotask(() => { this.data.set(key, value); request.dispatch("success"); });
    return request;
  }
  get(key) {
    const request = makeRequest(this.data.get(key));
    queueMicrotask(() => request.dispatch("success"));
    return request;
  }
}
class MemoryDatabase {
  constructor(name) {
    this.name = name;
    this.stores = new Map();
  }
  createObjectStore(name) {
    const store = new MemoryObjectStore();
    this.stores.set(name, store);
    return store;
  }
  transaction() {
    return { objectStore: name => this.stores.get(name) };
  }
  close() {}
}
const indexedDB = {
  open(name) {
    const db = new MemoryDatabase(name);
    const request = makeRequest(db);
    queueMicrotask(() => {
      request.dispatch("upgradeneeded");
      request.dispatch("success");
    });
    return request;
  },
  deleteDatabase() {
    const request = makeRequest(null);
    queueMicrotask(() => request.dispatch("success"));
    return request;
  },
};
globalThis.indexedDB = indexedDB;
globalThis.window = { indexedDB };
''', 'indexedDB true ok dart2esm\n');
    return;
  }
  if (fixture.id == 'libraries/js') {
    await _expectNodeOutput(output, 'jsLegacy 5 ok true 12 4 3\n');
    return;
  }
  if (fixture.id == 'libraries/js_interop') {
    await _expectNodeOutput(
      output,
      'jsInterop true true 7 ok true\n'
      'jsInteropModern hello true 2 42 true true 9 true true true true true 1 yes true 1970\n'
      'jsUtil a2 5,12,4.5,8,1 true,false,true,true,true,true,true,true true true fallback,ok,2147483647 true,true,true,x,true,true,false,true,true\n'
      'jsExternal 8 3 1970\n'
      'jsPromise 11 11 13 17 19\n'
      'jsIterator unique dart2esm.shared true 1 2 true 1,2 3 true 5 21 true\n'
      'jsTyped 4 23 7,8,9 23\n'
      'jsBox 31 dart-ref true\n'
      'jsExport 9 counter:9 15\n'
      'jsFunction 7 8 true this:ok\n',
    );
    return;
  }
  if (fixture.id == 'libraries/svg') {
    await _expectNodeOutputWithPrelude(output, '''
class SvgElementStub {
  constructor(namespaceURI, tagName) {
    this.namespaceURI = namespaceURI;
    this.tagName = tagName;
    this.id = "";
    this.textContent = "";
    this.children = [];
    this.attributes = new Map();
  }
  append(node) {
    this.children.push(node);
    this.textContent += node.textContent ?? "";
    return node;
  }
  appendChild(node) { return this.append(node); }
  setAttribute(name, value) { this.attributes.set(String(name), String(value)); }
  getAttribute(name) { return this.attributes.has(String(name)) ? this.attributes.get(String(name)) : null; }
}
globalThis.SVGElement = SvgElementStub;
globalThis.Node = SvgElementStub;
globalThis.document = {
  createElementNS: (namespaceURI, tagName) => new SvgElementStub(namespaceURI, tagName),
};
''', 'svg root 0 0 10 10 1 Dart true\n');
    return;
  }
  if (fixture.id == 'libraries/web_gl') {
    await _expectNodeOutputWithPrelude(output, '''
class WebGLRenderingContext {
  clearColor() {}
  clear() {}
}
globalThis.WebGLRenderingContext = WebGLRenderingContext;
globalThis.window = { WebGLRenderingContext };
globalThis.document = {
  createElement: tagName => ({
    tagName,
    width: 0,
    height: 0,
    getContext: contextId => contextId === "webgl" ? new WebGLRenderingContext() : null,
  }),
};
''', 'webgl true 16388 16 8 true true true true\n');
    return;
  }
  if (fixture.id == 'libraries/web_audio') {
    await _expectNodeOutputWithPrelude(output, '''
class AudioContext {
  constructor() {
    this.currentTime = 1.5;
    this.destination = { connect() {} };
  }
  createGain() {
    return { gain: { value: 0.75 }, connect() {} };
  }
  createOscillator() {
    return { type: "sine", connect() {}, start() {}, stop() {} };
  }
}
globalThis.AudioContext = AudioContext;
globalThis.window = { AudioContext };
''', 'webAudio true 1.5 0.75 sine true true true\n');
    return;
  }
  await _expectSameDartAndNodeOutput(fixture.source, output);
}

Future<void> _expectNodeOutput(File output, String stdout) async {
  final nodeRun = await Process.run('node', [
    output.path,
  ], workingDirectory: output.parent.path);
  expect(nodeRun.exitCode, 0, reason: '${nodeRun.stdout}\n${nodeRun.stderr}');
  expect(nodeRun.stdout, stdout);
  expect(nodeRun.stderr, isEmpty);
}

Future<void> _expectNodeOutputWithPrelude(
  File output,
  String prelude,
  String stdout,
) async {
  final nodeRun = await Process.run('node', [
    '--input-type=module',
    '-e',
    '$prelude\nawait import(${jsonEncode(output.uri.toString())});',
  ], workingDirectory: output.parent.path);
  expect(nodeRun.exitCode, 0, reason: '${nodeRun.stdout}\n${nodeRun.stderr}');
  expect(nodeRun.stdout, stdout);
  expect(nodeRun.stderr, isEmpty);
}

Future<void> _expectSameDartAndNodeOutput(File input, File output) async {
  final dartRun = await Process.run(Platform.resolvedExecutable, [
    input.path,
  ], workingDirectory: Directory.current.path);
  final nodeRun = await Process.run('node', [
    output.path,
  ], workingDirectory: output.parent.path);
  expect(nodeRun.exitCode, dartRun.exitCode);
  expect(nodeRun.stdout, dartRun.stdout);
  expect(nodeRun.stderr, dartRun.stderr);
}

final class _GoldenFixture {
  const _GoldenFixture({
    required this.root,
    required this.source,
    required this.expectedEsm,
  });

  final Directory root;
  final File source;
  final File expectedEsm;

  String get expectedCode => expectedEsm.readAsStringSync();

  String get id => p.withoutExtension(p.relative(source.path, from: root.path));

  String get name => p.basenameWithoutExtension(source.path);
}
