import 'package:dart2esm/src/kernel/sdk_symbols.dart';
import 'package:kernel/kernel.dart' as k;
import 'package:test/test.dart';

void main() {
  test('classifies legacy dart:js factory symbols', () {
    expect(
      legacyJsFactorySymbol(_reference('dart:js::JsObject::@factories::')),
      LegacyJsFactorySymbol.jsObject,
    );
    expect(
      legacyJsFactorySymbol(
        _reference('dart:js::JsObject::@factories::fromBrowserObject'),
      ),
      LegacyJsFactorySymbol.jsObjectFromBrowserObject,
    );
    expect(
      legacyJsFactorySymbol(
        _reference('dart:js::JsFunction::@factories::withThis'),
      ),
      LegacyJsFactorySymbol.jsFunctionWithThis,
    );
    expect(legacyJsFactorySymbol(_reference('dart:core::Object')), isNull);
  });

  test('classifies JS interop static getters', () {
    expect(
      jsInteropStaticGetSymbol(
        _reference('dart:js_util::@getters::globalThis'),
      ),
      JsInteropStaticGetSymbol.globalThis,
    );
    expect(
      jsInteropStaticGetSymbol(
        _reference('dart:js_util::@getters::objectPrototype'),
      ),
      JsInteropStaticGetSymbol.objectPrototype,
    );
    expect(jsInteropStaticGetSymbol(_reference('dart:core::Object')), isNull);
  });

  test('extracts JSSymbol getter names', () {
    expect(
      jsSymbolStaticGetterName(
        _reference('dart:js_interop::JSSymbol::@getters::iterator'),
      ),
      'iterator',
    );
    expect(jsSymbolStaticGetterName(_reference('dart:core::Object')), isNull);
  });

  test('matches kernel member path segments', () {
    expect(
      kernelPathHasMember('dart:core::String::@methods::contains', 'contains'),
      isTrue,
    );
    expect(
      kernelPathHasMember('dart:core::Object::@getters::hashCode', 'hashCode'),
      isTrue,
    );
    expect(
      kernelPathHasMember(
        'dart:core::Object::@setters::debugName',
        'debugName',
      ),
      isTrue,
    );
    expect(
      kernelPathHasMember('dart:core::Object::@getters::hashCode', 'debugName'),
      isFalse,
    );
  });

  test('classifies sdk library class members', () {
    expect(
      isDartSdkLibraryClassMember(
        _reference('dart:html::Element::@getters::children'),
        'dart:html',
        'Element',
        'children',
      ),
      isTrue,
    );
    expect(
      isDartSdkLibraryClassMember(
        _reference('dart:html::Node::@getters::children'),
        'dart:html',
        'Element',
        'children',
      ),
      isFalse,
    );
  });

  test('classifies dart:core members', () {
    expect(
      isDartCoreMember(
        _reference('dart:core::String::@methods::contains'),
        'String',
        'contains',
      ),
      isTrue,
    );
    expect(
      isDartCoreNumberMember(
        _reference('dart:core::double::@methods::round'),
        'round',
      ),
      isTrue,
    );
    expect(
      isDartCoreUriMember(
        _reference('dart:core::_Uri::@getters::path'),
        'path',
      ),
      isTrue,
    );
    expect(
      isDartCoreUriMember(
        _reference('dart:async::Future::@getters::path'),
        'path',
      ),
      isFalse,
    );
  });

  test('classifies dart:core Object static invocations', () {
    expect(
      dartCoreObjectStaticInvocationSymbol(
        _reference('dart:core::Object::@methods::hash'),
      ),
      DartCoreObjectStaticInvocationSymbol.hash,
    );
    expect(
      dartCoreObjectStaticInvocationSymbol(
        _reference('dart:core::Object::@methods::hashAll'),
      ),
      DartCoreObjectStaticInvocationSymbol.hashAll,
    );
    expect(
      dartCoreObjectStaticInvocationSymbol(
        _reference('dart:core::Object::@methods::hashAllUnordered'),
      ),
      DartCoreObjectStaticInvocationSymbol.hashAllUnordered,
    );
    expect(
      dartCoreObjectStaticInvocationSymbol(_reference('dart:core::Object')),
      isNull,
    );
  });

  test('classifies dart:developer symbols', () {
    expect(
      dartDeveloperStaticInvocationSymbol(
        _reference('dart:developer::@methods::inspect'),
      ),
      DartDeveloperStaticInvocationSymbol.inspect,
    );
    expect(
      dartDeveloperStaticInvocationSymbol(
        _reference('dart:developer::Timeline::@methods::timeSync'),
      ),
      DartDeveloperStaticInvocationSymbol.timelineTimeSync,
    );
    expect(
      dartDeveloperStaticInvocationSymbol(
        _reference('dart:developer::Service::@methods::getIsolateID'),
      ),
      DartDeveloperStaticInvocationSymbol.serviceGetIsolateId,
    );
    expect(
      dartDeveloperStaticInvocationSymbol(_reference('dart:core::Object')),
      isNull,
    );
    expect(
      dartDeveloperStaticGetSymbol(
        _reference('dart:developer::Timeline::@getters::now'),
      ),
      DartDeveloperStaticGetSymbol.timelineNow,
    );
    expect(
      dartDeveloperStaticGetSymbol(
        _reference('dart:developer::UserTag::@getters::defaultTag'),
      ),
      DartDeveloperStaticGetSymbol.userTagDefaultTag,
    );
    expect(
      dartDeveloperStaticGetSymbol(_reference('dart:core::Object')),
      isNull,
    );
  });

  test('classifies dart:math symbols', () {
    expect(
      dartMathStaticInvocationSymbol(_reference('dart:math::@methods::min')),
      DartMathStaticInvocationSymbol.min,
    );
    expect(
      dartMathStaticInvocationSymbol(
        _reference('dart:math::Random::@factories::secure'),
      ),
      DartMathStaticInvocationSymbol.randomSecure,
    );
    expect(
      dartMathStaticInvocationSymbol(
        _reference('dart:math::Rectangle::@factories::fromPoints'),
      ),
      DartMathStaticInvocationSymbol.rectangleFromPoints,
    );
    expect(
      dartMathStaticGetSymbol(_reference('dart:math::@fields::sqrt2')),
      DartMathStaticGetSymbol.sqrt2,
    );
    expect(
      isDartMathRectangleConstructorReference(
        _reference('dart:math::Rectangle::@constructors::'),
      ),
      isTrue,
    );
    expect(
      dartMathStaticInvocationSymbol(_reference('dart:core::Object')),
      isNull,
    );
  });

  test('classifies dart:core object and collection members', () {
    expect(
      isDartCoreWeakReferenceMember(
        _reference('dart:core::_WeakReference::@getters::target'),
        'target',
      ),
      isTrue,
    );
    expect(
      isDartCoreFinalizerMember(
        _reference('dart:core::_FinalizerImpl::@methods::detach'),
        'detach',
      ),
      isTrue,
    );
    expect(
      isDartCoreCollectionMember(
        _reference('dart:collection::ListQueue::@methods::add'),
        'add',
      ),
      isTrue,
    );
    expect(
      isDartCoreListMember(
        _reference('dart:_internal::_GrowableList::@methods::add'),
        'add',
      ),
      isTrue,
    );
    expect(
      isDartCoreSetMember(
        _reference('dart:_compact_hash::CompactLinkedHashSet::@methods::add'),
        'add',
      ),
      isTrue,
    );
    expect(
      isDartCoreMapMember(
        _reference('dart:core::_Map::@methods::containsKey'),
        'containsKey',
      ),
      isTrue,
    );
    expect(
      isDartCoreMapMember(
        _reference('dart:collection::MapBase::@methods::[]'),
        '[]',
      ),
      isTrue,
    );
    expect(
      isDartCoreMapMember(
        _reference('dart:collection::MapView::@methods::containsKey'),
        'containsKey',
      ),
      isTrue,
    );
    expect(
      isDartCoreCollectionMember(
        _reference('dart:async::Stream::@methods::map'),
        'map',
      ),
      isFalse,
    );
  });

  test('classifies dart:core references and constructors', () {
    expect(
      isDartCoreReference(
        _reference('dart:core::@methods::print'),
        '@methods',
        'print',
      ),
      isTrue,
    );
    expect(
      isDartCoreGrowableListLiteral(
        _reference('dart:core::_GrowableList::@factories::dart:core::_literal'),
      ),
      isTrue,
    );
    expect(
      isDartCoreGrowableListFactory(
        _reference('dart:core::_GrowableList::@factories::filled'),
      ),
      isTrue,
    );
    expect(
      isDartCoreObjectConstructorReference(
        _reference('dart:core::Object::@constructors::'),
      ),
      isTrue,
    );
    expect(
      dartCoreExceptionReferenceName(_reference('dart:core::FormatException')),
      'FormatException',
    );
    expect(
      dartCoreExceptionConstructorTypeName(
        _reference('dart:core::StateError::@constructors::'),
      ),
      'StateError',
    );
    expect(
      dartCoreErrorConstructorName(
        _reference('dart:_internal::ReachabilityError::@constructors::'),
      ),
      'ReachabilityError',
    );
    expect(
      dartCoreErrorFactoryName(
        _reference('dart:core::ArgumentError::@factories::value'),
      ),
      'ArgumentError',
    );
  });

  test('classifies sdk static invocation symbols', () {
    expect(
      dartSdkStaticInvocationSymbol(
        _reference('dart:core::@methods::EnumName|get#name'),
      ),
      DartSdkStaticInvocationSymbol.coreEnumName,
    );
    expect(
      dartSdkStaticInvocationSymbol(
        _reference('dart:core::@methods::EnumByName|byName'),
      ),
      DartSdkStaticInvocationSymbol.coreEnumByName,
    );
    expect(
      dartSdkStaticInvocationSymbol(
        _reference('dart:core::@methods::DateTimeCopyWith|copyWith'),
      ),
      DartSdkStaticInvocationSymbol.coreDateTimeCopyWith,
    );
    expect(
      dartSdkStaticInvocationSymbol(
        _reference('dart:core::Function::@methods::apply'),
      ),
      DartSdkStaticInvocationSymbol.coreFunctionApply,
    );
    expect(
      dartSdkStaticInvocationSymbol(
        _reference('dart:core::Iterable::@methods::iterableToFullString'),
      ),
      DartSdkStaticInvocationSymbol.coreIterableToFullString,
    );
    expect(
      dartSdkStaticInvocationSymbol(
        _reference(
          'dart:collection::@methods::NullableIterableExtensions|get#nonNulls',
        ),
      ),
      DartSdkStaticInvocationSymbol.collectionNonNulls,
    );
    expect(
      dartSdkStaticInvocationSymbol(
        _reference(
          'dart:collection::@methods::IterableExtensions|elementAtOrNull',
        ),
      ),
      DartSdkStaticInvocationSymbol.collectionElementAtOrNull,
    );
    expect(
      dartSdkStaticInvocationSymbol(
        _reference('dart:_internal::@methods::checkNotNullable'),
      ),
      DartSdkStaticInvocationSymbol.internalCheckNotNullable,
    );
    expect(
      dartSdkStaticInvocationSymbol(
        _reference('dart:typed_data::BytesBuilder::@factories::'),
      ),
      DartSdkStaticInvocationSymbol.internalBytesBuilder,
    );
    expect(
      dartSdkStaticInvocationSymbol(
        _reference('dart:_internal::IterableElementError::@methods::tooMany'),
      ),
      DartSdkStaticInvocationSymbol.iterableElementErrorTooMany,
    );
    expect(
      dartSdkStaticInvocationSymbol(
        _reference('dart:collection::MapBase::@methods::mapToString'),
      ),
      DartSdkStaticInvocationSymbol.collectionMapBaseToString,
    );
    expect(
      dartSdkStaticInvocationSymbol(_reference('dart:core::Object')),
      isNull,
    );
  });

  test('classifies dart:async members', () {
    expect(
      isDartAsyncStreamMember(
        _reference('dart:async::Stream::@methods::listen'),
        'listen',
      ),
      isTrue,
    );
    expect(
      isDartAsyncStreamTransformerMember(
        _reference('dart:async::StreamTransformer::@methods::bind'),
        'bind',
      ),
      isTrue,
    );
    expect(
      isDartAsyncStreamConsumerMember(
        _reference('dart:async::StreamController::@getters::sink'),
        'sink',
      ),
      isTrue,
    );
    expect(
      isDartAsyncFutureMember(
        _reference('dart:async::Future::@methods::then'),
        'then',
      ),
      isTrue,
    );
    expect(
      isDartAsyncZoneMember(
        _reference('dart:async::Zone::@methods::run'),
        'run',
      ),
      isTrue,
    );
    expect(
      isDartAsyncZoneMember(
        _reference('dart:async::Future::@methods::run'),
        'run',
      ),
      isFalse,
    );
  });

  test('classifies dart:convert members', () {
    expect(
      isDartConvertStringConversionSinkMember(
        _reference('dart:convert::_StringAdapterSink::@methods::add'),
        'add',
      ),
      isTrue,
    );
    expect(
      isDartConvertConverterMember(
        _reference('dart:convert::Utf8Encoder::@methods::convert'),
        'convert',
      ),
      isTrue,
    );
    expect(
      isDartConvertLineSplitterMember(
        _reference('dart:convert::LineSplitter::@methods::convert'),
        'convert',
      ),
      isTrue,
    );
    expect(
      isDartConvertConverterMember(
        _reference('dart:core::Utf8Encoder::@methods::convert'),
        'convert',
      ),
      isFalse,
    );
  });

  test('classifies dart:typed_data members', () {
    expect(
      isDartTypedDataMember(
        _reference('dart:typed_data::Uint8List::@methods::sublist'),
        'sublist',
      ),
      isTrue,
    );
    expect(
      isDartTypedDataClassMember(
        _reference('dart:typed_data::ByteData::@methods::getUint8'),
        'ByteData',
        'getUint8',
      ),
      isTrue,
    );
    expect(
      isDartTypedDataByteBufferMember(
        _reference('dart:typed_data::ByteBuffer::@methods::asUint8List'),
        'asUint8List',
      ),
      isTrue,
    );
    expect(
      isDartTypedDataClassMember(
        _reference('dart:typed_data::Uint8List::@methods::getUint8'),
        'ByteData',
        'getUint8',
      ),
      isFalse,
    );
  });

  test('classifies sdk constructor references', () {
    expect(
      isDartCompactHashSetConstructorReference(
        _reference('dart:_compact_hash::_Set::@constructors::'),
      ),
      isTrue,
    );
    expect(
      isDartAsyncStreamIteratorConstructorReference(
        _reference('dart:async::_StreamIterator::@constructors::'),
      ),
      isTrue,
    );
    expect(
      isDartListIteratorConstructorReference(
        _reference('dart:collection::ListIterator::@constructors::'),
      ),
      isTrue,
    );
    expect(
      isDartFollowedByIterableConstructorReference(
        _reference(
          'dart:_internal::EfficientLengthFollowedByIterable::@constructors::',
        ),
      ),
      isTrue,
    );
    expect(
      isDartCoreExpandoConstructorReference(
        _reference('dart:core::Expando::@constructors::'),
      ),
      isTrue,
    );
    expect(
      isDartCoreWeakReferenceConstructorReference(
        _reference('dart:core::_WeakReference::@constructors::'),
      ),
      isTrue,
    );
    expect(
      isDartCoreFinalizerConstructorReference(
        _reference('dart:core::_FinalizerImpl::@constructors::'),
      ),
      isTrue,
    );
    expect(
      isDartInternalSymbolConstructorReference(
        _reference('dart:_internal::Symbol::@constructors::'),
      ),
      isTrue,
    );
    expect(
      isDartMathPointConstructorReference(
        _reference('dart:math::Point::@constructors::'),
      ),
      isTrue,
    );
    expect(
      isDartCollectionQueueConstructorReference(
        _reference('dart:collection::DoubleLinkedQueue::@constructors::'),
      ),
      isTrue,
    );
    expect(
      isDartEmptyIterableConstructorReference(
        _reference('dart:_internal::EmptyIterable::@constructors::'),
      ),
      isTrue,
    );
  });

  test('classifies internal iterable constructor paths', () {
    expect(
      isDartMappedIterableConstructorPath(
        'dart:_internal::MappedListIterable::@constructors::',
      ),
      isTrue,
    );
    expect(
      isDartWhereIterableConstructorPath(
        'dart:_internal::WhereIterable::@constructors::',
      ),
      isTrue,
    );
    expect(
      isDartExpandIterableConstructorPath(
        'dart:_internal::ExpandIterable::@constructors::',
      ),
      isTrue,
    );
    expect(
      isDartTakeIterableConstructorPath(
        'dart:_internal::EfficientLengthTakeIterable::@constructors::',
      ),
      isTrue,
    );
    expect(
      isDartSkipIterableConstructorPath(
        'dart:_internal::EfficientLengthSkipIterable::@constructors::',
      ),
      isTrue,
    );
    expect(
      isDartSubListIterableConstructorPath(
        'dart:_internal::SubListIterable::@constructors::',
      ),
      isTrue,
    );
    expect(
      isDartTakeWhileIterableConstructorPath(
        'dart:_internal::TakeWhileIterable::@constructors::',
      ),
      isTrue,
    );
    expect(
      isDartSkipWhileIterableConstructorPath(
        'dart:_internal::SkipWhileIterable::@constructors::',
      ),
      isTrue,
    );
    expect(
      isDartWhereTypeIterableConstructorPath(
        'dart:_internal::WhereTypeIterable::@constructors::',
      ),
      isTrue,
    );
    expect(
      isDartNonNullsIterableConstructorPath(
        'dart:_internal::NonNullsIterable::@constructors::',
      ),
      isTrue,
    );
    expect(
      isDartIndexedIterableConstructorPath(
        'dart:_internal::EfficientLengthIndexedIterable::@constructors::',
      ),
      isTrue,
    );
    expect(
      isDartListMapViewConstructorPath(
        'dart:_internal::ListMapView::@constructors::',
      ),
      isTrue,
    );
    expect(
      isDartListIndicesIterableConstructorPath(
        'dart:_internal::_ListIndicesIterable::@constructors::',
      ),
      isTrue,
    );
    expect(
      isDartReversedListIterableConstructorPath(
        'dart:_internal::ReversedListIterable::@constructors::',
      ),
      isTrue,
    );
  });
}

k.Reference _reference(String path) {
  final reference = k.Reference();
  reference.canonicalName = _FakeCanonicalName(path);
  return reference;
}

final class _FakeCanonicalName implements k.CanonicalName {
  _FakeCanonicalName(this.path);

  final String path;

  @override
  String toStringInternal() => path;

  @override
  dynamic noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
}
