import 'dart:convert';

import 'package:kernel/kernel.dart' as k;

EsmBackendResult emitEsm(k.Component component, {bool runMain = true}) {
  final emitter = _EsmEmitter(component, runMain: runMain);
  return emitter.emit();
}

final class EsmBackendResult {
  const EsmBackendResult({required this.code, required this.diagnostics});

  final String code;
  final List<String> diagnostics;
}

final class UnsupportedKernelNode implements Exception {
  UnsupportedKernelNode(this.node, this.context);

  final Object node;
  final String context;

  @override
  String toString() =>
      'Unsupported Kernel node in $context: ${node.runtimeType}';
}

final class _EsmEmitter {
  _EsmEmitter(this.component, {required this.runMain});

  final k.Component component;
  final bool runMain;
  var _buffer = StringBuffer();
  final _diagnostics = <String>[];
  final _procedureNames = <k.Procedure, String>{};
  final _classNames = <k.Class, String>{};
  final _fieldNames = <k.Field, _TopLevelFieldNames>{};
  final _variableNames = <k.VariableDeclaration, String>{};
  final _labelNames = <k.LabeledStatement, String>{};
  final _usedHelpers = <String>{};
  final _usedNames = <String>{};
  var _indent = 0;
  k.Class? _currentClass;

  EsmBackendResult emit() {
    final main = component.mainMethod;
    if (main == null) {
      throw UnsupportedKernelNode(component, 'component without main method');
    }
    final mainLibrary = main.enclosingLibrary;
    final libraries = _emittableLibraries(mainLibrary);
    for (final library in libraries) {
      _declareTopLevelNames(library);
    }

    writeln('// Generated by dart2esm.');
    writeln();
    for (final library in libraries) {
      _emitLibrary(library, export: identical(library, mainLibrary));
    }
    if (runMain) {
      _emitMainCall(main);
    }
    final body = _buffer.toString();
    final helpers = _emitHelpers();
    return EsmBackendResult(
      code: helpers.isEmpty ? body : '$helpers\n$body',
      diagnostics: List.unmodifiable(_diagnostics),
    );
  }

  List<k.Library> _emittableLibraries(k.Library mainLibrary) {
    final libraries = [
      for (final library in component.libraries)
        if (identical(library, mainLibrary) ||
            library.importUri.scheme != 'dart')
          library,
    ];
    libraries.sort((left, right) {
      if (identical(left, mainLibrary)) {
        return identical(right, mainLibrary) ? 0 : 1;
      }
      if (identical(right, mainLibrary)) {
        return -1;
      }
      return _librarySortKey(left).compareTo(_librarySortKey(right));
    });
    return libraries;
  }

  String _librarySortKey(k.Library library) {
    return library.fileUri.toString();
  }

  void _emitLibrary(k.Library library, {required bool export}) {
    for (final field in library.fields) {
      _emitTopLevelField(field, export: export);
      writeln();
    }
    for (final klass in library.classes) {
      _emitClass(klass, export: export);
      writeln();
    }
    for (final procedure in library.procedures) {
      if (procedure.kind == k.ProcedureKind.Method && !procedure.isExternal) {
        _emitProcedure(procedure, export: export);
        writeln();
      }
    }
  }

  void _declareTopLevelNames(k.Library library) {
    for (final field in library.fields) {
      _fieldNames[field] = _freshTopLevelFieldNames(field.name.text);
    }
    for (final klass in library.classes) {
      _classNames[klass] = _freshName(klass.name);
    }
    for (final procedure in library.procedures) {
      if (procedure.kind == k.ProcedureKind.Method) {
        _procedureNames[procedure] = _freshName(procedure.name.text);
      }
    }
  }

  _TopLevelFieldNames _freshTopLevelFieldNames(String name) {
    final base = _sanitizeIdentifier(name);
    return _TopLevelFieldNames(value: _freshName(base));
  }

  void _emitTopLevelField(k.Field field, {required bool export}) {
    if (!field.isStatic) {
      throw UnsupportedKernelNode(field, 'instance field in library scope');
    }
    if (field.isLate) {
      throw UnsupportedKernelNode(field, 'late top-level field');
    }
    final names = _fieldName(field);
    final initializer = field.initializer;
    if (field.isConst) {
      writeln(
        '${export ? 'export ' : ''}const ${names.value} = ${_emitTopLevelConstInitializer(field)};',
      );
      return;
    }
    _usedHelpers.add('__dartLazyField');
    final initializerCode = initializer == null
        ? 'null'
        : emitExpression(initializer);
    writeln(
      '${export ? 'export ' : ''}const ${names.value} = __dartLazyField(${jsonEncode(field.name.text)}, () => $initializerCode, ${field.hasSetter});',
    );
  }

  String _emitTopLevelConstInitializer(k.Field field) {
    final initializer = field.initializer;
    if (initializer == null) {
      return 'null';
    }
    if (initializer is k.ConstantExpression) {
      return _emitEsmConst(initializer.constant);
    }
    return switch (initializer) {
      k.NullLiteral() ||
      k.BoolLiteral() ||
      k.IntLiteral() ||
      k.DoubleLiteral() ||
      k.StringLiteral() ||
      k.StaticTearOff() => emitExpression(initializer),
      _ => throw UnsupportedKernelNode(field, 'top-level const initializer'),
    };
  }

  void _emitClass(k.Class klass, {required bool export}) {
    if (klass.isEnum) {
      _emitEnumClass(klass, export: export);
      return;
    }
    final supertype = klass.supertype;
    if (supertype != null && !_isCoreClass(supertype.className, 'Object')) {
      throw UnsupportedKernelNode(klass, 'class inheritance');
    }
    final previousClass = _currentClass;
    _currentClass = klass;
    writeln('${export ? 'export ' : ''}class ${_className(klass)} {');
    _indent++;
    if (klass.constructors.isEmpty) {
      _emitDefaultConstructor(klass);
    } else {
      for (final constructor in klass.constructors) {
        if (constructor.name.text.isNotEmpty) {
          throw UnsupportedKernelNode(constructor, 'named constructor');
        }
        if (_canOmitConstructor(constructor, klass)) {
          continue;
        }
        _emitConstructor(constructor, klass);
      }
    }
    for (final procedure in klass.procedures) {
      if (procedure.isExternal || procedure.isAbstract) {
        continue;
      }
      _emitMethod(procedure);
    }
    _indent--;
    writeln('}');
    _currentClass = previousClass;
  }

  void _emitEnumClass(k.Class klass, {required bool export}) {
    final valuesFields = klass.fields
        .where((field) => field.isStatic && field.name.text == 'values')
        .toList();
    final entries = klass.fields
        .where((field) => field.isStatic && field.name.text != 'values')
        .toList();
    if (valuesFields.length != 1 ||
        entries.isEmpty ||
        klass.fields.any((field) => !field.isStatic) ||
        klass.constructors.length != 1 ||
        klass.procedures.any(
          (procedure) => procedure.name.text != '_enumToString',
        )) {
      throw UnsupportedKernelNode(klass, 'enhanced enum');
    }

    final className = _className(klass);
    writeln('${export ? 'export ' : ''}class $className {');
    _indent++;
    writeln('constructor(index, name) {');
    _indent++;
    writeln(
      'Object.defineProperty(this, "index", { value: index, enumerable: true });',
    );
    writeln(
      'Object.defineProperty(this, "name", { value: name, enumerable: true });',
    );
    writeln('Object.freeze(this);');
    _indent--;
    writeln('}');
    writeln('toString() {');
    _indent++;
    writeln('return ${jsonEncode('${klass.name}.')} + this.name;');
    _indent--;
    writeln('}');
    _indent--;
    writeln('}');
    writeln('Object.defineProperties($className, {');
    _indent++;
    for (var i = 0; i < entries.length; i++) {
      final entry = entries[i];
      final comma = i == entries.length - 1 ? '' : ',';
      writeln(
        '${_propertyKey(entry.name.text)}: { value: new $className($i, ${jsonEncode(entry.name.text)}), enumerable: true }$comma',
      );
    }
    _indent--;
    writeln('});');
    writeln(
      'Object.defineProperty($className, "values", { value: Object.freeze([${entries.map((entry) => '$className.${_memberName(entry.name.text)}').join(', ')}]), enumerable: true });',
    );
  }

  void _emitDefaultConstructor(k.Class klass) {
    if (!klass.fields.any((field) => !field.isStatic)) {
      return;
    }
    writeln('constructor() {');
    _indent++;
    _emitInstanceFieldDefaults(klass);
    _indent--;
    writeln('}');
  }

  bool _canOmitConstructor(k.Constructor constructor, k.Class klass) {
    final function = constructor.function;
    if (klass.fields.any((field) => !field.isStatic) ||
        function.positionalParameters.isNotEmpty ||
        function.namedParameters.isNotEmpty ||
        constructor.initializers.any(_isEffectiveInitializer)) {
      return false;
    }
    return _isEmptyBody(function.body);
  }

  bool _isEffectiveInitializer(k.Initializer initializer) {
    return switch (initializer) {
      k.SuperInitializer(:final isSynthetic) => !isSynthetic,
      _ => true,
    };
  }

  bool _isEmptyBody(k.Statement? body) {
    return switch (body) {
      null || k.EmptyStatement() => true,
      k.Block(:final statements) => statements.every(_isEmptyBody),
      _ => false,
    };
  }

  void _emitConstructor(k.Constructor constructor, k.Class klass) {
    final function = constructor.function;
    if (function.asyncMarker != k.AsyncMarker.Sync) {
      throw UnsupportedKernelNode(constructor, 'async constructor');
    }
    writeln('constructor(${_emitParameterList(function)}) {');
    _indent++;
    _emitInstanceFieldDefaults(
      klass,
      skipFields: _initializedFields(constructor.initializers),
    );
    for (final initializer in constructor.initializers) {
      _emitInitializer(initializer);
    }
    final body = function.body;
    if (body != null) {
      _emitFunctionBody(body);
    }
    _indent--;
    writeln('}');
  }

  void _emitInitializer(k.Initializer initializer) {
    switch (initializer) {
      case k.FieldInitializer():
        final field = initializer.fieldReference.node;
        if (field is! k.Field) {
          throw UnsupportedKernelNode(initializer, 'field initializer');
        }
        writeln(
          'this.${_memberName(field.name.text)} = ${emitExpression(initializer.value)};',
        );
      case k.LocalInitializer():
        emitStatement(initializer.variable);
      case k.AssertInitializer():
        _diagnostics.add('AssertInitializer is currently emitted as a no-op.');
      case k.SuperInitializer():
        if (!initializer.isSynthetic) {
          throw UnsupportedKernelNode(initializer, 'super initializer');
        }
      default:
        throw UnsupportedKernelNode(initializer, 'initializer');
    }
  }

  Set<k.Field> _initializedFields(List<k.Initializer> initializers) {
    final fields = <k.Field>{};
    for (final initializer in initializers) {
      if (initializer is k.FieldInitializer) {
        final field = initializer.fieldReference.node;
        if (field is k.Field) {
          fields.add(field);
        }
      }
    }
    return fields;
  }

  void _emitInstanceFieldDefaults(
    k.Class klass, {
    Set<k.Field> skipFields = const {},
  }) {
    for (final field in klass.fields) {
      if (field.isStatic || skipFields.contains(field)) {
        continue;
      }
      final initializer = field.initializer;
      writeln(
        'this.${_memberName(field.name.text)} = ${initializer == null ? 'null' : emitExpression(initializer)};',
      );
    }
  }

  void _emitMethod(k.Procedure procedure) {
    final function = procedure.function;
    final asyncPrefix = switch (function.asyncMarker) {
      k.AsyncMarker.Sync => '',
      k.AsyncMarker.Async => 'async ',
      k.AsyncMarker.SyncStar || k.AsyncMarker.AsyncStar =>
        throw UnsupportedKernelNode(function, 'method ${procedure.name.text}'),
    };
    final name = _memberName(procedure.name.text);
    final prefix = switch (procedure.kind) {
      k.ProcedureKind.Method || k.ProcedureKind.Operator => '$asyncPrefix$name',
      k.ProcedureKind.Getter => 'get $name',
      k.ProcedureKind.Setter => 'set $name',
      k.ProcedureKind.Factory => throw UnsupportedKernelNode(
        procedure,
        'factory procedure',
      ),
    };
    writeln('$prefix(${_emitParameterList(function)}) {');
    _indent++;
    final body = function.body;
    if (body == null) {
      throw UnsupportedKernelNode(function, 'method body');
    }
    _emitFunctionBody(body);
    _indent--;
    writeln('}');
  }

  void _emitProcedure(k.Procedure procedure, {required bool export}) {
    final name = _procedureName(procedure);
    final function = procedure.function;
    final asyncPrefix = switch (function.asyncMarker) {
      k.AsyncMarker.Sync => '',
      k.AsyncMarker.Async => 'async ',
      k.AsyncMarker.SyncStar ||
      k.AsyncMarker.AsyncStar => throw UnsupportedKernelNode(
        function,
        'function ${procedure.name.text}',
      ),
    };
    writeln(
      '${export ? 'export ' : ''}${asyncPrefix}function $name(${_emitParameterList(function)}) {',
    );
    _indent++;
    final body = function.body;
    if (body == null) {
      throw UnsupportedKernelNode(function, 'external/abstract function body');
    }
    _emitFunctionBody(body);
    _indent--;
    writeln('}');
  }

  void _declareParameters(k.FunctionNode function) {
    for (final parameter in function.positionalParameters) {
      _declareVariable(parameter);
    }
    for (final parameter in function.namedParameters) {
      _declareVariable(parameter);
    }
  }

  String _functionAsyncPrefix(k.FunctionNode function, String context) {
    return switch (function.asyncMarker) {
      k.AsyncMarker.Sync => '',
      k.AsyncMarker.Async => 'async ',
      k.AsyncMarker.SyncStar ||
      k.AsyncMarker.AsyncStar => throw UnsupportedKernelNode(function, context),
    };
  }

  String _emitParameterList(k.FunctionNode function) {
    _declareParameters(function);
    final parameters = <String>[];
    for (var i = 0; i < function.positionalParameters.length; i++) {
      final parameter = function.positionalParameters[i];
      final name = _variableName(parameter);
      if (i < function.requiredParameterCount) {
        parameters.add(name);
      } else {
        parameters.add('$name = ${_defaultParameterValue(parameter)}');
      }
    }
    if (function.namedParameters.isNotEmpty) {
      parameters.add(
        '{ ${function.namedParameters.map(_emitNamedParameterBinding).join(', ')} } = {}',
      );
    }
    return parameters.join(', ');
  }

  String _emitNamedParameterBinding(k.VariableDeclaration parameter) {
    final name = parameter.name ?? _variableName(parameter);
    final local = _variableName(parameter);
    final binding =
        local == name && _isIdentifier(name) && !_reservedNames.contains(name)
        ? local
        : '${_propertyKey(name)}: $local';
    if (parameter.isRequired) {
      return binding;
    }
    return '$binding = ${_defaultParameterValue(parameter)}';
  }

  String _defaultParameterValue(k.VariableDeclaration parameter) {
    final initializer = parameter.initializer;
    return initializer == null ? 'null' : emitExpression(initializer);
  }

  void _emitFunctionBody(k.Statement body) {
    if (body is k.Block) {
      for (final statement in body.statements) {
        emitStatement(statement);
      }
    } else {
      emitStatement(body);
    }
  }

  void _emitMainCall(k.Procedure main) {
    final name = _procedureName(main);
    if (main.function.asyncMarker == k.AsyncMarker.Async) {
      writeln('await $name();');
    } else {
      writeln('$name();');
    }
  }

  void emitStatement(k.Statement statement) {
    switch (statement) {
      case k.ExpressionStatement():
        writeln('${emitExpression(statement.expression)};');
      case k.Block():
        writeln('{');
        _indent++;
        for (final child in statement.statements) {
          emitStatement(child);
        }
        _indent--;
        writeln('}');
      case k.EmptyStatement():
        break;
      case k.ReturnStatement():
        final expression = statement.expression;
        writeln(
          expression == null
              ? 'return;'
              : 'return ${emitExpression(expression)};',
        );
      case k.VariableDeclaration():
        _declareVariable(statement);
        final initializer = statement.initializer;
        final keyword = statement.isFinal || statement.isConst
            ? 'const'
            : 'let';
        writeln(
          '$keyword ${_variableName(statement)} = ${initializer == null ? 'null' : emitExpression(initializer)};',
        );
      case k.FunctionDeclaration():
        _emitFunctionDeclaration(statement);
      case k.IfStatement():
        writeln('if (${emitExpression(statement.condition)}) {');
        _indent++;
        emitStatement(statement.then);
        _indent--;
        final otherwise = statement.otherwise;
        if (otherwise == null || otherwise is k.EmptyStatement) {
          writeln('}');
        } else {
          writeln('} else {');
          _indent++;
          emitStatement(otherwise);
          _indent--;
          writeln('}');
        }
      case k.WhileStatement():
        writeln('while (${emitExpression(statement.condition)}) {');
        _indent++;
        emitStatement(statement.body);
        _indent--;
        writeln('}');
      case k.DoStatement():
        _emitDoStatement(statement);
      case k.ForStatement():
        _emitForStatement(statement);
      case k.ForInStatement():
        _emitForInStatement(statement);
      case k.SwitchStatement():
        _emitSwitchStatement(statement);
      case k.TryCatch():
        _emitTryCatch(statement);
      case k.TryFinally():
        writeln('try {');
        _indent++;
        emitStatement(statement.body);
        _indent--;
        writeln('} finally {');
        _indent++;
        emitStatement(statement.finalizer);
        _indent--;
        writeln('}');
      case k.BreakStatement():
        writeln('break ${_labelName(statement.target)};');
      case k.ContinueSwitchStatement():
        throw UnsupportedKernelNode(statement, 'continue switch statement');
      case k.LabeledStatement():
        writeln('${_labelName(statement)}:');
        emitStatement(statement.body);
      case k.AssertBlock():
        for (final child in statement.statements) {
          emitStatement(child);
        }
      case k.AssertStatement():
        _diagnostics.add('AssertStatement is currently emitted as a no-op.');
      default:
        throw UnsupportedKernelNode(statement, 'statement');
    }
  }

  void _emitFunctionDeclaration(k.FunctionDeclaration statement) {
    _declareVariable(statement.variable);
    final function = statement.function;
    final asyncPrefix = _functionAsyncPrefix(function, 'local function');
    writeln(
      '${asyncPrefix}function ${_variableName(statement.variable)}(${_emitParameterList(function)}) {',
    );
    _indent++;
    final body = function.body;
    if (body == null) {
      throw UnsupportedKernelNode(function, 'local function body');
    }
    _emitFunctionBody(body);
    _indent--;
    writeln('}');
  }

  void _emitDoStatement(k.DoStatement statement) {
    writeln('do {');
    _indent++;
    emitStatement(statement.body);
    _indent--;
    writeln('} while (${emitExpression(statement.condition)});');
  }

  void _emitForStatement(k.ForStatement statement) {
    if (statement.variables.length > 1) {
      throw UnsupportedKernelNode(
        statement,
        'for statement with multiple variables',
      );
    }
    final initializer = statement.variables.isEmpty
        ? ''
        : (() {
            final variable = statement.variables.single;
            _declareVariable(variable);
            final value = variable.initializer == null
                ? 'null'
                : emitExpression(variable.initializer!);
            return 'let ${_variableName(variable)} = $value';
          })();
    final condition = statement.condition == null
        ? ''
        : emitExpression(statement.condition!);
    final updates = statement.updates.map(emitExpression).join(', ');
    writeln('for ($initializer; $condition; $updates) {');
    _indent++;
    emitStatement(statement.body);
    _indent--;
    writeln('}');
  }

  void _emitForInStatement(k.ForInStatement statement) {
    if (statement.isAsync) {
      throw UnsupportedKernelNode(statement, 'await for statement');
    }
    final variable = statement.variable;
    _declareVariable(variable);
    final keyword = variable.isFinal || variable.isConst ? 'const' : 'let';
    writeln(
      'for ($keyword ${_variableName(variable)} of ${emitExpression(statement.iterable)}) {',
    );
    _indent++;
    emitStatement(statement.body);
    _indent--;
    writeln('}');
  }

  void _emitSwitchStatement(k.SwitchStatement statement) {
    writeln('switch (${emitExpression(statement.expression)}) {');
    _indent++;
    for (final switchCase in statement.cases) {
      for (final expression in switchCase.expressions) {
        writeln('case ${emitExpression(expression)}:');
      }
      if (switchCase.isDefault) {
        writeln('default:');
      }
      _indent++;
      emitStatement(switchCase.body);
      _indent--;
    }
    _indent--;
    writeln('}');
  }

  void _emitTryCatch(k.TryCatch statement) {
    if (statement.catches.length != 1) {
      throw UnsupportedKernelNode(statement, 'try/catch with multiple catches');
    }
    final catchNode = statement.catches.single;
    final exception = catchNode.exception;
    if (exception != null) {
      _declareVariable(exception);
    }
    writeln('try {');
    _indent++;
    emitStatement(statement.body);
    _indent--;
    writeln(
      '} catch (${exception == null ? '_e' : _variableName(exception)}) {',
    );
    _indent++;
    emitStatement(catchNode.body);
    _indent--;
    writeln('}');
  }

  String emitExpression(k.Expression expression) {
    switch (expression) {
      case k.StringLiteral():
        return jsonEncode(expression.value);
      case k.IntLiteral():
        return expression.value.toString();
      case k.DoubleLiteral():
        return _emitDouble(expression.value);
      case k.BoolLiteral():
        return expression.value ? 'true' : 'false';
      case k.NullLiteral():
        return 'null';
      case k.VariableGet():
        return _variableName(expression.variable);
      case k.VariableSet():
        return '${_variableName(expression.variable)} = ${emitExpression(expression.value)}';
      case k.StringConcatenation():
        if (expression.expressions.isEmpty) {
          return '""';
        }
        return expression.expressions.map(_emitStringPart).join(' + ');
      case k.StaticInvocation():
        return _emitStaticInvocation(expression);
      case k.StaticTearOff():
        return _emitStaticTearOff(expression);
      case k.InstanceInvocation():
        return _emitInstanceInvocation(
          expression.receiver,
          expression.name.text,
          expression.arguments,
        );
      case k.FunctionInvocation():
        return _emitFunctionInvocation(expression);
      case k.LocalFunctionInvocation():
        return '${_variableName(expression.variable)}(${_emitArguments(expression.arguments)})';
      case k.DynamicInvocation():
        return _emitDynamicInvocation(expression);
      case k.Not():
        return '!(${emitExpression(expression.operand)})';
      case k.LogicalExpression():
        final operator =
            expression.operatorEnum == k.LogicalExpressionOperator.AND
            ? '&&'
            : '||';
        return '(${emitExpression(expression.left)} $operator ${emitExpression(expression.right)})';
      case k.ConditionalExpression():
        return '(${emitExpression(expression.condition)} ? ${emitExpression(expression.then)} : ${emitExpression(expression.otherwise)})';
      case k.EqualsNull():
        return '(${emitExpression(expression.expression)} === null)';
      case k.EqualsCall():
        _usedHelpers.add('__dartEquals');
        return '__dartEquals(${emitExpression(expression.left)}, ${emitExpression(expression.right)})';
      case k.AwaitExpression():
        return 'await ${emitExpression(expression.operand)}';
      case k.Throw():
        return '(() => { throw ${emitExpression(expression.expression)}; })()';
      case k.ListLiteral():
        return '[${expression.expressions.map(emitExpression).join(', ')}]';
      case k.SetLiteral():
        return 'new Set([${expression.expressions.map(emitExpression).join(', ')}])';
      case k.MapLiteral():
        return 'new Map([${expression.entries.map((entry) => '[${emitExpression(entry.key)}, ${emitExpression(entry.value)}]').join(', ')}])';
      case k.RecordLiteral():
        return _emitRecordLiteral(expression);
      case k.RecordIndexGet():
        return '${emitExpression(expression.receiver)}.${_recordPositionalKey(expression.index)}';
      case k.RecordNameGet():
        return _emitPropertyGet(
          emitExpression(expression.receiver),
          expression.name,
        );
      case k.AsExpression():
        return emitExpression(expression.operand);
      case k.IsExpression():
        return _emitIsExpression(expression);
      case k.Let():
        return _emitLetExpression(expression);
      case k.StaticGet():
        return _emitStaticGet(expression);
      case k.StaticSet():
        return _emitStaticSet(expression);
      case k.ConstructorInvocation():
        return _emitConstructorInvocation(expression);
      case k.InstanceCreation():
        return _emitInstanceCreation(expression);
      case k.InstanceGet():
        return _emitInstanceGet(expression);
      case k.InstanceSet():
        return '${emitExpression(expression.receiver)}.${_memberName(expression.name.text)} = ${emitExpression(expression.value)}';
      case k.ThisExpression():
        return 'this';
      case k.ConstantExpression():
        return _emitEsmConst(expression.constant);
      case k.FunctionExpression():
        return _emitFunctionExpression(expression);
      default:
        throw UnsupportedKernelNode(expression, 'expression');
    }
  }

  String _emitFunctionExpression(k.FunctionExpression expression) {
    final function = expression.function;
    final asyncPrefix = _functionAsyncPrefix(function, 'function expression');
    final body = function.body;
    if (body == null) {
      throw UnsupportedKernelNode(function, 'function expression body');
    }
    final inlineBody = _emitInlineFunctionBody(body);
    if (inlineBody != null) {
      return '${asyncPrefix}function(${_emitParameterList(function)}) { $inlineBody }';
    }
    final bodyCode = _captureFunctionBody(body);
    return '${asyncPrefix}function(${_emitParameterList(function)}) {\n$bodyCode}';
  }

  String? _emitInlineFunctionBody(k.Statement body) {
    return switch (body) {
      k.ReturnStatement(:final expression) =>
        expression == null
            ? 'return;'
            : 'return ${emitExpression(expression)};',
      k.Block(statements: [final k.ReturnStatement statement]) =>
        _emitInlineFunctionBody(statement),
      _ => null,
    };
  }

  String _captureFunctionBody(k.Statement body) {
    final previousBuffer = _buffer;
    final previousIndent = _indent;
    final localBuffer = StringBuffer();
    _buffer = localBuffer;
    _indent = previousIndent + 1;
    _emitFunctionBody(body);
    _buffer = previousBuffer;
    _indent = previousIndent;
    return localBuffer.toString();
  }

  String _emitStringPart(k.Expression expression) {
    if (expression is k.StringLiteral) {
      return emitExpression(expression);
    }
    _usedHelpers.add('__dartStr');
    return '__dartStr(${emitExpression(expression)})';
  }

  String _emitRecordLiteral(k.RecordLiteral expression) {
    _usedHelpers.add('__dartRecord');
    final positional = expression.positional.map(emitExpression).join(', ');
    final named = _emitRecordNamedFields(expression.named);
    return '__dartRecord([$positional], $named)';
  }

  String _emitRecordNamedField(k.NamedExpression expression) {
    return '${_propertyKey(expression.name)}: ${emitExpression(expression.value)}';
  }

  String _emitRecordNamedFields(List<k.NamedExpression> fields) {
    if (fields.isEmpty) {
      return '{}';
    }
    return '{ ${fields.map(_emitRecordNamedField).join(', ')} }';
  }

  String _emitEsmConst(k.Constant constant) {
    switch (constant) {
      case k.NullConstant():
        return 'null';
      case k.BoolConstant():
        return constant.value ? 'true' : 'false';
      case k.IntConstant():
        return constant.value.toString();
      case k.DoubleConstant():
        return _emitDouble(constant.value);
      case k.StringConstant():
        return jsonEncode(constant.value);
      case k.InstanceConstant():
        return _emitInstanceConstant(constant);
      case k.RecordConstant():
        _usedHelpers.add('__dartRecord');
        return '__dartRecord([${constant.positional.map(_emitEsmConst).join(', ')}], ${_emitRecordConstantNamedFields(constant.named)})';
      case k.StaticTearOffConstant():
        return _emitStaticTearOffReference(constant.targetReference, constant);
      case k.ListConstant():
        final enumValues = _emitEnumValuesConstant(constant);
        if (enumValues != null) {
          return enumValues;
        }
        throw UnsupportedKernelNode(
          constant,
          'const collection with Dart immutability/canonicalization semantics',
        );
      case k.SetConstant() || k.MapConstant():
        throw UnsupportedKernelNode(
          constant,
          'const collection with Dart immutability/canonicalization semantics',
        );
      default:
        throw UnsupportedKernelNode(constant, 'constant');
    }
  }

  String _emitDouble(double value) {
    if (value.isNaN) {
      return 'Number.NaN';
    }
    if (value == double.infinity) {
      return 'Infinity';
    }
    if (value == double.negativeInfinity) {
      return '-Infinity';
    }
    return value.toString();
  }

  String _emitInstanceConstant(k.InstanceConstant constant) {
    final classNode = constant.classReference.node;
    if (classNode is k.Class && classNode.isEnum) {
      final name = constant.fieldValues.values
          .whereType<k.StringConstant>()
          .single
          .value;
      return '${_className(classNode)}.${_memberName(name)}';
    }
    throw UnsupportedKernelNode(constant, 'instance constant');
  }

  String? _emitEnumValuesConstant(k.ListConstant constant) {
    k.Class? enumClass;
    final names = <String>[];
    for (final entry in constant.entries) {
      if (entry is! k.InstanceConstant) {
        return null;
      }
      final classNode = entry.classReference.node;
      if (classNode is! k.Class || !classNode.isEnum) {
        return null;
      }
      enumClass ??= classNode;
      if (enumClass != classNode) {
        return null;
      }
      names.add(
        entry.fieldValues.values.whereType<k.StringConstant>().single.value,
      );
    }
    final klass = enumClass;
    if (klass == null) {
      return null;
    }
    final enumEntryNames = klass.fields
        .where((field) => field.isStatic && field.name.text != 'values')
        .map((field) => field.name.text)
        .toList();
    if (names.length != enumEntryNames.length) {
      return null;
    }
    for (var i = 0; i < names.length; i++) {
      if (names[i] != enumEntryNames[i]) {
        return null;
      }
    }
    return '${_className(klass)}.values';
  }

  String _emitRecordConstantNamedFields(Map<String, k.Constant> fields) {
    if (fields.isEmpty) {
      return '{}';
    }
    return '{ ${fields.entries.map((entry) => '${_propertyKey(entry.key)}: ${_emitEsmConst(entry.value)}').join(', ')} }';
  }

  String _emitConstructorInvocation(k.ConstructorInvocation expression) {
    final target = expression.targetReference.node;
    if (target is! k.Constructor) {
      throw UnsupportedKernelNode(
        expression,
        'constructor invocation ${_referencePath(expression.targetReference)}',
      );
    }
    if (target.name.text.isNotEmpty) {
      throw UnsupportedKernelNode(expression, 'named constructor invocation');
    }
    final args = _emitArguments(expression.arguments);
    return 'new ${_className(target.enclosingClass)}($args)';
  }

  String _emitInstanceCreation(k.InstanceCreation expression) {
    final target = expression.classReference.node;
    if (target is! k.Class) {
      throw UnsupportedKernelNode(
        expression,
        'instance creation ${_referencePath(expression.classReference)}',
      );
    }
    if (expression.fieldValues.isNotEmpty || expression.asserts.isNotEmpty) {
      throw UnsupportedKernelNode(expression, 'lowered instance creation');
    }
    return 'new ${_className(target)}()';
  }

  String _emitStaticInvocation(k.StaticInvocation expression) {
    final positionalArgs = expression.arguments.positional
        .map(emitExpression)
        .toList();
    final args = _emitArguments(expression.arguments);
    if (_isCoreReference(
          expression.targetReference,
          '@methods',
          'EnumName|get#name',
        ) &&
        positionalArgs.length == 1) {
      return '${positionalArgs.single}.name';
    }
    if (_isCoreReference(expression.targetReference, '@methods', 'print')) {
      _usedHelpers.add('__dartPrint');
      _usedHelpers.add('__dartStr');
      return '__dartPrint($args)';
    }
    if (_isCoreGrowableListLiteral(expression.targetReference)) {
      return '[${positionalArgs.join(', ')}]';
    }
    final targetNode = expression.targetReference.node;
    if (targetNode is! k.Procedure) {
      throw UnsupportedKernelNode(
        expression,
        'static invocation ${_referencePath(expression.targetReference)}',
      );
    }
    final target = targetNode;
    if (_procedureNames.containsKey(target)) {
      return '${_procedureName(target)}($args)';
    }
    throw UnsupportedKernelNode(
      expression,
      'static invocation ${target.name.text}',
    );
  }

  String _emitStaticTearOff(k.StaticTearOff expression) {
    return _emitStaticTearOffReference(expression.targetReference, expression);
  }

  String _emitStaticTearOffReference(k.Reference reference, Object node) {
    final target = reference.node;
    if (target is k.Procedure && _procedureNames.containsKey(target)) {
      return _procedureName(target);
    }
    throw UnsupportedKernelNode(
      node,
      'static tear-off ${_referencePath(reference)}',
    );
  }

  String _emitStaticGet(k.StaticGet expression) {
    final target = expression.targetReference.node;
    if (target is k.Field && _fieldNames.containsKey(target)) {
      if (target.isConst) {
        return _fieldName(target).value;
      }
      return '${_fieldName(target).value}.get()';
    }
    if (target is k.Field && target.enclosingClass?.isEnum == true) {
      return '${_className(target.enclosingClass!)}.${_memberName(target.name.text)}';
    }
    if (target is k.Procedure && _procedureNames.containsKey(target)) {
      return _procedureName(target);
    }
    throw UnsupportedKernelNode(
      expression,
      'static get ${_referencePath(expression.targetReference)}',
    );
  }

  String _emitStaticSet(k.StaticSet expression) {
    final target = expression.targetReference.node;
    if (target is k.Field && _fieldNames.containsKey(target)) {
      if (!target.hasSetter) {
        throw UnsupportedKernelNode(expression, 'write to final field');
      }
      return '${_fieldName(target).value}.set(${emitExpression(expression.value)})';
    }
    throw UnsupportedKernelNode(
      expression,
      'static set ${_referencePath(expression.targetReference)}',
    );
  }

  String _emitInstanceInvocation(
    k.Expression receiver,
    String name,
    k.Arguments arguments,
  ) {
    final left = emitExpression(receiver);
    final positionalArgs = arguments.positional.map(emitExpression).toList();
    final args = _emitArguments(arguments);
    if (arguments.named.isEmpty &&
        positionalArgs.length == 1 &&
        _binaryOperators.contains(name)) {
      final operator = name == '~/' ? null : name;
      if (operator != null) {
        return '($left $operator ${positionalArgs.single})';
      }
      _usedHelpers.add('__dartTruncDiv');
      return '__dartTruncDiv($left, ${positionalArgs.single})';
    }
    if (arguments.named.isEmpty && name == '[]' && positionalArgs.length == 1) {
      return '$left[${positionalArgs.single}]';
    }
    if (arguments.named.isEmpty &&
        name == '[]=' &&
        positionalArgs.length == 2) {
      return '$left[${positionalArgs[0]}] = ${positionalArgs[1]}';
    }
    if (arguments.named.isEmpty &&
        positionalArgs.isEmpty &&
        name == 'toString') {
      _usedHelpers.add('__dartStr');
      return '__dartStr($left)';
    }
    return '$left.${_memberName(name)}($args)';
  }

  String _emitFunctionInvocation(k.FunctionInvocation expression) {
    return '(${emitExpression(expression.receiver)})(${_emitArguments(expression.arguments)})';
  }

  String _emitInstanceGet(k.InstanceGet expression) {
    final name = expression.name.text;
    if (name == 'iterator') {
      _usedHelpers.add('__dartIterator');
      return '__dartIterator(${emitExpression(expression.receiver)})';
    }
    return '${emitExpression(expression.receiver)}.${_memberName(name)}';
  }

  String _emitDynamicInvocation(k.DynamicInvocation expression) {
    final receiver = emitExpression(expression.receiver);
    final name = expression.name.text;
    final args = _emitArguments(expression.arguments);
    return '$receiver.$name($args)';
  }

  String _emitArguments(k.Arguments arguments) {
    final args = arguments.positional.map(emitExpression).toList();
    if (arguments.named.isNotEmpty) {
      args.add('{ ${arguments.named.map(_emitNamedArgument).join(', ')} }');
    }
    return args.join(', ');
  }

  String _emitNamedArgument(k.NamedExpression argument) {
    return '${_propertyKey(argument.name)}: ${emitExpression(argument.value)}';
  }

  String _emitIsExpression(k.IsExpression expression) {
    final operand = emitExpression(expression.operand);
    final type = expression.type;
    if (type is k.InterfaceType) {
      final typeName = type.classNode.name;
      return switch (typeName) {
        'String' => 'typeof $operand === "string"',
        'int' || 'double' || 'num' => 'typeof $operand === "number"',
        'bool' => 'typeof $operand === "boolean"',
        'Null' => '$operand === null',
        _ => throw UnsupportedKernelNode(expression, 'is $typeName'),
      };
    }
    throw UnsupportedKernelNode(expression, 'is expression');
  }

  String _emitLetExpression(k.Let expression) {
    _declareVariable(expression.variable);
    final initializer = expression.variable.initializer == null
        ? 'null'
        : emitExpression(expression.variable.initializer!);
    return '(() => { let ${_variableName(expression.variable)} = $initializer; return ${emitExpression(expression.body)}; })()';
  }

  bool _isCoreReference(k.Reference reference, String namespace, String name) {
    return _referencePath(reference) == 'dart:core::$namespace::$name';
  }

  bool _isCoreGrowableListLiteral(k.Reference reference) {
    return _referencePath(
      reference,
    ).startsWith('dart:core::_GrowableList::@factories::dart:core::_literal');
  }

  bool _isCoreClass(k.Reference reference, String name) {
    return _referencePath(reference) == 'dart:core::$name';
  }

  String _referencePath(k.Reference reference) {
    return reference.canonicalName?.toStringInternal() ??
        reference.node?.toStringInternal() ??
        '<unbound>';
  }

  void _declareVariable(k.VariableDeclaration variable) {
    _variableNames.putIfAbsent(
      variable,
      () => _freshName(variable.name ?? 'v'),
    );
  }

  String _variableName(k.VariableDeclaration variable) {
    return _variableNames.putIfAbsent(
      variable,
      () => _freshName(variable.name ?? 'v'),
    );
  }

  String _labelName(k.LabeledStatement statement) {
    return _labelNames.putIfAbsent(statement, () => _freshName('L'));
  }

  String _procedureName(k.Procedure procedure) {
    return _procedureNames.putIfAbsent(
      procedure,
      () => _freshName(procedure.name.text),
    );
  }

  String _className(k.Class klass) {
    return _classNames.putIfAbsent(klass, () => _freshName(klass.name));
  }

  _TopLevelFieldNames _fieldName(k.Field field) {
    return _fieldNames[field] ??= _freshTopLevelFieldNames(field.name.text);
  }

  String _memberName(String name) {
    if (_isIdentifier(name) && !_reservedNames.contains(name)) {
      return name;
    }
    return _sanitizeIdentifier(name);
  }

  String _propertyKey(String name) {
    if (_isIdentifier(name) && !_reservedNames.contains(name)) {
      return name;
    }
    return jsonEncode(name);
  }

  String _emitPropertyGet(String receiver, String name) {
    if (_isIdentifier(name) && !_reservedNames.contains(name)) {
      return '$receiver.$name';
    }
    return '$receiver[${jsonEncode(name)}]';
  }

  String _recordPositionalKey(int index) => '\$${index + 1}';

  bool _isIdentifier(String name) {
    if (name.isEmpty) {
      return false;
    }
    for (var i = 0; i < name.length; i++) {
      final code = name.codeUnitAt(i);
      final isAlpha = code >= 65 && code <= 90 || code >= 97 && code <= 122;
      final isDigit = code >= 48 && code <= 57;
      final isValid = isAlpha || isDigit || code == 95 || code == 36;
      if (!isValid || i == 0 && isDigit) {
        return false;
      }
    }
    return true;
  }

  String _freshName(String original) {
    final sanitized = _sanitizeIdentifier(original);
    var candidate = sanitized;
    var suffix = 0;
    while (_reservedNames.contains(candidate) ||
        _usedNames.contains(candidate)) {
      suffix++;
      candidate = '${sanitized}_$suffix';
    }
    _usedNames.add(candidate);
    return candidate;
  }

  String _sanitizeIdentifier(String name) {
    final buffer = StringBuffer();
    for (var i = 0; i < name.length; i++) {
      final code = name.codeUnitAt(i);
      final isAlpha = code >= 65 && code <= 90 || code >= 97 && code <= 122;
      final isDigit = code >= 48 && code <= 57;
      final isValid = isAlpha || isDigit || code == 95 || code == 36;
      if (i == 0 && isDigit) {
        buffer.write('_');
      }
      buffer.write(isValid ? name[i] : '_');
    }
    final result = buffer.toString();
    return result.isEmpty ? 'v' : result;
  }

  String _emitHelpers() {
    final helper = StringBuffer();
    final usesRecord = _usedHelpers.contains('__dartRecord');
    if (usesRecord) {
      helper.writeln('const __dartRecordShape = Symbol("dart.recordShape");');
      helper.writeln('function __dartIsRecord(value) {');
      helper.writeln(
        '  return value != null && typeof value === "object" && Array.isArray(value[__dartRecordShape]);',
      );
      helper.writeln('}');
    }
    if (_usedHelpers.contains('__dartStr')) {
      helper.writeln('function __dartStr(value) {');
      helper.writeln('  return value == null ? "null" : String(value);');
      helper.writeln('}');
    }
    if (_usedHelpers.contains('__dartPrint')) {
      helper.writeln('function __dartPrint(value) {');
      helper.writeln('  console.log(__dartStr(value));');
      helper.writeln('}');
    }
    if (_usedHelpers.contains('__dartEquals')) {
      helper.writeln('function __dartEquals(left, right) {');
      if (usesRecord) {
        helper.writeln('  if (left === right) return true;');
        helper.writeln(
          '  if (__dartIsRecord(left) && __dartIsRecord(right)) {',
        );
        helper.writeln('    const leftShape = left[__dartRecordShape];');
        helper.writeln('    const rightShape = right[__dartRecordShape];');
        helper.writeln(
          '    if (leftShape.length !== rightShape.length) return false;',
        );
        helper.writeln('    for (let i = 0; i < leftShape.length; i++) {');
        helper.writeln('      const name = leftShape[i];');
        helper.writeln('      if (name !== rightShape[i]) return false;');
        helper.writeln(
          '      if (!__dartEquals(left[name], right[name])) return false;',
        );
        helper.writeln('    }');
        helper.writeln('    return true;');
        helper.writeln('  }');
        helper.writeln('  return false;');
      } else {
        helper.writeln('  return left === right;');
      }
      helper.writeln('}');
    }
    if (_usedHelpers.contains('__dartTruncDiv')) {
      helper.writeln('function __dartTruncDiv(left, right) {');
      helper.writeln('  return Math.trunc(left / right);');
      helper.writeln('}');
    }
    if (_usedHelpers.contains('__dartRecord')) {
      helper.writeln('function __dartRecord(positional, named) {');
      helper.writeln('  const record = {};');
      helper.writeln('  const shape = [];');
      helper.writeln('  for (let i = 0; i < positional.length; i++) {');
      helper.writeln('    const name = "\$" + (i + 1);');
      helper.writeln('    shape.push(name);');
      helper.writeln(
        '    Object.defineProperty(record, name, { value: positional[i], enumerable: true });',
      );
      helper.writeln('  }');
      helper.writeln('  for (const name of Object.keys(named).sort()) {');
      helper.writeln('    shape.push(name);');
      helper.writeln(
        '    Object.defineProperty(record, name, { value: named[name], enumerable: true });',
      );
      helper.writeln('  }');
      helper.writeln(
        '  Object.defineProperty(record, __dartRecordShape, { value: Object.freeze(shape) });',
      );
      helper.writeln('  Object.defineProperty(record, "toString", {');
      helper.writeln('    value() {');
      helper.writeln('      return "(" + shape.map((name) => {');
      helper.writeln('        const value = String(record[name]);');
      helper.writeln(
        '        return name.startsWith("\$") ? value : name + ": " + value;',
      );
      helper.writeln('      }).join(", ") + ")";');
      helper.writeln('    },');
      helper.writeln('  });');
      helper.writeln('  return Object.freeze(record);');
      helper.writeln('}');
    }
    if (_usedHelpers.contains('__dartLazyField')) {
      helper.writeln('function __dartLazyField(name, initialize, writable) {');
      helper.writeln('  let state = 0;');
      helper.writeln('  let value;');
      helper.writeln('  function get() {');
      helper.writeln('    if (state === 2) return value;');
      helper.writeln('    if (state === 1) {');
      helper.writeln(
        '      throw new Error("Cyclic initialization of top-level field " + name);',
      );
      helper.writeln('    }');
      helper.writeln('    state = 1;');
      helper.writeln('    try {');
      helper.writeln('      value = initialize();');
      helper.writeln('      state = 2;');
      helper.writeln('      return value;');
      helper.writeln('    } catch (error) {');
      helper.writeln('      state = 0;');
      helper.writeln('      throw error;');
      helper.writeln('    }');
      helper.writeln('  }');
      helper.writeln('  function set(next) {');
      helper.writeln('    if (!writable) {');
      helper.writeln(
        '      throw new TypeError("Cannot assign to final top-level field " + name);',
      );
      helper.writeln('    }');
      helper.writeln('    value = next;');
      helper.writeln('    state = 2;');
      helper.writeln('    return next;');
      helper.writeln('  }');
      helper.writeln('  return new Proxy({ get, set }, {');
      helper.writeln('    get(target, property, receiver) {');
      helper.writeln('      if (property === Symbol.toPrimitive) return get;');
      helper.writeln('      if (property === "valueOf") return get;');
      helper.writeln(
        '      if (property === "toString") return () => String(get());',
      );
      helper.writeln('      if (property === "value") return get();');
      helper.writeln('      return Reflect.get(target, property, receiver);');
      helper.writeln('    },');
      helper.writeln('    set(_target, property, next) {');
      helper.writeln('      if (property === "value") {');
      helper.writeln('        set(next);');
      helper.writeln('        return true;');
      helper.writeln('      }');
      helper.writeln('      return false;');
      helper.writeln('    },');
      helper.writeln('  });');
      helper.writeln('}');
    }
    if (_usedHelpers.contains('__dartIterator')) {
      helper.writeln('function __dartIterator(iterable) {');
      helper.writeln(
        '  const values = Array.isArray(iterable) ? iterable : Array.from(iterable);',
      );
      helper.writeln('  let index = -1;');
      helper.writeln('  return {');
      helper.writeln('    current: undefined,');
      helper.writeln('    moveNext() {');
      helper.writeln('      index++;');
      helper.writeln('      if (index < values.length) {');
      helper.writeln('        this.current = values[index];');
      helper.writeln('        return true;');
      helper.writeln('      }');
      helper.writeln('      this.current = undefined;');
      helper.writeln('      return false;');
      helper.writeln('    },');
      helper.writeln('  };');
      helper.writeln('}');
    }
    return helper.toString();
  }

  void writeln([String line = '']) {
    if (line.isEmpty) {
      _buffer.writeln();
      return;
    }
    _buffer.write('  ' * _indent);
    _buffer.writeln(line);
  }
}

final class _TopLevelFieldNames {
  const _TopLevelFieldNames({required this.value});

  final String value;
}

const _binaryOperators = {
  '+',
  '-',
  '*',
  '/',
  '~/',
  '%',
  '<',
  '<=',
  '>',
  '>=',
  '==',
};

const _reservedNames = {
  'await',
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'debugger',
  'default',
  'delete',
  'do',
  'else',
  'export',
  'extends',
  'finally',
  'for',
  'function',
  'if',
  'import',
  'in',
  'instanceof',
  'let',
  'new',
  'return',
  'super',
  'switch',
  'this',
  'throw',
  'try',
  'typeof',
  'var',
  'void',
  'while',
  'with',
  'yield',
};
