function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartIndexGet(receiver, index) {
  if (Array.isArray(receiver) || (ArrayBuffer.isView(receiver) && !(receiver instanceof DataView)) || typeof receiver === "string") return receiver[index];
  const op = receiver?.["[]"];
  if (typeof op === "function") return op.call(receiver, index);
  return receiver[index];
}
function __dartEquals(left, right) {
  if (left === right) return true;
  if (left == null || right == null) return false;
  if ((typeof left === "number" || left.__dartType === "double") && (typeof right === "number" || right.__dartType === "double")) return Number(left) === Number(right);
  const equals = left["=="];
  return typeof equals === "function" ? equals.call(left, right) : false;
}
const __dartConstValues = new Map();
function __dartConst(key, create) {
  if (!__dartConstValues.has(key)) {
    __dartConstValues.set(key, create());
  }
  return __dartConstValues.get(key);
}

// Generated by dart2esm.

export class Box {
  constructor(value) {
    this.value = value;
    this.label = "box";
  }
  static named(value) {
    return $Box_named(Box, value);
  }
  static alias(value) {
    return Box.named(value);
  }
  describe() {
    return __dartStr(this.label) + ":" + __dartStr(this.value);
  }
}

function $Box_named($newTarget, value) {
  const $self = Object.create($newTarget.prototype);
  $self.value = value;
  $self.label = "named";
  return $self;
}

export class Options {
  constructor(value, { label = "options" } = {}) {
    this.value = value;
    this.label = label;
  }
  describe() {
    return __dartStr(this.label) + ":" + __dartStr(this.value);
  }
}

export class Holder {
  constructor(value) {
    this.value = value;
  }
  describe() {
    return __dartStr(this.value);
  }
}

export function main() {
  const unnamed = $Box_new_tearoff;
  const unnamedAgain = $Box_new_tearoff;
  const named = $Box_named_tearoff;
  const alias = $Box_alias_tearoff;
  const aliasType = $Box_new_tearoff;
  const options = $Options_new_tearoff;
  const intHolder = $Holder_new_tearoff;
  const constMakers = __dartConst("[\"list\",\"FunctionType(Box Function(int))\",[\"constructorTearOff\",\"constructor:Box.\"],[\"constructorTearOff\",\"constructor:Box.named\"],[\"redirectingFactoryTearOff\",\"procedure:Box.alias\"]]", () => Object.freeze([$Box_new_tearoff, $Box_named_tearoff, $Box_alias_tearoff]));
  __dartPrint((unnamed)(1).describe());
  __dartPrint((named)(2).describe());
  __dartPrint((alias)(3).describe());
  __dartPrint((aliasType)(4).describe());
  __dartPrint((options)(5).describe());
  __dartPrint((options)(6, { label: "custom" }).describe());
  __dartPrint((intHolder)(7).describe());
  __dartPrint((__dartIndexGet(__dartConst("[\"list\",\"FunctionType(Box Function(int))\",[\"constructorTearOff\",\"constructor:Box.\"],[\"constructorTearOff\",\"constructor:Box.named\"],[\"redirectingFactoryTearOff\",\"procedure:Box.alias\"]]", () => Object.freeze([$Box_new_tearoff, $Box_named_tearoff, $Box_alias_tearoff])), 0))(8).describe());
  __dartPrint((__dartIndexGet(__dartConst("[\"list\",\"FunctionType(Box Function(int))\",[\"constructorTearOff\",\"constructor:Box.\"],[\"constructorTearOff\",\"constructor:Box.named\"],[\"redirectingFactoryTearOff\",\"procedure:Box.alias\"]]", () => Object.freeze([$Box_new_tearoff, $Box_named_tearoff, $Box_alias_tearoff])), 1))(9).describe());
  __dartPrint((__dartIndexGet(__dartConst("[\"list\",\"FunctionType(Box Function(int))\",[\"constructorTearOff\",\"constructor:Box.\"],[\"constructorTearOff\",\"constructor:Box.named\"],[\"redirectingFactoryTearOff\",\"procedure:Box.alias\"]]", () => Object.freeze([$Box_new_tearoff, $Box_named_tearoff, $Box_alias_tearoff])), 2))(10).describe());
  __dartPrint(__dartEquals(unnamed, unnamedAgain));
  __dartPrint(__dartEquals(unnamed, $Box_new_tearoff));
}


function $Box_new_tearoff(value) {
  return new Box(value);
}

function $Box_named_tearoff(value) {
  return Box.named(value);
}

function $Box_alias_tearoff(value) {
  return Box.alias(value);
}

function $Options_new_tearoff(value, { label = "options" } = {}) {
  return new Options(value, { label: label });
}

function $Holder_new_tearoff(value) {
  return new Holder(value);
}
main();
