function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartFormatException(message) {
  const error = new Error(String(message));
  error.name = "FormatException";
  return error;
}
function __dartIntTryParse(source, radix = null) {
  const text = String(source).trim();
  let base = radix == null ? null : Number(radix);
  if (base != null && (!Number.isInteger(base) || base < 2 || base > 36)) return null;
  if (base == null && /^[+-]?0x[0-9a-f]+$/i.test(text)) return Number.parseInt(text, 16);
  base ??= 10;
  const sign = /^[+-]/.test(text) ? text[0] : "";
  const digits = sign === "" ? text : text.slice(1);
  if (digits.length === 0) return null;
  for (const char of digits.toLowerCase()) {
    const code = char.charCodeAt(0);
    const value = code >= 48 && code <= 57 ? code - 48 : code >= 97 && code <= 122 ? code - 87 : -1;
    if (value < 0 || value >= base) return null;
  }
  return Number.parseInt(text, base);
}
function __dartIntParse(source, radix = null) {
  const value = __dartIntTryParse(source, radix);
  if (value == null) throw __dartFormatException("Invalid integer literal");
  return value;
}
function __dartDoubleTryParse(source) {
  const text = String(source).trim();
  if (text === "") return null;
  const value = Number(text);
  return Number.isNaN(value) ? null : value;
}
function __dartDoubleParse(source) {
  const value = __dartDoubleTryParse(source);
  if (value == null) throw __dartFormatException("Invalid double literal");
  return value;
}
function __dartNumTryParse(source) {
  return __dartDoubleTryParse(source);
}
function __dartNumParse(source) {
  const value = __dartNumTryParse(source);
  if (value == null) throw __dartFormatException("Invalid number literal");
  return value;
}
function __dartAs(value, test, typeName) {
  if (test(value)) return value;
  throw new TypeError("Type cast failed: expected " + typeName);
}

// Generated by dart2esm.

export class UserId {
  static parse(text) {
    return UserId_parse(text);
  }
  static get zeroValue() {
    return UserId_zeroValue();
  }
  plus(amount) {
    return UserId_plus(this, amount);
  }
  "+"(amount) {
    return UserId__(this, amount);
  }
  constructor(value) {
    this.value = UserId_constructor_(value);
  }
}

function UserId_parse(text) {
  return new UserId(__dartIntParse(text, null));
}

function UserId_zeroValue() {
  return 0;
}

function UserId_plus(_this, amount) {
  return (__dartAs(_this.value, value => typeof value === "number", "int") + amount);
}

function UserId__(_this, amount) {
  return new UserId((__dartAs(_this.value, value => typeof value === "number", "int") + amount));
}

function UserId_constructor_(value) {
  const _this = value;
  return _this;
}

export function hide(value) {
  return value;
}

export function main() {
  const id = new UserId(5);
  const maybeId = hide(id);
  __dartPrint(__dartStr(__dartAs(id.value, value => typeof value === "number", "int")) + " " + __dartStr(id.plus(2)) + " " + __dartStr(maybeId instanceof UserId));
  __dartPrint(__dartStr(__dartAs(UserId.parse("9").value, value => typeof value === "number", "int")) + " " + __dartStr(UserId.zeroValue) + " " + __dartStr(__dartAs(id["+"](3).value, value => typeof value === "number", "int")));
}

main();
