// Generated by dart2esm.

function __dartPrint(value) {
  console.log(__dartStr(value));
}

function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}

export class Animal {
  constructor(name) {
    Object.defineProperty(this, "name", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "name", { value: name, writable: true, enumerable: true, configurable: true });
  }
  get label() {
    return `animal ${__dartStr(this.name)}`;
  }
  set label(value) {
    this.name = value;
  }
  describe() {
    return `animal ${__dartStr(this.name)}`;
  }
}

export class Dog extends Animal {
  constructor(name, age) {
    super(name);
    Object.defineProperty(this, "age", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "age", { value: age, writable: true, enumerable: true, configurable: true });
  }
  describe() {
    return `${__dartStr(super.describe())} dog ${__dartStr(this.age)}`;
  }
  birthday() {
    this.age = this.age + 1;
    return this.describe();
  }
  rename(value) {
    super.label = value;
    return super.label;
  }
}

export function identity(value) {
  return value;
}

export function main() {
  const dog = new Dog("Rex", 4);
  const value = identity(dog);
  __dartPrint(dog.describe());
  __dartPrint(dog.birthday());
  __dartPrint(dog.rename("Ada"));
  __dartPrint(dog.describe());
  __dartPrint(`animal ${__dartStr(value instanceof Animal)}`);
  __dartPrint(`dog ${__dartStr(value instanceof Dog)}`);
}

main();
