function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}

// Generated by dart2esm.

export class Box {
  constructor(value) {
    this.value = value;
  }
  read() {
    return this.value;
  }
}

export class Named {
  label() {
    return "name:" + __dartStr(this.name);
  }
}

export class _User_Object_Named extends Named {
  constructor() {
    super();
  }
  label() {
    return "name:" + __dartStr(this.name);
  }
}

export class User extends _User_Object_Named {
  constructor(name) {
    super();
    this.name = name;
  }
}

export function identity(value) {
  return value;
}

export function StringTools_twice(_this) {
  return (_this + _this);
}

export function StringTools_get_twice(_this) {
  return function() { return StringTools_twice(_this); };
}

export function main() {
  const box = new Box(3);
  __dartPrint(__dartStr(box.read()) + " " + __dartStr(identity("x")) + " " + __dartStr(StringTools_twice("a")) + " " + __dartStr(new User("u").label()));
}

main();
