// Generated by dart2esm.

function __dartPrint(value) {
  console.log(value);
}

export class Animal {
  constructor() {
    throw new TypeError("Class Animal has no unnamed constructor");
  }
  static named(name) {
    const $self = Object.create(this.prototype);
    $self.name = name;
    $self.source = "named animal";
    $self.source = `${$self.source}!`;
    return $self;
  }
  describe() {
    return `${this.source} ${this.name}`;
  }
}

export class Dog extends Animal {
  constructor() {
    throw new TypeError("Class Dog has no unnamed constructor");
  }
  static named(name, age) {
    const $self = Animal.named.call(this, name);
    $self.age = age;
    $self.label = "dog";
    $self.label = `${$self.label}!`;
    return $self;
  }
  describe() {
    return `${super.describe()} ${this.label} ${this.age}`;
  }
}

export class Cat extends Animal {
  constructor(name, color) {
    const $self = Animal.named.call(new.target, name);
    $self.color = color;
    $self.color = `${$self.color}!`;
    return $self;
  }
  describe() {
    return `${super.describe()} cat ${this.color}`;
  }
}

export class Puppy extends Dog {
  constructor() {
    throw new TypeError("Class Puppy has no unnamed constructor");
  }
  static named(name, age, toy) {
    const $self = Dog.named.call(this, name, age);
    $self.toy = toy;
    return $self;
  }
  describe() {
    return `${super.describe()} toy ${this.toy}`;
  }
}

export function main() {
  const dog = Dog.named("Rex", 4);
  const cat = new Cat("Mia", "black");
  const puppy = Puppy.named("Tiny", 1, "ball");
  __dartPrint(dog.describe());
  __dartPrint(cat.describe());
  __dartPrint(puppy.describe());
}

main();
