function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}

// Generated by dart2esm.

export class Animal {
  constructor(name) {
    this.name = name;
  }
  describe() {
    return "animal " + __dartStr(this.name);
  }
}

export class Dog extends Animal {
  constructor(age, name) {
    super(name);
    this.age = age;
    this.label = "dog";
  }
  static named(name, age) {
    return $Dog_named(Dog, name, age);
  }
  describe() {
    return __dartStr(super.describe()) + " " + __dartStr(this.label) + " " + __dartStr(this.age);
  }
}

function $Dog_named($newTarget, name, age) {
  const $self = Reflect.construct(Animal, [name], $newTarget);
  $self.age = age;
  $self.label = "named dog";
  $self.label = __dartStr($self.label) + "!";
  return $self;
}

export class Cat extends Animal {
  constructor() {
    throw new TypeError("Class Cat has no unnamed constructor");
  }
  static named(name) {
    return $Cat_named(Cat, name);
  }
  describe() {
    return __dartStr(super.describe()) + " cat " + __dartStr(this.lives);
  }
}

function $Cat_named($newTarget, name) {
  const $self = Reflect.construct(Animal, [name], $newTarget);
  $self.lives = 9;
  return $self;
}

export function main() {
  const dog = Dog.named("Rex", 4);
  const regular = new Dog(2, "Ada");
  const cat = Cat.named("Mia");
  __dartPrint(dog.describe());
  __dartPrint(regular.describe());
  __dartPrint(cat.describe());
}

main();
