function __dartStr(value) {
  return value == null ? "null" : String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}

// Generated by dart2esm.

export class Point {
  constructor(x, y) {
    this.x = x;
    this.y = y;
    this.label = "point";
  }
  static origin() {
    return $Point_origin(Point);
  }
  static square(size) {
    return $Point_square(Point, size);
  }
  describe() {
    return __dartStr(this.label) + ":" + __dartStr(this.x) + "," + __dartStr(this.y);
  }
}

function $Point_origin($newTarget) {
  const $self = Object.create($newTarget.prototype);
  $self.x = 0;
  $self.y = 0;
  $self.label = "origin";
  $self.label = __dartStr($self.label) + "!";
  return $self;
}

function $Point_square($newTarget_1, size) {
  const $self_1 = Object.create($newTarget_1.prototype);
  $self_1.x = size;
  $self_1.y = size;
  $self_1.label = "square";
  return $self_1;
}

export class Token {
  constructor() {
    throw new TypeError("Class Token has no unnamed constructor");
  }
  static named(value) {
    return $Token_named(Token, value);
  }
  describe() {
    return "token " + __dartStr(this.value);
  }
}

function $Token_named($newTarget_2, value) {
  const $self_2 = Object.create($newTarget_2.prototype);
  $self_2.value = value;
  return $self_2;
}

export function main() {
  const origin = Point.origin();
  const square = Point.square(4);
  const regular = new Point(2, 3);
  const token = Token.named("alpha");
  __dartPrint(origin.describe());
  __dartPrint(square.describe());
  __dartPrint(regular.describe());
  __dartPrint(token.describe());
}

main();
