// Generated by dart2esm.

function __dartPrint(value) {
  console.log(__dartStr(value));
}

function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}

function __dartAs(value, test, typeName) {
  if (test(value)) {
    return value;
  }
  throw new TypeError("Type cast failed: expected " + typeName);
}

const $Shape_interface = Symbol("Shape");
export class Shape {
  constructor(size) {
    return new Square(size);
  }
  static named(size) {
    return Square.named(size);
  }
  static alias(size) {
    return Shape.named(size);
  }
  static newAlias(size) {
    return new Square(size);
  }
  static withDefault(size = 8) {
    return Square.withDefault(size);
  }
  static options({ size = 9, label = "options" } = {}) {
    return Square.options({ size: size, label: label });
  }
}

Object.defineProperty(Shape, Symbol.hasInstance, { value: function(value) {
  return value != null && value[$Shape_interface] === true;
} });
export class Square {
  constructor(size) {
    this.size = size;
    this.label = "square";
    Object.defineProperty(this, $Shape_interface, { value: true });
  }
  static named(size) {
    const $self = Object.create(this.prototype);
    $self.size = size;
    $self.label = "named";
    Object.defineProperty($self, $Shape_interface, { value: true });
    return $self;
  }
  static withDefault(size = 8) {
    const $self = Object.create(this.prototype);
    $self.size = size;
    $self.label = "default";
    Object.defineProperty($self, $Shape_interface, { value: true });
    return $self;
  }
  static options({ size = 9, label = "options" } = {}) {
    const $self = Object.create(this.prototype);
    $self.size = size;
    $self.label = label;
    Object.defineProperty($self, $Shape_interface, { value: true });
    return $self;
  }
  describe() {
    return `${__dartStr(this.label)}:${__dartStr(this.size)}`;
  }
}

const $Widget_interface = Symbol("Widget");
export class Widget {
  static d() {
    return new Button();
  }
  static named(label) {
    return Button.named(label);
  }
}

Object.defineProperty(Widget, Symbol.hasInstance, { value: function(value) {
  return value != null && value[$Widget_interface] === true;
} });
export class Button {
  constructor() {
    this.label = "button";
    Object.defineProperty(this, $Widget_interface, { value: true });
  }
  static named(label) {
    const $self = Object.create(this.prototype);
    $self.label = label;
    Object.defineProperty($self, $Widget_interface, { value: true });
    return $self;
  }
  describe() {
    return `button:${__dartStr(this.label)}`;
  }
}

export function main() {
  const unnamed = __dartAs(new Square(2), (value) => value instanceof Square, "Square");
  const named = __dartAs(Square.named(3), (value) => value instanceof Square, "Square");
  const alias = __dartAs(Square.named(4), (value) => value instanceof Square, "Square");
  const newAlias = __dartAs(new Square(5), (value) => value instanceof Square, "Square");
  const withDefault = __dartAs(Square.withDefault(), (value) => value instanceof Square, "Square");
  const optionsDefault = __dartAs(Square.options(), (value) => value instanceof Square, "Square");
  const optionsCustom = __dartAs(Square.options({ size: 6, label: "custom" }), (value) => value instanceof Square, "Square");
  const widget = __dartAs(new Button(), (value) => value instanceof Button, "Button");
  const namedWidget = __dartAs(Button.named("primary"), (value) => value instanceof Button, "Button");
  __dartPrint(unnamed.describe());
  __dartPrint(named.describe());
  __dartPrint(alias.describe());
  __dartPrint(newAlias.describe());
  __dartPrint(withDefault.describe());
  __dartPrint(optionsDefault.describe());
  __dartPrint(optionsCustom.describe());
  __dartPrint(widget.describe());
  __dartPrint(namedWidget.describe());
}

main();
