// Generated by dart2esm.

function __dartPrint(value) {
  console.log(value);
}

export class Point {
  constructor(x, y) {
    this.x = x;
    this.y = y;
    this.label = "point";
  }
  static zero() {
    return Reflect.construct(Point, [0, 0], this);
  }
  static named(x, y, label) {
    const $self = Object.create(this.prototype);
    $self.x = x;
    $self.y = y;
    $self.label = label;
    return $self;
  }
  static alias(value) {
    return Point.named.call(this, value, value + 1, "alias");
  }
  describe() {
    return `${this.label}:${this.x},${this.y}`;
  }
}

export class Pair {
  constructor() {
    return Pair.named.call(new.target, 0, 1, "default");
  }
  static named(left, right, label) {
    const $self = Object.create(this.prototype);
    $self.left = left;
    $self.right = right;
    $self.label = label;
    return $self;
  }
  static mirror(value) {
    return Pair.named.call(this, value, value, "mirror");
  }
  describe() {
    return `${this.label}:${this.left},${this.right}`;
  }
}

export class Range {
  constructor() {
    throw new TypeError("Class Range has no unnamed constructor");
  }
  static start(start = 0) {
    return Range.between.call(this, start, start + 10);
  }
  static between(start, end) {
    const $self = Object.create(this.prototype);
    $self.start = start;
    $self.end = end;
    return $self;
  }
  describe() {
    return `${this.start}..${this.end}`;
  }
}

export class Options {
  constructor() {
    throw new TypeError("Class Options has no unnamed constructor");
  }
  static named({ count, label = "default", enabled = true } = {}) {
    const $self = Object.create(this.prototype);
    $self.count = count;
    $self.label = label;
    $self.enabled = enabled;
    return $self;
  }
  static defaults() {
    return Options.named.call(this, { count: 1 });
  }
  static from({ count, label = "from" } = {}) {
    return Options.named.call(this, { count: count, label: label });
  }
  static disabled(count) {
    return Options.named.call(this, { count: count, label: "off", enabled: false });
  }
  describe() {
    return `${this.label}:${this.count}:${this.enabled}`;
  }
}

export class Animal {
  constructor() {
    throw new TypeError("Class Animal has no unnamed constructor");
  }
  static named(name) {
    const $self = Object.create(this.prototype);
    $self.name = name;
    $self.source = "animal";
    return $self;
  }
  describe() {
    return `${this.source} ${this.name}`;
  }
}

export class Dog extends Animal {
  constructor() {
    throw new TypeError("Class Dog has no unnamed constructor");
  }
  static named(name, age) {
    return Dog.full.call(this, name, age, "dog");
  }
  static full(name, age, label) {
    const $self = Animal.named.call(this, name);
    $self.age = age;
    $self.label = label;
    $self.label = `${$self.label}!`;
    return $self;
  }
  describe() {
    return `${super.describe()} ${this.label} ${this.age}`;
  }
}

export class Puppy extends Dog {
  constructor() {
    throw new TypeError("Class Puppy has no unnamed constructor");
  }
  static named(name) {
    return Puppy.full.call(this, name, 1, "ball");
  }
  static full(name, age, toy) {
    const $self = Dog.named.call(this, name, age);
    $self.toy = toy;
    return $self;
  }
  describe() {
    return `${super.describe()} toy ${this.toy}`;
  }
}

export class ColoredPoint extends Point {
  constructor() {
    throw new TypeError("Class ColoredPoint has no unnamed constructor");
  }
  static zero(color) {
    const $self = Point.zero.call(this);
    $self.color = color;
    return $self;
  }
  describe() {
    return `${super.describe()} ${this.color}`;
  }
}

export class WrappedPair extends Pair {
  constructor(wrapper) {
    super();
    this.wrapper = wrapper;
  }
  describe() {
    return `${super.describe()} ${this.wrapper}`;
  }
}

export function main() {
  const zero = Point.zero();
  const alias = Point.alias(4);
  const pair = new Pair();
  const mirror = Pair.mirror(5);
  const defaultRange = Range.start();
  const shiftedRange = Range.start(5);
  const defaults = Options.defaults();
  const from = Options.from({ count: 2 });
  const disabled = Options.disabled(3);
  const dog = Dog.named("Rex", 4);
  const puppy = Puppy.named("Tiny");
  const colored = ColoredPoint.zero("red");
  const wrapped = new WrappedPair("wrapped");
  __dartPrint(zero.describe());
  __dartPrint(alias.describe());
  __dartPrint(pair.describe());
  __dartPrint(mirror.describe());
  __dartPrint(defaultRange.describe());
  __dartPrint(shiftedRange.describe());
  __dartPrint(defaults.describe());
  __dartPrint(from.describe());
  __dartPrint(disabled.describe());
  __dartPrint(dog.describe());
  __dartPrint(puppy.describe());
  __dartPrint(colored.describe());
  __dartPrint(wrapped.describe());
}

main();
