// Generated by dart2esm.

function __dartPrint(value) {
  console.log(__dartStr(value));
}

function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}

export class Pair {
  constructor() {
    return Pair.named.call(new.target, 0, 1, "default");
  }
  static named(left, right, label) {
    const $self = Object.create(this.prototype);
    Object.defineProperty($self, "left", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty($self, "right", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty($self, "label", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty($self, "left", { value: left, writable: true, enumerable: true, configurable: true });
    Object.defineProperty($self, "right", { value: right, writable: true, enumerable: true, configurable: true });
    Object.defineProperty($self, "label", { value: label, writable: true, enumerable: true, configurable: true });
    return $self;
  }
  describe() {
    return `${__dartStr(this.label)}:${__dartStr(this.left)},${__dartStr(this.right)}`;
  }
}

export class Animal {
  constructor() {
    throw new TypeError("Class Animal has no unnamed constructor");
  }
  static named(name) {
    const $self = Object.create(this.prototype);
    Object.defineProperty($self, "name", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty($self, "name", { value: name, writable: true, enumerable: true, configurable: true });
    return $self;
  }
  describe() {
    return `animal ${__dartStr(this.name)}`;
  }
}

export class Dog extends Animal {
  constructor() {
    return Dog.named.call(new.target, "Rex", 4);
  }
  static named(name, age) {
    const $self = Animal.named.call(this, name);
    Object.defineProperty($self, "age", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty($self, "label", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty($self, "age", { value: age, writable: true, enumerable: true, configurable: true });
    Object.defineProperty($self, "label", { value: "dog", writable: true, enumerable: true, configurable: true });
    $self.label = `${__dartStr($self.label)}!`;
    return $self;
  }
  describe() {
    return `${__dartStr(super.describe())} ${__dartStr(this.label)} ${__dartStr(this.age)}`;
  }
}

export function main() {
  const pair = new Pair();
  const dog = new Dog();
  __dartPrint(pair.describe());
  __dartPrint(dog.describe());
}

main();
