function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartNullCheck(value) {
  if (value == null) {
    throw new TypeError("Null check operator used on a null value");
  }
  return value;
}
function __dartEnumByName(values, name) {
  for (const value of values) {
    if (value.name === name) return value;
  }
  throw new RangeError("No enum value with name " + name);
}
function __dartEnumAsNameMap(values) {
  const map = new Map();
  for (const value of values) map.set(value.name, value);
  return map;
}
function __dartCompare(left, right, compare = null) {
  if (typeof compare === "function") return Number(compare(left, right));
  const compareTo = left?.compareTo;
  if (typeof compareTo === "function") return Number(compareTo.call(left, right));
  return left < right ? -1 : (left > right ? 1 : 0);
}
const __dartMapMissingKey = Symbol("dart.mapMissingKey");
function __dartMapKey(map, key) {
  if (map.__dartIdentityMap) return map.has(key) ? key : __dartMapMissingKey;
  if (map.__dartSplayCompare !== undefined) {
    for (const candidate of map.keys()) {
      if (__dartCompare(candidate, key, map.__dartSplayCompare) === 0) return candidate;
    }
    return __dartMapMissingKey;
  }
  for (const candidate of map.keys()) {
    if (__dartEquals(candidate, key)) return candidate;
  }
  return __dartMapMissingKey;
}
function __dartMapGet(map, key) {
  const actualKey = __dartMapKey(map, key);
  return actualKey === __dartMapMissingKey ? null : map.get(actualKey);
}
function __dartEquals(left, right) {
  if (left === right) return true;
  if (left == null || right == null) return false;
  if ((typeof left === "number" || left.__dartType === "double") && (typeof right === "number" || right.__dartType === "double")) return Number(left) === Number(right);
  const equals = left["=="];
  return typeof equals === "function" ? equals.call(left, right) : false;
}
const __dartConstValues = new Map();
function __dartConst(key, create) {
  if (!__dartConstValues.has(key)) {
    __dartConstValues.set(key, create());
  }
  return __dartConstValues.get(key);
}

// Generated by dart2esm.

export class Status {
  constructor(index, name, code, label) {
    Object.defineProperty(this, "index", { value: index, enumerable: true });
    Object.defineProperty(this, "name", { value: name, enumerable: true });
    Object.defineProperty(this, "code", { value: code, enumerable: true });
    Object.defineProperty(this, "label", { value: label, enumerable: true });
    Object.freeze(this);
  }
  static isErrorCode(code) {
    return (code >= 400);
  }
  get ok() {
    return (this.code < 400);
  }
  describe() {
    return __dartStr(this.name) + ":" + __dartStr(this.code) + ":" + __dartStr(this.label);
  }
  toString() {
    return "Status." + this.name;
  }
}
Object.defineProperties(Status, {
  ready: { value: new Status(0, "ready", 200, "Ready"), enumerable: true },
  failed: { value: new Status(1, "failed", 500, "Failed"), enumerable: true }
});
Object.defineProperty(Status, "values", { value: Object.freeze([Status.ready, Status.failed]), enumerable: true });


Object.defineProperty(Status, "fallback", { value: Status.failed, enumerable: true });
export function main() {
  __dartPrint("entry " + __dartStr(Status.ready.name) + " " + __dartStr(Status.ready.index));
  __dartPrint("fields " + __dartStr(Status.failed.code) + " " + __dartStr(Status.failed.label));
  __dartPrint("getter " + __dartStr(Status.ready.ok) + " " + __dartStr(Status.failed.ok));
  __dartPrint("method " + __dartStr(Status.ready.describe()));
  __dartPrint("values " + __dartStr(__dartConst("[\"list\",\"InterfaceType(Status)\",[\"instance\",\"class:Status\",[\"field\",\"dart:core::_Enum::@fields::dart:core::_name\",[\"string\",\"ready\"]],[\"field\",\"dart:core::_Enum::@fields::index\",[\"int\",\"0\"]],[\"field\",\"field:Status.code\",[\"int\",\"200\"]],[\"field\",\"field:Status.label\",[\"string\",\"Ready\"]]],[\"instance\",\"class:Status\",[\"field\",\"dart:core::_Enum::@fields::dart:core::_name\",[\"string\",\"failed\"]],[\"field\",\"dart:core::_Enum::@fields::index\",[\"int\",\"1\"]],[\"field\",\"field:Status.code\",[\"int\",\"500\"]],[\"field\",\"field:Status.label\",[\"string\",\"Failed\"]]]]", () => Object.freeze([Status.ready, Status.failed])).length) + " " + __dartStr(__dartConst("[\"list\",\"InterfaceType(Status)\",[\"instance\",\"class:Status\",[\"field\",\"dart:core::_Enum::@fields::dart:core::_name\",[\"string\",\"ready\"]],[\"field\",\"dart:core::_Enum::@fields::index\",[\"int\",\"0\"]],[\"field\",\"field:Status.code\",[\"int\",\"200\"]],[\"field\",\"field:Status.label\",[\"string\",\"Ready\"]]],[\"instance\",\"class:Status\",[\"field\",\"dart:core::_Enum::@fields::dart:core::_name\",[\"string\",\"failed\"]],[\"field\",\"dart:core::_Enum::@fields::index\",[\"int\",\"1\"]],[\"field\",\"field:Status.code\",[\"int\",\"500\"]],[\"field\",\"field:Status.label\",[\"string\",\"Failed\"]]]]", () => Object.freeze([Status.ready, Status.failed]))[1].name));
  const byName = __dartEnumByName(__dartConst("[\"list\",\"InterfaceType(Status)\",[\"instance\",\"class:Status\",[\"field\",\"dart:core::_Enum::@fields::dart:core::_name\",[\"string\",\"ready\"]],[\"field\",\"dart:core::_Enum::@fields::index\",[\"int\",\"0\"]],[\"field\",\"field:Status.code\",[\"int\",\"200\"]],[\"field\",\"field:Status.label\",[\"string\",\"Ready\"]]],[\"instance\",\"class:Status\",[\"field\",\"dart:core::_Enum::@fields::dart:core::_name\",[\"string\",\"failed\"]],[\"field\",\"dart:core::_Enum::@fields::index\",[\"int\",\"1\"]],[\"field\",\"field:Status.code\",[\"int\",\"500\"]],[\"field\",\"field:Status.label\",[\"string\",\"Failed\"]]]]", () => Object.freeze([Status.ready, Status.failed])), "ready");
  const nameMap = __dartEnumAsNameMap(__dartConst("[\"list\",\"InterfaceType(Status)\",[\"instance\",\"class:Status\",[\"field\",\"dart:core::_Enum::@fields::dart:core::_name\",[\"string\",\"ready\"]],[\"field\",\"dart:core::_Enum::@fields::index\",[\"int\",\"0\"]],[\"field\",\"field:Status.code\",[\"int\",\"200\"]],[\"field\",\"field:Status.label\",[\"string\",\"Ready\"]]],[\"instance\",\"class:Status\",[\"field\",\"dart:core::_Enum::@fields::dart:core::_name\",[\"string\",\"failed\"]],[\"field\",\"dart:core::_Enum::@fields::index\",[\"int\",\"1\"]],[\"field\",\"field:Status.code\",[\"int\",\"500\"]],[\"field\",\"field:Status.label\",[\"string\",\"Failed\"]]]]", () => Object.freeze([Status.ready, Status.failed])));
  __dartPrint("byName " + __dartStr(byName.code) + " " + __dartStr(__dartNullCheck(__dartMapGet(nameMap, "failed")).label));
  __dartPrint("static " + __dartStr(Status.failed.name) + " " + __dartStr(Status.isErrorCode(500)));
  __dartPrint("string " + __dartStr(Status.failed));
}

main();
