name: dart2esm
description: A Dart-to-native-ESM compiler backend experiment.
version: 0.1.0
publish_to: none
repository: https://github.com/medz/dart2esm
issue_tracker: https://github.com/medz/dart2esm/issues

environment:
  sdk: ^3.8.0

executables:
  dart2esm:

dependencies:
  args: ^2.7.0
  kernel:
    git:
      url: https://github.com/dart-lang/sdk.git
      ref: 3.12.2
      path: pkg/kernel
  path: ^1.9.1

dev_dependencies:
  test: ^1.26.0
