import 'dart:convert';

import '../ir/esm_ir.dart';
import '../runtime/runtime_helpers.dart';
import '../transform/module_normalizer.dart';

final class CodegenStageResult {
  const CodegenStageResult({required this.code, required this.diagnostics});

  final String code;
  final List<String> diagnostics;
}

final class EsmCodegenStage {
  const EsmCodegenStage();

  CodegenStageResult emit(NormalizationResult normalized) {
    final printer = _EsmIrPrinter();
    return CodegenStageResult(
      code: printer.print(normalized.module),
      diagnostics: const [],
    );
  }
}

final class _EsmIrPrinter {
  final _buffer = StringBuffer();
  var _indent = 0;

  String print(EsmModuleIr module) {
    _buffer.writeln('// Generated by dart2esm.');
    _buffer.writeln();
    _emitRuntimeHelpers(module.runtimeHelpers);
    for (var i = 0; i < module.items.length; i++) {
      _emitModuleItem(module.items[i]);
      if (i != module.items.length - 1 &&
          (module.items[i] is EsmClassIr || module.items[i] is EsmFunctionIr)) {
        _buffer.writeln();
      }
    }
    return _buffer.toString();
  }

  void _emitRuntimeHelpers(List<EsmRuntimeHelper> helpers) {
    for (final helper in helpers) {
      _buffer.write(esmRuntimeHelperSource(helper));
      _buffer.writeln();
    }
  }

  void _emitModuleItem(EsmModuleItemIr item) {
    switch (item) {
      case EsmClassIr():
        _emitClass(item);
      case EsmFunctionIr():
        _emitFunction(item);
      case EsmStatementIr():
        _emitStatement(item);
    }
  }

  void _emitClass(EsmClassIr klass) {
    final exportPrefix = klass.export ? 'export ' : '';
    final superclass = klass.superclass == null
        ? ''
        : ' extends ${klass.superclass}';
    _writeIndented('${exportPrefix}class ${klass.name}$superclass {');
    _indent++;
    final constructor = klass.constructor;
    if (constructor != null) {
      _writeIndented('constructor(${constructor.parameters.join(', ')}) {');
      _indent++;
      for (final statement in constructor.body) {
        _emitStatement(statement);
      }
      _indent--;
      _writeIndented('}');
    }
    for (final method in klass.methods) {
      _emitClassMethod(method);
    }
    _indent--;
    _writeIndented('}');
  }

  void _emitClassMethod(EsmClassMethodIr method) {
    final prefix = switch (method.kind) {
      EsmClassMethodKindIr.method => '',
      EsmClassMethodKindIr.getter => 'get ',
      EsmClassMethodKindIr.setter => 'set ',
    };
    _writeIndented('$prefix${method.name}(${method.parameters.join(', ')}) {');
    _indent++;
    for (final statement in method.body) {
      _emitStatement(statement);
    }
    _indent--;
    _writeIndented('}');
  }

  void _emitFunction(EsmFunctionIr function) {
    final exportPrefix = function.export ? 'export ' : '';
    _writeIndented(
      '${exportPrefix}function ${function.name}(${function.parameters.join(', ')}) {',
    );
    _indent++;
    for (final statement in function.body) {
      _emitStatement(statement);
    }
    _indent--;
    _writeIndented('}');
  }

  void _emitStatement(EsmStatementIr statement) {
    switch (statement) {
      case EsmExpressionStatementIr():
        _writeIndented('${_emitExpression(statement.expression)};');
      case EsmLabeledStatementIr():
        _emitLabeledStatement(statement);
      case EsmBreakStatementIr():
        _writeIndented('break ${statement.label};');
      case EsmVariableDeclarationIr():
        final keyword = statement.mutable ? 'let' : 'const';
        final exportPrefix = statement.export ? 'export ' : '';
        final initializer = statement.initializer;
        _writeIndented(
          initializer == null
              ? '$exportPrefix$keyword ${statement.name};'
              : '$exportPrefix$keyword ${statement.name} = ${_emitExpression(initializer)};',
        );
      case EsmIfStatementIr():
        _emitIfStatement(statement);
      case EsmWhileStatementIr():
        _emitWhileStatement(statement);
      case EsmDoStatementIr():
        _emitDoStatement(statement);
      case EsmSwitchStatementIr():
        _emitSwitchStatement(statement);
      case EsmForStatementIr():
        _emitForStatement(statement);
      case EsmReturnStatementIr():
        final expression = statement.expression;
        _writeIndented(
          expression == null
              ? 'return;'
              : 'return ${_emitExpression(expression)};',
        );
    }
  }

  void _emitLabeledStatement(EsmLabeledStatementIr statement) {
    _writeIndented('${statement.label}: {');
    _indent++;
    for (final child in statement.body) {
      _emitStatement(child);
    }
    _indent--;
    _writeIndented('}');
  }

  void _emitIfStatement(EsmIfStatementIr statement) {
    _writeIndented('if (${_emitExpression(statement.condition)}) {');
    _indent++;
    for (final child in statement.thenBody) {
      _emitStatement(child);
    }
    _indent--;
    final otherwiseBody = statement.otherwiseBody;
    if (otherwiseBody == null) {
      _writeIndented('}');
      return;
    }
    _writeIndented('} else {');
    _indent++;
    for (final child in otherwiseBody) {
      _emitStatement(child);
    }
    _indent--;
    _writeIndented('}');
  }

  void _emitWhileStatement(EsmWhileStatementIr statement) {
    _writeIndented('while (${_emitExpression(statement.condition)}) {');
    _indent++;
    for (final child in statement.body) {
      _emitStatement(child);
    }
    _indent--;
    _writeIndented('}');
  }

  void _emitDoStatement(EsmDoStatementIr statement) {
    _writeIndented('do {');
    _indent++;
    for (final child in statement.body) {
      _emitStatement(child);
    }
    _indent--;
    _writeIndented('} while (${_emitExpression(statement.condition)});');
  }

  void _emitSwitchStatement(EsmSwitchStatementIr statement) {
    _writeIndented('switch (${_emitExpression(statement.expression)}) {');
    _indent++;
    for (final switchCase in statement.cases) {
      _emitSwitchCase(switchCase);
    }
    _indent--;
    _writeIndented('}');
  }

  void _emitSwitchCase(EsmSwitchCaseIr switchCase) {
    for (final expression in switchCase.expressions) {
      _writeIndented('case ${_emitExpression(expression)}:');
    }
    if (switchCase.isDefault) {
      _writeIndented('default:');
    }
    _indent++;
    for (final child in switchCase.body) {
      _emitStatement(child);
    }
    _indent--;
  }

  void _emitForStatement(EsmForStatementIr statement) {
    final initializer = _emitForInitializer(statement.initializers);
    final condition = statement.condition == null
        ? ''
        : _emitExpression(statement.condition!);
    final updates = statement.updates.map(_emitExpression).join(', ');
    _writeIndented('for ($initializer; $condition; $updates) {');
    _indent++;
    for (final child in statement.body) {
      _emitStatement(child);
    }
    _indent--;
    _writeIndented('}');
  }

  String _emitForInitializer(List<EsmVariableDeclarationIr> initializers) {
    if (initializers.isEmpty) {
      return '';
    }
    final mutable = initializers.first.mutable;
    final keyword = mutable ? 'let' : 'const';
    return '$keyword ${initializers.map(_emitForInitializerBinding).join(', ')}';
  }

  String _emitForInitializerBinding(EsmVariableDeclarationIr initializer) {
    final value = initializer.initializer;
    return value == null
        ? initializer.name
        : '${initializer.name} = ${_emitExpression(value)}';
  }

  String _emitExpression(EsmExpressionIr expression) {
    return switch (expression) {
      EsmIdentifierIr() => expression.name,
      EsmStringLiteralIr() => jsonEncode(expression.value),
      EsmStringConcatenationIr() => _emitStringConcatenation(expression),
      EsmAssignmentIr() =>
        '${_emitExpression(expression.target)} = ${_emitExpression(expression.value)}',
      EsmBinaryIr() =>
        '${_emitExpression(expression.left)} ${expression.operator} ${_emitExpression(expression.right)}',
      EsmNumberLiteralIr() => _emitNumber(expression.value),
      EsmBooleanLiteralIr() => expression.value ? 'true' : 'false',
      EsmNullLiteralIr() => 'null',
      EsmCallIr() =>
        '${_emitExpression(expression.callee)}(${expression.arguments.map(_emitExpression).join(', ')})',
      EsmNewIr() =>
        'new ${_emitExpression(expression.callee)}(${expression.arguments.map(_emitExpression).join(', ')})',
      EsmPropertyAccessIr() =>
        '${_emitExpression(expression.receiver)}.${expression.property}',
      EsmThisIr() => 'this',
      EsmSuperIr() => 'super',
    };
  }

  String _emitStringConcatenation(EsmStringConcatenationIr expression) {
    if (expression.expressions.isEmpty) {
      return '""';
    }
    final buffer = StringBuffer('`');
    for (final part in expression.expressions) {
      if (part case EsmStringLiteralIr()) {
        buffer.write(_escapeTemplateText(part.value));
      } else {
        buffer.write(r'${');
        buffer.write(_emitExpression(part));
        buffer.write('}');
      }
    }
    buffer.write('`');
    return buffer.toString();
  }

  String _escapeTemplateText(String value) {
    return value
        .replaceAll(r'\', r'\\')
        .replaceAll('`', r'\`')
        .replaceAll(r'${', r'\${');
  }

  String _emitNumber(num value) {
    if (value.isNaN) {
      return 'NaN';
    }
    if (value == double.infinity) {
      return 'Infinity';
    }
    if (value == double.negativeInfinity) {
      return '-Infinity';
    }
    return value.toString();
  }

  void _writeIndented(String line) {
    _buffer.write('  ' * _indent);
    _buffer.writeln(line);
  }
}
