import 'dart:convert';

import '../compiler_stage.dart';
import '../ir/esm_ir.dart';

final class CodegenStageResult {
  const CodegenStageResult({required this.code, required this.diagnostics});

  final String code;
  final List<String> diagnostics;
}

final class EsmCodegenStage
    implements Dart2EsmCompilerStage<EsmModuleIr, CodegenStageResult> {
  const EsmCodegenStage();

  @override
  Dart2EsmCompilerStageId get stageId => Dart2EsmCompilerStageId.esmCodegen;

  @override
  CodegenStageResult run(EsmModuleIr input, Dart2EsmStageContext context) {
    return emit(input);
  }

  CodegenStageResult emit(EsmModuleIr module) {
    final printer = _EsmIrPrinter();
    return CodegenStageResult(
      code: printer.print(module),
      diagnostics: const [],
    );
  }
}

final class _EsmIrPrinter {
  final _buffer = StringBuffer();
  var _indent = 0;

  String print(EsmModuleIr module) {
    _buffer.writeln('// Generated by dart2esm.');
    _buffer.writeln();
    for (var i = 0; i < module.items.length; i++) {
      _emitModuleItem(module.items[i]);
      if (i != module.items.length - 1 &&
          _needsBlankLineAfter(module.items[i])) {
        _buffer.writeln();
      }
    }
    return _buffer.toString();
  }

  bool _needsBlankLineAfter(EsmModuleItemIr item) {
    return item is EsmRawModuleItemIr ||
        item is EsmClassIr ||
        item is EsmFunctionIr;
  }

  void _emitModuleItem(EsmModuleItemIr item) {
    switch (item) {
      case EsmRawModuleItemIr():
        _writeIndented(item.source.trimRight());
      case EsmClassIr():
        _emitClass(item);
      case EsmFunctionIr():
        _emitFunction(item);
      case EsmStatementIr():
        _emitStatement(item);
    }
  }

  void _emitClass(EsmClassIr klass) {
    final exportPrefix = klass.export ? 'export ' : '';
    final superclass = klass.superclass == null
        ? ''
        : ' extends ${_emitExpression(klass.superclass!)}';
    _writeIndented('${exportPrefix}class ${klass.name}$superclass {');
    _indent++;
    final constructor = klass.constructor;
    if (constructor != null) {
      _writeIndented(
        'constructor(${constructor.parameters.map(_emitParameter).join(', ')}) {',
      );
      _indent++;
      for (final statement in constructor.body) {
        _emitStatement(statement);
      }
      _indent--;
      _writeIndented('}');
    }
    for (final method in klass.methods) {
      _emitClassMethod(method);
    }
    _indent--;
    _writeIndented('}');
  }

  void _emitClassMethod(EsmClassMethodIr method) {
    final staticPrefix = method.isStatic ? 'static ' : '';
    final prefix = switch (method.kind) {
      EsmClassMethodKindIr.method => '',
      EsmClassMethodKindIr.getter => 'get ',
      EsmClassMethodKindIr.setter => 'set ',
    };
    _writeIndented(
      '$staticPrefix$prefix${_emitObjectPropertyName(method.name)}(${method.parameters.map(_emitParameter).join(', ')}) {',
    );
    _indent++;
    for (final statement in method.body) {
      _emitStatement(statement);
    }
    _indent--;
    _writeIndented('}');
  }

  void _emitFunction(EsmFunctionIr function) {
    final exportPrefix = function.export ? 'export ' : '';
    _writeIndented(
      '${exportPrefix}function ${function.name}(${function.parameters.map(_emitParameter).join(', ')}) {',
    );
    _indent++;
    for (final statement in function.body) {
      _emitStatement(statement);
    }
    _indent--;
    _writeIndented('}');
  }

  void _emitStatement(EsmStatementIr statement) {
    switch (statement) {
      case EsmExpressionStatementIr():
        _writeIndented('${_emitExpression(statement.expression)};');
      case EsmBlockStatementIr():
        _emitBlockStatement(statement);
      case EsmLabeledStatementIr():
        _emitLabeledStatement(statement);
      case EsmBreakStatementIr():
        final label = statement.label;
        _writeIndented(label == null ? 'break;' : 'break $label;');
      case EsmContinueStatementIr():
        final label = statement.label;
        _writeIndented(label == null ? 'continue;' : 'continue $label;');
      case EsmVariableDeclarationIr():
        final keyword = statement.mutable ? 'let' : 'const';
        final exportPrefix = statement.export ? 'export ' : '';
        final initializer = statement.initializer;
        final binding = _emitBinding(statement.binding);
        _writeIndented(
          initializer == null
              ? '$exportPrefix$keyword $binding;'
              : '$exportPrefix$keyword $binding = ${_emitExpression(initializer)};',
        );
      case EsmIfStatementIr():
        _emitIfStatement(statement);
      case EsmWhileStatementIr():
        _emitWhileStatement(statement);
      case EsmDoStatementIr():
        _emitDoStatement(statement);
      case EsmSwitchStatementIr():
        _emitSwitchStatement(statement);
      case EsmForStatementIr():
        _emitForStatement(statement);
      case EsmReturnStatementIr():
        final expression = statement.expression;
        _writeIndented(
          expression == null
              ? 'return;'
              : 'return ${_emitExpression(expression)};',
        );
      case EsmThrowStatementIr():
        _writeIndented('throw ${_emitExpression(statement.expression)};');
      case EsmTryStatementIr():
        _emitTryStatement(statement);
    }
  }

  void _emitBlockStatement(EsmBlockStatementIr statement) {
    _writeIndented('{');
    _indent++;
    for (final child in statement.body) {
      _emitStatement(child);
    }
    _indent--;
    _writeIndented('}');
  }

  void _emitLabeledStatement(EsmLabeledStatementIr statement) {
    final body = statement.statement;
    if (body is EsmBlockStatementIr) {
      _writeIndented('${statement.label}: {');
      _indent++;
      for (final child in body.body) {
        _emitStatement(child);
      }
      _indent--;
      _writeIndented('}');
      return;
    }
    if (body is EsmWhileStatementIr) {
      _emitWhileStatement(body, label: statement.label);
      return;
    }
    _writeIndented('${statement.label}:');
    _indent++;
    _emitStatement(body);
    _indent--;
  }

  void _emitIfStatement(EsmIfStatementIr statement) {
    _writeIndented('if (${_emitExpression(statement.condition)}) {');
    _indent++;
    for (final child in statement.thenBody) {
      _emitStatement(child);
    }
    _indent--;
    final otherwiseBody = statement.otherwiseBody;
    if (otherwiseBody == null) {
      _writeIndented('}');
      return;
    }
    _writeIndented('} else {');
    _indent++;
    for (final child in otherwiseBody) {
      _emitStatement(child);
    }
    _indent--;
    _writeIndented('}');
  }

  void _emitWhileStatement(EsmWhileStatementIr statement, {String? label}) {
    final prefix = label == null ? '' : '$label: ';
    _writeIndented(
      '${prefix}while (${_emitExpression(statement.condition)}) {',
    );
    _indent++;
    for (final child in statement.body) {
      _emitStatement(child);
    }
    _indent--;
    _writeIndented('}');
  }

  void _emitDoStatement(EsmDoStatementIr statement) {
    _writeIndented('do {');
    _indent++;
    for (final child in statement.body) {
      _emitStatement(child);
    }
    _indent--;
    _writeIndented('} while (${_emitExpression(statement.condition)});');
  }

  void _emitSwitchStatement(EsmSwitchStatementIr statement) {
    _writeIndented('switch (${_emitExpression(statement.expression)}) {');
    _indent++;
    for (final switchCase in statement.cases) {
      _emitSwitchCase(switchCase);
    }
    _indent--;
    _writeIndented('}');
  }

  void _emitSwitchCase(EsmSwitchCaseIr switchCase) {
    for (final expression in switchCase.expressions) {
      _writeIndented('case ${_emitExpression(expression)}:');
    }
    if (switchCase.isDefault) {
      _writeIndented('default:');
    }
    _indent++;
    for (final child in switchCase.body) {
      _emitStatement(child);
    }
    _indent--;
  }

  void _emitTryStatement(EsmTryStatementIr statement) {
    _writeIndented('try {');
    _indent++;
    for (final child in statement.body) {
      _emitStatement(child);
    }
    _indent--;
    final catchBody = statement.catchBody;
    final finallyBody = statement.finallyBody;
    if (catchBody != null) {
      final catchParameter = statement.catchParameter;
      _writeIndented(
        catchParameter == null
            ? '} catch {'
            : '} catch (${_emitBindingPattern(catchParameter)}) {',
      );
      _indent++;
      for (final child in catchBody) {
        _emitStatement(child);
      }
      _indent--;
    }
    if (finallyBody != null) {
      _writeIndented('} finally {');
      _indent++;
      for (final child in finallyBody) {
        _emitStatement(child);
      }
      _indent--;
    }
    _writeIndented('}');
  }

  void _emitForStatement(EsmForStatementIr statement) {
    final initializer = _emitForInitializer(statement.initializers);
    final condition = statement.condition == null
        ? ''
        : _emitExpression(statement.condition!);
    final updates = statement.updates.map(_emitExpression).join(', ');
    _writeIndented('for ($initializer; $condition; $updates) {');
    _indent++;
    for (final child in statement.body) {
      _emitStatement(child);
    }
    _indent--;
    _writeIndented('}');
  }

  String _emitForInitializer(List<EsmVariableDeclarationIr> initializers) {
    if (initializers.isEmpty) {
      return '';
    }
    final mutable = initializers.first.mutable;
    final keyword = mutable ? 'let' : 'const';
    return '$keyword ${initializers.map(_emitForInitializerBinding).join(', ')}';
  }

  String _emitForInitializerBinding(EsmVariableDeclarationIr initializer) {
    final value = initializer.initializer;
    final binding = _emitBinding(initializer.binding);
    return value == null ? binding : '$binding = ${_emitExpression(value)}';
  }

  String _emitBinding(EsmBindingIr binding) {
    return switch (binding) {
      EsmIdentifierBindingIr() => binding.name,
      EsmObjectBindingPatternIr() =>
        '{ ${binding.bindings.map(_emitObjectPatternBinding).join(', ')} }',
      EsmArrayBindingPatternIr() =>
        '[${binding.elements.map(_emitBinding).join(', ')}]',
    };
  }

  String _emitParameter(EsmParameterIr parameter) {
    return switch (parameter) {
      EsmIdentifierParameterIr() =>
        parameter.defaultValue == null
            ? parameter.name
            : '${_emitBindingPattern(parameter)} = ${_emitExpression(parameter.defaultValue!)}',
      EsmObjectPatternParameterIr() => '${_emitBindingPattern(parameter)} = {}',
      EsmArrayPatternParameterIr() => _emitBindingPattern(parameter),
    };
  }

  String _emitBindingPattern(EsmParameterIr parameter) {
    return switch (parameter) {
      EsmIdentifierParameterIr() => parameter.name,
      EsmObjectPatternParameterIr() =>
        '{ ${parameter.bindings.map(_emitObjectPatternBinding).join(', ')} }',
      EsmArrayPatternParameterIr() =>
        '[${parameter.elements.map(_emitBindingPattern).join(', ')}]',
    };
  }

  String _emitObjectPatternBinding(EsmObjectPatternBindingIr binding) {
    final property = _emitObjectPropertyName(binding.property);
    final name = binding.property == binding.name ? '' : ': ${binding.name}';
    final defaultValue = binding.defaultValue == null
        ? ''
        : ' = ${_emitExpression(binding.defaultValue!)}';
    return '$property$name$defaultValue';
  }

  String _emitExpression(EsmExpressionIr expression) {
    return switch (expression) {
      EsmIdentifierIr() => expression.name,
      EsmImportMetaIr() => 'import.meta',
      EsmStringLiteralIr() => jsonEncode(expression.value),
      EsmStringConcatenationIr() => _emitStringConcatenation(expression),
      EsmAssignmentIr() =>
        '${_emitExpression(expression.target)} = ${_emitExpression(expression.value)}',
      EsmBinaryIr() => _emitBinaryExpression(expression),
      EsmUnaryIr() => _emitUnaryExpression(expression),
      EsmConditionalIr() =>
        '(${_emitExpression(expression.condition)} ? ${_emitExpression(expression.thenExpression)} : ${_emitExpression(expression.otherwiseExpression)})',
      EsmNullishCoalesceIr() =>
        '(${_emitNullishOperand(expression.left)} ?? ${_emitNullishOperand(expression.right)})',
      EsmParenthesizedIr() => '(${_emitExpression(expression.expression)})',
      EsmNumberLiteralIr() => _emitNumber(expression.value),
      EsmBooleanLiteralIr() => expression.value ? 'true' : 'false',
      EsmNullLiteralIr() => 'null',
      EsmArrayLiteralIr() =>
        '[${expression.elements.map(_emitExpression).join(', ')}]',
      EsmObjectLiteralIr() =>
        '{ ${expression.properties.map(_emitObjectLiteralProperty).join(', ')} }',
      EsmArrowFunctionIr() =>
        '(${expression.parameters.map(_emitParameter).join(', ')}) => ${_emitExpression(expression.body)}',
      EsmFunctionExpressionIr() => _emitFunctionExpression(expression),
      EsmArrowBlockFunctionIr() => _emitArrowBlockFunction(expression),
      EsmCallIr() =>
        '${_emitCallCallee(expression.callee)}(${expression.arguments.map(_emitExpression).join(', ')})',
      EsmNewIr() =>
        'new ${_emitExpression(expression.callee)}(${expression.arguments.map(_emitExpression).join(', ')})',
      EsmPropertyAccessIr() =>
        '${_emitExpression(expression.receiver)}.${expression.property}',
      EsmComputedPropertyAccessIr() =>
        '${_emitExpression(expression.receiver)}[${_emitExpression(expression.property)}]',
      EsmOptionalPropertyAccessIr() =>
        '${_emitExpression(expression.receiver)}?.${expression.property}',
      EsmOptionalMethodCallIr() =>
        '${_emitExpression(expression.receiver)}?.${expression.property}(${expression.arguments.map(_emitExpression).join(', ')})',
      EsmThisIr() => 'this',
      EsmNewTargetIr() => 'new.target',
      EsmSuperIr() => 'super',
    };
  }

  String _emitBinaryExpression(EsmBinaryIr expression) {
    final left = _emitBinaryOperand(
      expression.left,
      expression.operator,
      isRight: false,
    );
    final right = _emitBinaryOperand(
      expression.right,
      expression.operator,
      isRight: true,
    );
    return '$left ${_emitBinaryOperator(expression.operator)} $right';
  }

  String _emitBinaryOperand(
    EsmExpressionIr operand,
    EsmBinaryOperatorIr parentOperator, {
    required bool isRight,
  }) {
    final text = _emitExpression(operand);
    if (operand case EsmBinaryIr(:final operator)) {
      final operandPrecedence = _binaryPrecedence(operator);
      final parentPrecedence = _binaryPrecedence(parentOperator);
      if (operandPrecedence < parentPrecedence ||
          (isRight &&
              operandPrecedence == parentPrecedence &&
              !_canFlattenRightBinary(parentOperator, operator))) {
        return '($text)';
      }
    }
    return text;
  }

  String _emitBinaryOperator(EsmBinaryOperatorIr operator) {
    return switch (operator) {
      EsmBinaryOperatorIr.multiply => '*',
      EsmBinaryOperatorIr.divide => '/',
      EsmBinaryOperatorIr.remainder => '%',
      EsmBinaryOperatorIr.add => '+',
      EsmBinaryOperatorIr.subtract => '-',
      EsmBinaryOperatorIr.leftShift => '<<',
      EsmBinaryOperatorIr.signedRightShift => '>>',
      EsmBinaryOperatorIr.unsignedRightShift => '>>>',
      EsmBinaryOperatorIr.lessThan => '<',
      EsmBinaryOperatorIr.lessThanOrEqual => '<=',
      EsmBinaryOperatorIr.greaterThan => '>',
      EsmBinaryOperatorIr.greaterThanOrEqual => '>=',
      EsmBinaryOperatorIr.instanceOf => 'instanceof',
      EsmBinaryOperatorIr.inOperator => 'in',
      EsmBinaryOperatorIr.looseEquals => '==',
      EsmBinaryOperatorIr.looseNotEquals => '!=',
      EsmBinaryOperatorIr.strictEquals => '===',
      EsmBinaryOperatorIr.strictNotEquals => '!==',
      EsmBinaryOperatorIr.bitAnd => '&',
      EsmBinaryOperatorIr.bitXor => '^',
      EsmBinaryOperatorIr.bitOr => '|',
      EsmBinaryOperatorIr.logicalAnd => '&&',
      EsmBinaryOperatorIr.logicalOr => '||',
    };
  }

  int _binaryPrecedence(EsmBinaryOperatorIr operator) {
    return switch (operator) {
      EsmBinaryOperatorIr.multiply ||
      EsmBinaryOperatorIr.divide ||
      EsmBinaryOperatorIr.remainder => 12,
      EsmBinaryOperatorIr.add || EsmBinaryOperatorIr.subtract => 11,
      EsmBinaryOperatorIr.leftShift ||
      EsmBinaryOperatorIr.signedRightShift ||
      EsmBinaryOperatorIr.unsignedRightShift => 10,
      EsmBinaryOperatorIr.lessThan ||
      EsmBinaryOperatorIr.lessThanOrEqual ||
      EsmBinaryOperatorIr.greaterThan ||
      EsmBinaryOperatorIr.greaterThanOrEqual ||
      EsmBinaryOperatorIr.instanceOf ||
      EsmBinaryOperatorIr.inOperator => 9,
      EsmBinaryOperatorIr.looseEquals ||
      EsmBinaryOperatorIr.looseNotEquals ||
      EsmBinaryOperatorIr.strictEquals ||
      EsmBinaryOperatorIr.strictNotEquals => 8,
      EsmBinaryOperatorIr.bitAnd => 7,
      EsmBinaryOperatorIr.bitXor => 6,
      EsmBinaryOperatorIr.bitOr => 5,
      EsmBinaryOperatorIr.logicalAnd => 4,
      EsmBinaryOperatorIr.logicalOr => 3,
    };
  }

  bool _canFlattenRightBinary(
    EsmBinaryOperatorIr parentOperator,
    EsmBinaryOperatorIr childOperator,
  ) {
    return parentOperator == childOperator &&
        (parentOperator == EsmBinaryOperatorIr.multiply ||
            parentOperator == EsmBinaryOperatorIr.logicalAnd ||
            parentOperator == EsmBinaryOperatorIr.logicalOr ||
            parentOperator == EsmBinaryOperatorIr.bitAnd ||
            parentOperator == EsmBinaryOperatorIr.bitXor ||
            parentOperator == EsmBinaryOperatorIr.bitOr);
  }

  String _emitUnaryExpression(EsmUnaryIr expression) {
    final operand = _emitUnaryOperand(expression.operand);
    return switch (expression.operator) {
      EsmUnaryOperatorIr.logicalNot => '!$operand',
      EsmUnaryOperatorIr.negate => '-$operand',
      EsmUnaryOperatorIr.bitNot => '~$operand',
      EsmUnaryOperatorIr.typeOf => 'typeof $operand',
    };
  }

  String _emitCallCallee(EsmExpressionIr expression) {
    return switch (expression) {
      EsmIdentifierIr() ||
      EsmImportMetaIr() ||
      EsmPropertyAccessIr() ||
      EsmComputedPropertyAccessIr() ||
      EsmOptionalPropertyAccessIr() ||
      EsmOptionalMethodCallIr() ||
      EsmCallIr() ||
      EsmNewIr() ||
      EsmThisIr() ||
      EsmSuperIr() ||
      EsmParenthesizedIr() => _emitExpression(expression),
      _ => '(${_emitExpression(expression)})',
    };
  }

  String _emitUnaryOperand(EsmExpressionIr expression) {
    return switch (expression) {
      EsmBinaryIr() ||
      EsmAssignmentIr() ||
      EsmConditionalIr() => '(${_emitExpression(expression)})',
      _ => _emitExpression(expression),
    };
  }

  String _emitNullishOperand(EsmExpressionIr expression) {
    return switch (expression) {
      EsmArrowFunctionIr() ||
      EsmAssignmentIr() ||
      EsmConditionalIr() ||
      EsmNullishCoalesceIr() => '(${_emitExpression(expression)})',
      _ => _emitExpression(expression),
    };
  }

  String _emitObjectLiteralProperty(EsmObjectLiteralPropertyIr property) {
    return '${_emitPropertyKey(property.key)}: ${_emitExpression(property.value)}';
  }

  String _emitPropertyKey(EsmPropertyKeyIr key) {
    return switch (key) {
      EsmStaticPropertyKeyIr() => _emitObjectPropertyName(key.value),
      EsmComputedPropertyKeyIr() => '[${_emitExpression(key.expression)}]',
    };
  }

  String _emitFunctionExpression(EsmFunctionExpressionIr expression) {
    final parameters = expression.parameters.map(_emitParameter).join(', ');
    if (expression.body.isEmpty) {
      return 'function($parameters) {}';
    }
    final bodyPrinter = _EsmIrPrinter().._indent = _indent + 1;
    for (final statement in expression.body) {
      bodyPrinter._emitStatement(statement);
    }
    final body = bodyPrinter._buffer.toString().trimRight();
    return 'function($parameters) {\n$body\n${'  ' * _indent}}';
  }

  String _emitArrowBlockFunction(EsmArrowBlockFunctionIr expression) {
    final parameters = expression.parameters.map(_emitParameter).join(', ');
    if (expression.body.isEmpty) {
      return '($parameters) => {}';
    }
    final bodyPrinter = _EsmIrPrinter().._indent = _indent + 1;
    for (final statement in expression.body) {
      bodyPrinter._emitStatement(statement);
    }
    final body = bodyPrinter._buffer.toString().trimRight();
    return '($parameters) => {\n$body\n${'  ' * _indent}}';
  }

  String _emitObjectPropertyName(String name) {
    return RegExp(r'^[A-Za-z_$][\w$]*$').hasMatch(name)
        ? name
        : jsonEncode(name);
  }

  String _emitStringConcatenation(EsmStringConcatenationIr expression) {
    if (expression.expressions.isEmpty) {
      return '""';
    }
    final buffer = StringBuffer('`');
    for (final part in expression.expressions) {
      if (part case EsmStringLiteralIr()) {
        buffer.write(_escapeTemplateText(part.value));
      } else {
        buffer.write(r'${');
        buffer.write(_emitExpression(part));
        buffer.write('}');
      }
    }
    buffer.write('`');
    return buffer.toString();
  }

  String _escapeTemplateText(String value) {
    return value
        .replaceAll(r'\', r'\\')
        .replaceAll('`', r'\`')
        .replaceAll(r'${', r'\${');
  }

  String _emitNumber(num value) {
    if (value.isNaN) {
      return 'NaN';
    }
    if (value == double.infinity) {
      return 'Infinity';
    }
    if (value == double.negativeInfinity) {
      return '-Infinity';
    }
    return value.toString();
  }

  void _writeIndented(String line) {
    _buffer.write('  ' * _indent);
    _buffer.writeln(line);
  }
}
