import 'dart:convert';

import '../ir/esm_ir.dart';
import '../transform/module_normalizer.dart';

final class CodegenStageResult {
  const CodegenStageResult({required this.code, required this.diagnostics});

  final String code;
  final List<String> diagnostics;
}

final class EsmCodegenStage {
  const EsmCodegenStage();

  CodegenStageResult emit(NormalizationResult normalized) {
    final printer = _EsmIrPrinter();
    return CodegenStageResult(
      code: printer.print(normalized.module),
      diagnostics: const [],
    );
  }
}

final class _EsmIrPrinter {
  final _buffer = StringBuffer();
  var _indent = 0;

  String print(EsmModuleIr module) {
    _buffer.writeln('// Generated by dart2esm.');
    _buffer.writeln();
    for (var i = 0; i < module.items.length; i++) {
      _emitModuleItem(module.items[i]);
      if (i != module.items.length - 1 && module.items[i] is EsmFunctionIr) {
        _buffer.writeln();
      }
    }
    return _buffer.toString();
  }

  void _emitModuleItem(EsmModuleItemIr item) {
    switch (item) {
      case EsmFunctionIr():
        _emitFunction(item);
      case EsmStatementIr():
        _emitStatement(item);
    }
  }

  void _emitFunction(EsmFunctionIr function) {
    final exportPrefix = function.export ? 'export ' : '';
    _writeIndented(
      '${exportPrefix}function ${function.name}(${function.parameters.join(', ')}) {',
    );
    _indent++;
    for (final statement in function.body) {
      _emitStatement(statement);
    }
    _indent--;
    _writeIndented('}');
  }

  void _emitStatement(EsmStatementIr statement) {
    switch (statement) {
      case EsmExpressionStatementIr():
        _writeIndented('${_emitExpression(statement.expression)};');
      case EsmReturnStatementIr():
        final expression = statement.expression;
        _writeIndented(
          expression == null
              ? 'return;'
              : 'return ${_emitExpression(expression)};',
        );
    }
  }

  String _emitExpression(EsmExpressionIr expression) {
    return switch (expression) {
      EsmIdentifierIr() => expression.name,
      EsmStringLiteralIr() => jsonEncode(expression.value),
      EsmNumberLiteralIr() => _emitNumber(expression.value),
      EsmBooleanLiteralIr() => expression.value ? 'true' : 'false',
      EsmNullLiteralIr() => 'null',
      EsmCallIr() =>
        '${_emitExpression(expression.callee)}(${expression.arguments.map(_emitExpression).join(', ')})',
    };
  }

  String _emitNumber(num value) {
    if (value.isNaN) {
      return 'NaN';
    }
    if (value == double.infinity) {
      return 'Infinity';
    }
    if (value == double.negativeInfinity) {
      return '-Infinity';
    }
    return value.toString();
  }

  void _writeIndented(String line) {
    _buffer.write('  ' * _indent);
    _buffer.writeln(line);
  }
}
