function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartDuration(options = {}) {
  const micros = Math.trunc((options.days ?? 0) * 86400000000 + (options.hours ?? 0) * 3600000000 + (options.minutes ?? 0) * 60000000 + (options.seconds ?? 0) * 1000000 + (options.milliseconds ?? 0) * 1000 + (options.microseconds ?? 0));
  return {
    get inDays() { return Math.trunc(micros / 86400000000); },
    get inHours() { return Math.trunc(micros / 3600000000); },
    get inMinutes() { return Math.trunc(micros / 60000000); },
    get inSeconds() { return Math.trunc(micros / 1000000); },
    get inMilliseconds() { return Math.trunc(micros / 1000); },
    get inMicroseconds() { return micros; },
    toString() { return String(micros) + "us"; },
  };
}
function __dartIterableJoin(iterable, separator = "") {
  return Array.from(iterable, (value) => __dartStr(value)).join(String(separator));
}
function __dartCompleter() {
  let completed = false;
  let resolveFuture;
  let rejectFuture;
  const future = new Promise((resolve, reject) => { resolveFuture = resolve; rejectFuture = reject; });
  return {
    future,
    get isCompleted() { return completed; },
    complete(value = null) {
      if (completed) throw new Error("Future already completed");
      completed = true;
      Promise.resolve(value).then(resolveFuture, rejectFuture);
      return null;
    },
    completeError(error, stackTrace = null) {
      if (completed) throw new Error("Future already completed");
      completed = true;
      rejectFuture(error);
      return null;
    },
  };
}
function __dartTimer(duration, callback, periodic) {
  const delay = Math.max(0, typeof duration === "number" ? duration : duration.inMilliseconds);
  let active = true;
  let tick = 0;
  let id;
  const timer = {
    get tick() { return tick; },
    get isActive() { return active; },
    cancel() {
      if (!active) return null;
      active = false;
      periodic ? clearInterval(id) : clearTimeout(id);
      return null;
    },
  };
  if (periodic) {
    id = setInterval(() => {
      if (!active) return;
      tick++;
      callback(timer);
    }, delay);
  } else {
    id = setTimeout(() => {
      if (!active) return;
      active = false;
      tick = 1;
      callback();
    }, delay);
  }
  return timer;
}
function __dartFutureAsStream(future) {
  return (async function*() {
    yield await future;
  })();
}
function __dartFutureTimeout(future, duration, onTimeout = null) {
  const delay = Math.max(0, typeof duration === "number" ? duration : duration.inMilliseconds);
  return new Promise((resolve, reject) => {
    let settled = false;
    const id = setTimeout(() => {
      if (settled) return;
      settled = true;
      try {
        if (typeof onTimeout === "function") {
          resolve(onTimeout());
        } else {
          reject(new Error("TimeoutException: Future not completed"));
        }
      } catch (error) {
        reject(error);
      }
    }, delay);
    Promise.resolve(future).then(
      (value) => {
        if (settled) return;
        settled = true;
        clearTimeout(id);
        resolve(value);
      },
      (error) => {
        if (settled) return;
        settled = true;
        clearTimeout(id);
        reject(error);
      },
    );
  });
}
function __dartStreamFromIterable(values) {
  return (async function*() {
    for (const value of values) yield value;
  })();
}
function __dartStreamMap(stream, convert) {
  return (async function*() {
    for await (const value of stream) {
      yield convert(value);
    }
  })();
}
function __dartStreamWhere(stream, test) {
  return (async function*() {
    for await (const value of stream) {
      if (test(value)) yield value;
    }
  })();
}
async function __dartStreamToList(stream) {
  const values = [];
  for await (const value of stream) values.push(value);
  return values;
}
async function __dartStreamFirst(stream) {
  for await (const value of stream) return value;
  throw new RangeError("No element");
}
function __dartEquals(left, right) {
  return left === right;
}

// Generated by dart2esm.

export async function main() {
  const first = await Promise.resolve(1);
  const second = await Promise.resolve().then(() => (function() { return 2; })());
  const delayed = await new Promise((resolve, reject) => setTimeout(() => { try { resolve((function() { return 3; })()); } catch (error) { reject(error); } }, Math.max(0, __dartDuration({ microseconds: 1000 }).inMilliseconds)));
  const values = await Promise.all(Array.from([Promise.resolve(first), Promise.resolve(second), Promise.resolve(delayed)]));
  __dartPrint("future " + __dartStr(__dartIterableJoin(values, ",")));
  const microtask = await Promise.resolve().then(() => (function() { return 4; })());
  const any = await Promise.race(Array.from([new Promise((resolve, reject) => setTimeout(() => { try { resolve((function() { return 99; })()); } catch (error) { reject(error); } }, Math.max(0, __dartDuration({ microseconds: 5000 }).inMilliseconds))), Promise.resolve(5)]));
  __dartPrint("more " + __dartStr(microtask) + " " + __dartStr(any));
  const completer = __dartCompleter();
  Promise.resolve().then(() => (function() { return completer.complete(6); })());
  __dartPrint("complete " + __dartStr(await completer.future) + " " + __dartStr(completer.isCompleted));
  const syncCompleter = __dartCompleter();
  syncCompleter.complete("ok");
  __dartPrint("sync " + __dartStr(await syncCompleter.future));
  const failed = __dartCompleter();
  failed.completeError("broken");
  try {
    {
      await failed.future;
    }
  } catch ($error) {
    if ($error != null) {
      const error = $error;
      {
        __dartPrint("completeError " + __dartStr(error));
      }
    } else {
      throw $error;
    }
  }
  const timerDone = __dartCompleter();
  const timer = __dartTimer(__dartDuration({ microseconds: 1000 }), function() {
    timerDone.complete("fired");
}, false);
  __dartPrint("timer-start " + __dartStr(timer.isActive) + " " + __dartStr(timer.tick));
  __dartPrint("timer " + __dartStr(await timerDone.future) + " " + __dartStr(timer.isActive));
  let canceledFired = false;
  const canceled = __dartTimer(__dartDuration({ microseconds: 5000 }), function() {
    canceledFired = true;
}, false);
  canceled.cancel();
  await new Promise((resolve, reject) => setTimeout(() => { try { resolve(null); } catch (error) { reject(error); } }, Math.max(0, __dartDuration({ microseconds: 10000 }).inMilliseconds)));
  __dartPrint("cancel " + __dartStr(canceled.isActive) + " " + __dartStr(canceledFired));
  const runDone = __dartCompleter();
  (__dartTimer(0, function() {
    runDone.complete("run");
}, false), null);
  __dartPrint("run " + __dartStr(await runDone.future));
  const periodicDone = __dartCompleter();
  __dartTimer(__dartDuration({ microseconds: 1000 }), function(timer) {
    if ((timer.tick >= 2)) {
      {
        periodicDone.complete(timer.tick);
        timer.cancel();
      }
    }
}, true);
  __dartPrint("periodic " + __dartStr(await periodicDone.future));
  let finalized = false;
  const chained = await Promise.resolve(7).then(function(value) { return (value + 1); });
  const recovered = await Promise.reject("recover").catch(function(error) { return 8; });
  const completed = await Promise.resolve(9).finally(function() {
    finalized = true;
});
  const handledThen = await Promise.reject("then-error").then(function(__wc0_formal) { return 0; }, function(error) { return 10; });
  const filtered = await Promise.reject("filtered").catch((error) => (function(error) { return __dartEquals(error, "filtered"); })(error) ? (function(error) { return 11; })(error) : Promise.reject(error));
  __dartPrint("chain " + __dartStr(chained) + " " + __dartStr(recovered) + " " + __dartStr(completed) + " " + __dartStr(finalized) + " " + __dartStr(handledThen) + " " + __dartStr(filtered));
  const streamed = await __dartStreamFirst(__dartFutureAsStream(Promise.resolve("streamed")));
  const fast = await __dartFutureTimeout(Promise.resolve("fast"), __dartDuration({ microseconds: 10000 }), null);
  const fallback = await __dartFutureTimeout(new Promise((resolve, reject) => setTimeout(() => { try { resolve((function() { return "slow"; })()); } catch (error) { reject(error); } }, Math.max(0, __dartDuration({ microseconds: 10000 }).inMilliseconds))), __dartDuration({ microseconds: 1000 }), function() { return "fallback"; });
  __dartPrint("futureStream " + __dartStr(streamed) + " " + __dartStr(fast) + " " + __dartStr(fallback));
  try {
    {
      await Promise.reject("boom");
    }
  } catch ($error_1) {
    if ($error_1 != null) {
      const error_1 = $error_1;
      {
        __dartPrint("caught " + __dartStr(error_1));
      }
    } else {
      throw $error_1;
    }
  }
}

await main();
