function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartDuration(options = {}) {
  const micros = Math.trunc((options.days ?? 0) * 86400000000 + (options.hours ?? 0) * 3600000000 + (options.minutes ?? 0) * 60000000 + (options.seconds ?? 0) * 1000000 + (options.milliseconds ?? 0) * 1000 + (options.microseconds ?? 0));
  return {
    get inDays() { return Math.trunc(micros / 86400000000); },
    get inHours() { return Math.trunc(micros / 3600000000); },
    get inMinutes() { return Math.trunc(micros / 60000000); },
    get inSeconds() { return Math.trunc(micros / 1000000); },
    get inMilliseconds() { return Math.trunc(micros / 1000); },
    get inMicroseconds() { return micros; },
    toString() { return String(micros) + "us"; },
  };
}
function __dartIterableJoin(iterable, separator = "") {
  return Array.from(iterable, (value) => __dartStr(value)).join(String(separator));
}

// Generated by dart2esm.

export async function main() {
  const first = await Promise.resolve(1);
  const second = await Promise.resolve().then(() => (function() { return 2; })());
  const delayed = await new Promise((resolve, reject) => setTimeout(() => { try { resolve((function() { return 3; })()); } catch (error) { reject(error); } }, Math.max(0, __dartDuration({ microseconds: 1000 }).inMilliseconds)));
  const values = await Promise.all(Array.from([Promise.resolve(first), Promise.resolve(second), Promise.resolve(delayed)]));
  __dartPrint("future " + __dartStr(__dartIterableJoin(values, ",")));
  try {
    {
      await Promise.reject("boom");
    }
  } catch ($error) {
    if ($error != null) {
      const error = $error;
      {
        __dartPrint("caught " + __dartStr(error));
      }
    } else {
      throw $error;
    }
  }
}

await main();
