function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartBigIntParse(source, radix = null, tryParse = false) {
  try {
    const text = String(source).trim();
    const sign = /^[+-]/.test(text) ? text[0] : "";
    let digits = sign === "" ? text : text.slice(1);
    let base = radix == null ? null : Number(radix);
    if (base == null && /^0x[0-9a-f]+$/i.test(digits)) { base = 16; digits = digits.slice(2); }
    base ??= 10;
    if (!Number.isInteger(base) || base < 2 || base > 36) throw new RangeError("Radix out of range");
    if (digits.length === 0) throw new Error("Invalid BigInt literal");
    let value = 0n;
    const bigBase = BigInt(base);
    for (const char of digits.toLowerCase()) {
      const code = char.charCodeAt(0);
      const digit = code >= 48 && code <= 57 ? code - 48 : code >= 97 && code <= 122 ? code - 87 : -1;
      if (digit < 0 || digit >= base) throw new Error("Invalid BigInt literal");
      value = value * bigBase + BigInt(digit);
    }
    return sign === "-" ? -value : value;
  } catch (error) {
    if (tryParse) return null;
    throw error;
  }
}
function __dartBigIntBitLength(value) {
  if (value === 0n || value === -1n) return 0;
  const magnitude = value < 0n ? -value - 1n : value;
  return magnitude.toString(2).length;
}
function __dartEquals(left, right) {
  if (left === right) return true;
  if (left == null || right == null) return false;
  if ((typeof left === "number" || left.__dartType === "double") && (typeof right === "number" || right.__dartType === "double")) return Number(left) === Number(right);
  const equals = left["=="];
  return typeof equals === "function" ? equals.call(left, right) : false;
}

// Generated by dart2esm.

export function hide(value) {
  return value;
}

export function main() {
  const parsed = __dartBigIntParse("42", null, false);
  const prefixed = __dartBigIntParse("0xff", null, false);
  const hex = __dartBigIntParse("ff", 16, false);
  const maybe = (__dartBigIntParse("nope", null, true) ?? BigInt(Math.trunc((-1))));
  const fromDouble = BigInt(Math.trunc(5.9));
  __dartPrint("parse " + __dartStr(parsed) + " " + __dartStr(prefixed) + " " + __dartStr(hex) + " " + __dartStr(maybe) + " " + __dartStr(fromDouble));
  const sum = (parsed + 2n);
  const product = (sum * BigInt(Math.trunc(2)));
  const divided = (product / BigInt(Math.trunc(3)));
  const mod = (product % BigInt(Math.trunc(5)));
  const negated = (-BigInt(Math.trunc(7)));
  __dartPrint("ops " + __dartStr(sum) + " " + __dartStr(product) + " " + __dartStr(divided) + " " + __dartStr(mod) + " " + __dartStr((negated < 0n ? -negated : negated)) + " " + __dartStr((negated < 0n)));
  __dartPrint("meta " + __dartStr(Number(parsed)) + " " + __dartStr(hex.toString(16)) + " " + __dartStr((parsed % 2n === 0n)) + " " + __dartStr((parsed % 2n !== 0n)) + " " + __dartStr((0n < 0n ? -1 : (0n > 0n ? 1 : 0))) + " " + __dartStr(__dartBigIntBitLength(prefixed)) + " " + __dartStr(typeof hide(parsed) === "bigint"));
  __dartPrint("compare " + __dartStr((parsed > 1n)) + " " + __dartStr(__dartEquals(parsed, BigInt(Math.trunc(42)))));
}

main();
