function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartSetAdd(set, value) {
  if (set.__dartIdentitySet) {
    if (set.has(value)) return false;
    set.add(value);
    return true;
  }
  if (__dartIterableContains(set, value)) return false;
  set.add(value);
  return true;
}
const __dartMapMissingKey = Symbol("dart.mapMissingKey");
function __dartMapKey(map, key) {
  if (map.__dartIdentityMap) return map.has(key) ? key : __dartMapMissingKey;
  for (const candidate of map.keys()) {
    if (__dartEquals(candidate, key)) return candidate;
  }
  return __dartMapMissingKey;
}
function __dartMapContainsKey(map, key) {
  return __dartMapKey(map, key) !== __dartMapMissingKey;
}
function __dartMapGet(map, key) {
  const actualKey = __dartMapKey(map, key);
  return actualKey === __dartMapMissingKey ? null : map.get(actualKey);
}
function __dartMapSet(map, key, value) {
  const actualKey = __dartMapKey(map, key);
  map.set(actualKey === __dartMapMissingKey ? key : actualKey, value);
  return value;
}
function __dartListRemove(list, needle) {
  const index = list.findIndex((value) => __dartEquals(value, needle));
  if (index < 0) return false;
  list.splice(index, 1);
  return true;
}
function __dartListRemoveWhere(list, test) {
  list.splice(0, list.length, ...list.filter((value) => !test(value)));
  return null;
}
function __dartListRetainWhere(list, test) {
  list.splice(0, list.length, ...list.filter((value) => test(value)));
  return null;
}
function __dartIterableContains(iterable, needle) {
  if (iterable instanceof Set && iterable.__dartIdentitySet) return iterable.has(needle);
  for (const value of iterable) {
    if (__dartEquals(value, needle)) return true;
  }
  return false;
}
function __dartIterableJoin(iterable, separator = "") {
  return Array.from(iterable, (value) => __dartStr(value)).join(String(separator));
}
function __dartEquals(left, right) {
  if (left === right) return true;
  if (left == null || right == null) return false;
  if ((typeof left === "number" || left.__dartType === "double") && (typeof right === "number" || right.__dartType === "double")) return Number(left) === Number(right);
  const equals = left["=="];
  return typeof equals === "function" ? equals.call(left, right) : false;
}

// Generated by dart2esm.

export function main() {
  const map = new Map();
  __dartMapSet(map, "one", 1);
  __dartMapSet(map, "two", 2);
  __dartPrint("hashMap " + __dartStr(map.size) + " " + __dartStr(__dartMapContainsKey(map, "two")) + " " + __dartStr(__dartMapGet(map, "one")));
  const set = new Set();
  __dartSetAdd(set, "a");
  __dartSetAdd(set, "b");
  __dartSetAdd(set, "a");
  __dartPrint("hashSet " + __dartStr(set.size) + " " + __dartStr(__dartIterableContains(set, "a")) + " " + __dartStr(__dartIterableJoin(set, ",")));
  const queue = [];
  (queue.push(1), null);
  (queue.unshift(0), null);
  (queue.push(2), null);
  __dartPrint("queue " + __dartStr(queue.length) + " " + __dartStr(queue[0]) + " " + __dartStr(queue[queue.length - 1]) + " " + __dartStr(__dartIterableJoin(queue, ",")));
  __dartPrint("remove " + __dartStr(queue.shift()) + " " + __dartStr(queue.pop()) + " " + __dartStr(__dartIterableJoin(queue, ",")));
  const linked = [];
  (linked.push(...Array.from(["b", "c"])), null);
  (linked.unshift("a"), null);
  __dartPrint("linkedQueue " + __dartStr(linked.length) + " " + __dartStr(__dartListRemove(linked, "b")) + " " + __dartStr(__dartIterableJoin(linked, ",")));
  const copied = Array.from([1, 2, 3, 4]);
  __dartListRemoveWhere(copied, function(value) { return (Math.trunc(value) % 2 !== 0); });
  __dartListRetainWhere(copied, function(value) { return (value > 2); });
  (copied.push(...Array.from(Array.from([5, 6]))), null);
  __dartPrint("listQueue " + __dartStr(copied[0]) + " " + __dartStr(copied[copied.length - 1]) + " " + __dartStr(copied.length !== 0) + " " + __dartStr(__dartIterableJoin(copied, ",")));
  __dartPrint("queueIter " + __dartStr(Array.from(copied)[1]) + " " + __dartStr(__dartIterableJoin(Array.from(copied), "|")) + " " + __dartStr(Array.from(copied).some(function(value) { return __dartEquals(value, 5); })) + " " + __dartStr(Array.from(copied).every(function(value) { return (value > 0); })));
  (copied.length = 0, null);
  __dartPrint("queueClear " + __dartStr(copied.length) + " " + __dartStr(copied.length === 0));
}

main();
