function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartSetAdd(set, value) {
  const hadValue = set.has(value);
  set.add(value);
  return !hadValue;
}
function __dartMapRemove(map, key) {
  const value = map.has(key) ? map.get(key) : null;
  map.delete(key);
  return value;
}
function __dartMapContainsValue(map, needle) {
  for (const value of map.values()) {
    if (__dartEquals(value, needle)) return true;
  }
  return false;
}
function __dartMapPutIfAbsent(map, key, ifAbsent) {
  if (map.has(key)) return map.get(key);
  const value = ifAbsent();
  map.set(key, value);
  return value;
}
function __dartMapUpdate(map, key, update, ifAbsent = null) {
  if (map.has(key)) {
    const value = update(map.get(key));
    map.set(key, value);
    return value;
  }
  if (typeof ifAbsent === "function") {
    const value = ifAbsent();
    map.set(key, value);
    return value;
  }
  throw new Error("Key not in map");
}
function __dartMapUpdateAll(map, update) {
  for (const [key, value] of Array.from(map)) {
    map.set(key, update(key, value));
  }
  return null;
}
function __dartListSort(list, compare = null) {
  if (typeof compare === "function") {
    list.sort((left, right) => compare(left, right));
  } else {
    list.sort((left, right) => left < right ? -1 : (left > right ? 1 : 0));
  }
  return null;
}
function __dartListRemove(list, needle) {
  const index = list.findIndex((value) => __dartEquals(value, needle));
  if (index < 0) return false;
  list.splice(index, 1);
  return true;
}
function __dartListSetAll(list, index, values) {
  let offset = 0;
  for (const value of values) {
    list[index + offset] = value;
    offset++;
  }
  return null;
}
function __dartListRemoveWhere(list, test) {
  list.splice(0, list.length, ...list.filter((value) => !test(value)));
  return null;
}
function __dartListRetainWhere(list, test) {
  list.splice(0, list.length, ...list.filter((value) => test(value)));
  return null;
}
function __dartListAsMap(list) {
  return new Map(Array.from(list, (value, index) => [index, value]));
}
function __dartIterableContains(iterable, needle) {
  for (const value of iterable) {
    if (__dartEquals(value, needle)) return true;
  }
  return false;
}
function __dartSetLookup(set, needle) {
  for (const value of set) {
    if (__dartEquals(value, needle)) return value;
  }
  return null;
}
function __dartIterableJoin(iterable, separator = "") {
  return Array.from(iterable, (value) => __dartStr(value)).join(String(separator));
}
function __dartIterableNoElement(orElse) {
  if (typeof orElse === "function") return orElse();
  throw new Error("Bad state: No element");
}
function __dartIterableFirstWhere(iterable, test, orElse = null) {
  for (const value of iterable) {
    if (test(value)) return value;
  }
  return __dartIterableNoElement(orElse);
}
function __dartIterableLastWhere(iterable, test, orElse = null) {
  let found = false;
  let last;
  for (const value of iterable) {
    if (test(value)) { found = true; last = value; }
  }
  return found ? last : __dartIterableNoElement(orElse);
}
function __dartIterableSingleWhere(iterable, test, orElse = null) {
  let found = false;
  let single;
  for (const value of iterable) {
    if (!test(value)) continue;
    if (found) throw new Error("Bad state: Too many elements");
    found = true;
    single = value;
  }
  return found ? single : __dartIterableNoElement(orElse);
}
function __dartEquals(left, right) {
  return left === right;
}

// Generated by dart2esm.

export function main() {
  const values = new Array(3).fill(1);
  values[1] = 2;
  (values.push(4), null);
  (values.push(...Array.from([5, 6])), null);
  __dartPrint("list " + __dartStr(values.length) + " " + __dartStr(values[0]) + " " + __dartStr(values[values.length - 1]));
  __dartPrint("list contains " + __dartStr(__dartIterableContains(values, 3)) + " " + __dartStr(__dartIterableContains(values, 4)));
  __dartPrint("list join " + __dartStr(__dartIterableJoin(values, ",")));
  const generated = Array.from({ length: 4 }, (_, index) => (function(index) { return (index * index); })(index));
  __dartPrint("generated " + __dartStr(__dartIterableJoin(generated, ":")));
  const filtered = Array.from(Array.from(Array.from(values).filter(function(value) { return __dartEquals((value % 2), 0); }), function(value) { return (value * 10); }));
  __dartPrint("filtered " + __dartStr(__dartIterableJoin(filtered, "|")));
  __dartPrint("fold " + __dartStr(Array.from(values).reduce((previous, value) => (function(total, value) { return (total + value); })(previous, value), 0)) + " " + __dartStr(Array.from(values).some(function(value) { return (value > 5); })) + " " + __dartStr(Array.from(values).every(function(value) { return (value > 0); })));
  __dartPrint("iter " + __dartStr(__dartIterableJoin(Array.from(Array.from(values).slice(2)).slice(0, 3), ",")) + " " + __dartStr(Array.from(values)[2]) + " " + __dartStr(Array.from(values).reduce((previous, value) => (function(total, value) { return (total + value); })(previous, value))));
  __dartPrint("where " + __dartStr(__dartIterableFirstWhere(values, function(value) { return (value > 3); }, null)) + " " + __dartStr(__dartIterableLastWhere(values, function(value) { return (Math.trunc(value) % 2 !== 0); }, null)) + " " + __dartStr(__dartIterableSingleWhere(values, function(value) { return __dartEquals(value, 4); }, null)) + " " + __dartStr(__dartIterableFirstWhere(values, function(value) { return (value > 99); }, function() { return (-1); })));
  let visited = 0;
  (Array.from(values).forEach(function(value) {
    visited = (visited + value);
}), null);
  __dartPrint("forEach " + __dartStr(visited));
  const mutable = [3, 1, 2];
  __dartListSort(mutable, null);
  const removed = mutable.splice(1, 1)[0];
  (mutable.splice(1, 0, 9), null);
  __dartPrint("mutable " + __dartStr(__dartIterableJoin(mutable, ",")) + " " + __dartStr(removed) + " " + __dartStr(__dartIterableJoin(mutable.slice(1), ",")) + " " + __dartStr(__dartIterableJoin(Array.from(mutable).reverse(), ",")));
  const indexed = __dartListAsMap(mutable);
  __dartPrint("asMap " + __dartStr(indexed.size) + " " + __dartStr(indexed.get(1)));
  const removedValue = __dartListRemove(mutable, 9);
  const removedMissing = __dartListRemove(mutable, 99);
  const removedLast = mutable.pop();
  __dartPrint("list remove " + __dartStr(removedValue) + " " + __dartStr(removedMissing) + " " + __dartStr(removedLast) + " " + __dartStr(__dartIterableJoin(mutable, ",")));
  (mutable.splice(1, 0, ...Array.from([8, 7])), null);
  __dartListSetAll(mutable, 0, [4, 5]);
  (mutable.fill(6, 1, 2), null);
  (mutable.splice(2, 3 - 2, ...Array.from([10, 11])), null);
  (mutable.splice(0, 1 - 0), null);
  __dartListRemoveWhere(mutable, function(value) { return (value > 10); });
  __dartListRetainWhere(mutable, function(value) { return (value >= 6); });
  __dartPrint("list bulk " + __dartStr(__dartIterableJoin(mutable, ",")));
  const names = (() => {
    const v = new Set();
    __dartSetAdd(v, "ada");
    __dartSetAdd(v, "bob");
    return v;
  })();
  __dartSetAdd(names, "cy");
  names.delete("bob");
  __dartPrint("set " + __dartStr(names.size) + " " + __dartStr(names.has("ada")) + " " + __dartStr(names.has("bob")));
  __dartPrint("set lookup " + __dartStr(__dartSetLookup(names, "ada")) + " " + __dartStr(__dartSetLookup(names, "missing")));
  __dartPrint("set join " + __dartStr(__dartIterableJoin(names, "/")));
  const counts = new Map([["one", 1]]);
  counts.set("two", 2);
  __dartPrint("map " + __dartStr(counts.size) + " " + __dartStr(counts.has("two")) + " " + __dartStr(counts.get("one")));
  __dartPrint("map iter " + __dartStr(__dartIterableJoin(counts.keys(), ",")) + " " + __dartStr(__dartIterableJoin(counts.values(), ",")));
  const three = __dartMapPutIfAbsent(counts, "three", function() { return 3; });
  __dartMapUpdate(counts, "two", function(value) { return (value * 10); }, null);
  __dartMapUpdate(counts, "missing", function(value) { return value; }, function() { return 4; });
  const mapPairs = new Array(0).fill(null);
  (counts.forEach((value, key) => (function(key, value) {
    (mapPairs.push(__dartStr(key) + "=" + __dartStr(value)), null);
})(key, value)), null);
  __dartPrint("map ops " + __dartStr(three) + " " + __dartStr(counts.get("two")) + " " + __dartStr(counts.get("missing")) + " " + __dartStr(__dartIterableJoin(mapPairs, "|")));
  __dartMapRemove(counts, "one");
  __dartPrint("map removed " + __dartStr(counts.size) + " " + __dartStr(counts.get("one")));
  __dartMapUpdateAll(counts, function(key, value) { return (value + key.length); });
  const entries = Array.from(Array.from(counts, ([key, value]) => ({ key, value })), function(entry) { return __dartStr(entry.key) + ":" + __dartStr(entry.value); });
  __dartPrint("map more " + __dartStr(__dartMapContainsValue(counts, 27)) + " " + __dartStr(__dartIterableJoin(entries, "|")));
  (counts.clear(), null);
  __dartPrint("map cleared " + __dartStr(counts.size === 0));
}

main();
