// Generated by dart2esm.

function __dartCompare(left, right, compare = null) {
  if (typeof compare === "function") return Number(compare(left, right));
  const compareTo = left == null ? null : left.compareTo;
  if (typeof compareTo === "function") return Number(compareTo.call(left, right));
  return left < right ? -1 : left > right ? 1 : 0;
}

function __dartCoreError(typeName, message) {
  const text = message == null ? "" : String(message);
  const display = text === "" ? typeName : typeName + ": " + text;
  const error = new Error(text);
  error.name = typeName;
  Object.defineProperty(error, "__dartCoreErrorType", { value: typeName });
  Object.defineProperty(error, "toString", { value() { return display; } });
  return error;
}
function __dartIsCoreError(value, typeName) {
  const actual = value == null ? null : value.__dartCoreErrorType;
  if (actual != null) {
    if (actual === typeName) return true;
    if (typeName === "Exception" && actual === "FormatException") return true;
    if (typeName === "RangeError" && actual === "IndexError") return true;
    if (typeName === "ArgumentError" && (actual === "RangeError" || actual === "IndexError")) return true;
    return typeName === "Error" && actual !== "Exception" && actual !== "FormatException";
  }
  if (typeName === "TypeError" && value instanceof TypeError) return true;
  return typeName === "Error" && value instanceof Error;
}

function __dartEquals(left, right) {
  if (left === right) return true;
  if (left == null || right == null) return false;
  if ((typeof left === "number" || left.__dartType === "double") && (typeof right === "number" || right.__dartType === "double")) return Number(left) === Number(right);
  if (__dartIsRecord(left) && __dartIsRecord(right)) {
    const leftShape = left[__dartRecordShape];
    const rightShape = right[__dartRecordShape];
    if (leftShape.length !== rightShape.length) return false;
    for (let i = 0; i < leftShape.length; i++) {
      const name = leftShape[i];
      if (name !== rightShape[i]) return false;
      if (!__dartEquals(left[name], right[name])) return false;
    }
    return true;
  }
  const equals = left["=="];
  return typeof equals === "function" ? equals.call(left, right) : false;
}

function __dartIterableFirstWhere(iterable, test, orElse = null) {
  for (const value of __dartIterableToArray(iterable)) {
    if (test(value)) return value;
  }
  if (typeof orElse === "function") return orElse();
  throw new Error("No element");
}
function __dartIterableFirstOrNull(iterable) {
  for (const value of __dartIterableToArray(iterable)) return value;
  return null;
}
function __dartIterableLastWhere(iterable, test, orElse = null) {
  let found = false;
  let result;
  for (const value of __dartIterableToArray(iterable)) {
    if (test(value)) {
      found = true;
      result = value;
    }
  }
  if (found) return result;
  if (typeof orElse === "function") return orElse();
  throw new Error("No element");
}
function __dartIterableLastOrNull(iterable) {
  let found = false;
  let result;
  for (const value of __dartIterableToArray(iterable)) {
    found = true;
    result = value;
  }
  return found ? result : null;
}
function __dartIterableSingle(iterable) {
  const values = __dartIterableToArray(iterable);
  if (values.length !== 1) throw new Error(values.length === 0 ? "No element" : "Too many elements");
  return values[0];
}
function __dartIterableSingleWhere(iterable, test, orElse = null) {
  let found = false;
  let result;
  for (const value of __dartIterableToArray(iterable)) {
    if (!test(value)) continue;
    if (found) throw new Error("Too many elements");
    found = true;
    result = value;
  }
  if (found) return result;
  if (typeof orElse === "function") return orElse();
  throw new Error("No element");
}
function __dartIterableSingleOrNull(iterable) {
  let found = false;
  let result;
  for (const value of __dartIterableToArray(iterable)) {
    if (found) return null;
    found = true;
    result = value;
  }
  return found ? result : null;
}
function __dartIterableElementAtOrNull(iterable, index) {
  const values = __dartIterableToArray(iterable);
  const offset = Number(index);
  return offset >= 0 && offset < values.length ? values[offset] : null;
}

function __dartIterableToArray(iterable) {
  if (Array.isArray(iterable)) return Array.from(iterable);
  if (iterable != null && typeof iterable["[]"] === "function" && typeof iterable.length === "number") {
    return Array.from({ length: Number(iterable.length) }, (_, index) => iterable["[]"](index));
  }
  return Array.from(iterable);
}

function __dartIterableTakeWhile(iterable, test) {
  const values = [];
  for (const value of __dartIterableToArray(iterable)) {
    if (!test(value)) break;
    values.push(value);
  }
  return values;
}
function __dartIterableSkipWhile(iterable, test) {
  const values = [];
  let skipping = true;
  for (const value of __dartIterableToArray(iterable)) {
    if (skipping && test(value)) continue;
    skipping = false;
    values.push(value);
  }
  return values;
}

function __dartListAdd(list, value) {
  if (Array.isArray(list)) {
    list.push(value);
  } else if (list != null && typeof list.add === "function") {
    list.add(value);
  } else {
    const index = list.length;
    list.length = index + 1;
    __dartListLikeSet(list, index, value);
  }
  return null;
}

function __dartListAddAll(list, values) {
  for (const value of __dartIterableToArray(values)) {
    __dartListAdd(list, value);
  }
  return null;
}

function __dartFixedList(values) {
  const list = __dartIterableToArray(values);
  Object.preventExtensions(list);
  return list;
}
function __dartListOf(values, growable = true) {
  const list = __dartIterableToArray(values);
  return growable ? list : __dartFixedList(list);
}
function __dartListFilled(length, fill, growable = false) {
  const list = Array(Number(length)).fill(fill);
  return growable ? list : __dartFixedList(list);
}
function __dartListGenerate(length, generator, growable = true) {
  const list = Array.from({ length: Number(length) }, (_, index) => generator(index));
  return growable ? list : __dartFixedList(list);
}
function __dartUnmodifiableList(values) {
  return Object.freeze(__dartIterableToArray(values));
}

function __dartListLikeGet(list, index) {
  if (Array.isArray(list) || ArrayBuffer.isView(list) || typeof list === "string") return list[index];
  const op = list == null ? null : list["[]"];
  return typeof op === "function" ? op.call(list, index) : list[index];
}
function __dartListLikeSet(list, index, value) {
  if (Array.isArray(list) || ArrayBuffer.isView(list)) {
    list[index] = value;
    return value;
  }
  const op = list == null ? null : list["[]="];
  if (typeof op === "function") return op.call(list, index, value);
  list[index] = value;
  return value;
}
function __dartListMixinFirst(list) {
  return __dartListLikeGet(list, 0);
}
function __dartListMixinLast(list) {
  return __dartListLikeGet(list, list.length - 1);
}
function __dartListMixinSingle(list) {
  if (list.length !== 1) throw __dartCoreError("StateError", "Too many elements");
  return __dartListLikeGet(list, 0);
}
function __dartListMixinInsert(list, index, value) {
  index = Number(index);
  const length = Number(list.length);
  list.length = length + 1;
  for (let i = length; i > index; i--) {
    __dartListLikeSet(list, i, __dartListLikeGet(list, i - 1));
  }
  __dartListLikeSet(list, index, value);
  return null;
}

function __dartListMutationRead(list, index) {
  return list != null && typeof list["[]"] === "function" ? list["[]"](index) : list[index];
}
function __dartListMutationWrite(list, index, value) {
  if (list != null && typeof list["[]="] === "function") {
    list["[]="](index, value);
  } else {
    list[index] = value;
  }
}
function __dartListMutationValues(values) {
  return __dartIterableToArray(values);
}
function __dartListShuffle(list, random = null) {
  for (let index = list.length - 1; index > 0; index--) {
    const nextInt = random == null ? Math.floor(Math.random() * (index + 1)) : Number(random.nextInt(index + 1));
    const current = __dartListMutationRead(list, index);
    __dartListMutationWrite(list, index, __dartListMutationRead(list, nextInt));
    __dartListMutationWrite(list, nextInt, current);
  }
  return null;
}
function __dartListRemoveAt(list, index) {
  index = Number(index);
  const value = __dartListMutationRead(list, index);
  __dartListRemoveRange(list, index, index + 1);
  return value;
}
function __dartListInsert(list, index, value) {
  index = Number(index);
  if (Array.isArray(list)) {
    list.splice(index, 0, value);
    return null;
  }
  const length = Number(list.length);
  list.length = length + 1;
  for (let cursor = length; cursor > index; cursor--) {
    __dartListMutationWrite(list, cursor, __dartListMutationRead(list, cursor - 1));
  }
  __dartListMutationWrite(list, index, value);
  return null;
}
function __dartListRemove(list, value) {
  for (let index = 0; index < list.length; index++) {
    if (__dartEquals(__dartListMutationRead(list, index), value)) {
      __dartListRemoveRange(list, index, index + 1);
      return true;
    }
  }
  return false;
}
function __dartListRemoveLast(list) {
  return __dartListRemoveAt(list, list.length - 1);
}
function __dartListInsertAll(list, index, values) {
  index = Number(index);
  const inserted = __dartListMutationValues(values);
  if (Array.isArray(list)) {
    list.splice(index, 0, ...inserted);
    return null;
  }
  const length = Number(list.length);
  list.length = length + inserted.length;
  for (let cursor = length - 1; cursor >= index; cursor--) {
    __dartListMutationWrite(list, cursor + inserted.length, __dartListMutationRead(list, cursor));
  }
  for (let cursor = 0; cursor < inserted.length; cursor++) {
    __dartListMutationWrite(list, index + cursor, inserted[cursor]);
  }
  return null;
}
function __dartListSetAll(list, index, values) {
  let cursor = Number(index);
  for (const value of __dartListMutationValues(values)) {
    __dartListMutationWrite(list, cursor++, value);
  }
  return null;
}
function __dartListFillRange(list, start, end, fill = null) {
  for (let index = Number(start); index < Number(end); index++) {
    __dartListMutationWrite(list, index, fill);
  }
  return null;
}
function __dartListReplaceRange(list, start, end, values) {
  start = Number(start);
  end = Number(end);
  const replacement = __dartListMutationValues(values);
  __dartListRemoveRange(list, start, end);
  __dartListInsertAll(list, start, replacement);
  return null;
}
function __dartListRemoveRange(list, start, end) {
  start = Number(start);
  end = Number(end);
  if (Array.isArray(list)) {
    list.splice(start, end - start);
    return null;
  }
  const length = Number(list.length);
  const count = end - start;
  for (let cursor = end; cursor < length; cursor++) {
    __dartListMutationWrite(list, cursor - count, __dartListMutationRead(list, cursor));
  }
  list.length = length - count;
  return null;
}
function __dartListRemoveWhere(list, test) {
  for (let index = list.length - 1; index >= 0; index--) {
    if (test(__dartListMutationRead(list, index))) {
      __dartListRemoveRange(list, index, index + 1);
    }
  }
  return null;
}
function __dartListRetainWhere(list, test) {
  for (let index = list.length - 1; index >= 0; index--) {
    if (!test(__dartListMutationRead(list, index))) {
      __dartListRemoveRange(list, index, index + 1);
    }
  }
  return null;
}
function __dartListAsMap(list) {
  const map = new Map();
  for (let index = 0; index < list.length; index++) map.set(index, __dartListMutationRead(list, index));
  return map;
}

function __dartListRangeRead(list, index) {
  return list != null && typeof list["[]"] === "function" ? list["[]"](index) : list[index];
}
function __dartListRangeWrite(list, index, value) {
  if (list != null && typeof list["[]="] === "function") {
    list["[]="](index, value);
  } else {
    list[index] = value;
  }
}
function __dartListRangeValues(source, start = 0, end = null) {
  const from = Number(start);
  return __dartIterableToArray(source).slice(from, end == null ? undefined : Number(end));
}
function __dartListCopyRange(target, at, source, start = 0, end = null) {
  const values = __dartListRangeValues(source, start, end);
  let index = Number(at);
  for (const value of values) __dartListRangeWrite(target, index++, value);
  return null;
}
function __dartListWriteIterable(target, at, source) {
  let index = Number(at);
  for (const value of __dartListRangeValues(source)) {
    __dartListRangeWrite(target, index++, value);
  }
  return null;
}
function __dartListSetRange(target, start, end, source, skipCount = 0) {
  const from = Number(skipCount);
  const count = Number(end) - Number(start);
  const values = __dartListRangeValues(source, from, from + count);
  let index = Number(start);
  for (const value of values) __dartListRangeWrite(target, index++, value);
  return null;
}

function __dartListIndexOf(list, needle, start = 0) {
  const values = Array.from(list);
  for (let index = Math.max(0, Number(start)); index < values.length; index++) {
    if (__dartEquals(values[index], needle)) return index;
  }
  return -1;
}
function __dartListLastIndexOf(list, needle, start = null) {
  const values = Array.from(list);
  let index = start == null ? values.length - 1 : Math.min(Number(start), values.length - 1);
  for (; index >= 0; index--) {
    if (__dartEquals(values[index], needle)) return index;
  }
  return -1;
}
function __dartListIndexWhere(list, test, start = 0) {
  const values = Array.from(list);
  for (let index = Math.max(0, Number(start)); index < values.length; index++) {
    if (test(values[index])) return index;
  }
  return -1;
}
function __dartListLastIndexWhere(list, test, start = null) {
  const values = Array.from(list);
  let index = start == null ? values.length - 1 : Math.min(Number(start), values.length - 1);
  for (; index >= 0; index--) {
    if (test(values[index])) return index;
  }
  return -1;
}

function __dartMapAddAll(map, entries) {
  for (const [key, value] of entries) __dartMapSet(map, key, value);
  return null;
}

function __dartMapContainsKey(map, key) {
  if (!(map instanceof Map) && map != null && typeof map.containsKey === "function") return map.containsKey(key);
  return __dartMapKey(map, key) !== __dartMapMissingKey;
}

function __dartMapFromEntries(entries) {
  const map = new Map();
  Object.defineProperty(map, "__dartEqualityMap", { value: true });
  __dartMapAddAll(map, entries);
  return map;
}
function __dartMapFromIterable(iterable, key = null, value = null) {
  const map = new Map();
  Object.defineProperty(map, "__dartEqualityMap", { value: true });
  for (const element of iterable) {
    __dartMapSet(
      map,
      typeof key === "function" ? key(element) : element,
      typeof value === "function" ? value(element) : element,
    );
  }
  return map;
}
function __dartMapFromIterables(keys, values) {
  const keyList = Array.from(keys);
  const valueList = Array.from(values);
  if (keyList.length !== valueList.length) throw new Error("Iterables do not have same length");
  const map = new Map();
  Object.defineProperty(map, "__dartEqualityMap", { value: true });
  for (let index = 0; index < keyList.length; index++) {
    __dartMapSet(map, keyList[index], valueList[index]);
  }
  return map;
}

const __dartMapMissingKey = Symbol("dart.mapMissingKey");
function __dartMapKey(map, key) {
  if (typeof map.__dartSplayIsValidKey === "function" && !map.__dartSplayIsValidKey(key)) return __dartMapMissingKey;
  if (map.__dartSplayCompare !== undefined) {
    for (const candidate of map.keys()) {
      if (__dartCompare(candidate, key, map.__dartSplayCompare) === 0) return candidate;
    }
    return __dartMapMissingKey;
  }
  if (typeof map.__dartMapIsValidKey === "function" && !map.__dartMapIsValidKey(key)) return __dartMapMissingKey;
  if (typeof map.__dartMapEquals === "function") {
    for (const candidate of map.keys()) {
      if (map.__dartMapEquals(candidate, key)) return candidate;
    }
    return __dartMapMissingKey;
  }
  if (!map.__dartEqualityMap) return map.has(key) ? key : __dartMapMissingKey;
  for (const candidate of map.keys()) {
    if (__dartEquals(candidate, key)) return candidate;
  }
  return __dartMapMissingKey;
}
function __dartMapGet(map, key) {
  if (!(map instanceof Map) && map != null && typeof map["[]"] === "function") return map["[]"](key);
  const actualKey = __dartMapKey(map, key);
  return actualKey === __dartMapMissingKey ? null : map.get(actualKey);
}

function __dartMapAddEntries(map, entries) {
  for (const [key, value] of entries) __dartMapSet(map, key, value);
  return null;
}
function __dartMapContainsValue(map, value) {
  for (const candidate of map.values()) {
    if (__dartEquals(candidate, value)) return true;
  }
  return false;
}
function __dartMapPutIfAbsent(map, key, ifAbsent) {
  const actualKey = __dartMapKey(map, key);
  if (actualKey !== __dartMapMissingKey) return map.get(actualKey);
  const value = ifAbsent();
  __dartMapSet(map, key, value);
  return value;
}
function __dartMapUpdate(map, key, update, ifAbsent = null) {
  const actualKey = __dartMapKey(map, key);
  if (actualKey !== __dartMapMissingKey) {
    const value = update(map.get(actualKey));
    map.set(actualKey, value);
    return value;
  }
  if (typeof ifAbsent === "function") {
    const value = ifAbsent();
    __dartMapSet(map, key, value);
    return value;
  }
  throw new Error("Key not found");
}
function __dartMapForEach(map, action) {
  for (const [key, value] of map) action(key, value);
  return null;
}
function __dartMapMap(map, transform) {
  const result = new Map();
  Object.defineProperty(result, "__dartEqualityMap", { value: true });
  for (const [key, value] of map) {
    const entry = transform(key, value);
    __dartMapSet(result, entry[0], entry[1]);
  }
  return result;
}
function __dartMapRemove(map, key) {
  const actualKey = __dartMapKey(map, key);
  if (actualKey === __dartMapMissingKey) return null;
  const value = map.get(actualKey);
  map.delete(actualKey);
  return value;
}
function __dartMapUpdateAll(map, update) {
  for (const [key, value] of Array.from(map)) {
    map.set(key, update(key, value));
  }
  return null;
}
function __dartMapRemoveWhere(map, test) {
  for (const [key, value] of Array.from(map)) {
    if (test(key, value)) map.delete(key);
  }
  return null;
}
function __dartMapClear(map) {
  map.clear();
  return null;
}

function __dartMapSet(map, key, value) {
  const actualKey = __dartMapKey(map, key);
  map.set(actualKey === __dartMapMissingKey ? key : actualKey, value);
  if (map.__dartSplayCompare !== undefined) __dartSplaySortMap(map);
  return value;
}

function __dartRandom(seed = null, secure = false) {
  let state = seed == null ? 0 : Number(seed) >>> 0;
  function nextUint32() {
    if (secure) {
      const crypto = globalThis.crypto || globalThis.msCrypto;
      if (crypto && typeof crypto.getRandomValues === "function") {
        const values = new Uint32Array(1);
        crypto.getRandomValues(values);
        return values[0] >>> 0;
      }
    }
    if (seed == null) {
      return Math.floor(Math.random() * 0x100000000) >>> 0;
    }
    state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
    return state;
  }
  return {
    nextInt(max) {
      if (!Number.isInteger(max) || max <= 0) throw new RangeError("max must be positive");
      return nextUint32() % max;
    },
    nextDouble() { return nextUint32() / 0x100000000; },
    nextBool() { return (nextUint32() & 1) === 1; },
  };
}

const __dartIdentityHashes = new WeakMap();
let __dartNextIdentityHash = 1;
function __dartCombineHash(hash, value) {
  hash = (((hash + value) & 0x1fffffff) + (((hash & 0x0007ffff) << 10) & 0x1fffffff)) & 0x1fffffff;
  return hash ^ (hash >> 6);
}
function __dartFinishHash(hash) {
  hash = (((hash + (((hash & 0x03ffffff) << 3) & 0x1fffffff)) & 0x1fffffff) ^ (hash >> 11));
  return (hash + (((hash & 0x00003fff) << 15) & 0x1fffffff)) & 0x1fffffff;
}
function __dartHashValue(value) {
  if (value == null) return 0;
  if (typeof value === "boolean") return value ? 1231 : 1237;
  if (typeof value === "number") return Number.isFinite(value) ? Math.trunc(value) & 0x1fffffff : 0;
  if (value.__dartType === "double") {
    const number = Number(value);
    return Number.isFinite(number) ? Math.trunc(number) & 0x1fffffff : 0;
  }
  if (typeof value === "string") {
    let hash = 0;
    for (let i = 0; i < value.length; i++) hash = __dartCombineHash(hash, value.charCodeAt(i));
    return __dartFinishHash(hash);
  }
  if (typeof value === "bigint") return Number(value & 0x1fffffffn);
  if (!__dartIdentityHashes.has(value)) {
    __dartIdentityHashes.set(value, __dartNextIdentityHash);
    __dartNextIdentityHash = (__dartNextIdentityHash + 1) & 0x1fffffff || 1;
  }
  return __dartIdentityHashes.get(value);
}
function __dartObjectHash(values) {
  let hash = 0;
  for (const value of values) hash = __dartCombineHash(hash, __dartHashValue(value));
  return __dartFinishHash(hash);
}
function __dartObjectHashUnordered(values) {
  let sum = 0;
  let xor = 0;
  let count = 0;
  for (const value of values) {
    const hash = __dartHashValue(value);
    sum = (sum + hash) & 0x1fffffff;
    xor ^= hash;
    count++;
  }
  return __dartObjectHash([sum, xor, count]);
}

function __dartPrint(value) {
  console.log(__dartStr(value));
}

const __dartRecordShape = Symbol("dart.recordShape");

function __dartIsRecord(value) {
  return value != null && typeof value === "object" && Array.isArray(value[__dartRecordShape]);
}

function __dartRecord(positional, named) {
  const record = {};
  const shape = [];
  for (let i = 0; i < positional.length; i++) {
    const name = "$" + (i + 1);
    shape.push(name);
    Object.defineProperty(record, name, { value: positional[i], enumerable: true });
  }
  for (const name of Object.keys(named).sort()) {
    shape.push(name);
    Object.defineProperty(record, name, { value: named[name], enumerable: true });
  }
  Object.defineProperty(record, __dartRecordShape, { value: Object.freeze(shape) });
  Object.defineProperty(record, "toString", {
    value() {
      return "(" + shape.map((name) => {
        const value = String(record[name]);
        return name.startsWith("$") ? value : name + ": " + value;
      }).join(", ") + ")";
    },
  });
  return Object.freeze(record);
}

function __dartSetContains(set, needle) {
  if (typeof set.__dartSplayIsValidKey === "function" && !set.__dartSplayIsValidKey(needle)) return false;
  if (set.__dartSplayCompare !== undefined) {
    for (const value of set) {
      if (__dartCompare(value, needle, set.__dartSplayCompare) === 0) return true;
    }
    return false;
  }
  if (!set.__dartEqualitySet) return set.has(needle);
  for (const value of set) {
    if (__dartEquals(value, needle)) return true;
  }
  return false;
}
function __dartSetAdd(set, value) {
  if (__dartSetContains(set, value)) return false;
  set.add(value);
  if (set.__dartSplayCompare !== undefined) __dartSplaySortSet(set);
  return true;
}
function __dartSetFrom(values) {
  const set = new Set();
  Object.defineProperty(set, "__dartEqualitySet", { value: true });
  for (const value of values) __dartSetAdd(set, value);
  return set;
}
function __dartSetAddAll(set, values) {
  for (const value of values) __dartSetAdd(set, value);
  return null;
}

function __dartSetLookup(set, needle) {
  for (const value of set) {
    if (__dartEquals(value, needle)) return value;
  }
  return null;
}
function __dartSetRemove(set, value) {
  for (const candidate of set) {
    if (__dartEquals(candidate, value)) {
      set.delete(candidate);
      return true;
    }
  }
  return false;
}
function __dartSetContainsAll(set, values) {
  for (const value of values) {
    if (!__dartSetContains(set, value)) return false;
  }
  return true;
}
function __dartSetRemoveAll(set, values) {
  for (const value of values) __dartSetRemove(set, value);
  return null;
}
function __dartSetRetainAll(set, values) {
  const keep = Array.from(values);
  for (const value of Array.from(set)) {
    if (!keep.some((candidate) => __dartEquals(candidate, value))) set.delete(value);
  }
  return null;
}
function __dartSetRemoveWhere(set, test) {
  for (const value of Array.from(set)) {
    if (test(value)) set.delete(value);
  }
  return null;
}
function __dartSetRetainWhere(set, test) {
  for (const value of Array.from(set)) {
    if (!test(value)) set.delete(value);
  }
  return null;
}
function __dartSetUnion(set, other) {
  const result = __dartSetFrom(set);
  __dartSetAddAll(result, other);
  return result;
}
function __dartSetIntersection(set, other) {
  const result = __dartSetFrom([]);
  for (const value of set) {
    if (__dartSetContains(other, value)) __dartSetAdd(result, value);
  }
  return result;
}
function __dartSetDifference(set, other) {
  const result = __dartSetFrom([]);
  for (const value of set) {
    if (!__dartSetContains(other, value)) __dartSetAdd(result, value);
  }
  return result;
}

function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}

export class EqBox {
  constructor(value) {
    Object.defineProperty(this, "value", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "value", { value: value, writable: true, enumerable: true, configurable: true });
  }
  "=="(other) {
    return (other instanceof EqBox && __dartEquals(other.value, this.value));
  }
  get hashCode() {
    return __dartHashValue(this.value);
  }
}

export function main() {
  const values = __dartListFilled(3, 1, true);
  __dartListLikeSet(values, 1, 2);
  __dartListAdd(values, 4);
  __dartListAddAll(values, [5, 6]);
  __dartPrint(`list ${__dartStr(values.length)} ${__dartStr(Array.from(values)[0])} ${__dartStr(Array.from(values).at(-1))}`);
  __dartPrint(`list contains ${__dartStr(values.includes(3))} ${__dartStr(values.includes(4))}`);
  __dartPrint(`list join ${__dartStr(Array.from(values).join(","))}`);
  const generated = __dartListGenerate(4, (index) => {
    return index * index;
  }, true);
  __dartPrint(`generated ${__dartStr(Array.from(generated).join(":"))}`);
  const iterableGenerated = __dartListGenerate(3, (index) => {
    return index + 1;
  }, false);
  const iterableGeneratedDefault = __dartListGenerate(3, (index) => index, false);
  const iterableEmpty = [];
  __dartPrint(`iterableFactory ${__dartStr(Array.from(iterableGenerated).join(","))} ${__dartStr(Array.from(iterableGeneratedDefault).join(","))} ${__dartStr(__dartIterableToArray(iterableEmpty).length === 0)}`);
  const castList = [1, 2];
  const castSet = (() => {
    const v = __dartSetFrom([]);
    __dartSetAdd(v, 1);
    __dartSetAdd(v, 2);
    return v;
  })();
  const castMap = __dartMapFromEntries([["a", 1]]);
  const copyTarget = [0, 0, 0, 0];
  __dartListCopyRange(copyTarget, 1, [7, 8, 9], 0, 2);
  const writeTarget = [0, 0, 0];
  __dartListWriteIterable(writeTarget, 0, [4, 5]);
  __dartPrint(`staticCollections ${__dartStr(Array.from(castList).join(","))} ${__dartStr(Array.from(castSet).join(","))} ${__dartStr(__dartMapGet(castMap, "a"))} ${__dartStr(Array.from(copyTarget).join(","))} ${__dartStr(Array.from(writeTarget).join(","))}`);
  const filtered = __dartListOf(Array.from(__dartIterableToArray(values).filter((value) => {
    return __dartEquals(value % 2, 0);
  }), (value) => {
    return value * 10;
  }), true);
  __dartPrint(`filtered ${__dartStr(Array.from(filtered).join("|"))}`);
  __dartPrint(`fold ${__dartStr(__dartIterableToArray(values).reduce((total, value) => {
    return total + value;
  }, 0))} ${__dartStr(__dartIterableToArray(values).some((value) => {
    return value > 5;
  }))} ${__dartStr(__dartIterableToArray(values).every((value) => {
    return value > 0;
  }))}`);
  __dartPrint(`iter ${__dartStr(Array.from(__dartIterableToArray(__dartIterableToArray(values).slice(2)).slice(0, 3)).join(","))} ${__dartStr(__dartIterableToArray(values)[2])} ${__dartStr(__dartIterableToArray(values).reduce((total, value) => {
    return total + value;
  }))}`);
  __dartPrint(`iterMore ${__dartStr(Array.from(__dartIterableTakeWhile(values, (value) => {
    return value < 4;
  })).join(","))} ${__dartStr(Array.from(__dartIterableSkipWhile(values, (value) => {
    return value < 4;
  })).join(","))} ${__dartStr(Array.from(__dartIterableToArray(values).concat(__dartIterableToArray([7]))).join(","))} ${__dartStr(Array.from(__dartIterableToArray(__dartIterableToArray(values).flatMap((value) => __dartIterableToArray(((value) => {
    return [value, value * 10];
  })(value)))).slice(0, 4)).join(","))}`);
  __dartPrint(`listQuery ${__dartStr(__dartListIndexWhere(values, (value) => {
    return __dartEquals(value, 4);
  }))} ${__dartStr(__dartListLastIndexWhere(values, (value) => {
    return __dartEquals(value, 1);
  }))} ${__dartStr(Array.from(__dartIterableToArray(values).slice(1, 4)).join(","))}`);
  const boxes = [new EqBox(1), new EqBox(2), new EqBox(1)];
  __dartPrint(`listEquality ${__dartStr(__dartListIndexOf(boxes, new EqBox(1)))} ${__dartStr(__dartListIndexOf(boxes, new EqBox(1), 1))} ${__dartStr(__dartListLastIndexOf(boxes, new EqBox(1)))} ${__dartStr(__dartListLastIndexOf(boxes, new EqBox(1), 1))}`);
  __dartPrint(`where ${__dartStr(__dartIterableFirstWhere(values, (value) => {
    return value > 3;
  }))} ${__dartStr(__dartIterableLastWhere(values, (value) => {
    return Math.trunc(value) % 2 !== 0;
  }))} ${__dartStr(__dartIterableSingleWhere(values, (value) => {
    return __dartEquals(value, 4);
  }))} ${__dartStr(__dartIterableFirstWhere(values, (value) => {
    return value > 99;
  }, () => {
    return -1;
  }))}`);
  const mixedValues = [1, "two", null, 3, "four"];
  __dartPrint(`typed ${__dartStr(Array.from(__dartIterableToArray(mixedValues).filter((value) => typeof value === "number")).join(","))} ${__dartStr(Array.from(__dartIterableToArray(mixedValues).filter((value) => value != null)).join("|"))} ${__dartStr(Array.from(Array.from(values, (value) => {
    return value + 1;
  })).join(","))}`);
  __dartPrint(`indexed ${__dartStr(Array.from(__dartIterableToArray(Array.from(__dartIterableToArray(values).map((value, index) => __dartRecord([index, value], {  })), (entry) => {
    return `${__dartStr(entry.$1)}:${__dartStr(entry.$2)}`;
  })).slice(0, 3)).join("|"))}`);
  const singleValue = [42];
  const emptyValues = Array(0).fill(null);
  __dartPrint(`nullableQuery ${__dartStr(__dartIterableSingle(singleValue))} ${__dartStr(__dartIterableSingleOrNull(singleValue))} ${__dartStr(__dartIterableSingleOrNull(values))} ${__dartStr(__dartIterableFirstOrNull(emptyValues))} ${__dartStr(__dartIterableFirstOrNull(values))} ${__dartStr(__dartIterableLastOrNull(emptyValues))} ${__dartStr(__dartIterableLastOrNull(values))} ${__dartStr(__dartIterableSingleOrNull(emptyValues))} ${__dartStr(__dartIterableElementAtOrNull(values, 2))} ${__dartStr(__dartIterableElementAtOrNull(values, 99))}`);
  let visited = 0;
  __dartIterableToArray(values).forEach((value) => {
    visited = visited + value;
  });
  __dartPrint(`forEach ${__dartStr(visited)}`);
  const mutable = [3, 1, 2];
  mutable.sort(__dartCompare);
  const shuffled = [1, 2, 3, 4, 5];
  __dartListShuffle(shuffled, __dartRandom(1, false));
  const removed = __dartListRemoveAt(mutable, 1);
  __dartListInsert(mutable, 1, 9);
  __dartPrint(`mutable ${__dartStr(Array.from(mutable).join(","))} ${__dartStr(removed)} ${__dartStr(Array.from(mutable.slice(1)).join(","))} ${__dartStr(Array.from(__dartIterableToArray(mutable).reverse()).join(","))}`);
  __dartPrint(`shuffle ${__dartStr(shuffled.length)} ${__dartStr(__dartIterableToArray(__dartSetFrom(shuffled)).length)} ${__dartStr(__dartIterableToArray(shuffled).every((value) => {
    return (value >= 1 && value <= 5);
  }))}`);
  const indexed = __dartListAsMap(mutable);
  __dartPrint(`asMap ${__dartStr(indexed.size)} ${__dartStr(__dartMapGet(indexed, 1))}`);
  const removedValue = __dartListRemove(mutable, 9);
  const removedMissing = __dartListRemove(mutable, 99);
  const removedLast = __dartListRemoveLast(mutable);
  __dartPrint(`list remove ${__dartStr(removedValue)} ${__dartStr(removedMissing)} ${__dartStr(removedLast)} ${__dartStr(Array.from(mutable).join(","))}`);
  __dartListInsertAll(mutable, 1, [8, 7]);
  __dartListSetAll(mutable, 0, [4, 5]);
  __dartListFillRange(mutable, 1, 2, 6);
  __dartListReplaceRange(mutable, 2, 3, [10, 11]);
  __dartListRemoveRange(mutable, 0, 1);
  __dartListRemoveWhere(mutable, (value) => {
    return value > 10;
  });
  __dartListRetainWhere(mutable, (value) => {
    return value >= 6;
  });
  __dartPrint(`list bulk ${__dartStr(Array.from(mutable).join(","))}`);
  const names = (() => {
    const v = __dartSetFrom([]);
    __dartSetAdd(v, "ada");
    __dartSetAdd(v, "bob");
    return v;
  })();
  __dartSetAdd(names, "cy");
  __dartSetRemove(names, "bob");
  __dartPrint(`set ${__dartStr(__dartIterableToArray(names).length)} ${__dartStr(__dartSetContains(names, "ada"))} ${__dartStr(__dartSetContains(names, "bob"))}`);
  __dartPrint(`set lookup ${__dartStr(__dartSetLookup(names, "ada"))} ${__dartStr(__dartSetLookup(names, "missing"))}`);
  __dartPrint(`set join ${__dartStr(Array.from(names).join("/"))}`);
  const setBulk = (() => {
    const v = __dartSetFrom([]);
    __dartSetAdd(v, "a");
    __dartSetAdd(v, "b");
    __dartSetAdd(v, "c");
    return v;
  })();
  const hasAll = __dartSetContainsAll(setBulk, ["a", "c"]);
  __dartSetRemoveAll(setBulk, ["b", "x"]);
  __dartSetRetainAll(setBulk, ["a", "z"]);
  __dartPrint(`set bulk ${__dartStr(hasAll)} ${__dartStr(Array.from(setBulk).join(","))}`);
  const setWhere = (() => {
    const v = __dartSetFrom([]);
    __dartSetAdd(v, 1);
    __dartSetAdd(v, 2);
    __dartSetAdd(v, 3);
    __dartSetAdd(v, 4);
    return v;
  })();
  __dartSetRemoveWhere(setWhere, (value) => {
    return Math.trunc(value) % 2 !== 0;
  });
  __dartSetRetainWhere(setWhere, (value) => {
    return value > 2;
  });
  __dartPrint(`set where ${__dartStr(Array.from(setWhere).join(","))}`);
  const setUnion = __dartSetUnion(names, (() => {
    const v = __dartSetFrom([]);
    __dartSetAdd(v, "ada");
    __dartSetAdd(v, "zoe");
    return v;
  })());
  const setIntersection = __dartSetIntersection(setUnion, (() => {
    const v = __dartSetFrom([]);
    __dartSetAdd(v, "ada");
    __dartSetAdd(v, "missing");
    return v;
  })());
  const setDifference = __dartSetDifference(setUnion, (() => {
    const v = __dartSetFrom([]);
    __dartSetAdd(v, "cy");
    return v;
  })());
  const castNames = names;
  __dartPrint(`set algebra ${__dartStr(Array.from(setUnion).join(","))} ${__dartStr(Array.from(setIntersection).join(","))} ${__dartStr(Array.from(setDifference).join(","))} ${__dartStr(__dartSetContains(castNames, "ada"))}`);
  const eqSet = (() => {
    const v = __dartSetFrom([]);
    return v;
  })();
  const firstBoxAdd = __dartSetAdd(eqSet, new EqBox(1));
  const duplicateBoxAdd = __dartSetAdd(eqSet, new EqBox(1));
  __dartSetAddAll(eqSet, [new EqBox(2), new EqBox(2)]);
  const containsBox = __dartSetContains(eqSet, new EqBox(1));
  const removedBox = __dartSetRemove(eqSet, new EqBox(2));
  const eqUnion = __dartSetUnion(eqSet, (() => {
    const v = __dartSetFrom([]);
    __dartSetAdd(v, new EqBox(1));
    __dartSetAdd(v, new EqBox(3));
    return v;
  })());
  const eqIntersection = __dartSetIntersection(eqUnion, (() => {
    const v = __dartSetFrom([]);
    __dartSetAdd(v, new EqBox(1));
    __dartSetAdd(v, new EqBox(4));
    return v;
  })());
  const eqDifference = __dartSetDifference(eqUnion, (() => {
    const v = __dartSetFrom([]);
    __dartSetAdd(v, new EqBox(1));
    return v;
  })());
  __dartPrint(`setEquality ${__dartStr(firstBoxAdd)} ${__dartStr(duplicateBoxAdd)} ${__dartStr(__dartIterableToArray(eqSet).length)} ${__dartStr(containsBox)} ${__dartStr(removedBox)} ${__dartStr(__dartIterableToArray(eqSet).length)} ${__dartStr(__dartIterableToArray(eqUnion).length)} ${__dartStr(__dartIterableToArray(eqIntersection).length)} ${__dartStr(__dartIterableToArray(eqDifference).length)}`);
  const eqToSet = __dartSetFrom([new EqBox(1), new EqBox(1), new EqBox(2)]);
  __dartPrint(`setToSet ${__dartStr(__dartIterableToArray(eqToSet).length)} ${__dartStr(__dartSetContains(eqToSet, new EqBox(1)))}`);
  const counts = __dartMapFromEntries([["one", 1]]);
  __dartMapSet(counts, "two", 2);
  __dartPrint(`map ${__dartStr(counts.size)} ${__dartStr(__dartMapContainsKey(counts, "two"))} ${__dartStr(__dartMapGet(counts, "one"))}`);
  __dartPrint(`map iter ${__dartStr(Array.from(__dartIterableToArray(counts.keys())).join(","))} ${__dartStr(Array.from(__dartIterableToArray(counts.values())).join(","))}`);
  const countKeys = __dartIterableToArray(counts.keys());
  __dartPrint(`map views ${__dartStr(__dartIterableToArray(__dartIterableToArray(__dartMapFromEntries([]).keys())).length === 0)} ${__dartStr(__dartIterableToArray(countKeys).length > 0)} ${__dartStr(__dartIterableToArray(countKeys).length)} ${__dartStr(Array.from(countKeys)[0])} ${__dartStr(Array.from(__dartIterableToArray(counts.values())).at(-1))} ${__dartStr(Array.from(countKeys).join("|"))}`);
  const three = __dartMapPutIfAbsent(counts, "three", () => {
    return 3;
  });
  __dartMapUpdate(counts, "two", (value) => {
    return value * 10;
  });
  __dartMapUpdate(counts, "missing", (value) => {
    return value;
  }, () => {
    return 4;
  });
  const mapPairs = Array(0).fill(null);
  __dartMapForEach(counts, (key, value) => {
    __dartListAdd(mapPairs, `${__dartStr(key)}=${__dartStr(value)}`);
  });
  __dartPrint(`map ops ${__dartStr(three)} ${__dartStr(__dartMapGet(counts, "two"))} ${__dartStr(__dartMapGet(counts, "missing"))} ${__dartStr(Array.from(mapPairs).join("|"))}`);
  const transformSource = __dartMapFromEntries([["a", 1], ["b", 2]]);
  __dartMapAddEntries(transformSource, [["c", 3]]);
  const transformed = __dartMapMap(transformSource, (key, value) => {
    return [`${__dartStr(key)}${__dartStr(value)}`, value + 10];
  });
  const transformedCast = transformSource;
  __dartPrint(`map transforms ${__dartStr(__dartMapGet(transformSource, "c"))} ${__dartStr(__dartMapGet(transformed, "b2"))} ${__dartStr((__dartMapGet(transformedCast, "a") ?? 0) + 1)}`);
  const eqMap = __dartMapFromEntries([]);
  __dartMapSet(eqMap, new EqBox(1), "one");
  __dartMapSet(eqMap, new EqBox(1), "uno");
  const eqContains = __dartMapContainsKey(eqMap, new EqBox(1));
  const eqRead = __dartMapGet(eqMap, new EqBox(1));
  const eqExisting = __dartMapPutIfAbsent(eqMap, new EqBox(1), () => {
    return "new";
  });
  const eqMissing = __dartMapPutIfAbsent(eqMap, new EqBox(2), () => {
    return "two";
  });
  const eqUpdated = __dartMapUpdate(eqMap, new EqBox(2), (value) => {
    return `${__dartStr(value)}!`;
  });
  const eqRemoved = __dartMapRemove(eqMap, new EqBox(1));
  __dartMapAddAll(eqMap, __dartMapFromEntries([[new EqBox(2), "twoAgain"], [new EqBox(3), "three"]]));
  __dartMapAddEntries(eqMap, [[new EqBox(3), "tres"]]);
  const identityMap = new Map();
  __dartMapSet(identityMap, new EqBox(1), "one");
  __dartPrint(`mapEquality ${__dartStr(eqContains)} ${__dartStr(eqRead)} ${__dartStr(eqExisting)} ${__dartStr(eqMissing)} ${__dartStr(eqUpdated)} ${__dartStr(eqRemoved)} ${__dartStr(__dartMapGet(eqMap, new EqBox(2)))} ${__dartStr(__dartMapGet(eqMap, new EqBox(3)))} ${__dartStr(eqMap.size)} ${__dartStr(__dartMapContainsKey(identityMap, new EqBox(1)))} ${__dartStr(identityMap.size)}`);
  __dartMapRemove(counts, "one");
  __dartPrint(`map removed ${__dartStr(counts.size)} ${__dartStr(__dartMapGet(counts, "one"))}`);
  __dartMapUpdateAll(counts, (key, value) => {
    return value + key.length;
  });
  __dartMapRemoveWhere(counts, (key, value) => {
    return Math.trunc(value) % 2 === 0;
  });
  const entries = Array.from(__dartIterableToArray(counts.entries()), (entry) => {
    return `${__dartStr(entry[0])}:${__dartStr(entry[1])}`;
  });
  __dartPrint(`map more ${__dartStr(__dartMapContainsValue(counts, 27))} ${__dartStr(Array.from(entries).join("|"))}`);
  __dartMapClear(counts);
  __dartPrint(`map cleared ${__dartStr(counts.size === 0)}`);
}

main();
