function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartAs(value, test, typeName) {
  if (test(value)) return value;
  throw new TypeError("Type cast failed: expected " + typeName);
}
function __dartFixedList(list) {
  return Object.seal(list);
}
function __dartGet(receiver, name) {
  const value = receiver[name];
  return typeof value === "function" ? value.bind(receiver) : value;
}
function __dartSetAdd(set, value) {
  if (__dartIterableContains(set, value)) return false;
  set.add(value);
  return true;
}
function __dartSetFrom(values) {
  const set = new Set();
  for (const value of values) __dartSetAdd(set, value);
  return set;
}
function __dartIdentityMap() {
  const map = new Map();
  Object.defineProperty(map, "__dartIdentityMap", { value: true });
  return map;
}
const __dartMapMissingKey = Symbol("dart.mapMissingKey");
function __dartMapKey(map, key) {
  if (map.__dartIdentityMap) return map.has(key) ? key : __dartMapMissingKey;
  for (const candidate of map.keys()) {
    if (__dartEquals(candidate, key)) return candidate;
  }
  return __dartMapMissingKey;
}
function __dartMapContainsKey(map, key) {
  return __dartMapKey(map, key) !== __dartMapMissingKey;
}
function __dartMapGet(map, key) {
  const actualKey = __dartMapKey(map, key);
  return actualKey === __dartMapMissingKey ? null : map.get(actualKey);
}
function __dartMapSet(map, key, value) {
  const actualKey = __dartMapKey(map, key);
  map.set(actualKey === __dartMapMissingKey ? key : actualKey, value);
  return value;
}
function __dartMapFromEntries(entries) {
  const map = new Map();
  for (const [key, value] of entries) {
    __dartMapSet(map, key, value);
  }
  return map;
}
function __dartMapFromIterable(iterable, key = null, value = null) {
  const map = new Map();
  for (const element of iterable) {
    __dartMapSet(map, key == null ? element : key(element), value == null ? element : value(element));
  }
  return map;
}
function __dartMapFromIterables(keys, values) {
  const keyList = Array.from(keys);
  const valueList = Array.from(values);
  if (keyList.length !== valueList.length) throw new Error("Iterables do not have same length");
  const map = new Map();
  for (let index = 0; index < keyList.length; index++) {
    __dartMapSet(map, keyList[index], valueList[index]);
  }
  return map;
}
function __dartIterableContains(iterable, needle) {
  for (const value of iterable) {
    if (__dartEquals(value, needle)) return true;
  }
  return false;
}
function __dartIterableJoin(iterable, separator = "") {
  return Array.from(iterable, (value) => __dartStr(value)).join(String(separator));
}
function __dartEquals(left, right) {
  if (left === right) return true;
  if (left == null || right == null) return false;
  const equals = left["=="];
  return typeof equals === "function" ? equals.call(left, right) : false;
}
function __dartConstSet(values) {
  const set = new Set(values);
  const throwConst = () => { throw new TypeError("Cannot modify const Set"); };
  Object.defineProperty(set, "add", { value: throwConst });
  Object.defineProperty(set, "delete", { value: throwConst });
  Object.defineProperty(set, "clear", { value: throwConst });
  return Object.freeze(set);
}
function __dartConstMap(entries) {
  const map = new Map(entries);
  const throwConst = () => { throw new TypeError("Cannot modify const Map"); };
  Object.defineProperty(map, "set", { value: throwConst });
  Object.defineProperty(map, "delete", { value: throwConst });
  Object.defineProperty(map, "clear", { value: throwConst });
  return Object.freeze(map);
}

// Generated by dart2esm.

export class EqBox {
  constructor(value) {
    this.value = value;
  }
  "=="(other) {
    return (other instanceof EqBox && __dartEquals(other.value, this.value));
  }
  get hashCode() {
    return this.value.hashCode;
  }
}

export function main() {
  const list = Array.from((() => {
    const v = new Set();
    __dartSetAdd(v, 1);
    __dartSetAdd(v, 2);
    __dartSetAdd(v, 3);
    return v;
  })());
  const listFrom = Array.from(list);
  const listFixed = Object.freeze(Array.from(listFrom));
  __dartPrint("list " + __dartStr(listFixed.length) + " " + __dartStr(__dartIterableJoin(listFixed, ",")));
  const fixedFilled = __dartFixedList(new Array(2).fill(7));
  fixedFilled[0] = 8;
  let fixedAddFailed = false;
  try {
    {
      (fixedFilled.push(9), null);
    }
  } catch ($error) {
    if ($error != null) {
      const __wc0_formal = $error;
      {
        fixedAddFailed = true;
      }
    } else {
      throw $error;
    }
  }
  const growableEmpty = [];
  (growableEmpty.push(1), null);
  const fixedCopy = __dartFixedList(Array.from([1, 2, 3]));
  fixedCopy[0] = 4;
  let fixedCopyAddFailed = false;
  try {
    {
      (fixedCopy.push(5), null);
    }
  } catch ($error_1) {
    if ($error_1 != null) {
      const __wc1_formal = $error_1;
      {
        fixedCopyAddFailed = true;
      }
    } else {
      throw $error_1;
    }
  }
  const fixedFrom = __dartFixedList(Array.from([5, 6]));
  __dartPrint("fixedList " + __dartStr(__dartIterableJoin(fixedFilled, ",")) + " " + __dartStr(fixedAddFailed) + " " + __dartStr(__dartIterableJoin(growableEmpty, ",")) + " " + __dartStr(__dartIterableJoin(fixedCopy, ",")) + " " + __dartStr(fixedCopyAddFailed) + " " + __dartStr(fixedFrom.length));
  const set = __dartSetFrom(["a", "b", "a"]);
  const setOf = __dartSetFrom(set);
  const setFixed = __dartConstSet(__dartSetFrom(setOf));
  __dartPrint("set " + __dartStr(setFixed.size) + " " + __dartStr(__dartIterableContains(setFixed, "a")) + " " + __dartStr(__dartIterableJoin(setFixed, "|")));
  const eqSetFrom = __dartSetFrom([new EqBox(1), new EqBox(1), new EqBox(2)]);
  const eqSetOf = __dartSetFrom((() => {
    const v = Array.from(eqSetFrom);
    (v.push(new EqBox(2)), null);
    (v.push(new EqBox(3)), null);
    return v;
  })());
  const eqSetFixed = __dartConstSet(__dartSetFrom([new EqBox(1), new EqBox(1)]));
  __dartPrint("setFactories " + __dartStr(eqSetFrom.size) + " " + __dartStr(__dartIterableContains(eqSetFrom, new EqBox(1))) + " " + __dartStr(eqSetOf.size) + " " + __dartStr(eqSetFixed.size) + " " + __dartStr(__dartIterableContains(eqSetFixed, new EqBox(1))));
  const map = __dartMapFromEntries(new Map([["one", 1], ["two", 2]]));
  const mapOf = __dartMapFromEntries(map);
  const mapFixed = __dartConstMap(mapOf);
  __dartPrint("map " + __dartStr(mapFixed.size) + " " + __dartStr(__dartMapGet(mapFixed, "one")) + " " + __dartStr(__dartIterableJoin(mapFixed.keys(), ",")));
  const entries = __dartMapFromEntries(Array.from([Object.freeze({ key: "three", value: 3 }), Object.freeze({ key: "four", value: 4 })], (entry) => [entry.key, entry.value]));
  const iterable = __dartMapFromIterable(["aa", "bbb"], function(value) { return __dartAs(__dartGet(value, "length"), value => typeof value === "number", "int"); }, function(value) { return __dartAs(value.toUpperCase(), value => typeof value === "string", "String"); });
  const iterables = __dartMapFromIterables(["x", "y"], [10, 20]);
  const identity = __dartIdentityMap();
  const identityKey = [1];
  __dartMapSet(identity, identityKey, "same");
  __dartPrint("mapFactories " + __dartStr(__dartMapGet(entries, "four")) + " " + __dartStr(__dartMapGet(iterable, 3)) + " " + __dartStr(__dartMapGet(iterables, "y")) + " " + __dartStr(__dartMapContainsKey(identity, identityKey)));
}

main();
