function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartAs(value, test, typeName) {
  if (test(value)) return value;
  throw new TypeError("Type cast failed: expected " + typeName);
}
function __dartGet(receiver, name) {
  const value = receiver[name];
  return typeof value === "function" ? value.bind(receiver) : value;
}
function __dartSetAdd(set, value) {
  if (__dartIterableContains(set, value)) return false;
  set.add(value);
  return true;
}
function __dartMapFromIterable(iterable, key = null, value = null) {
  const map = new Map();
  for (const element of iterable) {
    map.set(key == null ? element : key(element), value == null ? element : value(element));
  }
  return map;
}
function __dartMapFromIterables(keys, values) {
  const keyList = Array.from(keys);
  const valueList = Array.from(values);
  if (keyList.length !== valueList.length) throw new Error("Iterables do not have same length");
  return new Map(keyList.map((key, index) => [key, valueList[index]]));
}
function __dartIterableContains(iterable, needle) {
  for (const value of iterable) {
    if (__dartEquals(value, needle)) return true;
  }
  return false;
}
function __dartIterableJoin(iterable, separator = "") {
  return Array.from(iterable, (value) => __dartStr(value)).join(String(separator));
}
function __dartEquals(left, right) {
  if (left === right) return true;
  if (left == null || right == null) return false;
  const equals = left["=="];
  return typeof equals === "function" ? equals.call(left, right) : false;
}
function __dartConstSet(values) {
  const set = new Set(values);
  const throwConst = () => { throw new TypeError("Cannot modify const Set"); };
  Object.defineProperty(set, "add", { value: throwConst });
  Object.defineProperty(set, "delete", { value: throwConst });
  Object.defineProperty(set, "clear", { value: throwConst });
  return Object.freeze(set);
}
function __dartConstMap(entries) {
  const map = new Map(entries);
  const throwConst = () => { throw new TypeError("Cannot modify const Map"); };
  Object.defineProperty(map, "set", { value: throwConst });
  Object.defineProperty(map, "delete", { value: throwConst });
  Object.defineProperty(map, "clear", { value: throwConst });
  return Object.freeze(map);
}

// Generated by dart2esm.

export function main() {
  const list = Array.from((() => {
    const v = new Set();
    __dartSetAdd(v, 1);
    __dartSetAdd(v, 2);
    __dartSetAdd(v, 3);
    return v;
  })());
  const listFrom = Array.from(list);
  const listFixed = Object.freeze(Array.from(listFrom));
  __dartPrint("list " + __dartStr(listFixed.length) + " " + __dartStr(__dartIterableJoin(listFixed, ",")));
  const set = new Set(["a", "b", "a"]);
  const setOf = new Set(set);
  const setFixed = __dartConstSet(setOf);
  __dartPrint("set " + __dartStr(setFixed.size) + " " + __dartStr(__dartIterableContains(setFixed, "a")) + " " + __dartStr(__dartIterableJoin(setFixed, "|")));
  const map = new Map(new Map([["one", 1], ["two", 2]]));
  const mapOf = new Map(map);
  const mapFixed = __dartConstMap(mapOf);
  __dartPrint("map " + __dartStr(mapFixed.size) + " " + __dartStr(mapFixed.get("one")) + " " + __dartStr(__dartIterableJoin(mapFixed.keys(), ",")));
  const entries = new Map(Array.from([Object.freeze({ key: "three", value: 3 }), Object.freeze({ key: "four", value: 4 })], (entry) => [entry.key, entry.value]));
  const iterable = __dartMapFromIterable(["aa", "bbb"], function(value) { return __dartAs(__dartGet(value, "length"), value => typeof value === "number", "int"); }, function(value) { return __dartAs(value.toUpperCase(), value => typeof value === "string", "String"); });
  const iterables = __dartMapFromIterables(["x", "y"], [10, 20]);
  const identity = new Map();
  const identityKey = [1];
  identity.set(identityKey, "same");
  __dartPrint("mapFactories " + __dartStr(entries.get("four")) + " " + __dartStr(iterable.get(3)) + " " + __dartStr(iterables.get("y")) + " " + __dartStr(identity.has(identityKey)));
}

main();
