function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartToJson(value, toEncodable) {
  if (value == null || typeof value === "string" || typeof value === "number" || typeof value === "boolean") return value;
  if (Array.isArray(value)) {
    return value.map((entry) => __dartToJson(entry, toEncodable));
  }
  if (value instanceof Set) {
    return Array.from(value, (entry) => __dartToJson(entry, toEncodable));
  }
  if (value instanceof Map) {
    const object = {};
    for (const [key, entry] of value) {
      object[String(key)] = __dartToJson(entry, toEncodable);
    }
    return object;
  }
  if (typeof value.toJson === "function") {
    return __dartToJson(value.toJson(), toEncodable);
  }
  if (typeof toEncodable === "function") {
    return __dartToJson(toEncodable(value), toEncodable);
  }
  throw new TypeError("Converting object to an encodable object failed");
}
function __dartFromJson(value) {
  if (Array.isArray(value)) {
    return value.map(__dartFromJson);
  }
  if (value != null && typeof value === "object" && Object.getPrototypeOf(value) === Object.prototype) {
    return new Map(Object.entries(value).map(([key, entry]) => [key, __dartFromJson(entry)]));
  }
  return value;
}
function __dartJsonEncode(value, toEncodable = null) {
  return JSON.stringify(__dartToJson(value, toEncodable));
}
function __dartJsonDecode(source) {
  return __dartFromJson(JSON.parse(source));
}
function __dartJsonCodec() {
  return {
    encode(value) { return __dartJsonEncode(value); },
    decode(source) { return __dartJsonDecode(source); },
  };
}
function __dartUtf8Encode(source) {
  return Array.from(new TextEncoder().encode(String(source)));
}
function __dartUtf8Decode(bytes) {
  return new TextDecoder("utf-8").decode(Uint8Array.from(bytes));
}
function __dartUtf8Codec() {
  return {
    encode(source) { return __dartUtf8Encode(source); },
    decode(bytes) { return __dartUtf8Decode(bytes); },
  };
}
function __dartBase64Encode(bytes, urlSafe = false) {
  const array = Uint8Array.from(bytes);
  let encoded;
  if (globalThis.Buffer) encoded = Buffer.from(array).toString("base64");
  else {
    let binary = "";
    for (const byte of array) binary += String.fromCharCode(byte);
    encoded = btoa(binary);
  }
  return urlSafe ? encoded.replace(/\+/g, "-").replace(/\//g, "_") : encoded;
}
function __dartBase64Decode(source) {
  let normalized = String(source).replace(/-/g, "+").replace(/_/g, "/");
  while (normalized.length % 4 !== 0) normalized += "=";
  if (globalThis.Buffer) return Array.from(Buffer.from(normalized, "base64"));
  const binary = atob(normalized);
  const bytes = new Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}
function __dartBase64Codec(urlSafe = false) {
  return {
    encode(bytes) { return __dartBase64Encode(bytes, urlSafe); },
    decode(source) { return __dartBase64Decode(source); },
  };
}
function __dartAs(value, test, typeName) {
  if (test(value)) return value;
  throw new TypeError("Type cast failed: expected " + typeName);
}

// Generated by dart2esm.

export function main() {
  const payload = new Map([["name", "dart2esm"], ["values", [1, 2, 3]], ["ok", true]]);
  const encoded = __dartJsonEncode(payload, null);
  const decoded = __dartAs(__dartJsonDecode(encoded), value => value instanceof Map, "Map<dynamic, dynamic>");
  __dartPrint("json " + __dartStr(decoded.get("name")) + " " + __dartStr(__dartAs(decoded.get("values"), value => (Array.isArray(value) || (ArrayBuffer.isView(value) && !(value instanceof DataView))), "List<dynamic>").length));
  const codecEncoded = __dartJsonCodec().encode(new Map([["answer", 42]]));
  const codecDecoded = __dartAs(__dartJsonCodec().decode(codecEncoded), value => value instanceof Map, "Map<dynamic, dynamic>");
  __dartPrint("codec " + __dartStr(codecDecoded.get("answer")));
  const bytes = __dartUtf8Codec().encode("hello");
  __dartPrint("utf8 " + __dartStr(bytes.length) + " " + __dartStr(__dartUtf8Codec().decode(bytes)));
  const token = __dartBase64Encode(bytes);
  __dartPrint("base64 " + __dartStr(token) + " " + __dartStr(__dartUtf8Codec().decode(__dartBase64Decode(token))));
  const urlToken = __dartBase64Codec(true).encode(bytes);
  __dartPrint("base64Url " + __dartStr(urlToken) + " " + __dartStr(__dartUtf8Codec().decode(__dartBase64Codec(true).decode(urlToken))));
}

main();
