function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartStringBuffer(initial = "") {
  let value = initial == null ? "" : String(initial);
  return {
    write(next) { value += String(next); },
    writeAll(values, separator = "") { value += Array.from(values, String).join(String(separator)); },
    writeCharCode(charCode) { value += String.fromCharCode(charCode); },
    writeln(next = "") { value += String(next) + "\n"; },
    clear() { value = ""; },
    toString() { return value; },
    get length() { return value.length; },
    get isEmpty() { return value.length === 0; },
    get isNotEmpty() { return value.length !== 0; },
  };
}
function __dartIterableLast(iterable) {
  let found = false;
  let last;
  for (const value of iterable) {
    found = true;
    last = value;
  }
  if (!found) throw new RangeError("No element");
  return last;
}

// Generated by dart2esm.

export function main() {
  const buffer = __dartStringBuffer("hello");
  buffer.write(" ");
  buffer.write(42);
  buffer.writeln();
  buffer.write("done");
  __dartPrint("buffer " + __dartStr(buffer.length) + " " + __dartStr(buffer.isNotEmpty) + " " + __dartStr(__dartStr(buffer).includes("\n")));
  buffer.writeAll(["x", "y"], "-");
  buffer.writeCharCode(33);
  __dartPrint("writeAll " + __dartStr(__dartIterableLast(__dartStr(buffer).split("\n"))));
  buffer.clear();
  __dartPrint("cleared " + __dartStr(buffer.isEmpty) + " " + __dartStr(__dartStr(buffer)));
  const encoded = encodeURIComponent("a b/ç");
  __dartPrint("uri " + __dartStr(encoded) + " " + __dartStr(decodeURIComponent(encoded)));
  const full = encodeURI("https://example.test/a b?q=ç");
  __dartPrint("full " + __dartStr(decodeURI(full)));
}

main();
