function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartNullCheck(value) {
  if (value == null) {
    throw new TypeError("Null check operator used on a null value");
  }
  return value;
}
function __dartAs(value, test, typeName) {
  if (test(value)) return value;
  throw new TypeError("Type cast failed: expected " + typeName);
}

// Generated by dart2esm.

export function hide(value) {
  return value;
}

export function main() {
  const title = globalThis.document.title;
  (typeof globalThis.window.localStorage.setItem === "function" ? (globalThis.window.localStorage.setItem("dart2esm", "ok"), null) : (globalThis.window.localStorage["dart2esm"] = "ok", null));
  const stored = (typeof globalThis.window.localStorage.getItem === "function" ? globalThis.window.localStorage.getItem("dart2esm") : globalThis.window.localStorage["dart2esm"]);
  const root = globalThis.document.createElement("section");
  root.id = "root";
  root.textContent = "hello";
  const child = globalThis.document.createElement("span");
  child.textContent = " child";
  root.appendChild(child);
  __dartNullCheck(globalThis.document.body).appendChild(root);
  const found = globalThis.document.querySelector("#root");
  const hiddenRoot = hide(root);
  const castRoot = __dartAs(hiddenRoot, value => (value === null || (typeof globalThis["Element"] === "function" && value instanceof globalThis["Element"])), "Element?");
  __dartPrint("html " + __dartStr(title.length === 0) + " " + __dartStr(stored) + " " + __dartStr(((found)?.id ?? null)) + " " + __dartStr(((found)?.textContent ?? null)) + " " + __dartStr((typeof globalThis["Element"] === "function" && hiddenRoot instanceof globalThis["Element"])) + " " + __dartStr(((castRoot)?.id ?? null)));
}

main();
