function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartRandom(seed = null, secure = false) {
  let state = seed == null ? 0 : Number(seed) >>> 0;
  function nextUint32() {
    if (secure) {
      const crypto = globalThis.crypto || globalThis.msCrypto;
      if (crypto && typeof crypto.getRandomValues === "function") {
        const values = new Uint32Array(1);
        crypto.getRandomValues(values);
        return values[0] >>> 0;
      }
    }
    if (seed == null) {
      return Math.floor(Math.random() * 0x100000000) >>> 0;
    }
    state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
    return state;
  }
  return {
    nextInt(max) {
      if (!Number.isInteger(max) || max <= 0) throw new RangeError("max must be positive");
      return nextUint32() % max;
    },
    nextDouble() { return nextUint32() / 0x100000000; },
    nextBool() { return (nextUint32() & 1) === 1; },
  };
}
function __dartEquals(left, right) {
  return left === right;
}

// Generated by dart2esm.

export function hide(value) {
  return value;
}

export function main() {
  __dartPrint("min " + __dartStr(Math.min(2, 3)));
  __dartPrint("max " + __dartStr(Math.max(2, 3)));
  __dartPrint("pow " + __dartStr(Math.pow(2, 3)));
  __dartPrint("atan2 " + __dartStr(__dartEquals(Math.atan2(0, 1), 0)));
  __dartPrint("pi " + __dartStr((3.141592653589793 > 3)));
  __dartPrint("sqrt2 " + __dartStr((1.4142135623730951 > 1)));
  const seededA = __dartRandom(1, false);
  const seededB = __dartRandom(1, false);
  const firstA = seededA.nextInt(1000);
  const firstB = seededB.nextInt(1000);
  const doubleValue = seededA.nextDouble();
  const boolValue = seededA.nextBool();
  __dartPrint("random " + __dartStr(__dartEquals(firstA, firstB)) + " " + __dartStr(((firstA >= 0) && (firstA < 1000))) + " " + __dartStr(((doubleValue >= 0) && (doubleValue < 1))) + " " + __dartStr(typeof hide(boolValue) === "boolean"));
  const secure = __dartRandom(null, true).nextInt(10);
  __dartPrint("secure " + __dartStr(((secure >= 0) && (secure < 10))));
}

main();
