function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartSetAdd(set, value) {
  const hadValue = set.has(value);
  set.add(value);
  return !hadValue;
}
function __dartEquals(left, right) {
  return left === right;
}
const __dartIdentityHashes = new WeakMap();
let __dartNextIdentityHash = 1;
function __dartCombineHash(hash, value) {
  hash = (((hash + value) & 0x1fffffff) + (((hash & 0x0007ffff) << 10) & 0x1fffffff)) & 0x1fffffff;
  return hash ^ (hash >> 6);
}
function __dartFinishHash(hash) {
  hash = (((hash + (((hash & 0x03ffffff) << 3) & 0x1fffffff)) & 0x1fffffff) ^ (hash >> 11));
  return (hash + (((hash & 0x00003fff) << 15) & 0x1fffffff)) & 0x1fffffff;
}
function __dartHashValue(value) {
  if (value == null) return 0;
  if (typeof value === "boolean") return value ? 1231 : 1237;
  if (typeof value === "number") return Number.isFinite(value) ? Math.trunc(value) & 0x1fffffff : 0;
  if (typeof value === "string") {
    let hash = 0;
    for (let i = 0; i < value.length; i++) hash = __dartCombineHash(hash, value.charCodeAt(i));
    return __dartFinishHash(hash);
  }
  if (typeof value === "bigint") return Number(value & 0x1fffffffn);
  if (!__dartIdentityHashes.has(value)) {
    __dartIdentityHashes.set(value, __dartNextIdentityHash);
    __dartNextIdentityHash = (__dartNextIdentityHash + 1) & 0x1fffffff || 1;
  }
  return __dartIdentityHashes.get(value);
}
function __dartObjectHash(values) {
  let hash = 0;
  for (const value of values) hash = __dartCombineHash(hash, __dartHashValue(value));
  return __dartFinishHash(hash);
}
function __dartObjectHashUnordered(values) {
  let sum = 0;
  let xor = 0;
  let count = 0;
  for (const value of values) {
    const hash = __dartHashValue(value);
    sum = (sum + hash) & 0x1fffffff;
    xor ^= hash;
    count++;
  }
  return __dartObjectHash([sum, xor, count]);
}

// Generated by dart2esm.

export function hide(value) {
  return value;
}

export function main() {
  const ordered = __dartObjectHash([1, "a"]);
  const orderedAgain = __dartObjectHash([1, "a"]);
  const fromIterable = __dartObjectHash(Array.from([1, "a"]));
  const reversed = __dartObjectHash(Array.from(["a", 1]));
  const unorderedA = __dartObjectHashUnordered(Array.from((() => {
    const v = new Set();
    __dartSetAdd(v, "a");
    __dartSetAdd(v, "b");
    return v;
  })()));
  const unorderedB = __dartObjectHashUnordered(Array.from((() => {
    const v = new Set();
    __dartSetAdd(v, "b");
    __dartSetAdd(v, "a");
    return v;
  })()));
  __dartPrint(typeof hide(ordered) === "number");
  __dartPrint(__dartStr(__dartEquals(ordered, orderedAgain)) + " " + __dartStr(__dartEquals(ordered, fromIterable)));
  __dartPrint(__dartEquals(ordered, reversed));
  __dartPrint(__dartEquals(unorderedA, unorderedB));
}

main();
