function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartRegExp(pattern, options = {}) {
  const source = String(pattern);
  const caseSensitive = options.caseSensitive !== false;
  const multiLine = options.multiLine === true;
  const unicode = options.unicode === true;
  const dotAll = options.dotAll === true;
  function make(global = false) {
    let flags = global ? "g" : "";
    if (!caseSensitive) flags += "i";
    if (multiLine) flags += "m";
    if (unicode) flags += "u";
    if (dotAll) flags += "s";
    return new RegExp(source, flags);
  }
  return {
    pattern: source,
    hasMatch(input) { return make(false).test(String(input)); },
    firstMatch(input) {
      const match = make(false).exec(String(input));
      return match == null ? null : __dartRegExpMatch(match);
    },
    stringMatch(input) {
      const match = this.firstMatch(input);
      return match == null ? null : match.group(0);
    },
    allMatches(input, start = 0) {
      const text = String(input);
      const regexp = make(true);
      regexp.lastIndex = start;
      const matches = [];
      let match;
      while ((match = regexp.exec(text)) !== null) {
        matches.push(__dartRegExpMatch(match));
        if (match[0] === "") regexp.lastIndex++;
      }
      return matches;
    },
    toString() { return source; },
  };
}
function __dartRegExpMatch(match) {
  const result = {
    start: match.index,
    end: match.index + match[0].length,
    get groupCount() { return match.length - 1; },
    group(index) { return index >= 0 && index < match.length ? (match[index] ?? null) : null; },
  };
  for (let i = 0; i < match.length; i++) {
    result[i] = match[i] ?? null;
  }
  return result;
}
function __dartNullCheck(value) {
  if (value == null) {
    throw new TypeError("Null check operator used on a null value");
  }
  return value;
}
function __dartIterator(iterable) {
  const values = Array.isArray(iterable) ? iterable : Array.from(iterable);
  let index = -1;
  return {
    current: undefined,
    moveNext() {
      index++;
      if (index < values.length) {
        this.current = values[index];
        return true;
      }
      this.current = undefined;
      return false;
    },
  };
}

// Generated by dart2esm.

export function main() {
  const pattern = __dartRegExp("([a-z]+)-(\\d+)", { caseSensitive: false, multiLine: false, unicode: false, dotAll: false });
  const input = "Item-42 next-7";
  const first = __dartNullCheck(pattern.firstMatch(input));
  __dartPrint("has " + __dartStr(pattern.hasMatch(input)) + " " + __dartStr(pattern.hasMatch("none")));
  __dartPrint("first " + __dartStr(first.group(0)) + " " + __dartStr(first.group(1)) + " " + __dartStr(first[2]) + " " + __dartStr(first.groupCount));
  __dartPrint("span " + __dartStr(first.start) + " " + __dartStr(first.end));
  __dartPrint("string " + __dartStr(pattern.stringMatch(input)));
  const parts = new Array(0).fill(null);
  {
    let _sync_for_iterator = __dartIterator(pattern.allMatches(input));
    for (; _sync_for_iterator.moveNext(); ) {
      {
        const match = _sync_for_iterator.current;
        {
          (parts.push(__dartNullCheck(match.group(0))), null);
        }
      }
    }
  }
  __dartPrint("all " + __dartStr(parts));
}

main();
