function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartIterableJoin(iterable, separator = "") {
  return Array.from(iterable, (value) => __dartStr(value)).join(String(separator));
}
function __dartStreamIterator(stream) {
  const iterator = stream[Symbol.asyncIterator]();
  return {
    current: undefined,
    _subscription: true,
    async moveNext() {
      const next = await iterator.next();
      if (next.done) {
        this.current = undefined;
        this._subscription = null;
        return false;
      }
      this.current = next.value;
      return true;
    },
    async cancel() {
      this._subscription = null;
      if (typeof iterator.return === "function") await iterator.return();
      return null;
    },
  };
}
function __dartStreamFromIterable(values) {
  return (async function*() {
    for (const value of values) yield value;
  })();
}
function __dartStreamMap(stream, convert) {
  return (async function*() {
    for await (const value of stream) {
      yield convert(value);
    }
  })();
}
function __dartStreamWhere(stream, test) {
  return (async function*() {
    for await (const value of stream) {
      if (test(value)) yield value;
    }
  })();
}
async function __dartStreamToList(stream) {
  const values = [];
  for await (const value of stream) values.push(value);
  return values;
}
async function __dartStreamFirst(stream) {
  for await (const value of stream) return value;
  throw new RangeError("No element");
}

// Generated by dart2esm.

export async function main() {
  const doubled = __dartStreamWhere(__dartStreamMap(__dartStreamFromIterable([1, 2, 3]), function(value) { return (value * 2); }), function(value) { return (value > 2); });
  const values = new Array(0).fill(null);
  {
    let _stream = doubled;
    let _for_iterator = __dartStreamIterator(_stream);
    try {
      while (await _for_iterator.moveNext()) {
        {
          const value = _for_iterator.current;
          {
            (values.push(value), null);
          }
        }
      }
    } finally {
      if (!((_for_iterator._subscription === null))) {
        await _for_iterator.cancel();
      }
    }
  }
  __dartPrint("stream " + __dartStr(__dartIterableJoin(values, ",")));
  const single = await __dartStreamFirst(__dartStreamFromIterable(["ok"]));
  const listed = await __dartStreamToList(__dartStreamFromIterable(["a", "b"]));
  __dartPrint("future " + __dartStr(single) + " " + __dartStr(__dartIterableJoin(listed, "|")));
}

await main();
