// Generated by dart2esm.

function __dartCompare(left, right, compare = null) {
  if (typeof compare === "function") return Number(compare(left, right));
  const compareTo = left == null ? null : left.compareTo;
  if (typeof compareTo === "function") return Number(compareTo.call(left, right));
  return left < right ? -1 : left > right ? 1 : 0;
}

function __dartCoreError(typeName, message) {
  const text = message == null ? "" : String(message);
  const display = text === "" ? typeName : typeName + ": " + text;
  const error = new Error(text);
  error.name = typeName;
  Object.defineProperty(error, "__dartCoreErrorType", { value: typeName });
  Object.defineProperty(error, "toString", { value() { return display; } });
  return error;
}
function __dartIsCoreError(value, typeName) {
  const actual = value == null ? null : value.__dartCoreErrorType;
  if (actual != null) {
    if (actual === typeName) return true;
    if (typeName === "Exception" && actual === "FormatException") return true;
    if (typeName === "RangeError" && actual === "IndexError") return true;
    if (typeName === "ArgumentError" && (actual === "RangeError" || actual === "IndexError")) return true;
    return typeName === "Error" && actual !== "Exception" && actual !== "FormatException";
  }
  if (typeName === "TypeError" && value instanceof TypeError) return true;
  return typeName === "Error" && value instanceof Error;
}

const __dartConstValues = new Map();
function __dartConst(key, create) {
  if (!__dartConstValues.has(key)) {
    __dartConstValues.set(key, create());
  }
  return __dartConstValues.get(key);
}

function __dartDoubleTryParse(source) {
  const text = String(source).trim();
  if (text.length === 0) return null;
  if (/^[+-]?NaN$/i.test(text)) return NaN;
  const value = Number(text);
  return Number.isNaN(value) ? null : value;
}
function __dartDoubleParse(source) {
  const value = __dartDoubleTryParse(source);
  if (value === null) {
    const error = new Error("Invalid double literal");
    error.name = "FormatException";
    throw error;
  }
  return value;
}
function __dartNumTryParse(source) {
  return __dartDoubleTryParse(source);
}
function __dartNumParse(source) {
  const value = __dartNumTryParse(source);
  if (value === null) {
    const error = new Error("Invalid number literal");
    error.name = "FormatException";
    throw error;
  }
  return value;
}

function __dartDoubleValue(value) {
  const number = Number(value);
  return Object.freeze({
    __dartType: "double",
    valueOf() { return number; },
    toString() {
      if (Number.isNaN(number)) return "NaN";
      if (number === Infinity) return "Infinity";
      if (number === -Infinity) return "-Infinity";
      if (Object.is(number, -0)) return "-0.0";
      return Number.isInteger(number) ? number.toString() + ".0" : number.toString();
    },
  });
}

function __dartLatin1Codec(allowInvalid = false) {
  return Object.freeze({
    name: "latin1",
    encode(source) {
      return Array.from(String(source), (char) => char.charCodeAt(0) & 255);
    },
    decode(bytes) {
      return String.fromCharCode.apply(null, Array.from(bytes, (byte) => Number(byte) & 255));
    },
  });
}
function __dartUtf8Codec(allowMalformed = false) {
  return Object.freeze({
    name: "utf8",
    encode(source) {
      return Array.from(new TextEncoder().encode(String(source)));
    },
    decode(bytes) {
      return new TextDecoder("utf-8", { fatal: !allowMalformed }).decode(Uint8Array.from(Array.from(bytes, (byte) => Number(byte) & 255)));
    },
  });
}

function __dartEquals(left, right) {
  if (left === right) return true;
  if (left == null || right == null) return false;
  if ((typeof left === "number" || left.__dartType === "double") && (typeof right === "number" || right.__dartType === "double")) return Number(left) === Number(right);
  if (__dartIsRecord(left) && __dartIsRecord(right)) {
    const leftShape = left[__dartRecordShape];
    const rightShape = right[__dartRecordShape];
    if (leftShape.length !== rightShape.length) return false;
    for (let i = 0; i < leftShape.length; i++) {
      const name = leftShape[i];
      if (name !== rightShape[i]) return false;
      if (!__dartEquals(left[name], right[name])) return false;
    }
    return true;
  }
  const equals = left["=="];
  return typeof equals === "function" ? equals.call(left, right) : false;
}

function __dartIntGcd(left, right) {
  let a = Math.abs(Math.trunc(Number(left)));
  let b = Math.abs(Math.trunc(Number(right)));
  while (b !== 0) {
    const next = a % b;
    a = b;
    b = next;
  }
  return a;
}

function __dartIntModInverse(value, modulus) {
  let a = ((Math.trunc(Number(value)) % Math.trunc(Number(modulus))) + Math.trunc(Number(modulus))) % Math.trunc(Number(modulus));
  let m = Math.trunc(Number(modulus));
  if (m <= 0) throw __dartCoreError("RangeError", "Modulus must be positive");
  let x0 = 0;
  let x1 = 1;
  let b = m;
  while (a > 1 && b !== 0) {
    const q = Math.trunc(a / b);
    [a, b] = [b, a % b];
    [x0, x1] = [x1 - q * x0, x0];
  }
  if (a !== 1) {
    throw __dartCoreError("Exception", "Not coprime");
  }
  return ((x1 % m) + m) % m;
}
function __dartIntModPow(value, exponent, modulus) {
  let e = Math.trunc(Number(exponent));
  const m = Math.trunc(Number(modulus));
  if (e < 0) throw __dartCoreError("RangeError", "Exponent must be non-negative");
  if (m <= 0) throw __dartCoreError("RangeError", "Modulus must be positive");
  let base = ((Math.trunc(Number(value)) % m) + m) % m;
  let result = 1 % m;
  while (e > 0) {
    if ((e & 1) === 1) result = (result * base) % m;
    e = Math.floor(e / 2);
    base = (base * base) % m;
  }
  return result;
}

function __dartFormatException(message) {
  const error = new Error(String(message));
  error.name = "FormatException";
  return error;
}
function __dartIntTryParse(source, radix = null) {
  const text = String(source).trim();
  let base = radix == null ? null : Number(radix);
  if (base != null && (!Number.isInteger(base) || base < 2 || base > 36)) return null;
  if (base == null && /^[+-]?0x[0-9a-f]+$/i.test(text)) return Number.parseInt(text, 16);
  base ??= 10;
  const sign = /^[+-]/.test(text) ? text[0] : "";
  const digits = sign === "" ? text : text.slice(1);
  if (digits.length === 0) return null;
  for (const char of digits.toLowerCase()) {
    const code = char.charCodeAt(0);
    const value = code >= 48 && code <= 57 ? code - 48 : code >= 97 && code <= 122 ? code - 87 : -1;
    if (value < 0 || value >= base) return null;
  }
  return Number.parseInt(text, base);
}
function __dartIntParse(source, radix = null) {
  const value = __dartIntTryParse(source, radix);
  if (value == null) throw __dartFormatException("Invalid integer literal");
  return value;
}

function __dartIterableToArray(iterable) {
  if (Array.isArray(iterable)) return Array.from(iterable);
  if (iterable != null && typeof iterable["[]"] === "function" && typeof iterable.length === "number") {
    return Array.from({ length: Number(iterable.length) }, (_, index) => iterable["[]"](index));
  }
  return Array.from(iterable);
}

function __dartMapAddAll(map, entries) {
  for (const [key, value] of entries) __dartMapSet(map, key, value);
  return null;
}

function __dartMapFromEntries(entries) {
  const map = new Map();
  Object.defineProperty(map, "__dartEqualityMap", { value: true });
  __dartMapAddAll(map, entries);
  return map;
}
function __dartMapFromIterable(iterable, key = null, value = null) {
  const map = new Map();
  Object.defineProperty(map, "__dartEqualityMap", { value: true });
  for (const element of iterable) {
    __dartMapSet(
      map,
      typeof key === "function" ? key(element) : element,
      typeof value === "function" ? value(element) : element,
    );
  }
  return map;
}
function __dartMapFromIterables(keys, values) {
  const keyList = Array.from(keys);
  const valueList = Array.from(values);
  if (keyList.length !== valueList.length) throw new Error("Iterables do not have same length");
  const map = new Map();
  Object.defineProperty(map, "__dartEqualityMap", { value: true });
  for (let index = 0; index < keyList.length; index++) {
    __dartMapSet(map, keyList[index], valueList[index]);
  }
  return map;
}

const __dartMapMissingKey = Symbol("dart.mapMissingKey");
function __dartMapKey(map, key) {
  if (typeof map.__dartSplayIsValidKey === "function" && !map.__dartSplayIsValidKey(key)) return __dartMapMissingKey;
  if (map.__dartSplayCompare !== undefined) {
    for (const candidate of map.keys()) {
      if (__dartCompare(candidate, key, map.__dartSplayCompare) === 0) return candidate;
    }
    return __dartMapMissingKey;
  }
  if (typeof map.__dartMapIsValidKey === "function" && !map.__dartMapIsValidKey(key)) return __dartMapMissingKey;
  if (typeof map.__dartMapEquals === "function") {
    for (const candidate of map.keys()) {
      if (map.__dartMapEquals(candidate, key)) return candidate;
    }
    return __dartMapMissingKey;
  }
  if (!map.__dartEqualityMap) return map.has(key) ? key : __dartMapMissingKey;
  for (const candidate of map.keys()) {
    if (__dartEquals(candidate, key)) return candidate;
  }
  return __dartMapMissingKey;
}
function __dartMapGet(map, key) {
  if (!(map instanceof Map) && map != null && typeof map["[]"] === "function") return map["[]"](key);
  const actualKey = __dartMapKey(map, key);
  return actualKey === __dartMapMissingKey ? null : map.get(actualKey);
}

function __dartMapSet(map, key, value) {
  const actualKey = __dartMapKey(map, key);
  map.set(actualKey === __dartMapMissingKey ? key : actualKey, value);
  if (map.__dartSplayCompare !== undefined) __dartSplaySortMap(map);
  return value;
}

function __dartNullCheck(value) {
  if (value == null) throw new TypeError("Null check operator used on a null value");
  return value;
}

function __dartPrint(value) {
  console.log(__dartStr(value));
}

const __dartRecordShape = Symbol("dart.recordShape");

function __dartIsRecord(value) {
  return value != null && typeof value === "object" && Array.isArray(value[__dartRecordShape]);
}

function __dartSafeToString(value) {
  try {
    if (value == null) return "null";
    if (typeof value === "object") {
      const toString = value.toString;
      if (typeof toString === "function" && toString !== Object.prototype.toString) return String(toString.call(value));
      const typeName = value.constructor && value.constructor.name ? value.constructor.name : "Object";
      return "Instance of '" + typeName + "'";
    }
    return String(value);
  } catch (_) {
    const typeName = value != null && value.constructor && value.constructor.name ? value.constructor.name : "Object";
    return "Instance of '" + typeName + "'";
  }
}

function __dartStringFromCharCodes(codes, start = 0, end = null) {
  const values = Array.from(codes).slice(Number(start), end == null ? undefined : Number(end));
  return String.fromCodePoint(...values);
}

function __dartStringCodeUnits(source) {
  const text = String(source);
  return Array.from({ length: text.length }, (_, index) => text.charCodeAt(index));
}
function __dartStringReplaceFirst(source, pattern, replacement, startIndex = 0) {
  const text = String(source);
  const needle = String(pattern);
  const index = text.indexOf(needle, Number(startIndex));
  if (index < 0) return text;
  return text.slice(0, index) + String(replacement) + text.slice(index + needle.length);
}
function __dartStringReplaceRange(source, start, end, replacement) {
  const text = String(source);
  const actualEnd = end == null ? text.length : Number(end);
  return text.slice(0, Number(start)) + String(replacement) + text.slice(actualEnd);
}

function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}

function __dartBase64Encode(bytes, urlSafe = false) {
  const values = Uint8Array.from(Array.from(bytes, (byte) => Number(byte) & 255));
  let encoded;
  if (typeof Buffer !== "undefined") {
    encoded = Buffer.from(values).toString("base64");
  } else {
    let binary = "";
    for (const byte of values) binary += String.fromCharCode(byte);
    encoded = btoa(binary);
  }
  return urlSafe ? encoded.replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, "") : encoded;
}
function __dartUriParse(source, tryParse = false) {
  const text = String(source);
  let url;
  let isRelative = false;
  let isProtocolRelative = false;
  try {
    if (text.startsWith("//")) {
      url = new URL("dart:" + text);
      isProtocolRelative = true;
    } else {
      url = new URL(text);
    }
  } catch (_) {
    try {
      url = new URL(text, "dart://relative");
      isRelative = true;
    } catch (_) {
      if (tryParse) return null;
      throw __dartCoreError("FormatException", "Invalid URI");
    }
  }
  const relativePath = isRelative ? text.split(/[?#]/, 1)[0] : url.pathname;
  const userInfo = isRelative ? "" : [url.username, url.password].filter((part) => part !== "").join(":");
  const defaultPort = url.protocol === "http:" ? 80 : url.protocol === "https:" ? 443 : 0;
  function queryParameters(all = false) {
    const map = new Map();
    for (const [key, value] of url.searchParams) {
      if (all) {
        const values = map.get(key) ?? [];
        values.push(value);
        map.set(key, values);
      } else {
        map.set(key, value);
      }
    }
    return map;
  }
  return Object.freeze({
    __dartType: "Uri",
    get scheme() { return isRelative || isProtocolRelative ? "" : url.protocol.slice(0, -1); },
    get host() { return isRelative ? "" : url.hostname; },
    get authority() { return isRelative ? "" : (userInfo === "" ? url.host : userInfo + "@" + url.host); },
    get userInfo() { return userInfo; },
    get port() { return isRelative ? 0 : (url.port === "" ? defaultPort : Number(url.port)); },
    get path() { return relativePath; },
    get pathSegments() { return relativePath.split("/").filter((segment) => segment !== "").map(decodeURIComponent); },
    get query() { return url.search.startsWith("?") ? url.search.slice(1) : ""; },
    get queryParameters() { return queryParameters(false); },
    get queryParametersAll() { return queryParameters(true); },
    get fragment() { return url.hash.startsWith("#") ? url.hash.slice(1) : ""; },
    get hasScheme() { return !isRelative && url.protocol !== ""; },
    get hasAuthority() { return !isRelative && url.host !== ""; },
    get hasPort() { return !isRelative && url.port !== ""; },
    get hasQuery() { return url.search !== ""; },
    get hasFragment() { return url.hash !== ""; },
    get isAbsolute() { return !isRelative && !isProtocolRelative && url.protocol !== "" && url.hash === ""; },
    toString() { return text; },
  });
}
function __dartUriEncodePath(path) { return String(path).split("/").map(encodeURIComponent).join("/"); }
function __dartUriEncodeQueryComponent(value, encoding = null) {
  const text = String(value);
  if (encoding == null || typeof encoding.encode !== "function") return encodeURIComponent(text).replace(/%20/g, "+");
  let result = "";
  for (const byte of encoding.encode(text)) {
    const value = Number(byte) & 255;
    if (value === 0x20) { result += "+"; continue; }
    const char = String.fromCharCode(value);
    result += /[A-Za-z0-9\-._~]/.test(char) ? char : "%" + value.toString(16).toUpperCase().padStart(2, "0");
  }
  return result;
}
function __dartUriDecodeQueryComponent(value, encoding = null) {
  const text = String(value).replace(/\+/g, " ");
  if (encoding == null || typeof encoding.decode !== "function") return decodeURIComponent(text);
  const bytes = [];
  for (let i = 0; i < text.length; i++) {
    const char = text[i];
    if (char === "%" && i + 2 < text.length) {
      const hex = text.slice(i + 1, i + 3);
      if (/^[0-9a-fA-F]{2}$/.test(hex)) {
        bytes.push(parseInt(hex, 16));
        i += 2;
        continue;
      }
    }
    bytes.push(char.charCodeAt(0));
  }
  return encoding.decode(bytes);
}
function __dartUriSplitQueryString(query, encoding = null) {
  const map = new Map();
  for (const element of String(query).split("&")) {
    const index = element.indexOf("=");
    if (index === -1) {
      if (element !== "") map.set(__dartUriDecodeQueryComponent(element, encoding), "");
      continue;
    }
    if (index === 0) continue;
    const key = element.slice(0, index);
    const value = element.slice(index + 1);
    map.set(__dartUriDecodeQueryComponent(key, encoding), __dartUriDecodeQueryComponent(value, encoding));
  }
  return map;
}
function __dartUriBuildQuery(queryParameters) {
  const parts = [];
  for (const [key, value] of queryParameters) {
    const encodedKey = __dartUriEncodeQueryComponent(key);
    if (value == null) {
      parts.push(encodedKey);
    } else if (typeof value !== "string" && typeof value[Symbol.iterator] === "function") {
      for (const item of value) parts.push(encodedKey + "=" + __dartUriEncodeQueryComponent(item));
    } else {
      parts.push(encodedKey + "=" + __dartUriEncodeQueryComponent(value));
    }
  }
  return parts.join("&");
}
function __dartUri(options = {}) {
  const scheme = options.scheme == null ? "" : String(options.scheme);
  const userInfo = options.userInfo == null ? "" : String(options.userInfo);
  const host = options.host == null ? "" : String(options.host);
  const port = options.port == null ? null : Number(options.port);
  let path = "";
  if (options.pathSegments != null) {
    path = Array.from(options.pathSegments, (segment) => encodeURIComponent(String(segment))).join("/");
  } else if (options.path != null) {
    path = __dartUriEncodePath(options.path);
  }
  const authority = host === ""
    ? ""
    : (userInfo === "" ? "" : userInfo + "@") + host + (port == null ? "" : ":" + port);
  let text = scheme === "" ? "" : scheme + ":";
  if (authority !== "") text += "//" + authority;
  if (path !== "") {
    if (authority !== "" && !path.startsWith("/")) text += "/";
    text += path;
  }
  if (options.queryParameters != null) {
    const query = __dartUriBuildQuery(options.queryParameters);
    if (query !== "") text += "?" + query;
  } else if (options.query != null) {
    text += "?" + String(options.query);
  }
  if (options.fragment != null) {
    text += "#" + encodeURIComponent(String(options.fragment));
  }
  return __dartUriParse(text, false);
}
function __dartUriFile(path, windows = false, directory = false) {
  let text = String(path);
  if (windows) text = text.replace(/\\/g, "/");
  if (directory && text !== "" && !text.endsWith("/") && !(windows && /^[a-zA-Z]:$/.test(text))) text += "/";
  const isAbsolute = windows ? (/^[a-zA-Z]:\//.test(text) || text.startsWith("//")) : text.startsWith("/");
  const encoded = __dartUriEncodePath(text);
  if (!isAbsolute) return __dartUriParse(encoded, false);
  const filePath = windows && /^[a-zA-Z]:\//.test(encoded) ? "/" + encoded : encoded;
  return __dartUriParse("file://" + filePath, false);
}
function __dartUriDataParameters(parameters) {
  if (parameters == null) return "";
  let result = "";
  for (const [key, value] of parameters) {
    result += ";" + encodeURIComponent(String(key)) + "=" + encodeURIComponent(String(value));
  }
  return result;
}
function __dartUriDataMediaType(mimeType) {
  if (mimeType == null || String(mimeType).toLowerCase() === "text/plain") return "";
  return String(mimeType);
}
function __dartUriPercentEncodeBytes(bytes) {
  let result = "";
  for (const byte of bytes) {
    const value = Number(byte) & 255;
    const char = String.fromCharCode(value);
    result += /[A-Za-z0-9\-._~]/.test(char) ? char : "%" + value.toString(16).toUpperCase().padStart(2, "0");
  }
  return result;
}
function __dartUriDataFromString(content, mimeType = null, encoding = null, parameters = null, base64 = false) {
  const text = String(content);
  let metadata = __dartUriDataMediaType(mimeType);
  if (encoding != null) metadata += ";charset=utf-8";
  metadata += __dartUriDataParameters(parameters);
  if (base64) {
    const bytes = new TextEncoder().encode(text);
    return __dartUriParse("data:" + metadata + ";base64," + __dartBase64Encode(bytes), false);
  }
  return __dartUriParse("data:" + metadata + "," + encodeURIComponent(text), false);
}
function __dartUriDataFromBytes(bytes, mimeType = null, parameters = null, percentEncoded = false) {
  const byteList = Array.from(bytes, (byte) => Number(byte) & 255);
  let metadata = mimeType == null ? "application/octet-stream" : __dartUriDataMediaType(mimeType);
  metadata += __dartUriDataParameters(parameters);
  if (percentEncoded) {
    return __dartUriParse("data:" + metadata + "," + __dartUriPercentEncodeBytes(byteList), false);
  }
  return __dartUriParse("data:" + metadata + ";base64," + __dartBase64Encode(byteList), false);
}
function __dartUriAssignQueryParameters(url, queryParameters) {
  const search = new URLSearchParams();
  for (const [key, value] of queryParameters) {
    if (value == null) continue;
    if (typeof value !== "string" && value != null && typeof value[Symbol.iterator] === "function") {
      for (const item of value) search.append(String(key), String(item));
    } else {
      search.append(String(key), String(value));
    }
  }
  url.search = search.toString();
}
function __dartUriResolve(uri, reference) {
  return __dartUriParse(new URL(String(reference), String(uri)).toString());
}
function __dartUriNormalizePath(uri) {
  return __dartUriParse(new URL(String(uri)).toString());
}
function __dartUriReplace(uri, options = {}) {
  const url = new URL(String(uri));
  if ("scheme" in options && options.scheme != null) url.protocol = String(options.scheme) + ":";
  if ("userInfo" in options && options.userInfo != null) {
    const parts = String(options.userInfo).split(":");
    url.username = parts[0] ?? "";
    url.password = parts.slice(1).join(":");
  }
  if ("host" in options && options.host != null) url.hostname = String(options.host);
  if ("port" in options && options.port != null) url.port = String(options.port);
  if ("pathSegments" in options && options.pathSegments != null) {
    url.pathname = Array.from(options.pathSegments, (segment) => encodeURIComponent(String(segment))).join("/");
  } else if ("path" in options && options.path != null) {
    url.pathname = String(options.path);
  }
  if ("queryParameters" in options) {
    if (options.queryParameters != null) __dartUriAssignQueryParameters(url, options.queryParameters);
  } else if ("query" in options) {
    if (options.query != null) url.search = String(options.query);
  }
  if (options.__removeFragment === true) url.hash = "";
  else if ("fragment" in options && options.fragment != null) url.hash = String(options.fragment);
  return __dartUriParse(url.toString());
}
function __dartUriBuild(scheme, authority, path, queryParameters = null) {
  const url = new URL(String(scheme) + "://" + String(authority));
  const rawPath = String(path);
  url.pathname = rawPath.startsWith("/") ? rawPath : "/" + rawPath;
  if (queryParameters != null) {
    __dartUriAssignQueryParameters(url, queryParameters);
  }
  return __dartUriParse(url.toString());
}

export function main() {
  const parsedInt = __dartIntParse("42");
  const parsedHex = __dartIntParse("ff", 16);
  const maybeInt = (__dartIntTryParse("nope") ?? -1);
  __dartPrint(`ints ${__dartStr(parsedInt)} ${__dartStr(parsedHex)} ${__dartStr(maybeInt)}`);
  const parsedDouble = __dartDoubleParse("3.5");
  const maybeDouble = (__dartDoubleTryParse("bad") ?? 1.25);
  const parsedNum = __dartNumParse("7.25");
  __dartPrint(`nums ${__dartStr(parsedDouble)} ${__dartStr(maybeDouble)} ${__dartStr(parsedNum)}`);
  const char = String.fromCodePoint(65);
  const chars = __dartStringFromCharCodes([68, 97, 114, 116]);
  const text = "  hello,dart  ";
  const trimmed = text.trim();
  __dartPrint(`strings ${__dartStr(char)} ${__dartStr(chars)} ${__dartStr(trimmed.charCodeAt(0))} ${__dartStr(trimmed.substring(1, 4))}`);
  __dartPrint(`checks ${__dartStr(trimmed.startsWith("he"))} ${__dartStr(trimmed.endsWith("rt"))} ${__dartStr(trimmed.indexOf("dart"))} ${__dartStr(__dartIterableToArray(trimmed.split(",")).join("|"))}`);
  __dartPrint(`replace ${__dartStr(trimmed.replaceAll("l", "L").toUpperCase())}`);
  __dartPrint(`stringMeta ${__dartStr(trimmed.length)} ${__dartStr(trimmed.length > 0)} ${__dartStr("".length === 0)} ${__dartStr(trimmed.includes("l", 3))} ${__dartStr("7".padStart(3, "0"))} ${__dartStr("x".padEnd(3, "."))} ${__dartStr("  left".trimStart())} ${__dartStr("right  ".trimEnd())} ${__dartStr(__dartCompare("abc", "abd"))}`);
  __dartPrint(`stringOps ${__dartStr(__dartStringReplaceFirst(trimmed, "l", "L"))} ${__dartStr(__dartStringReplaceFirst(trimmed, "l", "L", 3))} ${__dartStr(__dartStringReplaceRange(trimmed, 1, 4, "EL"))} ${__dartStr(__dartIterableToArray(__dartIterableToArray(__dartStringCodeUnits(trimmed)).slice(0, 3)).join("-"))}`);
  const numeric = -3.6;
  __dartPrint(`numOps ${__dartStr(Math.abs(numeric))} ${__dartStr((Number.isNaN(numeric) ? NaN : (numeric < 0 ? -1 : (numeric > 0 ? 1 : numeric))) < 0)} ${__dartStr(Math.round(numeric))} ${__dartStr(Math.floor(numeric))} ${__dartStr(Math.ceil(numeric))} ${__dartStr(Math.trunc(numeric))}`);
  __dartPrint(`numFormat ${__dartStr(Math.min(Math.max(numeric, -3), 2))} ${__dartStr(numeric % 2)} ${__dartStr(Number(3.14159).toFixed(2))} ${__dartStr(Number(3.14159).toPrecision(3))}`);
  __dartPrint(`numMeta ${__dartStr(Number.isNaN(NaN))} ${__dartStr((Infinity === Infinity || Infinity === -Infinity))} ${__dartStr(Number.isFinite(3.0))} ${__dartStr((-0.0 < 0 || Object.is(-0.0, -0)))}`);
  __dartPrint(`intMore ${__dartStr(Math.trunc(5) % 2 === 0)} ${__dartStr(Math.trunc(5) % 2 !== 0)} ${__dartStr(__dartIntGcd(5, 15))} ${__dartStr(__dartIntGcd(-12, 18))} ${__dartStr(__dartIntModInverse(5, 7))} ${__dartStr(__dartIntModPow(5, 3, 7))} ${__dartStr((-31).toString(16))}`);
  const bits = 3855;
  const lowerBits = 255;
  __dartPrint(`bitOps ${__dartStr(bits & lowerBits)} ${__dartStr(bits | 4096)} ${__dartStr(bits ^ lowerBits)} ${__dartStr(3 << 4)} ${__dartStr(16 >> 2)} ${__dartStr(16 >>> 2)}`);
  __dartPrint(`doubleMore ${__dartStr(__dartDoubleValue(Math.round(3.7)))} ${__dartStr(__dartDoubleValue(Math.floor(3.7)))} ${__dartStr(__dartDoubleValue(Math.ceil(3.2)))} ${__dartStr(__dartDoubleValue(Math.trunc(3.2)))}`);
  try {
    __dartIntModInverse(6, 9);
  } catch ($error) {
    if (__dartIsCoreError($error, "Exception")) {
      const error = $error;
      __dartPrint(`modInverseError ${__dartStr(__dartSafeToString(error).includes("Not coprime"))}`);
    } else {
      throw $error;
    }
  }
  try {
    __dartIntModPow(5, -1, 7);
  } catch ($error) {
    if (__dartIsCoreError($error, "RangeError")) {
      __dartPrint("modPowError true");
    } else {
      throw $error;
    }
  }
  const uri = __dartUriParse("https://user:pass@example.test:8443/a/b?x=1&x=2&empty=#frag", false);
  __dartPrint(`uri ${__dartStr(uri.scheme)} ${__dartStr(uri.host)} ${__dartStr(uri.path)} ${__dartStr(uri.query)} ${__dartStr(uri.fragment)}`);
  __dartPrint(`uri meta ${__dartStr(uri.authority)} ${__dartStr(uri.userInfo)} ${__dartStr(uri.port)} ${__dartStr(__dartIterableToArray(uri.pathSegments).join("|"))} ${__dartStr(uri.hasScheme)} ${__dartStr(uri.hasAuthority)} ${__dartStr(uri.hasPort)} ${__dartStr(uri.hasQuery)} ${__dartStr(uri.hasFragment)} ${__dartStr(uri.isAbsolute)}`);
  __dartPrint(`uri query ${__dartStr(__dartMapGet(uri.queryParameters, "x"))} ${__dartStr(__dartMapGet(uri.queryParameters, "empty"))} ${__dartStr(__dartIterableToArray(__dartNullCheck(__dartMapGet(uri.queryParametersAll, "x"))).join("|"))}`);
  const queryEncoded = __dartUriEncodeQueryComponent("a b/é", null);
  const queryDecoded = __dartUriDecodeQueryComponent("a+b%2F%C3%A9", null);
  const latinEncoded = __dartUriEncodeQueryComponent("é", __dartConst("[\"InstanceConstant\",\"InstanceConstant(const Latin1Codec{Latin1Codec._allowInvalid: false})\"]", () => __dartLatin1Codec(false)));
  const latinDecoded = __dartUriDecodeQueryComponent("caf%E9", __dartConst("[\"InstanceConstant\",\"InstanceConstant(const Latin1Codec{Latin1Codec._allowInvalid: false})\"]", () => __dartLatin1Codec(false)));
  const splitQuery = __dartUriSplitQueryString("a=1&empty&space=a+b&latin=caf%E9", __dartConst("[\"InstanceConstant\",\"InstanceConstant(const Latin1Codec{Latin1Codec._allowInvalid: false})\"]", () => __dartLatin1Codec(false)));
  __dartPrint(`uri queryOps ${__dartStr(queryEncoded)} ${__dartStr(queryDecoded)} ${__dartStr(latinEncoded)} ${__dartStr(latinDecoded)} ${__dartStr(__dartMapGet(splitQuery, "empty"))} ${__dartStr(__dartMapGet(splitQuery, "space"))} ${__dartStr(__dartMapGet(splitQuery, "latin"))}`);
  __dartPrint(`uri string ${__dartStr(String(uri))}`);
  const https = __dartUriBuild("https", "example.test", "/a/b", __dartMapFromEntries([["q", "dart esm"], ["page", "1"]]));
  const http = __dartUriBuild("http", "example.test:8080", "plain path", __dartMapFromEntries([["x", "a/b"]]));
  __dartPrint(`uri build ${__dartStr(https.scheme)} ${__dartStr(https.host)} ${__dartStr(https.path)} ${__dartStr(https.query)}`);
  __dartPrint(`uri built ${__dartStr(String(https))} ${__dartStr(String(http))}`);
  const replaced = __dartUriReplace(uri, { path: "/c/d", queryParameters: __dartMapFromEntries([["z", "9"], ["many", ["a", "b"]]]), fragment: null });
  const resolved = __dartUriResolve(uri, "../c?q=1");
  const resolvedUri = __dartUriResolve(uri, __dartUriParse("/root?q=2", false));
  const normalized = __dartUriNormalizePath(__dartUriParse("https://example.test/a/../b/./c", false));
  __dartPrint(`uri ops ${__dartStr(String(replaced))} ${__dartStr(__dartUriReplace(uri, { __removeFragment: true }).hasFragment)} ${__dartStr(resolved.path)} ${__dartStr(resolved.query)} ${__dartStr(resolvedUri.path)} ${__dartStr(normalized.path)}`);
  const relative = __dartUriParse("relative/path.txt", false);
  const file = __dartUriFile("/tmp/a b.txt", false, false);
  const directory = __dartUriFile("/tmp/a b", false, true);
  const relativeFile = __dartUriFile("relative/path.txt", false, false);
  __dartPrint(`uri factories ${__dartStr(relative.path)} ${__dartStr(relative.isAbsolute)} ${__dartStr(file.scheme)} ${__dartStr(file.path)} ${__dartStr(directory.path.endsWith("/"))} ${__dartStr(relativeFile.scheme)} ${__dartStr(relativeFile.path)}`);
  const constructedUri = __dartUri({ scheme: "https", host: "example.test", pathSegments: ["a b", "c"], queryParameters: __dartMapFromEntries([["q", "x y"]]) });
  const authorityUri = __dartUri({ userInfo: "u:p", host: "example.test", port: 8080, path: "/p", fragment: "f" });
  const relativeCtor = __dartUri({ path: "/a b", queryParameters: __dartMapFromEntries([["x", ["1", "2"]], ["empty", null]]) });
  __dartPrint(`uri ctor ${__dartStr(String(constructedUri))} ${__dartStr(constructedUri.path)} ${__dartStr(__dartMapGet(constructedUri.queryParameters, "q"))} ${__dartStr(String(authorityUri))} ${__dartStr(authorityUri.host)} ${__dartStr(String(relativeCtor))}`);
  const dataText = __dartUriDataFromString("hello world", null, null, null, false);
  const dataJson = __dartUriDataFromString("hello world", "application/json", null, null, false);
  const dataUtf8 = __dartUriDataFromString("å", null, __dartConst("[\"InstanceConstant\",\"InstanceConstant(const Utf8Codec{Utf8Codec._allowMalformed: false})\"]", () => __dartUtf8Codec(false)), null, false);
  const dataBase64 = __dartUriDataFromString("hello", null, null, null, true);
  const dataBytes = __dartUriDataFromBytes([65, 66, 67], null, null, false);
  const dataBytesText = __dartUriDataFromBytes([65, 66, 67], "text/plain", null, false);
  const dataBytesPercent = __dartUriDataFromBytes([65, 66, 67], null, null, true);
  __dartPrint(`uri data ${__dartStr(String(dataText))} ${__dartStr(String(dataJson))} ${__dartStr(String(dataUtf8))} ${__dartStr(String(dataBase64))} ${__dartStr(String(dataBytes))} ${__dartStr(String(dataBytesText))} ${__dartStr(String(dataBytesPercent))}`);
  const tryUri = __dartUriParse("https://example.test/try", true);
  const invalidUri = __dartUriParse("http://[::1", true);
  __dartPrint(`uri try ${__dartStr(__dartNullCheck(tryUri).host)} ${__dartStr(invalidUri === null)}`);
  try {
    __dartUriParse("http://[::1", false);
  } catch ($error) {
    if (__dartIsCoreError($error, "FormatException")) {
      __dartPrint("uri parseError true");
    } else {
      throw $error;
    }
  }
}

main();
