function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartFormatException(message) {
  const error = new Error(String(message));
  error.name = "FormatException";
  return error;
}
function __dartIntTryParse(source, radix = null) {
  const text = String(source).trim();
  let base = radix == null ? null : Number(radix);
  if (base != null && (!Number.isInteger(base) || base < 2 || base > 36)) return null;
  if (base == null && /^[+-]?0x[0-9a-f]+$/i.test(text)) return Number.parseInt(text, 16);
  base ??= 10;
  const sign = /^[+-]/.test(text) ? text[0] : "";
  const digits = sign === "" ? text : text.slice(1);
  if (digits.length === 0) return null;
  for (const char of digits.toLowerCase()) {
    const code = char.charCodeAt(0);
    const value = code >= 48 && code <= 57 ? code - 48 : code >= 97 && code <= 122 ? code - 87 : -1;
    if (value < 0 || value >= base) return null;
  }
  return Number.parseInt(text, base);
}
function __dartIntParse(source, radix = null) {
  const value = __dartIntTryParse(source, radix);
  if (value == null) throw __dartFormatException("Invalid integer literal");
  return value;
}
function __dartDoubleTryParse(source) {
  const text = String(source).trim();
  if (text === "") return null;
  const value = Number(text);
  return Number.isNaN(value) ? null : value;
}
function __dartDoubleParse(source) {
  const value = __dartDoubleTryParse(source);
  if (value == null) throw __dartFormatException("Invalid double literal");
  return value;
}
function __dartNumTryParse(source) {
  return __dartDoubleTryParse(source);
}
function __dartNumParse(source) {
  const value = __dartNumTryParse(source);
  if (value == null) throw __dartFormatException("Invalid number literal");
  return value;
}
function __dartUriParse(source) {
  const text = String(source);
  let url;
  try {
    url = new URL(text);
  } catch (_) {
    url = new URL(text, "dart://relative");
  }
  const isRelative = url.protocol === "dart:";
  return Object.freeze({
    get scheme() { return isRelative ? "" : url.protocol.slice(0, -1); },
    get host() { return isRelative ? "" : url.host; },
    get path() { return url.pathname; },
    get query() { return url.search.startsWith("?") ? url.search.slice(1) : ""; },
    get fragment() { return url.hash.startsWith("#") ? url.hash.slice(1) : ""; },
    toString() { return text; },
  });
}
function __dartUriBuild(scheme, authority, path, queryParameters = null) {
  const url = new URL(String(scheme) + "://" + String(authority));
  const rawPath = String(path);
  url.pathname = rawPath.startsWith("/") ? rawPath : "/" + rawPath;
  if (queryParameters != null) {
    const search = new URLSearchParams();
    for (const [key, value] of queryParameters) {
      if (value == null) continue;
      if (typeof value !== "string" && value != null && typeof value[Symbol.iterator] === "function") {
        for (const item of value) search.append(String(key), String(item));
      } else {
        search.append(String(key), String(value));
      }
    }
    url.search = search.toString();
  }
  return __dartUriParse(url.toString());
}
function __dartIterableJoin(iterable, separator = "") {
  return Array.from(iterable, (value) => __dartStr(value)).join(String(separator));
}

// Generated by dart2esm.

export function main() {
  const parsedInt = __dartIntParse("42", null);
  const parsedHex = __dartIntParse("ff", 16);
  const maybeInt = (() => { let v = __dartIntTryParse("nope", null); return ((v === null) ? (-1) : v); })();
  __dartPrint("ints " + __dartStr(parsedInt) + " " + __dartStr(parsedHex) + " " + __dartStr(maybeInt));
  const parsedDouble = __dartDoubleParse("3.5");
  const maybeDouble = (() => { let v_1 = __dartDoubleTryParse("bad"); return ((v_1 === null) ? 1.25 : v_1); })();
  const parsedNum = __dartNumParse("7.25");
  __dartPrint("nums " + __dartStr(parsedDouble) + " " + __dartStr(maybeDouble) + " " + __dartStr(parsedNum));
  const char = String.fromCharCode(65);
  const chars = String.fromCharCode(...Array.from([68, 97, 114, 116]));
  const text = "  hello,dart  ";
  const trimmed = text.trim();
  __dartPrint("strings " + __dartStr(char) + " " + __dartStr(chars) + " " + __dartStr(trimmed.charCodeAt(0)) + " " + __dartStr(trimmed.substring(1, 4)));
  __dartPrint("checks " + __dartStr(trimmed.startsWith("he")) + " " + __dartStr(trimmed.endsWith("rt")) + " " + __dartStr(trimmed.indexOf("dart")) + " " + __dartStr(__dartIterableJoin(trimmed.split(","), "|")));
  __dartPrint("replace " + __dartStr(trimmed.replaceAll("l", "L").toUpperCase()));
  __dartPrint("stringMeta " + __dartStr(trimmed.length) + " " + __dartStr(trimmed.length !== 0) + " " + __dartStr("".length === 0) + " " + __dartStr(trimmed.includes("l", 3)) + " " + __dartStr("7".padStart(3, "0")) + " " + __dartStr("x".padEnd(3, ".")) + " " + __dartStr("  left".trimStart()) + " " + __dartStr("right  ".trimEnd()) + " " + __dartStr(("abc" < "abd" ? -1 : ("abc" > "abd" ? 1 : 0))));
  const uri = __dartUriParse("https://example.test/a/b?x=1#frag");
  __dartPrint("uri " + __dartStr(uri.scheme) + " " + __dartStr(uri.host) + " " + __dartStr(uri.path) + " " + __dartStr(uri.query) + " " + __dartStr(uri.fragment));
  __dartPrint("uri string " + __dartStr(__dartStr(uri)));
  const https = __dartUriBuild("https", "example.test", "/a/b", new Map([["q", "dart esm"], ["page", "1"]]));
  const http = __dartUriBuild("http", "example.test:8080", "plain path", new Map([["x", "a/b"]]));
  __dartPrint("uri build " + __dartStr(https.scheme) + " " + __dartStr(https.host) + " " + __dartStr(https.path) + " " + __dartStr(https.query));
  __dartPrint("uri built " + __dartStr(__dartStr(https)) + " " + __dartStr(__dartStr(http)));
}

main();
