function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartDuration(options = {}) {
  const micros = Math.trunc((options.days ?? 0) * 86400000000 + (options.hours ?? 0) * 3600000000 + (options.minutes ?? 0) * 60000000 + (options.seconds ?? 0) * 1000000 + (options.milliseconds ?? 0) * 1000 + (options.microseconds ?? 0));
  return {
    get inDays() { return Math.trunc(micros / 86400000000); },
    get inHours() { return Math.trunc(micros / 3600000000); },
    get inMinutes() { return Math.trunc(micros / 60000000); },
    get inSeconds() { return Math.trunc(micros / 1000000); },
    get inMilliseconds() { return Math.trunc(micros / 1000); },
    get inMicroseconds() { return micros; },
    toString() { return String(micros) + "us"; },
  };
}
function __dartDateTimeFromParts(isUtc, year, month = 1, day = 1, hour = 0, minute = 0, second = 0, millisecond = 0, microsecond = 0) {
  const millis = isUtc ? Date.UTC(year, month - 1, day, hour, minute, second, millisecond) : new Date(year, month - 1, day, hour, minute, second, millisecond).getTime();
  return __dartDateTime(millis, isUtc, microsecond);
}
function __dartDateTime(millis, isUtc = false, microsecond = 0) {
  const date = new Date(millis);
  const read = (utcName, localName) => isUtc ? date[utcName]() : date[localName]();
  return {
    get millisecondsSinceEpoch() { return millis; },
    get microsecond() { return microsecond; },
    get millisecond() { return read("getUTCMilliseconds", "getMilliseconds"); },
    get second() { return read("getUTCSeconds", "getSeconds"); },
    get minute() { return read("getUTCMinutes", "getMinutes"); },
    get hour() { return read("getUTCHours", "getHours"); },
    get day() { return read("getUTCDate", "getDate"); },
    get month() { return read("getUTCMonth", "getMonth") + 1; },
    get year() { return read("getUTCFullYear", "getFullYear"); },
    get isUtc() { return isUtc; },
    toUtc() { return __dartDateTime(millis, true, microsecond); },
    toLocal() { return __dartDateTime(millis, false, microsecond); },
    toIso8601String() { return date.toISOString(); },
    toString() { return this.toIso8601String(); },
  };
}
function __dartDateTimeParse(source) {
  const text = String(source);
  const millis = Date.parse(text);
  const isUtc = /(?:z|[+-]\d\d(?::?\d\d)?)$/i.test(text);
  return __dartDateTime(millis, isUtc, 0);
}
function __dartStopwatchNowMicros() {
  const now = globalThis.performance && typeof globalThis.performance.now === "function" ? globalThis.performance.now() : Date.now();
  return Math.trunc(now * 1000);
}
function __dartStopwatch() {
  let start = 0;
  let stop = 0;
  const watch = {
    get frequency() { return 1000000; },
    get elapsedTicks() { return (stop ?? __dartStopwatchNowMicros()) - start; },
    get elapsedMicroseconds() { return this.elapsedTicks; },
    get elapsedMilliseconds() { return Math.trunc(this.elapsedMicroseconds / 1000); },
    get elapsed() { return __dartDuration({ microseconds: this.elapsedMicroseconds }); },
    get isRunning() { return stop == null; },
    start() {
      if (stop != null) {
        start += __dartStopwatchNowMicros() - stop;
        stop = null;
      }
      return null;
    },
    stop() {
      if (stop == null) stop = __dartStopwatchNowMicros();
      return null;
    },
    reset() {
      start = stop ?? __dartStopwatchNowMicros();
      return null;
    },
  };
  return watch;
}
const __dartConstValues = new Map();
function __dartConst(key, create) {
  if (!__dartConstValues.has(key)) {
    __dartConstValues.set(key, create());
  }
  return __dartConstValues.get(key);
}

// Generated by dart2esm.

export async function main() {
  const duration = __dartDuration({ days: 1, hours: 2, minutes: 3, seconds: 4, milliseconds: 5, microseconds: 6 });
  __dartPrint("duration " + __dartStr(duration.inMilliseconds) + " " + __dartStr(duration.inSeconds));
  const utc = __dartDateTimeFromParts(true, 2026, 1, 2, 3, 4, 5, 6, 7);
  __dartPrint("utc " + __dartStr(utc.year) + "-" + __dartStr(utc.month) + "-" + __dartStr(utc.day) + " " + __dartStr(utc.hour) + ":" + __dartStr(utc.minute) + ":" + __dartStr(utc.second) + " " + __dartStr(utc.millisecond) + " " + __dartStr(utc.microsecond) + " " + __dartStr(utc.isUtc));
  const epoch = __dartDateTime(0, true);
  __dartPrint("epoch " + __dartStr(epoch.toIso8601String()) + " " + __dartStr(epoch.millisecondsSinceEpoch));
  const parsed = __dartDateTimeParse("2026-01-02T03:04:05.006Z");
  __dartPrint("parsed " + __dartStr(parsed.toUtc().toIso8601String()));
  const watch = __dartStopwatch();
  __dartPrint("watch-start " + __dartStr(watch.isRunning) + " " + __dartStr(watch.elapsedMicroseconds));
  watch.start();
  await new Promise((resolve, reject) => setTimeout(() => { try { resolve(null); } catch (error) { reject(error); } }, Math.max(0, __dartConst("[\"instance\",\"dart:core::Duration\",[\"field\",\"dart:core::Duration::@fields::dart:core::_duration\",[\"int\",\"1000\"]]]", () => __dartDuration({ microseconds: 1000 })).inMilliseconds)));
  watch.stop();
  __dartPrint("watch-stop " + __dartStr(watch.isRunning) + " " + __dartStr((watch.elapsedMicroseconds > 0)));
  watch.reset();
  __dartPrint("watch-reset " + __dartStr(watch.elapsedMicroseconds));
}

await main();
