function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartListSetAll(list, index, values) {
  let offset = 0;
  for (const value of values) {
    list[index + offset] = value;
    offset++;
  }
  return null;
}
function __dartListAsMap(list) {
  return new (class extends Map {
    get size() { return list.length; }
    get(key) { return Number.isInteger(key) && key >= 0 && key < list.length ? list[key] : undefined; }
    has(key) { return Number.isInteger(key) && key >= 0 && key < list.length; }
    entries() { return Array.from(list, (value, index) => [index, value])[Symbol.iterator](); }
    keys() { return Array.from({ length: list.length }, (_, index) => index)[Symbol.iterator](); }
    values() { return Array.from(list)[Symbol.iterator](); }
    [Symbol.iterator]() { return this.entries(); }
    forEach(callback, thisArg = undefined) {
      for (let index = 0; index < list.length; index++) {
        callback.call(thisArg, list[index], index, this);
      }
    }
    set() { throw new TypeError("Unsupported operation: Cannot modify unmodifiable map"); }
    delete() { throw new TypeError("Unsupported operation: Cannot modify unmodifiable map"); }
    clear() { throw new TypeError("Unsupported operation: Cannot modify unmodifiable map"); }
  })();
}
function __dartIterableJoin(iterable, separator = "") {
  return Array.from(iterable, (value) => __dartStr(value)).join(String(separator));
}
function __dartTypedDataSublistView(data, start, end, viewConstructor, bytesPerElement) {
  const elementSize = data instanceof DataView ? 1 : data.BYTES_PER_ELEMENT;
  const elementCount = Math.trunc(data.byteLength / elementSize);
  const effectiveEnd = end == null ? elementCount : end;
  const byteOffset = data.byteOffset + start * elementSize;
  const byteLength = (effectiveEnd - start) * elementSize;
  if (viewConstructor === DataView) return new DataView(data.buffer, byteOffset, byteLength);
  return new viewConstructor(data.buffer, byteOffset, Math.trunc(byteLength / bytesPerElement));
}
function __dartListSetRange(target, start, end, source, skipCount = 0) {
  const values = Array.from(source).slice(skipCount, skipCount + (end - start));
  for (let index = 0; index < values.length; index++) {
    target[start + index] = values[index];
  }
  return null;
}

// Generated by dart2esm.

export function main() {
  const bytes = Uint8Array.from([1, 2, 255]);
  let hidden = bytes;
  __dartPrint("from " + __dartStr(bytes.length) + " " + __dartStr(bytes[2]) + " " + __dartStr(hidden instanceof Uint8Array));
  __dartPrint("types " + __dartStr((Array.isArray(hidden) || (ArrayBuffer.isView(hidden) && !(hidden instanceof DataView)))) + " " + __dartStr(hidden != null && typeof hidden !== "string" && !(hidden instanceof Map) && typeof hidden[Symbol.iterator] === "function"));
  const zeros = new Uint8Array(3);
  zeros[0] = 7;
  zeros[2] = 9;
  __dartPrint("new " + __dartStr(zeros.length) + " " + __dartStr(zeros[0]) + " " + __dartStr(zeros[1]) + " " + __dartStr(zeros[2]));
  const ints = Int32Array.from([1, (-2), 3]);
  const floats = new Float64Array(2);
  floats[0] = 1.5;
  floats[1] = (-2.25);
  __dartPrint("typed " + __dartStr(ints.length) + " " + __dartStr(ints[1]) + " " + __dartStr(floats[0]) + " " + __dartStr(floats[1]));
  const data = new DataView(new ArrayBuffer(4));
  let hiddenData = data;
  data.setInt16(0, 4660);
  data.setUint8(2, 255);
  __dartPrint("bytes " + __dartStr(data.byteLength) + " " + __dartStr(data.getInt16(0)) + " " + __dartStr(data.getUint8(2)));
  __dartPrint("datatypes " + __dartStr(hiddenData instanceof DataView) + " " + __dartStr(ArrayBuffer.isView(hiddenData)));
  const words = new Uint16Array(bytes.buffer, 0, 1);
  let hiddenBuffer = bytes.buffer;
  words[0] = 513;
  __dartPrint("view " + __dartStr(bytes[0]) + " " + __dartStr(bytes[1]) + " " + __dartStr(words.byteLength) + " " + __dartStr(words.byteOffset) + " " + __dartStr((words instanceof DataView ? 1 : words.BYTES_PER_ELEMENT)));
  __dartPrint("buffertype " + __dartStr(hiddenBuffer instanceof ArrayBuffer));
  const sublist = __dartTypedDataSublistView(bytes, 1, 3, Uint8Array, 1);
  sublist[0] = 8;
  __dartPrint("sublist " + __dartStr(sublist.length) + " " + __dartStr(sublist[0]) + " " + __dartStr(bytes[1]));
  const fromBuffer = new Uint8Array(bytes.buffer, 1, 2);
  __dartPrint("buffer " + __dartStr(fromBuffer.length) + " " + __dartStr(fromBuffer[0]) + " " + __dartStr(bytes.buffer.byteLength));
  const dataView = new DataView(bytes.buffer, 0, bytes.byteLength);
  dataView.setUint16(0, 2571, true);
  __dartPrint("viewdata " + __dartStr(bytes[0]) + " " + __dartStr(bytes[1]) + " " + __dartStr(dataView.byteOffset) + " " + __dartStr((dataView instanceof DataView ? 1 : dataView.BYTES_PER_ELEMENT)));
  const byteSlice = __dartTypedDataSublistView(bytes, 0, 2, DataView, 1);
  __dartPrint("byteslice " + __dartStr(byteSlice.byteLength) + " " + __dartStr(byteSlice.getUint8(1)));
  const ops = Uint8Array.from([1, 2, 3, 4]);
  const opsCopy = ops.slice(1, 3);
  __dartListSetAll(ops, 1, [9, 8]);
  __dartListSetRange(ops, 0, 2, [5, 6, 7], 1);
  __dartPrint("typedOps " + __dartStr(__dartIterableJoin(opsCopy, ",")) + " " + __dartStr(__dartIterableJoin(ops, ",")) + " " + __dartStr(ops.buffer.byteLength));
  const queries = Uint8Array.from([4, 5, 4, 6]);
  const queryRange = __dartIterableJoin(queries.slice(1, 3), ",");
  const queryMap = __dartListAsMap(queries);
  (queries.fill(9, 1, 3), null);
  __dartPrint("typedQueries " + __dartStr(queryRange) + " " + __dartStr(queryMap.size) + ":" + __dartStr(queryMap.get(2)) + " " + __dartStr(queries.indexOf(4)) + " " + __dartStr(queries.indexOf(4, 1)) + " " + __dartStr(queries.lastIndexOf(4)) + " " + __dartStr(queries.lastIndexOf(4, 2)) + " " + __dartStr(__dartIterableJoin(queries, ",")));
}

main();
