// Generated by dart2esm.

function __dartEquals(left, right) {
  if (left === right) return true;
  if (left == null || right == null) return false;
  if ((typeof left === "number" || left.__dartType === "double") && (typeof right === "number" || right.__dartType === "double")) return Number(left) === Number(right);
  if (__dartIsRecord(left) && __dartIsRecord(right)) {
    const leftShape = left[__dartRecordShape];
    const rightShape = right[__dartRecordShape];
    if (leftShape.length !== rightShape.length) return false;
    for (let i = 0; i < leftShape.length; i++) {
      const name = leftShape[i];
      if (name !== rightShape[i]) return false;
      if (!__dartEquals(left[name], right[name])) return false;
    }
    return true;
  }
  const equals = left["=="];
  return typeof equals === "function" ? equals.call(left, right) : false;
}

function __dartFinalizer(callback) {
  const registry = typeof FinalizationRegistry === "function" ? new FinalizationRegistry(callback) : null;
  const detachTokens = new Map();
  const finalizer = {
    attach(value, token, options = {}) {
      if (registry != null) {
        const detach = options.detach ?? null;
        let unregisterToken = undefined;
        if (detach != null) {
          unregisterToken = detachTokens.get(detach);
          if (unregisterToken == null) {
            unregisterToken = {};
            detachTokens.set(detach, unregisterToken);
          }
        }
        registry.register(value, token, unregisterToken);
      }
      return null;
    },
    detach(detach) {
      if (registry != null) {
        const unregisterToken = detachTokens.get(detach);
        if (unregisterToken != null) {
          registry.unregister(unregisterToken);
          detachTokens.delete(detach);
        }
      }
      return null;
    },
    toString() {
      return "Finalizer";
    },
  };
  Object.defineProperty(finalizer, "__dartType", { value: "Finalizer" });
  return Object.freeze(finalizer);
}

function __dartListAdd(list, value) {
  list.push(value);
  return null;
}

function __dartPrint(value) {
  console.log(__dartStr(value));
}

const __dartRecordShape = Symbol("dart.recordShape");

function __dartIsRecord(value) {
  return value != null && typeof value === "object" && Array.isArray(value[__dartRecordShape]);
}

function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}

function __dartWeakReference(target) {
  const ref = typeof WeakRef === "function" ? new WeakRef(target) : { deref() { return target; } };
  const weak = {
    get target() {
      return ref.deref() ?? null;
    },
    toString() {
      return "WeakReference";
    },
  };
  Object.defineProperty(weak, "__dartType", { value: "WeakReference" });
  return Object.freeze(weak);
}

export class PlainToken {
  constructor(name) {
    this.name = null;
    this.name = name;
  }
  toString() {
    return this.name;
  }
}

export function hide(value) {
  return value;
}

export function makeWeak(token) {
  return __dartWeakReference(token);
}

export function describeWeak(token) {
  const weak = __dartWeakReference(token);
  return `${__dartStr(__dartEquals(weak.target, token))} ${__dartStr(((hide(weak) != null && typeof hide(weak) === "object") && hide(weak).__dartType === "WeakReference"))}`;
}

export function describeFinalizer(token) {
  const observed = Array(0).fill(null);
  const detachKey = {  };
  const finalizer = __dartFinalizer(function(value) {
    __dartListAdd(observed, value);
  });
  finalizer.attach(token, "collected", { detach: detachKey });
  finalizer.detach(detachKey);
  return `${__dartStr(((hide(finalizer) != null && typeof hide(finalizer) === "object") && hide(finalizer).__dartType === "Finalizer"))} ${__dartStr(observed.length)}`;
}

export function main() {
  const token = new PlainToken("dart");
  const weak = makeWeak(token);
  __dartPrint(`weak ${__dartStr(__dartEquals(weak.target, token))} ${__dartStr(weak.target?.name)}`);
  __dartPrint(`weakType ${__dartStr(describeWeak(token))}`);
  __dartPrint(`finalizer ${__dartStr(describeFinalizer(token))}`);
}

main();
