function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartNullCheck(value) {
  if (value == null) {
    throw new TypeError("Null check operator used on a null value");
  }
  return value;
}

// Generated by dart2esm.

export function main() {
  const supported = (!!(globalThis.window?.AudioContext || globalThis.window?.webkitAudioContext || globalThis.AudioContext || globalThis.webkitAudioContext));
  const context = new (globalThis.window?.AudioContext ?? globalThis.window?.webkitAudioContext ?? globalThis.AudioContext ?? globalThis.webkitAudioContext)();
  const gain = context.createGain();
  const oscillator = context.createOscillator();
  (oscillator.connect(gain, 0, 0), null);
  (gain.connect(__dartNullCheck(context.destination), 0, 0), null);
  (oscillator.start(), null);
  oscillator.stop(0.25);
  __dartPrint("webAudio " + __dartStr(supported) + " " + __dartStr(context.currentTime) + " " + __dartStr((() => { let v = gain.gain; return ((v === null) ? null : v.value); })()) + " " + __dartStr(oscillator.type) + " " + __dartStr(!((context.destination === null))));
}

main();
