// Generated by dart2esm.

function __dartIterableToArray(iterable) {
  if (Array.isArray(iterable)) return Array.from(iterable);
  if (iterable != null && typeof iterable["[]"] === "function" && typeof iterable.length === "number") {
    return Array.from({ length: Number(iterable.length) }, (_, index) => iterable["[]"](index));
  }
  return Array.from(iterable);
}

function __dartLazyField(name, initialize, writable, publish = null) {
  let state = 0;
  let value;
  function get() {
    if (state === 2) return value;
    if (state === 1) {
      throw new Error("Cyclic initialization of field " + name);
    }
    if (initialize == null) {
      throw new Error("Late field " + name + " has not been initialized");
    }
    state = 1;
    try {
      value = initialize();
      if (publish) publish(value);
      state = 2;
      return value;
    } catch (error) {
      state = 0;
      throw error;
    }
  }
  function set(next) {
    if (writable === false || (writable === "once" && state === 2)) {
      throw new TypeError("Cannot assign to final field " + name);
    }
    value = next;
    if (publish) publish(value);
    state = 2;
    return next;
  }
  return { get, set };
}

function __dartListAdd(list, value) {
  if (Array.isArray(list)) {
    list.push(value);
  } else if (list != null && typeof list.add === "function") {
    list.add(value);
  } else {
    const index = list.length;
    list.length = index + 1;
    __dartListLikeSet(list, index, value);
  }
  return null;
}

function __dartPrint(value) {
  console.log(__dartStr(value));
}

function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}

export class Holder {
  constructor(value) {
    const $lazyInstance = __dartLazyField("Holder.lazyInstance", () => init("instance", 30), true);
    Object.defineProperty(this, "lazyInstance", { get: function() {
      return $lazyInstance.get();
    }, set: function(value) {
      $lazyInstance.set(value);
    }, enumerable: true });
    const $assigned = __dartLazyField("Holder.assigned", null, true);
    Object.defineProperty(this, "assigned", { get: function() {
      return $assigned.get();
    }, set: function(value) {
      $assigned.set(value);
    }, enumerable: true });
    const $once = __dartLazyField("Holder.once", null, "once");
    Object.defineProperty(this, "once", { get: function() {
      return $once.get();
    }, set: function(value) {
      $once.set(value);
    }, enumerable: true });
    this.assigned = value;
    this.once = value + 1;
  }
  read() {
    return this.lazyInstance + this.assigned + this.once;
  }
}

const $Holder_lazyStatic = __dartLazyField("Holder.lazyStatic", () => init("static", 20), true);
Object.defineProperty(Holder, "lazyStatic", { get: function() {
  return $Holder_lazyStatic.get();
}, set: function(value) {
  $Holder_lazyStatic.set(value);
}, enumerable: true });
export let initCount = 0;
export let lazyTop;
const $static_lazyTop = __dartLazyField("lazyTop", () => init("top", 10), true, (value) => lazyTop = value);
export let assignTop;
const $static_assignTop = __dartLazyField("assignTop", null, true, (value) => assignTop = value);
export let finalTop;
const $static_finalTop = __dartLazyField("finalTop", null, "once", (value) => finalTop = value);
export function init(name, value) {
  __dartPrint(`init ${__dartStr(name)}`);
  initCount = initCount + 1;
  return value;
}

export function localLate() {
  const log = Array(0).fill(null);
  const initLocal = () => {
    __dartListAdd(log, "init local");
    return 3;
  };
  const _lazy_initializer = () => {
    return initLocal();
  };
  const lazy = __dartLazyField("lazy", () => _lazy_initializer(), true);
  const assigned = __dartLazyField("assigned", null, true);
  const once = __dartLazyField("once", null, "once");
  const readAssigned = () => {
    return String(assigned.get());
  };
  const writeOnce = (value) => {
    once.set(value);
  };
  let uninitializedBlocked = false;
  try {
    readAssigned();
  } catch ($error) {
    if ($error != null) {
      const __wc0_formal = $error;
      uninitializedBlocked = true;
    } else {
      throw $error;
    }
  }
  assigned.set(4);
  writeOnce(5);
  const first = lazy.get();
  const second = lazy.get();
  let onceBlocked = false;
  try {
    writeOnce(6);
  } catch ($error) {
    if ($error != null) {
      const __wc1_formal = $error;
      onceBlocked = true;
    } else {
      throw $error;
    }
  }
  return `local ${__dartStr(uninitializedBlocked)} ${__dartStr(first)} ${__dartStr(second)} ${__dartStr(assigned.get())} ${__dartStr(once.get())} ${__dartStr(onceBlocked)} ${__dartStr(__dartIterableToArray(log).join(","))}`;
}

export function main() {
  $static_assignTop.set(5);
  $static_finalTop.set(6);
  __dartPrint(`before ${__dartStr(initCount)}`);
  __dartPrint(`top ${__dartStr($static_lazyTop.get())}`);
  __dartPrint(`top again ${__dartStr($static_lazyTop.get())}`);
  __dartPrint(`assign ${__dartStr($static_assignTop.get())}`);
  __dartPrint(`final ${__dartStr($static_finalTop.get())}`);
  try {
    $static_finalTop.set(7);
  } catch ($error) {
    if ($error != null) {
      const __wc0_formal = $error;
      __dartPrint("final blocked");
    } else {
      throw $error;
    }
  }
  __dartPrint(`static ${__dartStr(Holder.lazyStatic)}`);
  const holder = new Holder(7);
  __dartPrint(`instance ${__dartStr(holder.read())}`);
  holder.assigned = 8;
  __dartPrint(`assigned ${__dartStr(holder.assigned)}`);
  try {
    holder.once = 9;
  } catch ($error) {
    if ($error != null) {
      const __wc1_formal = $error;
      __dartPrint("once blocked");
    } else {
      throw $error;
    }
  }
  __dartPrint(localLate());
  __dartPrint(`count ${__dartStr(initCount)}`);
}

main();
