function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}

// Generated by dart2esm.

export let initCount = 0;

export let readFirst = init("readFirst", 10);

export let assignFirst = init("assignFirst", 20);

export const finalValue = init("finalValue", 30);

export const constValue = 40;

export function init(name, value) {
  __dartPrint("init " + __dartStr(name));
  initCount = (initCount + 1);
  return value;
}

export function main() {
  const firstRead = readFirst;
  const firstAssign = assignFirst;
  const firstFinal = finalValue;
  assignFirst = 99;
  __dartPrint("initial " + __dartStr(firstAssign));
  __dartPrint("assigned " + __dartStr(assignFirst));
  __dartPrint("read " + __dartStr(firstRead));
  __dartPrint("read again " + __dartStr(readFirst));
  __dartPrint("final " + __dartStr(firstFinal));
  __dartPrint("const 40");
  __dartPrint("count " + __dartStr(initCount));
}

main();
