function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartObjectToString(value) {
  if (value == null) return "null";
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
    const typeName = value.constructor && value.constructor.name ? value.constructor.name : "Object";
    return "Instance of '" + typeName + "'";
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartAs(value, test, typeName) {
  if (test(value)) return value;
  throw new TypeError("Type cast failed: expected " + typeName);
}
function __dartCoreError(typeName, message) {
  const text = message == null ? "" : String(message);
  const display = text === "" ? typeName : typeName + ": " + text;
  const error = new Error(text);
  error.name = typeName;
  Object.defineProperty(error, "__dartCoreErrorType", { value: typeName });
  Object.defineProperty(error, "toString", { value() { return display; } });
  return error;
}
function __dartIsCoreError(value, typeName) {
  const actual = value == null ? null : value.__dartCoreErrorType;
  if (actual != null) {
    if (actual === typeName) return true;
    if (typeName === "Exception" && actual === "FormatException") return true;
    return typeName === "Error" && actual !== "Exception" && actual !== "FormatException";
  }
  if (typeName === "TypeError" && value instanceof TypeError) return true;
  return typeName === "Error" && value instanceof Error;
}
function __dartEquals(left, right) {
  if (left === right) return true;
  if (left == null || right == null) return false;
  const equals = left["=="];
  return typeof equals === "function" ? equals.call(left, right) : false;
}

// Generated by dart2esm.

export function classify(kind) {
  try {
    {
      if (__dartEquals(kind, "format")) {
        {
          (() => { throw __dartCoreError("FormatException", "bad"); })();
        }
      }
      if (__dartEquals(kind, "plain")) {
        {
          (() => { throw __dartCoreError("Exception", "plain"); })();
        }
      }
      if (__dartEquals(kind, "text")) {
        {
          (() => { throw "text"; })();
        }
      }
      let value = 1;
      __dartAs(value, value => typeof value === "string", "String");
      return "no error";
    }
  } catch ($error) {
    if (__dartIsCoreError($error, "FormatException")) {
      const error = $error;
      {
        return "format:" + __dartStr(__dartStr(error));
      }
    } else if (__dartIsCoreError($error, "Exception")) {
      const error_1 = $error;
      {
        return "exception:" + __dartStr(__dartObjectToString(error_1));
      }
    } else if (__dartIsCoreError($error, "Error")) {
      const __wc0_formal = $error;
      {
        return "error";
      }
    } else if ($error != null) {
      const error_2 = $error;
      {
        return "fallback:" + __dartStr(error_2);
      }
    } else {
      throw $error;
    }
  }
}

export function main() {
  __dartPrint(classify("format"));
  __dartPrint(classify("plain"));
  __dartPrint(classify("text"));
  __dartPrint(classify("cast"));
}

main();
