function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartEquals(left, right) {
  if (left === right) return true;
  if (left == null || right == null) return false;
  if ((typeof left === "number" || left.__dartType === "double") && (typeof right === "number" || right.__dartType === "double")) return Number(left) === Number(right);
  const equals = left["=="];
  return typeof equals === "function" ? equals.call(left, right) : false;
}

// Generated by dart2esm.

export class ParseIssue {
  constructor(message) {
    this.message = message;
  }
}

export class NotFound {
  constructor(path) {
    this.path = path;
  }
}

export class UnknownIssue {
  constructor(code) {
    this.code = code;
  }
}

export function classify(kind) {
  try {
    {
      if (__dartEquals(kind, "parse")) {
        {
          (() => { throw new ParseIssue("line"); })();
        }
      }
      if (__dartEquals(kind, "missing")) {
        {
          (() => { throw new NotFound("index"); })();
        }
      }
      if (__dartEquals(kind, "string")) {
        {
          (() => { throw "text"; })();
        }
      }
      (() => { throw new UnknownIssue("other"); })();
    }
  } catch ($error) {
    if ($error instanceof ParseIssue) {
      const error = $error;
      {
        return "parse:" + __dartStr(error.message);
      }
    } else if ($error instanceof NotFound) {
      const error_1 = $error;
      const stack = $error?.stack ?? "<javascript stack unavailable>";
      {
        return "missing:" + __dartStr(error_1.path) + ":" + __dartStr((__dartEquals(__dartStr(stack), "") ? "missing" : "trace"));
      }
    } else if (typeof $error === "string") {
      const error_2 = $error;
      {
        return "string:" + __dartStr(error_2);
      }
    } else if ($error != null) {
      const error_3 = $error;
      {
        return "fallback";
      }
    } else {
      throw $error;
    }
  }
}

export function runFinally() {
  let state = "start";
  try {
    try {
      {
        (() => { throw "boom"; })();
      }
    } catch ($error) {
      if ($error != null) {
        const error = $error;
        {
          __dartPrint("caught:" + __dartStr(state));
          state = "caught";
        }
      } else {
        throw $error;
      }
    }
  } finally {
    {
      __dartPrint("finally:" + __dartStr(state));
    }
  }
}

export function rethrowFlow() {
  try {
    {
      try {
        {
          (() => { throw new NotFound("inner"); })();
        }
      } catch ($error_1) {
        if ($error_1 instanceof ParseIssue) {
          {
            return "wrong";
          }
        } else if ($error_1 != null) {
          const error = $error_1;
          {
            (() => { throw $error_1; })();
          }
        } else {
          throw $error_1;
        }
      }
    }
  } catch ($error) {
    if ($error instanceof NotFound) {
      const error_1 = $error;
      {
        return "rethrow:" + __dartStr(error_1.path);
      }
    } else {
      throw $error;
    }
  }
}

export function main() {
  __dartPrint(classify("parse"));
  __dartPrint(classify("missing"));
  __dartPrint(classify("string"));
  __dartPrint(classify("unknown"));
  runFinally();
  __dartPrint(rethrowFlow());
}

main();
