function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartEquals(left, right) {
  if (left === right) return true;
  if (left == null || right == null) return false;
  const equals = left["=="];
  return typeof equals === "function" ? equals.call(left, right) : false;
}
function __dartIterator(iterable) {
  const values = Array.isArray(iterable) ? iterable : Array.from(iterable);
  let index = -1;
  return {
    current: undefined,
    moveNext() {
      index++;
      if (index < values.length) {
        this.current = values[index];
        return true;
      }
      this.current = undefined;
      return false;
    },
  };
}

// Generated by dart2esm.

export function main() {
  let total = 0;
  let i = 0;
  do {
    {
      total = (total + i);
      i = (i + 1);
    }
  } while ((i < 3));
  L:
  {
    let _sync_for_iterator = __dartIterator([1, 2, 3, 4]);
    for (; _sync_for_iterator.moveNext(); ) {
      {
        const value = _sync_for_iterator.current;
        L_1:
        {
          if (__dartEquals(value, 3)) {
            {
              break L_1;
            }
          }
          total = (total + value);
          if ((total > 6)) {
            {
              break L;
            }
          }
        }
      }
    }
  }
  L_2:
  switch (total) {
    case 6:
      {
        __dartPrint("six");
        break L_2;
      }
    case 7:
    case 8:
      {
        __dartPrint("seven/eight");
        break L_2;
      }
    default:
      {
        __dartPrint("other " + __dartStr(total));
      }
  }
  __dartPrint("total " + __dartStr(total));
}

main();
