const __dartRecordShape = Symbol("dart.recordShape");
function __dartIsRecord(value) {
  return value != null && typeof value === "object" && Array.isArray(value[__dartRecordShape]);
}
function __dartStr(value) {
  return value == null ? "null" : String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartEquals(left, right) {
  if (left === right) return true;
  if (__dartIsRecord(left) && __dartIsRecord(right)) {
    const leftShape = left[__dartRecordShape];
    const rightShape = right[__dartRecordShape];
    if (leftShape.length !== rightShape.length) return false;
    for (let i = 0; i < leftShape.length; i++) {
      const name = leftShape[i];
      if (name !== rightShape[i]) return false;
      if (!__dartEquals(left[name], right[name])) return false;
    }
    return true;
  }
  return false;
}
function __dartRecord(positional, named) {
  const record = {};
  const shape = [];
  for (let i = 0; i < positional.length; i++) {
    const name = "$" + (i + 1);
    shape.push(name);
    Object.defineProperty(record, name, { value: positional[i], enumerable: true });
  }
  for (const name of Object.keys(named).sort()) {
    shape.push(name);
    Object.defineProperty(record, name, { value: named[name], enumerable: true });
  }
  Object.defineProperty(record, __dartRecordShape, { value: Object.freeze(shape) });
  Object.defineProperty(record, "toString", {
    value() {
      return "(" + shape.map((name) => {
        const value = String(record[name]);
        return name.startsWith("$") ? value : name + ": " + value;
      }).join(", ") + ")";
    },
  });
  return Object.freeze(record);
}

// Generated by dart2esm.

export const fixedRecord = __dartRecord([4], { label: "four" });

export function makeNamed(value) {
  return __dartRecord([], { label: "v" + __dartStr(value), value: value });
}

export function makeMixed(value) {
  return __dartRecord([value], { label: "v" + __dartStr(value) });
}

export function main() {
  const pair = __dartRecord([1, "two"], {});
  __dartPrint("pair " + __dartStr(pair.$1) + " " + __dartStr(pair.$2));
  const named = makeNamed(2);
  __dartPrint("named " + __dartStr(named.label) + " " + __dartStr(named.value));
  const mixed = makeMixed(3);
  __dartPrint("mixed " + __dartStr(mixed.$1) + " " + __dartStr(mixed.label));
  __dartPrint("record " + __dartStr(mixed));
  __dartPrint("equals " + __dartStr(__dartEquals(mixed, __dartRecord([3], { label: "v3" }))));
  const ordered = (() => { let v = 1; return __dartRecord([], { a: 2, z: v }); })();
  __dartPrint("ordered " + __dartStr(ordered));
  __dartPrint("ordered equals " + __dartStr(__dartEquals(ordered, __dartRecord([], { a: 2, z: 1 }))));
}

main();
