function __dartStr(value) {
  return value == null ? "null" : String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}

// Generated by dart2esm.

export function helper(value) {
  __dartPrint("helper: " + __dartStr(value));
}

export function main() {
  const value = (40 + 2);
  helper("answer " + __dartStr(value));
}

main();
