function __dartStr(value) {
  return value == null ? "null" : String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}

// Generated by dart2esm.

export class Formatter {
  wrap(value, { left = "[", right = "]" } = {}) {
    return __dartStr(left) + __dartStr(value) + __dartStr(right);
  }
}

export function describe(name, punctuation = "!", repeat = 1) {
  let out = "";
  for (let i = 0; (i < repeat); i = (i + 1)) {
    {
      out = __dartStr(out) + __dartStr(name) + __dartStr(punctuation);
    }
  }
  return out;
}

export function tag(value, { prefix = "item", index } = {}) {
  return __dartStr(prefix) + ":" + __dartStr(index) + ":" + __dartStr(value);
}

export function main() {
  __dartPrint(describe("a"));
  __dartPrint(describe("b", "?", 2));
  __dartPrint(tag("x", { index: 3 }));
  __dartPrint(tag("y", { prefix: "custom", index: 4 }));
  const formatter = new Formatter();
  __dartPrint(formatter.wrap("z"));
  __dartPrint(formatter.wrap("z", { right: ")", left: "(" }));
}

main();
