// Generated by dart2esm.

function __dartCompare(left, right, compare = null) {
  if (typeof compare === "function") return Number(compare(left, right));
  const compareTo = left == null ? null : left.compareTo;
  if (typeof compareTo === "function") return Number(compareTo.call(left, right));
  return left < right ? -1 : left > right ? 1 : 0;
}

function __dartCoreError(typeName, message) {
  const text = message == null ? "" : String(message);
  const display = text === "" ? typeName : typeName + ": " + text;
  const error = new Error(text);
  error.name = typeName;
  Object.defineProperty(error, "__dartCoreErrorType", { value: typeName });
  Object.defineProperty(error, "toString", { value() { return display; } });
  return error;
}
function __dartIsCoreError(value, typeName) {
  const actual = value == null ? null : value.__dartCoreErrorType;
  if (actual != null) {
    if (actual === typeName) return true;
    if (typeName === "Exception" && actual === "FormatException") return true;
    if (typeName === "RangeError" && actual === "IndexError") return true;
    if (typeName === "ArgumentError" && (actual === "RangeError" || actual === "IndexError")) return true;
    return typeName === "Error" && actual !== "Exception" && actual !== "FormatException";
  }
  if (typeName === "TypeError" && value instanceof TypeError) return true;
  return typeName === "Error" && value instanceof Error;
}

const __dartConstValues = new Map();
function __dartConst(key, create) {
  if (!__dartConstValues.has(key)) {
    __dartConstValues.set(key, create());
  }
  return __dartConstValues.get(key);
}

function __dartCustomHashMap(equals = null, hashCode = null, isValidKey = null) {
  const map = new Map();
  Object.defineProperty(map, "__dartEqualityMap", { value: true });
  Object.defineProperty(map, "__dartMapEquals", { value: equals });
  Object.defineProperty(map, "__dartMapHashCode", { value: hashCode });
  Object.defineProperty(map, "__dartMapIsValidKey", { value: isValidKey });
  return map;
}

function __dartEquals(left, right) {
  if (left === right) return true;
  if (left == null || right == null) return false;
  if ((typeof left === "number" || left.__dartType === "double") && (typeof right === "number" || right.__dartType === "double")) return Number(left) === Number(right);
  if (__dartIsRecord(left) && __dartIsRecord(right)) {
    const leftShape = left[__dartRecordShape];
    const rightShape = right[__dartRecordShape];
    if (leftShape.length !== rightShape.length) return false;
    for (let i = 0; i < leftShape.length; i++) {
      const name = leftShape[i];
      if (name !== rightShape[i]) return false;
      if (!__dartEquals(left[name], right[name])) return false;
    }
    return true;
  }
  const equals = left["=="];
  return typeof equals === "function" ? equals.call(left, right) : false;
}

function __dartIterator(iterable) {
  const values = (iterable != null && typeof iterable["[]"] === "function" && typeof iterable.length === "number")
    ? { length: iterable.length, get(index) { return iterable["[]"](index); } }
    : Array.from(iterable);
  let index = -1;
  return {
    current: undefined,
    moveNext() {
      index++;
      if (index < values.length) {
        this.current = typeof values.get === "function" ? values.get(index) : values[index];
        return true;
      }
      this.current = undefined;
      return false;
    },
  };
}

function __dartLazyField(name, initialize, writable, publish = null) {
  let state = 0;
  let value;
  function get() {
    if (state === 2) return value;
    if (state === 1) {
      throw new Error("Cyclic initialization of field " + name);
    }
    if (initialize == null) {
      throw new Error("Late field " + name + " has not been initialized");
    }
    state = 1;
    try {
      value = initialize();
      if (publish) publish(value);
      state = 2;
      return value;
    } catch (error) {
      state = 0;
      throw error;
    }
  }
  function set(next) {
    if (writable === false || (writable === "once" && state === 2)) {
      throw new TypeError("Cannot assign to final field " + name);
    }
    value = next;
    if (publish) publish(value);
    state = 2;
    return next;
  }
  return { get, set };
}

function __dartListAdd(list, value) {
  list.push(value);
  return null;
}

function __dartListLikeGet(list, index) {
  if (Array.isArray(list) || ArrayBuffer.isView(list) || typeof list === "string") return list[index];
  const op = list == null ? null : list["[]"];
  return typeof op === "function" ? op.call(list, index) : list[index];
}
function __dartListLikeSet(list, index, value) {
  if (Array.isArray(list) || ArrayBuffer.isView(list)) {
    list[index] = value;
    return value;
  }
  const op = list == null ? null : list["[]="];
  if (typeof op === "function") return op.call(list, index, value);
  list[index] = value;
  return value;
}
function __dartListMixinFirst(list) {
  return __dartListLikeGet(list, 0);
}
function __dartListMixinLast(list) {
  return __dartListLikeGet(list, list.length - 1);
}
function __dartListMixinSingle(list) {
  if (list.length !== 1) throw __dartCoreError("StateError", "Too many elements");
  return __dartListLikeGet(list, 0);
}
function __dartListMixinInsert(list, index, value) {
  index = Number(index);
  const length = Number(list.length);
  list.length = length + 1;
  for (let i = length; i > index; i--) {
    __dartListLikeSet(list, i, __dartListLikeGet(list, i - 1));
  }
  __dartListLikeSet(list, index, value);
  return null;
}

function __dartListCopyRange(target, at, source, start = 0, end = null) {
  const values = Array.from(source).slice(Number(start), end == null ? undefined : Number(end));
  let index = Number(at);
  for (const value of values) target[index++] = value;
  return null;
}
function __dartListWriteIterable(target, at, source) {
  let index = Number(at);
  for (const value of source) target[index++] = value;
  return null;
}
function __dartListSetRange(target, start, end, source, skipCount = 0) {
  const from = Number(skipCount);
  const count = Number(end) - Number(start);
  const values = Array.from(source).slice(from, from + count);
  let index = Number(start);
  for (const value of values) target[index++] = value;
  return null;
}

function __dartMapAddAll(map, entries) {
  for (const [key, value] of entries) __dartMapSet(map, key, value);
  return null;
}

function __dartMapFromEntries(entries) {
  const map = new Map();
  Object.defineProperty(map, "__dartEqualityMap", { value: true });
  __dartMapAddAll(map, entries);
  return map;
}
function __dartMapFromIterable(iterable, key = null, value = null) {
  const map = new Map();
  Object.defineProperty(map, "__dartEqualityMap", { value: true });
  for (const element of iterable) {
    __dartMapSet(
      map,
      typeof key === "function" ? key(element) : element,
      typeof value === "function" ? value(element) : element,
    );
  }
  return map;
}
function __dartMapFromIterables(keys, values) {
  const keyList = Array.from(keys);
  const valueList = Array.from(values);
  if (keyList.length !== valueList.length) throw new Error("Iterables do not have same length");
  const map = new Map();
  Object.defineProperty(map, "__dartEqualityMap", { value: true });
  for (let index = 0; index < keyList.length; index++) {
    __dartMapSet(map, keyList[index], valueList[index]);
  }
  return map;
}

const __dartMapMissingKey = Symbol("dart.mapMissingKey");
function __dartMapKey(map, key) {
  if (typeof map.__dartSplayIsValidKey === "function" && !map.__dartSplayIsValidKey(key)) return __dartMapMissingKey;
  if (map.__dartSplayCompare !== undefined) {
    for (const candidate of map.keys()) {
      if (__dartCompare(candidate, key, map.__dartSplayCompare) === 0) return candidate;
    }
    return __dartMapMissingKey;
  }
  if (typeof map.__dartMapIsValidKey === "function" && !map.__dartMapIsValidKey(key)) return __dartMapMissingKey;
  if (typeof map.__dartMapEquals === "function") {
    for (const candidate of map.keys()) {
      if (map.__dartMapEquals(candidate, key)) return candidate;
    }
    return __dartMapMissingKey;
  }
  if (!map.__dartEqualityMap) return map.has(key) ? key : __dartMapMissingKey;
  for (const candidate of map.keys()) {
    if (__dartEquals(candidate, key)) return candidate;
  }
  return __dartMapMissingKey;
}
function __dartMapGet(map, key) {
  if (!(map instanceof Map) && map != null && typeof map["[]"] === "function") return map["[]"](key);
  const actualKey = __dartMapKey(map, key);
  return actualKey === __dartMapMissingKey ? null : map.get(actualKey);
}

function __dartMapSet(map, key, value) {
  const actualKey = __dartMapKey(map, key);
  map.set(actualKey === __dartMapMissingKey ? key : actualKey, value);
  if (map.__dartSplayCompare !== undefined) __dartSplaySortMap(map);
  return value;
}

function __dartNullCheck(value) {
  if (value == null) throw new TypeError("Null check operator used on a null value");
  return value;
}

const __dartIdentityHashes = new WeakMap();
let __dartNextIdentityHash = 1;
function __dartCombineHash(hash, value) {
  hash = (((hash + value) & 0x1fffffff) + (((hash & 0x0007ffff) << 10) & 0x1fffffff)) & 0x1fffffff;
  return hash ^ (hash >> 6);
}
function __dartFinishHash(hash) {
  hash = (((hash + (((hash & 0x03ffffff) << 3) & 0x1fffffff)) & 0x1fffffff) ^ (hash >> 11));
  return (hash + (((hash & 0x00003fff) << 15) & 0x1fffffff)) & 0x1fffffff;
}
function __dartHashValue(value) {
  if (value == null) return 0;
  if (typeof value === "boolean") return value ? 1231 : 1237;
  if (typeof value === "number") return Number.isFinite(value) ? Math.trunc(value) & 0x1fffffff : 0;
  if (value.__dartType === "double") {
    const number = Number(value);
    return Number.isFinite(number) ? Math.trunc(number) & 0x1fffffff : 0;
  }
  if (typeof value === "string") {
    let hash = 0;
    for (let i = 0; i < value.length; i++) hash = __dartCombineHash(hash, value.charCodeAt(i));
    return __dartFinishHash(hash);
  }
  if (typeof value === "bigint") return Number(value & 0x1fffffffn);
  if (!__dartIdentityHashes.has(value)) {
    __dartIdentityHashes.set(value, __dartNextIdentityHash);
    __dartNextIdentityHash = (__dartNextIdentityHash + 1) & 0x1fffffff || 1;
  }
  return __dartIdentityHashes.get(value);
}
function __dartObjectHash(values) {
  let hash = 0;
  for (const value of values) hash = __dartCombineHash(hash, __dartHashValue(value));
  return __dartFinishHash(hash);
}
function __dartObjectHashUnordered(values) {
  let sum = 0;
  let xor = 0;
  let count = 0;
  for (const value of values) {
    const hash = __dartHashValue(value);
    sum = (sum + hash) & 0x1fffffff;
    xor ^= hash;
    count++;
  }
  return __dartObjectHash([sum, xor, count]);
}

function __dartPrint(value) {
  console.log(__dartStr(value));
}

const __dartRecordShape = Symbol("dart.recordShape");

function __dartIsRecord(value) {
  return value != null && typeof value === "object" && Array.isArray(value[__dartRecordShape]);
}

function __dartSetContains(set, needle) {
  if (typeof set.__dartSplayIsValidKey === "function" && !set.__dartSplayIsValidKey(needle)) return false;
  if (set.__dartSplayCompare !== undefined) {
    for (const value of set) {
      if (__dartCompare(value, needle, set.__dartSplayCompare) === 0) return true;
    }
    return false;
  }
  if (!set.__dartEqualitySet) return set.has(needle);
  for (const value of set) {
    if (__dartEquals(value, needle)) return true;
  }
  return false;
}
function __dartSetAdd(set, value) {
  if (__dartSetContains(set, value)) return false;
  set.add(value);
  if (set.__dartSplayCompare !== undefined) __dartSplaySortSet(set);
  return true;
}
function __dartSetFrom(values) {
  const set = new Set();
  Object.defineProperty(set, "__dartEqualitySet", { value: true });
  for (const value of values) __dartSetAdd(set, value);
  return set;
}
function __dartSetAddAll(set, values) {
  for (const value of values) __dartSetAdd(set, value);
  return null;
}

function __dartSplayTreeSet(compare = null, isValidKey = null) {
  const set = new Set();
  Object.defineProperty(set, "__dartEqualitySet", { value: true });
  Object.defineProperty(set, "__dartSplayCompare", { value: compare });
  Object.defineProperty(set, "__dartSplayIsValidKey", { value: isValidKey });
  return set;
}
function __dartSplaySortSet(set) {
  const values = Array.from(set).sort((left, right) => __dartCompare(left, right, set.__dartSplayCompare));
  set.clear();
  for (const value of values) set.add(value);
}
function __dartSplayTreeSetFrom(values, compare = null, isValidKey = null) {
  const set = __dartSplayTreeSet(compare, isValidKey);
  for (const value of values) __dartSetAdd(set, value);
  return set;
}
function __dartSplayTreeMap(compare = null, isValidKey = null) {
  const map = new Map();
  Object.defineProperty(map, "__dartEqualityMap", { value: true });
  Object.defineProperty(map, "__dartSplayCompare", { value: compare });
  Object.defineProperty(map, "__dartSplayIsValidKey", { value: isValidKey });
  return map;
}
function __dartSplaySortMap(map) {
  const entries = Array.from(map).sort(([left], [right]) => __dartCompare(left, right, map.__dartSplayCompare));
  map.clear();
  for (const [key, value] of entries) map.set(key, value);
}
function __dartSplayTreeMapFromEntries(entries, compare = null, isValidKey = null) {
  const map = __dartSplayTreeMap(compare, isValidKey);
  for (const [key, value] of entries) __dartMapSet(map, key, value);
  return map;
}

function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}

function __dartAs(value, test, typeName) {
  if (test(value)) {
    return value;
  }
  throw new TypeError("Type cast failed: expected " + typeName);
}

const $Equality_interface = Symbol("Equality");
class Equality {
  constructor() {
    return new DefaultEquality();
  }
  equals(e1, e2) {
    throw new TypeError("Abstract member Equality.equals");
  }
  hash(e) {
    throw new TypeError("Abstract member Equality.hash");
  }
  isValidKey(o) {
    throw new TypeError("Abstract member Equality.isValidKey");
  }
}

Object.defineProperty(Equality, Symbol.hasInstance, { value: function(value) {
  return value != null && (Equality.prototype.isPrototypeOf(value) || value[$Equality_interface] === true);
} });
class DefaultEquality {
  constructor() {
    Object.defineProperty(this, $Equality_interface, { value: true });
  }
  equals(e1, e2) {
    return __dartEquals(e1, e2);
  }
  hash(e) {
    return __dartHashValue(e);
  }
  isValidKey(o) {
    return true;
  }
}

class IterableEquality {
  constructor(elementEquality = __dartConst("[\"InstanceConstant\",\"InstanceConstant(const DefaultEquality<Never>{})\"]", () => Object.freeze(Object.assign(Object.create(DefaultEquality.prototype), {  })))) {
    Object.defineProperty(this, "_elementEquality_package_collection_src_equality_dart", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "_elementEquality_package_collection_src_equality_dart", { value: elementEquality, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, $Equality_interface, { value: true });
  }
  equals(elements1, elements2) {
    if (Object.is(elements1, elements2)) {
      return true;
    }
    if ((elements1 === null || elements2 === null)) {
      return false;
    }
    let it1 = __dartIterator(elements1);
    let it2 = __dartIterator(elements2);
    while (true) {
      let hasNext = it1.moveNext();
      if (!(__dartEquals(hasNext, it2.moveNext()))) {
        return false;
      }
      if (!(hasNext)) {
        return true;
      }
      if (!(this._elementEquality_package_collection_src_equality_dart.equals(it1.current, it2.current))) {
        return false;
      }
    }
  }
  hash(elements) {
    if (elements === null) {
      return __dartHashValue(null);
    }
    let hash = 0;
    let _sync_for_iterator = __dartIterator(elements);
    for (; _sync_for_iterator.moveNext(); ) {
      let element = _sync_for_iterator.current;
      let c = this._elementEquality_package_collection_src_equality_dart.hash(element);
      hash = hash + c & 2147483647;
      hash = hash + (hash << 10) & 2147483647;
      hash = hash ^ hash >> 6;
    }
    hash = hash + (hash << 3) & 2147483647;
    hash = hash ^ hash >> 11;
    hash = hash + (hash << 15) & 2147483647;
    return hash;
  }
  isValidKey(o) {
    return (((o != null && typeof o !== "string") && !(o instanceof Map)) && typeof o[Symbol.iterator] === "function");
  }
}

class ListEquality {
  constructor(elementEquality = __dartConst("[\"InstanceConstant\",\"InstanceConstant(const DefaultEquality<Never>{})\"]", () => Object.freeze(Object.assign(Object.create(DefaultEquality.prototype), {  })))) {
    Object.defineProperty(this, "_elementEquality_package_collection_src_equality_dart", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "_elementEquality_package_collection_src_equality_dart", { value: elementEquality, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, $Equality_interface, { value: true });
  }
  equals(list1, list2) {
    if (Object.is(list1, list2)) {
      return true;
    }
    if ((list1 === null || list2 === null)) {
      return false;
    }
    let length = list1.length;
    if (!(__dartEquals(length, list2.length))) {
      return false;
    }
    for (let i = 0; i < length; i = i + 1) {
      if (!(this._elementEquality_package_collection_src_equality_dart.equals(__dartListLikeGet(list1, i), __dartListLikeGet(list2, i)))) {
        return false;
      }
    }
    return true;
  }
  hash(list) {
    if (list === null) {
      return __dartHashValue(null);
    }
    let hash = 0;
    for (let i = 0; i < list.length; i = i + 1) {
      let c = this._elementEquality_package_collection_src_equality_dart.hash(__dartListLikeGet(list, i));
      hash = hash + c & 2147483647;
      hash = hash + (hash << 10) & 2147483647;
      hash = hash ^ hash >> 6;
    }
    hash = hash + (hash << 3) & 2147483647;
    hash = hash ^ hash >> 11;
    hash = hash + (hash << 15) & 2147483647;
    return hash;
  }
  isValidKey(o) {
    return (Array.isArray(o) || (ArrayBuffer.isView(o) && !(o instanceof DataView)));
  }
}

const $_UnorderedEquality_interface = Symbol("_UnorderedEquality");
class _UnorderedEquality {
  constructor(_elementEquality) {
    Object.defineProperty(this, "_elementEquality_package_collection_src_equality_dart", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "_elementEquality_package_collection_src_equality_dart", { value: _elementEquality, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, $Equality_interface, { value: true });
  }
  equals(elements1, elements2) {
    if (Object.is(elements1, elements2)) {
      return true;
    }
    if ((elements1 === null || elements2 === null)) {
      return false;
    }
    let counts = __dartCustomHashMap(__dartAs((function() {
      const $receiver = this._elementEquality_package_collection_src_equality_dart;
      return function(e1, e2) {
        return $receiver.equals(e1, e2);
      };
    })(), (value) => typeof value === "function", "FunctionType(bool Function(_UnorderedEquality.E%, _UnorderedEquality.E%))"), __dartAs((function() {
      const $receiver = this._elementEquality_package_collection_src_equality_dart;
      return function(e) {
        return $receiver.hash(e);
      };
    })(), (value) => typeof value === "function", "FunctionType(int Function(_UnorderedEquality.E%))"), (function() {
      const $receiver = this._elementEquality_package_collection_src_equality_dart;
      return function(o) {
        return $receiver.isValidKey(o);
      };
    })());
    let length = 0;
    let _sync_for_iterator = __dartIterator(elements1);
    for (; _sync_for_iterator.moveNext(); ) {
      let e = _sync_for_iterator.current;
      let count = (__dartMapGet(counts, e) ?? 0);
      __dartMapSet(counts, e, count + 1);
      length = length + 1;
    }
    let _sync_for_iterator_1 = __dartIterator(elements2);
    for (; _sync_for_iterator_1.moveNext(); ) {
      let e_1 = _sync_for_iterator_1.current;
      let count_1 = __dartMapGet(counts, e_1);
      if ((count_1 === null || __dartEquals(count_1, 0))) {
        return false;
      }
      __dartMapSet(counts, e_1, count_1 - 1);
      length = length - 1;
    }
    return __dartEquals(length, 0);
  }
  hash(elements) {
    if (elements === null) {
      return __dartHashValue(null);
    }
    let hash = 0;
    let _sync_for_iterator = __dartIterator(elements);
    for (; _sync_for_iterator.moveNext(); ) {
      let element = _sync_for_iterator.current;
      let c = this._elementEquality_package_collection_src_equality_dart.hash(element);
      hash = hash + c & 2147483647;
    }
    hash = hash + (hash << 3) & 2147483647;
    hash = hash ^ hash >> 11;
    hash = hash + (hash << 15) & 2147483647;
    return hash;
  }
}

Object.defineProperty(_UnorderedEquality, Symbol.hasInstance, { value: function(value) {
  return value != null && (_UnorderedEquality.prototype.isPrototypeOf(value) || value[$_UnorderedEquality_interface] === true);
} });
class UnorderedIterableEquality extends _UnorderedEquality {
  constructor(elementEquality = __dartConst("[\"InstanceConstant\",\"InstanceConstant(const DefaultEquality<Never>{})\"]", () => Object.freeze(Object.assign(Object.create(DefaultEquality.prototype), {  })))) {
    super(elementEquality);
  }
  isValidKey(o) {
    return (((o != null && typeof o !== "string") && !(o instanceof Map)) && typeof o[Symbol.iterator] === "function");
  }
}

class SetEquality extends _UnorderedEquality {
  constructor(elementEquality = __dartConst("[\"InstanceConstant\",\"InstanceConstant(const DefaultEquality<Never>{})\"]", () => Object.freeze(Object.assign(Object.create(DefaultEquality.prototype), {  })))) {
    super(elementEquality);
  }
  isValidKey(o) {
    return o instanceof Set;
  }
}

class _MapEntry {
  constructor(equality, key, value) {
    Object.defineProperty(this, "equality", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "key", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "value", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "equality", { value: equality, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "key", { value: key, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "value", { value: value, writable: true, enumerable: true, configurable: true });
  }
  get hashCode() {
    return 3 * this.equality._keyEquality_package_collection_src_equality_dart.hash(this.key) + 7 * this.equality._valueEquality_package_collection_src_equality_dart.hash(this.value) & 2147483647;
  }
  "=="(other) {
    return ((other instanceof _MapEntry && this.equality._keyEquality_package_collection_src_equality_dart.equals(this.key, other.key)) && this.equality._valueEquality_package_collection_src_equality_dart.equals(this.value, other.value));
  }
}

class MapEquality {
  constructor({ keys = __dartConst("[\"InstanceConstant\",\"InstanceConstant(const DefaultEquality<Never>{})\"]", () => Object.freeze(Object.assign(Object.create(DefaultEquality.prototype), {  }))), values = __dartConst("[\"InstanceConstant\",\"InstanceConstant(const DefaultEquality<Never>{})\"]", () => Object.freeze(Object.assign(Object.create(DefaultEquality.prototype), {  }))) } = {}) {
    Object.defineProperty(this, "_keyEquality_package_collection_src_equality_dart", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "_valueEquality_package_collection_src_equality_dart", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "_keyEquality_package_collection_src_equality_dart", { value: keys, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "_valueEquality_package_collection_src_equality_dart", { value: values, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, $Equality_interface, { value: true });
  }
  equals(map1, map2) {
    if (Object.is(map1, map2)) {
      return true;
    }
    if ((map1 === null || map2 === null)) {
      return false;
    }
    let length = map1.size;
    if (!(__dartEquals(length, map2.size))) {
      return false;
    }
    let equalElementCounts = __dartCustomHashMap(null, null, null);
    let _sync_for_iterator = __dartIterator(Array.from(map1.keys()));
    for (; _sync_for_iterator.moveNext(); ) {
      let key = _sync_for_iterator.current;
      let entry = new _MapEntry(this, key, __dartMapGet(map1, key));
      let count = (__dartMapGet(equalElementCounts, entry) ?? 0);
      __dartMapSet(equalElementCounts, entry, count + 1);
    }
    let _sync_for_iterator_1 = __dartIterator(Array.from(map2.keys()));
    for (; _sync_for_iterator_1.moveNext(); ) {
      let key_1 = _sync_for_iterator_1.current;
      let entry_1 = new _MapEntry(this, key_1, __dartMapGet(map2, key_1));
      let count_1 = __dartMapGet(equalElementCounts, entry_1);
      if ((count_1 === null || __dartEquals(count_1, 0))) {
        return false;
      }
      __dartMapSet(equalElementCounts, entry_1, count_1 - 1);
    }
    return true;
  }
  hash(map) {
    if (map === null) {
      return __dartHashValue(null);
    }
    let hash = 0;
    let _sync_for_iterator = __dartIterator(Array.from(map.keys()));
    for (; _sync_for_iterator.moveNext(); ) {
      let key = _sync_for_iterator.current;
      let keyHash = this._keyEquality_package_collection_src_equality_dart.hash(key);
      let valueHash = this._valueEquality_package_collection_src_equality_dart.hash((() => {
        let v = __dartMapGet(map, key);
        return (v === null ? __dartAs(v, (value) => true, "TypeParameterType(MapEquality.V%)") : v);
      })());
      hash = hash + 3 * keyHash + 7 * valueHash & 2147483647;
    }
    hash = hash + (hash << 3) & 2147483647;
    hash = hash ^ hash >> 11;
    hash = hash + (hash << 15) & 2147483647;
    return hash;
  }
  isValidKey(o) {
    return o instanceof Map;
  }
}

class DeepCollectionEquality {
  constructor(base = __dartConst("[\"InstanceConstant\",\"InstanceConstant(const DefaultEquality<Never>{})\"]", () => Object.freeze(Object.assign(Object.create(DefaultEquality.prototype), {  })))) {
    Object.defineProperty(this, "_base_package_collection_src_equality_dart", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "_unordered_package_collection_src_equality_dart", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "_base_package_collection_src_equality_dart", { value: base, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "_unordered_package_collection_src_equality_dart", { value: false, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, $Equality_interface, { value: true });
  }
  static unordered(base = __dartConst("[\"InstanceConstant\",\"InstanceConstant(const DefaultEquality<Never>{})\"]", () => Object.freeze(Object.assign(Object.create(DefaultEquality.prototype), {  })))) {
    const $self = Object.create(this.prototype);
    Object.defineProperty($self, "_base_package_collection_src_equality_dart", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty($self, "_unordered_package_collection_src_equality_dart", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty($self, "_base_package_collection_src_equality_dart", { value: base, writable: true, enumerable: true, configurable: true });
    Object.defineProperty($self, "_unordered_package_collection_src_equality_dart", { value: true, writable: true, enumerable: true, configurable: true });
    Object.defineProperty($self, $Equality_interface, { value: true });
    return $self;
  }
  equals(e1, e2) {
    if (e1 instanceof Set) {
      return (e2 instanceof Set && new SetEquality(this).equals(e1, e2));
    }
    if (e1 instanceof Map) {
      return (e2 instanceof Map && new MapEquality({ keys: this, values: this }).equals(e1, e2));
    }
    if (!(this._unordered_package_collection_src_equality_dart)) {
      if ((Array.isArray(e1) || (ArrayBuffer.isView(e1) && !(e1 instanceof DataView)))) {
        return ((Array.isArray(e2) || (ArrayBuffer.isView(e2) && !(e2 instanceof DataView))) && new ListEquality(this).equals(e1, e2));
      }
      if ((((e1 != null && typeof e1 !== "string") && !(e1 instanceof Map)) && typeof e1[Symbol.iterator] === "function")) {
        return ((((e2 != null && typeof e2 !== "string") && !(e2 instanceof Map)) && typeof e2[Symbol.iterator] === "function") && new IterableEquality(this).equals(e1, e2));
      }
    } else {
      if ((((e1 != null && typeof e1 !== "string") && !(e1 instanceof Map)) && typeof e1[Symbol.iterator] === "function")) {
        if (!(__dartEquals((Array.isArray(e1) || (ArrayBuffer.isView(e1) && !(e1 instanceof DataView))), (Array.isArray(e2) || (ArrayBuffer.isView(e2) && !(e2 instanceof DataView)))))) {
          return false;
        }
        return ((((e2 != null && typeof e2 !== "string") && !(e2 instanceof Map)) && typeof e2[Symbol.iterator] === "function") && new UnorderedIterableEquality(this).equals(e1, e2));
      }
    }
    return this._base_package_collection_src_equality_dart.equals(e1, e2);
  }
  hash(o) {
    if (o instanceof Set) {
      return new SetEquality(this).hash(o);
    }
    if (o instanceof Map) {
      return new MapEquality({ keys: this, values: this }).hash(o);
    }
    if (!(this._unordered_package_collection_src_equality_dart)) {
      if ((Array.isArray(o) || (ArrayBuffer.isView(o) && !(o instanceof DataView)))) {
        return new ListEquality(this).hash(o);
      }
      if ((((o != null && typeof o !== "string") && !(o instanceof Map)) && typeof o[Symbol.iterator] === "function")) {
        return new IterableEquality(this).hash(o);
      }
    } else {
      if ((((o != null && typeof o !== "string") && !(o instanceof Map)) && typeof o[Symbol.iterator] === "function")) {
        return new UnorderedIterableEquality(this).hash(o);
      }
    }
    return this._base_package_collection_src_equality_dart.hash(o);
  }
  isValidKey(o) {
    return (((((o != null && typeof o !== "string") && !(o instanceof Map)) && typeof o[Symbol.iterator] === "function") || o instanceof Map) || this._base_package_collection_src_equality_dart.isValidKey(o));
  }
}

const $PriorityQueue_interface = Symbol("PriorityQueue");
class PriorityQueue {
  constructor(comparison = null) {
    return new HeapPriorityQueue(comparison);
  }
  get length() {
    throw new TypeError("Abstract member PriorityQueue.length");
  }
  get isEmpty() {
    throw new TypeError("Abstract member PriorityQueue.isEmpty");
  }
  get isNotEmpty() {
    throw new TypeError("Abstract member PriorityQueue.isNotEmpty");
  }
  contains(object) {
    throw new TypeError("Abstract member PriorityQueue.contains");
  }
  get unorderedElements() {
    throw new TypeError("Abstract member PriorityQueue.unorderedElements");
  }
  add(element) {
    throw new TypeError("Abstract member PriorityQueue.add");
  }
  addAll(elements) {
    throw new TypeError("Abstract member PriorityQueue.addAll");
  }
  get first() {
    throw new TypeError("Abstract member PriorityQueue.first");
  }
  removeFirst() {
    throw new TypeError("Abstract member PriorityQueue.removeFirst");
  }
  remove(element) {
    throw new TypeError("Abstract member PriorityQueue.remove");
  }
  removeAll() {
    throw new TypeError("Abstract member PriorityQueue.removeAll");
  }
  clear() {
    throw new TypeError("Abstract member PriorityQueue.clear");
  }
  toList() {
    throw new TypeError("Abstract member PriorityQueue.toList");
  }
  toUnorderedList() {
    throw new TypeError("Abstract member PriorityQueue.toUnorderedList");
  }
  toSet() {
    throw new TypeError("Abstract member PriorityQueue.toSet");
  }
}

Object.defineProperty(PriorityQueue, Symbol.hasInstance, { value: function(value) {
  return value != null && (PriorityQueue.prototype.isPrototypeOf(value) || value[$PriorityQueue_interface] === true);
} });
class HeapPriorityQueue {
  constructor(comparison = null) {
    Object.defineProperty(this, "comparison", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "_queue_package_collection_src_priority_queue_dart", { value: Array(7).fill(null), writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "_length_package_collection_src_priority_queue_dart", { value: 0, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "_modificationCount_package_collection_src_priority_queue_dart", { value: 0, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "comparison", { value: (comparison ?? defaultCompare), writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, $PriorityQueue_interface, { value: true });
  }
  _elementAt_package_collection_src_priority_queue_dart(index) {
    return (__dartListLikeGet(this._queue_package_collection_src_priority_queue_dart, index) ?? (() => {
      let v = null;
      return (v === null ? __dartAs(v, (value) => true, "TypeParameterType(HeapPriorityQueue.E%)") : v);
    })());
  }
  add(element) {
    this._modificationCount_package_collection_src_priority_queue_dart = this._modificationCount_package_collection_src_priority_queue_dart + 1;
    this._add_package_collection_src_priority_queue_dart(element);
  }
  addAll(elements) {
    let modified = 0;
    let _sync_for_iterator = __dartIterator(elements);
    for (; _sync_for_iterator.moveNext(); ) {
      let element = _sync_for_iterator.current;
      modified = 1;
      this._add_package_collection_src_priority_queue_dart(element);
    }
    this._modificationCount_package_collection_src_priority_queue_dart = this._modificationCount_package_collection_src_priority_queue_dart + modified;
  }
  clear() {
    this._modificationCount_package_collection_src_priority_queue_dart = this._modificationCount_package_collection_src_priority_queue_dart + 1;
    this._queue_package_collection_src_priority_queue_dart = __dartConst("[\"list\",\"NeverType(Never)\"]", () => Object.freeze([]));
    this._length_package_collection_src_priority_queue_dart = 0;
  }
  contains(object) {
    return this._locate_package_collection_src_priority_queue_dart(object) >= 0;
  }
  get unorderedElements() {
    return new _UnorderedElementsIterable(this);
  }
  get first() {
    if (__dartEquals(this._length_package_collection_src_priority_queue_dart, 0)) {
      throw __dartCoreError("StateError", "No element");
    }
    return this._elementAt_package_collection_src_priority_queue_dart(0);
  }
  get isEmpty() {
    return __dartEquals(this._length_package_collection_src_priority_queue_dart, 0);
  }
  get isNotEmpty() {
    return !(__dartEquals(this._length_package_collection_src_priority_queue_dart, 0));
  }
  get length() {
    return this._length_package_collection_src_priority_queue_dart;
  }
  remove(element) {
    let index = this._locate_package_collection_src_priority_queue_dart(element);
    if (index < 0) {
      return false;
    }
    this._modificationCount_package_collection_src_priority_queue_dart = this._modificationCount_package_collection_src_priority_queue_dart + 1;
    let last = this._removeLast_package_collection_src_priority_queue_dart();
    if (index < this._length_package_collection_src_priority_queue_dart) {
      let comp = (() => {
        const v = last;
        return (() => {
          const v_1 = element;
          return this.comparison(v, v_1);
        })();
      })();
      if (comp <= 0) {
        this._bubbleUp_package_collection_src_priority_queue_dart(last, index);
      } else {
        this._bubbleDown_package_collection_src_priority_queue_dart(last, index);
      }
    }
    return true;
  }
  removeAll() {
    this._modificationCount_package_collection_src_priority_queue_dart = this._modificationCount_package_collection_src_priority_queue_dart + 1;
    let result = this._queue_package_collection_src_priority_queue_dart;
    let length = this._length_package_collection_src_priority_queue_dart;
    this._queue_package_collection_src_priority_queue_dart = __dartConst("[\"list\",\"NeverType(Never)\"]", () => Object.freeze([]));
    this._length_package_collection_src_priority_queue_dart = 0;
    return Array.from(result).slice(0, length);
  }
  removeFirst() {
    if (__dartEquals(this._length_package_collection_src_priority_queue_dart, 0)) {
      throw __dartCoreError("StateError", "No element");
    }
    this._modificationCount_package_collection_src_priority_queue_dart = this._modificationCount_package_collection_src_priority_queue_dart + 1;
    let result = this._elementAt_package_collection_src_priority_queue_dart(0);
    let last = this._removeLast_package_collection_src_priority_queue_dart();
    if (this._length_package_collection_src_priority_queue_dart > 0) {
      this._bubbleDown_package_collection_src_priority_queue_dart(last, 0);
    }
    return result;
  }
  toList() {
    return (() => {
      const v = this._toUnorderedList_package_collection_src_priority_queue_dart();
      return (() => {
        v.sort((left, right) => __dartCompare(left, right, this.comparison));
        return v;
      })();
    })();
  }
  toSet() {
    let set = __dartSplayTreeSet(this.comparison, null);
    for (let i = 0; i < this._length_package_collection_src_priority_queue_dart; i = i + 1) {
      __dartSetAdd(set, this._elementAt_package_collection_src_priority_queue_dart(i));
    }
    return set;
  }
  toUnorderedList() {
    return this._toUnorderedList_package_collection_src_priority_queue_dart();
  }
  _toUnorderedList_package_collection_src_priority_queue_dart() {
    return (() => {
      const v = Array(0).fill(null);
      for (let i = 0; i < this._length_package_collection_src_priority_queue_dart; i = i + 1) {
        __dartListAdd(v, this._elementAt_package_collection_src_priority_queue_dart(i));
      }
      return v;
    })();
  }
  toString() {
    return String(Array.from(this._queue_package_collection_src_priority_queue_dart).slice(0, this._length_package_collection_src_priority_queue_dart));
  }
  _add_package_collection_src_priority_queue_dart(element) {
    if (__dartEquals(this._length_package_collection_src_priority_queue_dart, this._queue_package_collection_src_priority_queue_dart.length)) {
      this._grow_package_collection_src_priority_queue_dart();
    }
    this._bubbleUp_package_collection_src_priority_queue_dart(element, (() => {
      const v = this._length_package_collection_src_priority_queue_dart;
      return (() => {
        const v_1 = this._length_package_collection_src_priority_queue_dart = v + 1;
        return v;
      })();
    })());
  }
  _locate_package_collection_src_priority_queue_dart(object) {
    if (__dartEquals(this._length_package_collection_src_priority_queue_dart, 0)) {
      return -1;
    }
    let position = 1;
    do {
      label: {
        let index = position - 1;
        let element = this._elementAt_package_collection_src_priority_queue_dart(index);
        let comp = (() => {
          const v = element;
          return (() => {
            const v_1 = object;
            return this.comparison(v, v_1);
          })();
        })();
        if (comp <= 0) {
          if ((__dartEquals(comp, 0) && __dartEquals(element, object))) {
            return index;
          }
          let leftChildPosition = position * 2;
          if (leftChildPosition <= this._length_package_collection_src_priority_queue_dart) {
            position = leftChildPosition;
            break label;
          }
        }
        do {
          while (Math.trunc(position) % 2 !== 0) {
            position = position >> 1;
          }
          position = position + 1;
        } while (position > this._length_package_collection_src_priority_queue_dart);
      }
    } while (!(__dartEquals(position, 1)));
    return -1;
  }
  _removeLast_package_collection_src_priority_queue_dart() {
    let newLength = this._length_package_collection_src_priority_queue_dart - 1;
    let last = this._elementAt_package_collection_src_priority_queue_dart(newLength);
    __dartListLikeSet(this._queue_package_collection_src_priority_queue_dart, newLength, null);
    this._length_package_collection_src_priority_queue_dart = newLength;
    return last;
  }
  _bubbleUp_package_collection_src_priority_queue_dart(element, index) {
    label: {
      while (index > 0) {
        let parentIndex = Math.trunc((index - 1) / 2);
        let parent = this._elementAt_package_collection_src_priority_queue_dart(parentIndex);
        if ((() => {
          const v = element;
          return (() => {
            const v_1 = parent;
            return this.comparison(v, v_1);
          })();
        })() > 0) {
          break label;
        }
        __dartListLikeSet(this._queue_package_collection_src_priority_queue_dart, index, parent);
        index = parentIndex;
      }
    }
    __dartListLikeSet(this._queue_package_collection_src_priority_queue_dart, index, element);
  }
  _bubbleDown_package_collection_src_priority_queue_dart(element, index) {
    let rightChildIndex = index * 2 + 2;
    while (rightChildIndex < this._length_package_collection_src_priority_queue_dart) {
      let leftChildIndex = rightChildIndex - 1;
      let leftChild = this._elementAt_package_collection_src_priority_queue_dart(leftChildIndex);
      let rightChild = this._elementAt_package_collection_src_priority_queue_dart(rightChildIndex);
      let comp = (() => {
        const v = leftChild;
        return (() => {
          const v_1 = rightChild;
          return this.comparison(v, v_1);
        })();
      })();
      let minChildIndex = null;
      let minChild = null;
      if (comp < 0) {
        minChild = leftChild;
        minChildIndex = leftChildIndex;
      } else {
        minChild = rightChild;
        minChildIndex = rightChildIndex;
      }
      comp = (() => {
        const v = element;
        return (() => {
          const v_1 = minChild;
          return this.comparison(v, v_1);
        })();
      })();
      if (comp <= 0) {
        __dartListLikeSet(this._queue_package_collection_src_priority_queue_dart, index, element);
        return;
      }
      __dartListLikeSet(this._queue_package_collection_src_priority_queue_dart, index, minChild);
      index = minChildIndex;
      rightChildIndex = index * 2 + 2;
    }
    let leftChildIndex_1 = rightChildIndex - 1;
    if (leftChildIndex_1 < this._length_package_collection_src_priority_queue_dart) {
      let child = this._elementAt_package_collection_src_priority_queue_dart(leftChildIndex_1);
      let comp_1 = (() => {
        const v = element;
        return (() => {
          const v_1 = child;
          return this.comparison(v, v_1);
        })();
      })();
      if (comp_1 > 0) {
        __dartListLikeSet(this._queue_package_collection_src_priority_queue_dart, index, child);
        index = leftChildIndex_1;
      }
    }
    __dartListLikeSet(this._queue_package_collection_src_priority_queue_dart, index, element);
  }
  _grow_package_collection_src_priority_queue_dart() {
    let newCapacity = this._queue_package_collection_src_priority_queue_dart.length * 2 + 1;
    if (newCapacity < 7) {
      newCapacity = 7;
    }
    let newQueue = Array(newCapacity).fill(null);
    __dartListSetRange(newQueue, 0, this._length_package_collection_src_priority_queue_dart, this._queue_package_collection_src_priority_queue_dart);
    this._queue_package_collection_src_priority_queue_dart = newQueue;
  }
}

const $HeapPriorityQueue__initialCapacity = __dartLazyField("HeapPriorityQueue._initialCapacity", () => 7, false);
Object.defineProperty(HeapPriorityQueue, "_initialCapacity_package_collection_src_priority_queue_dart", { get: function() {
  return $HeapPriorityQueue__initialCapacity.get();
}, set: function(value) {
  $HeapPriorityQueue__initialCapacity.set(value);
}, enumerable: true });
class _UnorderedElementsIterable {
  constructor(_queue) {
    Object.defineProperty(this, "_queue_package_collection_src_priority_queue_dart", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "_queue_package_collection_src_priority_queue_dart", { value: _queue, writable: true, enumerable: true, configurable: true });
  }
  get iterator() {
    return new _UnorderedElementsIterator(this._queue_package_collection_src_priority_queue_dart);
  }
}

class _UnorderedElementsIterator {
  constructor(_queue) {
    Object.defineProperty(this, "_queue_package_collection_src_priority_queue_dart", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "_initialModificationCount_package_collection_src_priority_queue_dart", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "_current_package_collection_src_priority_queue_dart", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "_index_package_collection_src_priority_queue_dart", { value: -1, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "_queue_package_collection_src_priority_queue_dart", { value: _queue, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "_initialModificationCount_package_collection_src_priority_queue_dart", { value: _queue._modificationCount_package_collection_src_priority_queue_dart, writable: true, enumerable: true, configurable: true });
  }
  moveNext() {
    if (!(__dartEquals(this._initialModificationCount_package_collection_src_priority_queue_dart, this._queue_package_collection_src_priority_queue_dart._modificationCount_package_collection_src_priority_queue_dart))) {
      throw __dartCoreError("ConcurrentModificationError", this._queue_package_collection_src_priority_queue_dart);
    }
    let nextIndex = this._index_package_collection_src_priority_queue_dart + 1;
    if ((0 <= nextIndex && nextIndex < this._queue_package_collection_src_priority_queue_dart.length)) {
      this._current_package_collection_src_priority_queue_dart = __dartListLikeGet(this._queue_package_collection_src_priority_queue_dart._queue_package_collection_src_priority_queue_dart, nextIndex);
      this._index_package_collection_src_priority_queue_dart = nextIndex;
      return true;
    }
    this._current_package_collection_src_priority_queue_dart = null;
    this._index_package_collection_src_priority_queue_dart = -2;
    return false;
  }
  get current() {
    return (this._index_package_collection_src_priority_queue_dart < 0 ? (() => {
      throw __dartCoreError("StateError", "No element");
    })() : (this._current_package_collection_src_priority_queue_dart ?? (() => {
      let v = null;
      return (v === null ? __dartAs(v, (value) => true, "TypeParameterType(_UnorderedElementsIterator.E%)") : v);
    })()));
  }
}

function defaultCompare(value1, value2) {
  return __dartCompare(__dartAs(value1, (value) => (value != null && (((typeof value === "number" || typeof value === "string") || typeof value === "bigint") || typeof value.compareTo === "function")), "Comparable"), value2);
}

function groupBy(values, key) {
  let map = __dartMapFromEntries([]);
  let _sync_for_iterator = __dartIterator(values);
  for (; _sync_for_iterator.moveNext(); ) {
    let element = _sync_for_iterator.current;
    __dartListAdd((() => {
      const v = map;
      return (() => {
        const v_1 = key(element);
        return (__dartMapGet(v, v_1) ?? (() => {
          const v_2 = Array(0).fill(null);
          return (() => {
            const v_3 = __dartMapSet(v, v_1, v_2);
            return v_2;
          })();
        })());
      })();
    })(), element);
  }
  return map;
}

function IterableExtension_firstWhereOrNull(_this, test) {
  let _sync_for_iterator = __dartIterator(_this);
  for (; _sync_for_iterator.moveNext(); ) {
    let element = _sync_for_iterator.current;
    if (test(element)) {
      return element;
    }
  }
  return null;
}

export function main() {
  const numbers = [1, 2, 3, 4, 5];
  const firstEven = IterableExtension_firstWhereOrNull(numbers, (value) => {
    return Math.trunc(value) % 2 === 0;
  });
  const groups = groupBy(["aa", "b", "cc", "d"], (value) => {
    return value.length;
  });
  const deepEqual = __dartConst("[\"InstanceConstant\",\"InstanceConstant(const DeepCollectionEquality{DeepCollectionEquality._base: const DefaultEquality<Never>{}, DeepCollectionEquality._unordered: false})\"]", () => Object.freeze(Object.assign(Object.create(DeepCollectionEquality.prototype), { _base_package_collection_src_equality_dart: __dartConst("[\"InstanceConstant\",\"InstanceConstant(const DefaultEquality<Never>{})\"]", () => Object.freeze(Object.assign(Object.create(DefaultEquality.prototype), {  }))), _unordered_package_collection_src_equality_dart: false }))).equals(__dartMapFromEntries([["a", [1, 2]]]), __dartMapFromEntries([["a", [1, 2]]]));
  const queue = (() => {
    const v = new HeapPriorityQueue();
    return (() => {
      v.addAll([3, 1, 2]);
      return v;
    })();
  })();
  const ordered = [queue.removeFirst(), queue.removeFirst(), queue.removeFirst()];
  __dartPrint(`collection ${__dartStr(firstEven)} ${__dartStr(Array.from(__dartNullCheck(__dartMapGet(groups, 2))).join("|"))} ${__dartStr(deepEqual)} ${__dartStr(Array.from(ordered).join(","))}`);
}

main();
