const __dartRecordShape = Symbol("dart.recordShape");
function __dartIsRecord(value) {
  return value != null && typeof value === "object" && Array.isArray(value[__dartRecordShape]);
}
function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartAs(value, test, typeName) {
  if (test(value)) return value;
  throw new TypeError("Type cast failed: expected " + typeName);
}
function __dartRecord(positional, named) {
  const record = {};
  const shape = [];
  for (let i = 0; i < positional.length; i++) {
    const name = "$" + (i + 1);
    shape.push(name);
    Object.defineProperty(record, name, { value: positional[i], enumerable: true });
  }
  for (const name of Object.keys(named).sort()) {
    shape.push(name);
    Object.defineProperty(record, name, { value: named[name], enumerable: true });
  }
  Object.defineProperty(record, __dartRecordShape, { value: Object.freeze(shape) });
  Object.defineProperty(record, "toString", {
    value() {
      return "(" + shape.map((name) => {
        const value = String(record[name]);
        return name.startsWith("$") ? value : name + ": " + value;
      }).join(", ") + ")";
    },
  });
  return Object.freeze(record);
}

// Generated by dart2esm.

export function castList(value) {
  try {
    {
      const list = __dartAs(value, value => (Array.isArray(value) || (ArrayBuffer.isView(value) && !(value instanceof DataView))), "List<dynamic>");
      return "list " + __dartStr(list.length);
    }
  } catch ($error) {
    if ($error != null) {
      const __wc0_formal = $error;
      {
        return "list blocked";
      }
    } else {
      throw $error;
    }
  }
}

export function castNullableString(value) {
  try {
    {
      const text = __dartAs(value, value => (value === null || typeof value === "string"), "String?");
      return "string " + __dartStr(text);
    }
  } catch ($error) {
    if ($error != null) {
      const __wc0_formal = $error;
      {
        return "string blocked";
      }
    } else {
      throw $error;
    }
  }
}

export function castRecord(value) {
  try {
    {
      const record = __dartAs(value, value => __dartIsRecord(value) && value[__dartRecordShape].length === 2 && value[__dartRecordShape][0] === "$1" && value[__dartRecordShape][1] === "label" && typeof value.$1 === "number" && typeof value.label === "string", "(int, {String label})");
      return "record " + __dartStr(record.$1) + " " + __dartStr(record.label);
    }
  } catch ($error) {
    if ($error != null) {
      const __wc0_formal = $error;
      {
        return "record blocked";
      }
    } else {
      throw $error;
    }
  }
}

export function main() {
  __dartPrint(castList([1, 2]));
  __dartPrint(castList(new Map([["a", 1]])));
  __dartPrint(castNullableString(null));
  __dartPrint(castNullableString("x"));
  __dartPrint(castNullableString(1));
  __dartPrint(castRecord(__dartRecord([3], { label: "three" })));
  __dartPrint(castRecord(__dartRecord([], { label: "three", value: 3 })));
}

main();
