function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartAs(value, test, typeName) {
  if (test(value)) return value;
  throw new TypeError("Type cast failed: expected " + typeName);
}
function __dartSetAdd(set, value) {
  if (__dartIterableContains(set, value)) return false;
  set.add(value);
  return true;
}
function __dartSetAddAll(set, values) {
  for (const value of values) __dartSetAdd(set, value);
  return null;
}
const __dartMapMissingKey = Symbol("dart.mapMissingKey");
function __dartMapKey(map, key) {
  if (map.__dartIdentityMap) return map.has(key) ? key : __dartMapMissingKey;
  for (const candidate of map.keys()) {
    if (__dartEquals(candidate, key)) return candidate;
  }
  return __dartMapMissingKey;
}
function __dartMapSet(map, key, value) {
  const actualKey = __dartMapKey(map, key);
  map.set(actualKey === __dartMapMissingKey ? key : actualKey, value);
  return value;
}
function __dartMapAddAll(map, entries) {
  for (const [key, value] of entries) __dartMapSet(map, key, value);
  return null;
}
function __dartIterableContains(iterable, needle) {
  for (const value of iterable) {
    if (__dartEquals(value, needle)) return true;
  }
  return false;
}
function __dartEquals(left, right) {
  if (left === right) return true;
  if (left == null || right == null) return false;
  const equals = left["=="];
  return typeof equals === "function" ? equals.call(left, right) : false;
}
function __dartIterator(iterable) {
  const values = Array.isArray(iterable) ? iterable : Array.from(iterable);
  let index = -1;
  return {
    current: undefined,
    moveNext() {
      index++;
      if (index < values.length) {
        this.current = values[index];
        return true;
      }
      this.current = undefined;
      return false;
    },
  };
}

// Generated by dart2esm.

export function isEnabled() {
  return true;
}

export function main() {
  const maybe = [4, 5];
  let none = null;
  const list = (() => {
    const v = [1];
    if (isEnabled()) {
      (v.push(2), null);
    } else {
      (v.push(99), null);
    }
    {
      let _sync_for_iterator = __dartIterator([3]);
      for (; _sync_for_iterator.moveNext(); ) {
        {
          const value = _sync_for_iterator.current;
          (v.push(value), null);
        }
      }
    }
    (v.push(...Array.from(maybe)), null);
    const v_1 = __dartAs(none, value => (value === null || value != null && typeof value !== "string" && !(value instanceof Map) && typeof value[Symbol.iterator] === "function"), "Iterable<dynamic>?");
    if (!((v_1 === null))) {
      (v.push(...Array.from(v_1)), null);
    }
    return v;
  })();
  const set = (() => {
    const v = new Set();
    __dartSetAdd(v, 1);
    if (isEnabled()) {
      __dartSetAdd(v, 2);
    }
    {
      let _sync_for_iterator = __dartIterator([2, 3]);
      for (; _sync_for_iterator.moveNext(); ) {
        {
          const value = _sync_for_iterator.current;
          __dartSetAdd(v, value);
        }
      }
    }
    __dartSetAddAll(v, (() => {
      const v = new Set();
      __dartSetAdd(v, 3);
      __dartSetAdd(v, 4);
      return v;
    })());
    const v_1 = __dartAs(none, value => (value === null || value != null && typeof value !== "string" && !(value instanceof Map) && typeof value[Symbol.iterator] === "function"), "Iterable<dynamic>?");
    if (!((v_1 === null))) {
      __dartSetAddAll(v, v_1);
    }
    return v;
  })();
  const map = (() => {
    const v = new Map([]);
    __dartMapSet(v, "a", 1);
    if (isEnabled()) {
      __dartMapSet(v, "b", 2);
    }
    {
      let _sync_for_iterator = __dartIterator([3, 4]);
      for (; _sync_for_iterator.moveNext(); ) {
        {
          const value = _sync_for_iterator.current;
          __dartMapSet(v, "k" + __dartStr(value), value);
        }
      }
    }
    __dartMapAddAll(v, new Map([["c", 5]]));
    const v_1 = __dartAs(none, value => (value === null || value instanceof Map), "Map<dynamic, dynamic>?");
    if (!((v_1 === null))) {
      __dartMapAddAll(v, v_1);
    }
    return v;
  })();
  __dartPrint(list);
  __dartPrint(set);
  __dartPrint(map);
}

main();
