// Generated by dart2esm.

function __dartEquals(left, right) {
  if (left === right) return true;
  if (left == null || right == null) return false;
  if ((typeof left === "number" || left.__dartType === "double") && (typeof right === "number" || right.__dartType === "double")) return Number(left) === Number(right);
  if (__dartIsRecord(left) && __dartIsRecord(right)) {
    const leftShape = left[__dartRecordShape];
    const rightShape = right[__dartRecordShape];
    if (leftShape.length !== rightShape.length) return false;
    for (let i = 0; i < leftShape.length; i++) {
      const name = leftShape[i];
      if (name !== rightShape[i]) return false;
      if (!__dartEquals(left[name], right[name])) return false;
    }
    return true;
  }
  const equals = left["=="];
  return typeof equals === "function" ? equals.call(left, right) : false;
}

function __dartIterableToArray(iterable) {
  if (Array.isArray(iterable)) return Array.from(iterable);
  if (iterable != null && typeof iterable["[]"] === "function" && typeof iterable.length === "number") {
    return Array.from({ length: Number(iterable.length) }, (_, index) => iterable["[]"](index));
  }
  return Array.from(iterable);
}

function __dartIterator(iterable) {
  const values = __dartIterableToArray(iterable);
  let index = -1;
  return {
    current: undefined,
    moveNext() {
      index++;
      if (index < values.length) {
        this.current = values[index];
        return true;
      }
      this.current = undefined;
      return false;
    },
  };
}

function __dartListAdd(list, value) {
  if (Array.isArray(list)) {
    list.push(value);
  } else if (list != null && typeof list.add === "function") {
    list.add(value);
  } else {
    const index = list.length;
    list.length = index + 1;
    __dartListLikeSet(list, index, value);
  }
  return null;
}

function __dartListAddAll(list, values) {
  for (const value of __dartIterableToArray(values)) {
    __dartListAdd(list, value);
  }
  return null;
}

function __dartMapAddAll(map, entries) {
  for (const [key, value] of entries) __dartMapSet(map, key, value);
  return null;
}

function __dartMapFromEntries(entries) {
  const map = new Map();
  Object.defineProperty(map, "__dartEqualityMap", { value: true });
  __dartMapAddAll(map, entries);
  return map;
}
function __dartMapFromIterable(iterable, key = null, value = null) {
  const map = new Map();
  Object.defineProperty(map, "__dartEqualityMap", { value: true });
  for (const element of iterable) {
    __dartMapSet(
      map,
      typeof key === "function" ? key(element) : element,
      typeof value === "function" ? value(element) : element,
    );
  }
  return map;
}
function __dartMapFromIterables(keys, values) {
  const keyList = Array.from(keys);
  const valueList = Array.from(values);
  if (keyList.length !== valueList.length) throw new Error("Iterables do not have same length");
  const map = new Map();
  Object.defineProperty(map, "__dartEqualityMap", { value: true });
  for (let index = 0; index < keyList.length; index++) {
    __dartMapSet(map, keyList[index], valueList[index]);
  }
  return map;
}

const __dartMapMissingKey = Symbol("dart.mapMissingKey");
function __dartMapKey(map, key) {
  if (typeof map.__dartSplayIsValidKey === "function" && !map.__dartSplayIsValidKey(key)) return __dartMapMissingKey;
  if (map.__dartSplayCompare !== undefined) {
    for (const candidate of map.keys()) {
      if (__dartCompare(candidate, key, map.__dartSplayCompare) === 0) return candidate;
    }
    return __dartMapMissingKey;
  }
  if (typeof map.__dartMapIsValidKey === "function" && !map.__dartMapIsValidKey(key)) return __dartMapMissingKey;
  if (typeof map.__dartMapEquals === "function") {
    for (const candidate of map.keys()) {
      if (map.__dartMapEquals(candidate, key)) return candidate;
    }
    return __dartMapMissingKey;
  }
  if (!map.__dartEqualityMap) return map.has(key) ? key : __dartMapMissingKey;
  for (const candidate of map.keys()) {
    if (__dartEquals(candidate, key)) return candidate;
  }
  return __dartMapMissingKey;
}
function __dartMapGet(map, key) {
  if (!(map instanceof Map) && map != null && typeof map["[]"] === "function") return map["[]"](key);
  const actualKey = __dartMapKey(map, key);
  return actualKey === __dartMapMissingKey ? null : map.get(actualKey);
}

function __dartMapSet(map, key, value) {
  const actualKey = __dartMapKey(map, key);
  map.set(actualKey === __dartMapMissingKey ? key : actualKey, value);
  if (map.__dartSplayCompare !== undefined) __dartSplaySortMap(map);
  return value;
}

function __dartPrint(value) {
  console.log(__dartStr(value));
}

const __dartRecordShape = Symbol("dart.recordShape");

function __dartIsRecord(value) {
  return value != null && typeof value === "object" && Array.isArray(value[__dartRecordShape]);
}

function __dartSetContains(set, needle) {
  if (typeof set.__dartSplayIsValidKey === "function" && !set.__dartSplayIsValidKey(needle)) return false;
  if (set.__dartSplayCompare !== undefined) {
    for (const value of set) {
      if (__dartCompare(value, needle, set.__dartSplayCompare) === 0) return true;
    }
    return false;
  }
  if (!set.__dartEqualitySet) return set.has(needle);
  for (const value of set) {
    if (__dartEquals(value, needle)) return true;
  }
  return false;
}
function __dartSetAdd(set, value) {
  if (__dartSetContains(set, value)) return false;
  set.add(value);
  if (set.__dartSplayCompare !== undefined) __dartSplaySortSet(set);
  return true;
}
function __dartSetFrom(values) {
  const set = new Set();
  Object.defineProperty(set, "__dartEqualitySet", { value: true });
  for (const value of values) __dartSetAdd(set, value);
  return set;
}
function __dartSetAddAll(set, values) {
  for (const value of values) __dartSetAdd(set, value);
  return null;
}

function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}

function __dartAs(value, test, typeName) {
  if (test(value)) {
    return value;
  }
  throw new TypeError("Type cast failed: expected " + typeName);
}

export function isEnabled() {
  return true;
}

export function main() {
  const maybe = [4, 5];
  const none = null;
  const list = (() => {
    const v = [1];
    if (isEnabled()) {
      __dartListAdd(v, 2);
    } else {
      __dartListAdd(v, 99);
    }
    let _sync_for_iterator = __dartIterator([3]);
    for (; _sync_for_iterator.moveNext(); ) {
      const value = _sync_for_iterator.current;
      __dartListAdd(v, value);
    }
    __dartListAddAll(v, maybe);
    const v_1 = __dartAs(none, (value) => (value === null || (((value != null && typeof value !== "string") && !(value instanceof Map)) && typeof value[Symbol.iterator] === "function")), "Iterable");
    if (!(v_1 === null)) {
      __dartListAddAll(v, v_1);
    }
    return v;
  })();
  const set = (() => {
    const v = __dartSetFrom([]);
    __dartSetAdd(v, 1);
    if (isEnabled()) {
      __dartSetAdd(v, 2);
    }
    let _sync_for_iterator = __dartIterator([2, 3]);
    for (; _sync_for_iterator.moveNext(); ) {
      const value = _sync_for_iterator.current;
      __dartSetAdd(v, value);
    }
    __dartSetAddAll(v, (() => {
      const v_1 = __dartSetFrom([]);
      __dartSetAdd(v_1, 3);
      __dartSetAdd(v_1, 4);
      return v_1;
    })());
    const v_1 = __dartAs(none, (value) => (value === null || (((value != null && typeof value !== "string") && !(value instanceof Map)) && typeof value[Symbol.iterator] === "function")), "Iterable");
    if (!(v_1 === null)) {
      __dartSetAddAll(v, v_1);
    }
    return v;
  })();
  const map = (() => {
    const v = __dartMapFromEntries([]);
    __dartMapSet(v, "a", 1);
    if (isEnabled()) {
      __dartMapSet(v, "b", 2);
    }
    let _sync_for_iterator = __dartIterator([3, 4]);
    for (; _sync_for_iterator.moveNext(); ) {
      const value = _sync_for_iterator.current;
      __dartMapSet(v, `k${__dartStr(value)}`, value);
    }
    __dartMapAddAll(v, __dartMapFromEntries([["c", 5]]));
    const v_1 = __dartAs(none, (value) => (value === null || value instanceof Map), "Map");
    if (!(v_1 === null)) {
      __dartMapAddAll(v, v_1);
    }
    return v;
  })();
  __dartPrint(list);
  __dartPrint(set);
  __dartPrint(map);
}

main();
