const __dartRecordShape = Symbol("dart.recordShape");
function __dartIsRecord(value) {
  return value != null && typeof value === "object" && Array.isArray(value[__dartRecordShape]);
}
function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartSetAdd(set, value) {
  if (set.__dartIdentitySet) {
    if (set.has(value)) return false;
    set.add(value);
    return true;
  }
  if (__dartIterableContains(set, value)) return false;
  set.add(value);
  return true;
}
const __dartMapMissingKey = Symbol("dart.mapMissingKey");
function __dartMapKey(map, key) {
  if (map.__dartIdentityMap) return map.has(key) ? key : __dartMapMissingKey;
  for (const candidate of map.keys()) {
    if (__dartEquals(candidate, key)) return candidate;
  }
  return __dartMapMissingKey;
}
function __dartMapSet(map, key, value) {
  const actualKey = __dartMapKey(map, key);
  map.set(actualKey === __dartMapMissingKey ? key : actualKey, value);
  return value;
}
function __dartIterableContains(iterable, needle) {
  if (iterable instanceof Set && iterable.__dartIdentitySet) return iterable.has(needle);
  for (const value of iterable) {
    if (__dartEquals(value, needle)) return true;
  }
  return false;
}
function __dartEquals(left, right) {
  if (left === right) return true;
  if (left == null || right == null) return false;
  if ((typeof left === "number" || left.__dartType === "double") && (typeof right === "number" || right.__dartType === "double")) return Number(left) === Number(right);
  if (__dartIsRecord(left) && __dartIsRecord(right)) {
    const leftShape = left[__dartRecordShape];
    const rightShape = right[__dartRecordShape];
    if (leftShape.length !== rightShape.length) return false;
    for (let i = 0; i < leftShape.length; i++) {
      const name = leftShape[i];
      if (name !== rightShape[i]) return false;
      if (!__dartEquals(left[name], right[name])) return false;
    }
    return true;
  }
  const equals = left["=="];
  return typeof equals === "function" ? equals.call(left, right) : false;
}
function __dartRecord(positional, named) {
  const record = {};
  const shape = [];
  for (let i = 0; i < positional.length; i++) {
    const name = "$" + (i + 1);
    shape.push(name);
    Object.defineProperty(record, name, { value: positional[i], enumerable: true });
  }
  for (const name of Object.keys(named).sort()) {
    shape.push(name);
    Object.defineProperty(record, name, { value: named[name], enumerable: true });
  }
  Object.defineProperty(record, __dartRecordShape, { value: Object.freeze(shape) });
  Object.defineProperty(record, "toString", {
    value() {
      return "(" + shape.map((name) => {
        const value = String(record[name]);
        return name.startsWith("$") ? value : name + ": " + value;
      }).join(", ") + ")";
    },
  });
  return Object.freeze(record);
}
const __dartConstValues = new Map();
function __dartConst(key, create) {
  if (!__dartConstValues.has(key)) {
    __dartConstValues.set(key, create());
  }
  return __dartConstValues.get(key);
}
function __dartConstSet(values) {
  const set = new Set();
  for (const value of values) __dartSetAdd(set, value);
  const throwConst = () => { throw new TypeError("Cannot modify const Set"); };
  Object.defineProperty(set, "add", { value: throwConst });
  Object.defineProperty(set, "delete", { value: throwConst });
  Object.defineProperty(set, "clear", { value: throwConst });
  return Object.freeze(set);
}
function __dartConstMap(entries) {
  const map = new Map();
  for (const [key, value] of entries) __dartMapSet(map, key, value);
  const throwConst = () => { throw new TypeError("Cannot modify const Map"); };
  Object.defineProperty(map, "set", { value: throwConst });
  Object.defineProperty(map, "delete", { value: throwConst });
  Object.defineProperty(map, "clear", { value: throwConst });
  return Object.freeze(map);
}

// Generated by dart2esm.

export const numbers = __dartConst("[\"list\",\"InterfaceType(int)\",[\"int\",\"1\"],[\"int\",\"2\"]]", () => Object.freeze([1, 2]));

export const sameNumbers = __dartConst("[\"list\",\"InterfaceType(int)\",[\"int\",\"1\"],[\"int\",\"2\"]]", () => Object.freeze([1, 2]));

export const names = __dartConst("[\"set\",\"InterfaceType(String)\",[\"string\",\"a\"],[\"string\",\"b\"]]", () => __dartConstSet(["a", "b"]));

export const sameNames = __dartConst("[\"set\",\"InterfaceType(String)\",[\"string\",\"a\"],[\"string\",\"b\"]]", () => __dartConstSet(["a", "b"]));

export const mapping = __dartConst("[\"map\",\"InterfaceType(String)\",\"InterfaceType(int)\",[[\"string\",\"a\"],[\"int\",\"1\"]],[[\"string\",\"b\"],[\"int\",\"2\"]]]", () => __dartConstMap([["a", 1], ["b", 2]]));

export const sameMapping = __dartConst("[\"map\",\"InterfaceType(String)\",\"InterfaceType(int)\",[[\"string\",\"a\"],[\"int\",\"1\"]],[[\"string\",\"b\"],[\"int\",\"2\"]]]", () => __dartConstMap([["a", 1], ["b", 2]]));

export const shape = __dartConst("[\"record\",[\"int\",\"1\"],[\"named\",\"name\",[\"string\",\"dart\"]]]", () => __dartRecord([1], { name: "dart" }));

export const sameShape = __dartConst("[\"record\",[\"int\",\"1\"],[\"named\",\"name\",[\"string\",\"dart\"]]]", () => __dartRecord([1], { name: "dart" }));

export function main() {
  __dartPrint(__dartStr(Object.is(__dartConst("[\"list\",\"InterfaceType(int)\",[\"int\",\"1\"],[\"int\",\"2\"]]", () => Object.freeze([1, 2])), __dartConst("[\"list\",\"InterfaceType(int)\",[\"int\",\"1\"],[\"int\",\"2\"]]", () => Object.freeze([1, 2])))) + " " + __dartStr(Object.is(__dartConst("[\"list\",\"InterfaceType(int)\",[\"int\",\"1\"],[\"int\",\"2\"]]", () => Object.freeze([1, 2])), __dartConst("[\"list\",\"InterfaceType(int)\",[\"int\",\"1\"],[\"int\",\"2\"]]", () => Object.freeze([1, 2])))));
  __dartPrint(__dartStr(Object.is(__dartConst("[\"set\",\"InterfaceType(String)\",[\"string\",\"a\"],[\"string\",\"b\"]]", () => __dartConstSet(["a", "b"])), __dartConst("[\"set\",\"InterfaceType(String)\",[\"string\",\"a\"],[\"string\",\"b\"]]", () => __dartConstSet(["a", "b"])))) + " " + __dartStr(Object.is(__dartConst("[\"set\",\"InterfaceType(String)\",[\"string\",\"a\"],[\"string\",\"b\"]]", () => __dartConstSet(["a", "b"])), __dartConst("[\"set\",\"InterfaceType(String)\",[\"string\",\"a\"],[\"string\",\"b\"]]", () => __dartConstSet(["a", "b"])))));
  __dartPrint(__dartStr(Object.is(__dartConst("[\"map\",\"InterfaceType(String)\",\"InterfaceType(int)\",[[\"string\",\"a\"],[\"int\",\"1\"]],[[\"string\",\"b\"],[\"int\",\"2\"]]]", () => __dartConstMap([["a", 1], ["b", 2]])), __dartConst("[\"map\",\"InterfaceType(String)\",\"InterfaceType(int)\",[[\"string\",\"a\"],[\"int\",\"1\"]],[[\"string\",\"b\"],[\"int\",\"2\"]]]", () => __dartConstMap([["a", 1], ["b", 2]])))) + " " + __dartStr(Object.is(__dartConst("[\"map\",\"InterfaceType(String)\",\"InterfaceType(int)\",[[\"string\",\"a\"],[\"int\",\"1\"]],[[\"string\",\"b\"],[\"int\",\"2\"]]]", () => __dartConstMap([["a", 1], ["b", 2]])), __dartConst("[\"map\",\"InterfaceType(String)\",\"InterfaceType(int)\",[[\"string\",\"a\"],[\"int\",\"1\"]],[[\"string\",\"b\"],[\"int\",\"2\"]]]", () => __dartConstMap([["a", 1], ["b", 2]])))));
  __dartPrint(__dartStr(Object.is(__dartConst("[\"record\",[\"int\",\"1\"],[\"named\",\"name\",[\"string\",\"dart\"]]]", () => __dartRecord([1], { name: "dart" })), __dartConst("[\"record\",[\"int\",\"1\"],[\"named\",\"name\",[\"string\",\"dart\"]]]", () => __dartRecord([1], { name: "dart" })))) + " " + __dartStr(Object.is(__dartConst("[\"record\",[\"int\",\"1\"],[\"named\",\"name\",[\"string\",\"dart\"]]]", () => __dartRecord([1], { name: "dart" })), __dartConst("[\"record\",[\"int\",\"1\"],[\"named\",\"name\",[\"string\",\"dart\"]]]", () => __dartRecord([1], { name: "dart" })))));
  __dartPrint(__dartConst("[\"list\",\"InterfaceType(int)\",[\"int\",\"1\"],[\"int\",\"2\"]]", () => Object.freeze([1, 2])));
  __dartPrint(__dartConst("[\"set\",\"InterfaceType(String)\",[\"string\",\"a\"],[\"string\",\"b\"]]", () => __dartConstSet(["a", "b"])));
  __dartPrint(__dartConst("[\"map\",\"InterfaceType(String)\",\"InterfaceType(int)\",[[\"string\",\"a\"],[\"int\",\"1\"]],[[\"string\",\"b\"],[\"int\",\"2\"]]]", () => __dartConstMap([["a", 1], ["b", 2]])));
  __dartPrint(__dartConst("[\"record\",[\"int\",\"1\"],[\"named\",\"name\",[\"string\",\"dart\"]]]", () => __dartRecord([1], { name: "dart" })));
}

main();
