// Generated by dart2esm.

function __dartCoreError(typeName, message) {
  const text = message == null ? "" : String(message);
  const display = text === "" ? typeName : typeName + ": " + text;
  const error = new Error(text);
  error.name = typeName;
  Object.defineProperty(error, "__dartCoreErrorType", { value: typeName });
  Object.defineProperty(error, "toString", { value() { return display; } });
  return error;
}
function __dartIsCoreError(value, typeName) {
  const actual = value == null ? null : value.__dartCoreErrorType;
  if (actual != null) {
    if (actual === typeName) return true;
    if (typeName === "Exception" && actual === "FormatException") return true;
    if (typeName === "RangeError" && actual === "IndexError") return true;
    if (typeName === "ArgumentError" && (actual === "RangeError" || actual === "IndexError")) return true;
    return typeName === "Error" && actual !== "Exception" && actual !== "FormatException";
  }
  if (typeName === "TypeError" && value instanceof TypeError) return true;
  return typeName === "Error" && value instanceof Error;
}

function __dartDynamicCall(receiver, positionalArguments, namedArguments = null) {
  const args = namedArguments == null ? Array.from(positionalArguments) : [...positionalArguments, namedArguments];
  if (typeof receiver === "function") return receiver(...args);
  const call = receiver?.call;
  if (typeof call === "function") return call.apply(receiver, args);
  throw new TypeError("Object is not callable");
}

function __dartDynamicGet(receiver, name) {
  if (receiver == null) throw new TypeError("Cannot read property " + name + " of " + receiver);
  if ((receiver instanceof Set || receiver instanceof Map) && name === "length") return receiver.size;
  const value = receiver[name];
  return typeof value === "function" ? value.bind(receiver) : value;
}

function __dartDynamicInvoke(receiver, name, positionalArguments, namedArguments = null) {
  if (receiver == null) throw new TypeError("Cannot call " + name + " on " + receiver);
  const args = namedArguments == null ? Array.from(positionalArguments) : [...positionalArguments, namedArguments];
  if (name === "[]") {
    const key = args[0];
    if (receiver instanceof Map) {
      return receiver.has(key) ? receiver.get(key) : null;
    }
    if (typeof receiver["[]"] === "function") return receiver["[]"](key);
    return receiver[key];
  }
  if (name === "[]=") {
    const key = args[0];
    const value = args[1];
    if (receiver instanceof Map) {
      receiver.set(key, value);
      return value;
    }
    if (typeof receiver["[]="] === "function") return receiver["[]="](key, value);
    receiver[key] = value;
    return value;
  }
  if (receiver instanceof Map) {
    if (name === "containsKey") return receiver.has(args[0]);
    if (name === "remove") {
      const key = args[0];
      const value = receiver.has(key) ? receiver.get(key) : null;
      receiver.delete(key);
      return value;
    }
  }
  if (receiver instanceof Set) {
    if (name === "add") {
      const value = args[0];
      const hadValue = receiver.has(value);
      receiver.add(value);
      return !hadValue;
    }
    if (name === "contains") return receiver.has(args[0]);
    if (name === "remove") return receiver.delete(args[0]);
  }
  const listLike = receiver != null && typeof receiver["[]"] === "function" && typeof receiver.length === "number";
  if (Array.isArray(receiver) || listLike) {
    if (name === "join") return __dartIterableJoin(receiver, args[0] ?? "");
    if (name === "contains") {
      if (Array.isArray(receiver)) return receiver.includes(args[0]);
      for (let index = 0; index < receiver.length; index++) {
        if (__dartEquals(receiver["[]"](index), args[0])) return true;
      }
      return false;
    }
    if (Array.isArray(receiver) && name === "add") {
      receiver.push(args[0]);
      return null;
    }
    if (Array.isArray(receiver) && name === "addAll") {
      receiver.push(...Array.from(args[0]));
      return null;
    }
  }
  if (typeof receiver === "string" && name === "contains") {
    return receiver.includes(args[0]);
  }
  const member = receiver[name];
  if (typeof member === "function") return member.apply(receiver, args);
  throw new TypeError("Object has no method " + name);
}

function __dartDynamicSet(receiver, name, value) {
  if (receiver == null) throw new TypeError("Cannot set property " + name + " of " + receiver);
  receiver[name] = value;
  return value;
}

function __dartEquals(left, right) {
  if (left === right) return true;
  if (left == null || right == null) return false;
  if ((typeof left === "number" || left.__dartType === "double") && (typeof right === "number" || right.__dartType === "double")) return Number(left) === Number(right);
  if (__dartIsRecord(left) && __dartIsRecord(right)) {
    const leftShape = left[__dartRecordShape];
    const rightShape = right[__dartRecordShape];
    if (leftShape.length !== rightShape.length) return false;
    for (let i = 0; i < leftShape.length; i++) {
      const name = leftShape[i];
      if (name !== rightShape[i]) return false;
      if (!__dartEquals(left[name], right[name])) return false;
    }
    return true;
  }
  const equals = left["=="];
  return typeof equals === "function" ? equals.call(left, right) : false;
}

function __dartIterableJoin(iterable, separator = "") {
  if (iterable != null && typeof iterable["[]"] === "function" && typeof iterable.length === "number") {
    const values = [];
    for (let index = 0; index < iterable.length; index++) values.push(__dartStr(iterable["[]"](index)));
    return values.join(String(separator));
  }
  return Array.from(iterable, (value) => __dartStr(value)).join(String(separator));
}

function __dartIterator(iterable) {
  const values = (iterable != null && typeof iterable["[]"] === "function" && typeof iterable.length === "number")
    ? { length: iterable.length, get(index) { return iterable["[]"](index); } }
    : Array.from(iterable);
  let index = -1;
  return {
    current: undefined,
    moveNext() {
      index++;
      if (index < values.length) {
        this.current = typeof values.get === "function" ? values.get(index) : values[index];
        return true;
      }
      this.current = undefined;
      return false;
    },
  };
}

function __dartListAdd(list, value) {
  list.push(value);
  return null;
}

function __dartListAddAll(list, values) {
  list.push(...Array.from(values));
  return null;
}

function __dartListLikeGet(list, index) {
  if (Array.isArray(list) || ArrayBuffer.isView(list) || typeof list === "string") return list[index];
  const op = list == null ? null : list["[]"];
  return typeof op === "function" ? op.call(list, index) : list[index];
}
function __dartListLikeSet(list, index, value) {
  if (Array.isArray(list) || ArrayBuffer.isView(list)) {
    list[index] = value;
    return value;
  }
  const op = list == null ? null : list["[]="];
  if (typeof op === "function") return op.call(list, index, value);
  list[index] = value;
  return value;
}
function __dartListMixinFirst(list) {
  return __dartListLikeGet(list, 0);
}
function __dartListMixinLast(list) {
  return __dartListLikeGet(list, list.length - 1);
}
function __dartListMixinSingle(list) {
  if (list.length !== 1) throw __dartCoreError("StateError", "Too many elements");
  return __dartListLikeGet(list, 0);
}
function __dartListMixinInsert(list, index, value) {
  index = Number(index);
  const length = Number(list.length);
  list.length = length + 1;
  for (let i = length; i > index; i--) {
    __dartListLikeSet(list, i, __dartListLikeGet(list, i - 1));
  }
  __dartListLikeSet(list, index, value);
  return null;
}

function __dartMapAddAll(map, entries) {
  for (const [key, value] of entries) __dartMapSet(map, key, value);
  return null;
}

function __dartMapFromEntries(entries) {
  const map = new Map();
  Object.defineProperty(map, "__dartEqualityMap", { value: true });
  __dartMapAddAll(map, entries);
  return map;
}
function __dartMapFromIterable(iterable, key = null, value = null) {
  const map = new Map();
  Object.defineProperty(map, "__dartEqualityMap", { value: true });
  for (const element of iterable) {
    __dartMapSet(
      map,
      typeof key === "function" ? key(element) : element,
      typeof value === "function" ? value(element) : element,
    );
  }
  return map;
}
function __dartMapFromIterables(keys, values) {
  const keyList = Array.from(keys);
  const valueList = Array.from(values);
  if (keyList.length !== valueList.length) throw new Error("Iterables do not have same length");
  const map = new Map();
  Object.defineProperty(map, "__dartEqualityMap", { value: true });
  for (let index = 0; index < keyList.length; index++) {
    __dartMapSet(map, keyList[index], valueList[index]);
  }
  return map;
}

const __dartMapMissingKey = Symbol("dart.mapMissingKey");
function __dartMapKey(map, key) {
  if (typeof map.__dartSplayIsValidKey === "function" && !map.__dartSplayIsValidKey(key)) return __dartMapMissingKey;
  if (map.__dartSplayCompare !== undefined) {
    for (const candidate of map.keys()) {
      if (__dartCompare(candidate, key, map.__dartSplayCompare) === 0) return candidate;
    }
    return __dartMapMissingKey;
  }
  if (typeof map.__dartMapIsValidKey === "function" && !map.__dartMapIsValidKey(key)) return __dartMapMissingKey;
  if (typeof map.__dartMapEquals === "function") {
    for (const candidate of map.keys()) {
      if (map.__dartMapEquals(candidate, key)) return candidate;
    }
    return __dartMapMissingKey;
  }
  if (!map.__dartEqualityMap) return map.has(key) ? key : __dartMapMissingKey;
  for (const candidate of map.keys()) {
    if (__dartEquals(candidate, key)) return candidate;
  }
  return __dartMapMissingKey;
}
function __dartMapGet(map, key) {
  if (!(map instanceof Map) && map != null && typeof map["[]"] === "function") return map["[]"](key);
  const actualKey = __dartMapKey(map, key);
  return actualKey === __dartMapMissingKey ? null : map.get(actualKey);
}

function __dartMapSet(map, key, value) {
  const actualKey = __dartMapKey(map, key);
  map.set(actualKey === __dartMapMissingKey ? key : actualKey, value);
  if (map.__dartSplayCompare !== undefined) __dartSplaySortMap(map);
  return value;
}

function __dartNullCheck(value) {
  if (value == null) throw new TypeError("Null check operator used on a null value");
  return value;
}

function __dartPrint(value) {
  console.log(__dartStr(value));
}

const __dartRecordShape = Symbol("dart.recordShape");

function __dartIsRecord(value) {
  return value != null && typeof value === "object" && Array.isArray(value[__dartRecordShape]);
}

function __dartRecord(positional, named) {
  const record = {};
  const shape = [];
  for (let i = 0; i < positional.length; i++) {
    const name = "$" + (i + 1);
    shape.push(name);
    Object.defineProperty(record, name, { value: positional[i], enumerable: true });
  }
  for (const name of Object.keys(named).sort()) {
    shape.push(name);
    Object.defineProperty(record, name, { value: named[name], enumerable: true });
  }
  Object.defineProperty(record, __dartRecordShape, { value: Object.freeze(shape) });
  Object.defineProperty(record, "toString", {
    value() {
      return "(" + shape.map((name) => {
        const value = String(record[name]);
        return name.startsWith("$") ? value : name + ": " + value;
      }).join(", ") + ")";
    },
  });
  return Object.freeze(record);
}

function __dartSetContains(set, needle) {
  if (typeof set.__dartSplayIsValidKey === "function" && !set.__dartSplayIsValidKey(needle)) return false;
  if (set.__dartSplayCompare !== undefined) {
    for (const value of set) {
      if (__dartCompare(value, needle, set.__dartSplayCompare) === 0) return true;
    }
    return false;
  }
  if (!set.__dartEqualitySet) return set.has(needle);
  for (const value of set) {
    if (__dartEquals(value, needle)) return true;
  }
  return false;
}
function __dartSetAdd(set, value) {
  if (__dartSetContains(set, value)) return false;
  set.add(value);
  if (set.__dartSplayCompare !== undefined) __dartSplaySortSet(set);
  return true;
}
function __dartSetFrom(values) {
  const set = new Set();
  Object.defineProperty(set, "__dartEqualitySet", { value: true });
  for (const value of values) __dartSetAdd(set, value);
  return set;
}
function __dartSetAddAll(set, values) {
  for (const value of values) __dartSetAdd(set, value);
  return null;
}

function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}

export class Bag {
  constructor(value) {
    Object.defineProperty(this, "value", { value: null, writable: true, enumerable: true, configurable: true });
    Object.defineProperty(this, "value", { value: value, writable: true, enumerable: true, configurable: true });
  }
  add(x) {
    return this.value + x;
  }
}

export function describe(input) {
  const list = (() => {
    const v = [0];
    __dartListAddAll(v, [1, 2]);
    if (!(input === null)) {
      __dartListAdd(v, 3);
    }
    let _sync_for_iterator = __dartIterator([4, 5]);
    for (; _sync_for_iterator.moveNext(); ) {
      const x = _sync_for_iterator.current;
      __dartListAdd(v, x);
    }
    return v;
  })();
  const set = (() => {
    const v = __dartSetFrom([]);
    __dartSetAdd(v, 0);
    __dartSetAddAll(v, (() => {
      const v_1 = __dartSetFrom([]);
      __dartSetAdd(v_1, 1);
      __dartSetAdd(v_1, 2);
      return v_1;
    })());
    if (!(input === null)) {
      __dartSetAdd(v, 3);
    }
    let _sync_for_iterator = __dartIterator([4, 5]);
    for (; _sync_for_iterator.moveNext(); ) {
      const x = _sync_for_iterator.current;
      __dartSetAdd(v, x);
    }
    return v;
  })();
  const map = (() => {
    const v = __dartMapFromEntries([]);
    __dartMapSet(v, "a", 1);
    __dartMapAddAll(v, __dartMapFromEntries([["b", 2]]));
    if (!(input === null)) {
      __dartMapSet(v, "c", 3);
    }
    let _sync_for_iterator = __dartIterator([4, 5]);
    for (; _sync_for_iterator.moveNext(); ) {
      const x = _sync_for_iterator.current;
      __dartMapSet(v, `${__dartStr(x)}`, x);
    }
    return v;
  })();
  let a = null;
  let b = null;
  const _0_0 = __dartRecord([1, 2], {  });
  a = _0_0.$1;
  b = _0_0.$2;
  const _1_0 = __dartRecord([b, a], {  });
  a = _1_0.$1;
  b = _1_0.$2;
  const result = (() => {
    let v = null;
    const _2_0 = input;
    label: {
      let value = null;
      if (((typeof _2_0 === "number" && (() => {
        const v_1 = value = _2_0;
        return true;
      })()) && value > 2)) {
        v = `big ${__dartStr(value)}`;
        break label;
      }
      let value_1 = null;
      if (typeof _2_0 === "string") {
        value_1 = _2_0;
        v = `string ${__dartStr(value_1)}`;
        break label;
      }
      if (true) {
        v = "other";
        break label;
      }
    }
    return v;
  })();
  let d = new Bag(10);
  __dartDynamicSet(d, "value", __dartDynamicInvoke(d, "add", [1], null));
  const tear = __dartDynamicGet(d, "add");
  let dynList = [1, 2];
  __dartDynamicInvoke(dynList, "add", [3], null);
  __dartDynamicInvoke(dynList, "[]=", [1, 4], null);
  const dynListText = `${__dartStr(__dartDynamicInvoke(dynList, "[]", [0], null))}:${__dartStr(__dartDynamicInvoke(dynList, "[]", [1], null))}:${__dartStr(__dartDynamicInvoke(dynList, "join", ["|"], null))}:${__dartStr(__dartDynamicInvoke(dynList, "contains", [3], null))}`;
  let dynMap = __dartMapFromEntries([["a", 1]]);
  __dartDynamicInvoke(dynMap, "[]=", ["b", 2], null);
  const dynMapText = `${__dartStr(__dartDynamicInvoke(dynMap, "[]", ["a"], null))}:${__dartStr(__dartDynamicInvoke(dynMap, "containsKey", ["b"], null))}:${__dartStr(__dartDynamicInvoke(dynMap, "remove", ["a"], null))}:${__dartStr(__dartDynamicInvoke(dynMap, "[]", ["a"], null))}`;
  let dynSet = (() => {
    const v = __dartSetFrom([]);
    __dartSetAdd(v, "a");
    return v;
  })();
  const dynSetAdded = __dartDynamicInvoke(dynSet, "add", ["b"], null);
  const dynSetDuplicate = __dartDynamicInvoke(dynSet, "add", ["b"], null);
  const dynSetText = `${__dartStr(dynSetAdded)}:${__dartStr(dynSetDuplicate)}:${__dartStr(__dartDynamicInvoke(dynSet, "contains", ["a"], null))}:${__dartStr(__dartDynamicInvoke(dynSet, "remove", ["a"], null))}:${__dartStr(__dartDynamicGet(dynSet, "length"))}`;
  let dynString = " Hello,Dart ";
  const dynStringText = `${__dartStr(__dartDynamicInvoke(__dartDynamicInvoke(dynString, "trim", [], null), "toUpperCase", [], null))}:${__dartStr(__dartDynamicInvoke(dynString, "contains", ["Dart"], null))}:${__dartStr(__dartDynamicInvoke(__dartDynamicInvoke(__dartDynamicInvoke(dynString, "split", [","], null), "[]", [1], null), "trim", [], null))}`;
  const sure = __dartNullCheck(input);
  return `${__dartStr(list)} ${__dartStr(set)} ${__dartStr(map)} ${__dartStr(a)} ${__dartStr(b)} ${__dartStr(result)} ${__dartStr(__dartDynamicGet(d, "value"))} ${__dartStr(__dartDynamicCall(tear, [2], null))} ${__dartStr(dynListText)} ${__dartStr(dynMapText)} ${__dartStr(dynSetText)} ${__dartStr(dynStringText)} ${__dartStr(sure)}`;
}

export function main() {
  __dartPrint(describe(4));
  __dartPrint(describe("x"));
}

main();
