const __dartRecordShape = Symbol("dart.recordShape");
function __dartIsRecord(value) {
  return value != null && typeof value === "object" && Array.isArray(value[__dartRecordShape]);
}
function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartNullCheck(value) {
  if (value == null) {
    throw new TypeError("Null check operator used on a null value");
  }
  return value;
}
function __dartGet(receiver, name) {
  const value = receiver[name];
  return typeof value === "function" ? value.bind(receiver) : value;
}
function __dartSetAdd(set, value) {
  if (__dartIterableContains(set, value)) return false;
  set.add(value);
  return true;
}
function __dartSetAddAll(set, values) {
  for (const value of values) __dartSetAdd(set, value);
  return null;
}
function __dartMapAddAll(map, entries) {
  for (const [key, value] of entries) map.set(key, value);
  return null;
}
function __dartIterableContains(iterable, needle) {
  for (const value of iterable) {
    if (__dartEquals(value, needle)) return true;
  }
  return false;
}
function __dartEquals(left, right) {
  if (left === right) return true;
  if (left == null || right == null) return false;
  if (__dartIsRecord(left) && __dartIsRecord(right)) {
    const leftShape = left[__dartRecordShape];
    const rightShape = right[__dartRecordShape];
    if (leftShape.length !== rightShape.length) return false;
    for (let i = 0; i < leftShape.length; i++) {
      const name = leftShape[i];
      if (name !== rightShape[i]) return false;
      if (!__dartEquals(left[name], right[name])) return false;
    }
    return true;
  }
  const equals = left["=="];
  return typeof equals === "function" ? equals.call(left, right) : false;
}
function __dartRecord(positional, named) {
  const record = {};
  const shape = [];
  for (let i = 0; i < positional.length; i++) {
    const name = "$" + (i + 1);
    shape.push(name);
    Object.defineProperty(record, name, { value: positional[i], enumerable: true });
  }
  for (const name of Object.keys(named).sort()) {
    shape.push(name);
    Object.defineProperty(record, name, { value: named[name], enumerable: true });
  }
  Object.defineProperty(record, __dartRecordShape, { value: Object.freeze(shape) });
  Object.defineProperty(record, "toString", {
    value() {
      return "(" + shape.map((name) => {
        const value = String(record[name]);
        return name.startsWith("$") ? value : name + ": " + value;
      }).join(", ") + ")";
    },
  });
  return Object.freeze(record);
}
function __dartIterator(iterable) {
  const values = Array.isArray(iterable) ? iterable : Array.from(iterable);
  let index = -1;
  return {
    current: undefined,
    moveNext() {
      index++;
      if (index < values.length) {
        this.current = values[index];
        return true;
      }
      this.current = undefined;
      return false;
    },
  };
}

// Generated by dart2esm.

export class Bag {
  constructor(value) {
    this.value = value;
  }
  add(x) {
    return (this.value + x);
  }
}

export function describe(input) {
  const list = (() => {
    const v = [0];
    (v.push(...Array.from([1, 2])), null);
    if (!((input === null))) {
      (v.push(3), null);
    }
    {
      let _sync_for_iterator = __dartIterator([4, 5]);
      for (; _sync_for_iterator.moveNext(); ) {
        {
          const x = _sync_for_iterator.current;
          (v.push(x), null);
        }
      }
    }
    return v;
  })();
  const set = (() => {
    const v = new Set();
    __dartSetAdd(v, 0);
    __dartSetAddAll(v, (() => {
      const v = new Set();
      __dartSetAdd(v, 1);
      __dartSetAdd(v, 2);
      return v;
    })());
    if (!((input === null))) {
      __dartSetAdd(v, 3);
    }
    {
      let _sync_for_iterator = __dartIterator([4, 5]);
      for (; _sync_for_iterator.moveNext(); ) {
        {
          const x = _sync_for_iterator.current;
          __dartSetAdd(v, x);
        }
      }
    }
    return v;
  })();
  const map = (() => {
    const v = new Map([]);
    v.set("a", 1);
    __dartMapAddAll(v, new Map([["b", 2]]));
    if (!((input === null))) {
      v.set("c", 3);
    }
    {
      let _sync_for_iterator = __dartIterator([4, 5]);
      for (; _sync_for_iterator.moveNext(); ) {
        {
          const x = _sync_for_iterator.current;
          v.set(__dartStr(x), x);
        }
      }
    }
    return v;
  })();
  let a = null;
  let b = null;
  {
    const _0_0 = __dartRecord([1, 2], {});
    a = _0_0.$1;
    b = _0_0.$2;
  }
  {
    const _1_0 = __dartRecord([b, a], {});
    a = _1_0.$1;
    b = _1_0.$2;
  }
  const result = (() => {
    let v = null;
    const _2_0 = input;
    L:
    {
      {
        let value = null;
        if (((typeof _2_0 === "number" && (() => { let v_1 = value = _2_0; return true; })()) && (value > 2))) {
          {
            v = "big " + __dartStr(value);
            break L;
          }
        }
      }
      {
        let value_1 = null;
        if (typeof _2_0 === "string") {
          {
            value_1 = _2_0;
            v = "string " + __dartStr(value_1);
            break L;
          }
        }
      }
      {
        if (true) {
          {
            v = "other";
            break L;
          }
        }
      }
    }
    return v;
  })();
  let d = new Bag(10);
  d.value = d.add(1);
  const tear = __dartGet(d, "add");
  const sure = __dartNullCheck(input);
  return __dartStr(list) + " " + __dartStr(set) + " " + __dartStr(map) + " " + __dartStr(a) + " " + __dartStr(b) + " " + __dartStr(result) + " " + __dartStr(__dartGet(d, "value")) + " " + __dartStr((tear)(2)) + " " + __dartStr(sure);
}

export function main() {
  __dartPrint(describe(4));
  __dartPrint(describe("x"));
}

main();
