const __dartRecordShape = Symbol("dart.recordShape");
function __dartIsRecord(value) {
  return value != null && typeof value === "object" && Array.isArray(value[__dartRecordShape]);
}
function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartAs(value, test, typeName) {
  if (test(value)) return value;
  throw new TypeError("Type cast failed: expected " + typeName);
}
function __dartRecord(positional, named) {
  const record = {};
  const shape = [];
  for (let i = 0; i < positional.length; i++) {
    const name = "$" + (i + 1);
    shape.push(name);
    Object.defineProperty(record, name, { value: positional[i], enumerable: true });
  }
  for (const name of Object.keys(named).sort()) {
    shape.push(name);
    Object.defineProperty(record, name, { value: named[name], enumerable: true });
  }
  Object.defineProperty(record, __dartRecordShape, { value: Object.freeze(shape) });
  Object.defineProperty(record, "toString", {
    value() {
      return "(" + shape.map((name) => {
        const value = String(record[name]);
        return name.startsWith("$") ? value : name + ": " + value;
      }).join(", ") + ")";
    },
  });
  return Object.freeze(record);
}

// Generated by dart2esm.

export function classify(value) {
  {
    const _0_0 = value;
    {
      let n = null;
      if (((typeof _0_0 === "number" && (() => { let v = n = _0_0; return true; })()) && (Math.trunc(n) % 2 === 0))) {
        {
          return "even " + __dartStr(n);
        }
      }
    }
  }
  return (() => {
    let v = null;
    const _1_0 = value;
    let _1_2 = null;
    let _1_2_isSet = false;
    let _1_3 = null;
    let _1_3_isSet = false;
    L:
    {
      {
        let s = null;
        if (typeof _1_0 === "string") {
          {
            s = _1_0;
            v = "string " + __dartStr(s);
            break L;
          }
        }
      }
      {
        let a = null;
        let b = null;
        if (((__dartIsRecord(_1_0) && _1_0[__dartRecordShape].length === 2 && _1_0[__dartRecordShape][0] === "$1" && _1_0[__dartRecordShape][1] === "$2" && (_1_0.$1 === null || _1_0.$1 != null) && (_1_0.$2 === null || _1_0.$2 != null) && (typeof (_1_2_isSet ? _1_2 : (() => { let v_1 = _1_2_isSet = true; return _1_2 = _1_0.$1; })()) === "number" && (() => { let v_2 = a = __dartAs((_1_2_isSet ? _1_2 : (() => { let v_3 = _1_2_isSet = true; return _1_2 = _1_0.$1; })()), value => typeof value === "number", "int"); return true; })())) && typeof (_1_3_isSet ? _1_3 : (() => { let v_4 = _1_3_isSet = true; return _1_3 = _1_0.$2; })()) === "number")) {
          {
            b = __dartAs((_1_3_isSet ? _1_3 : (() => { let v_5 = _1_3_isSet = true; return _1_3 = _1_0.$2; })()), value => typeof value === "number", "int");
            v = "record " + __dartStr((a + b));
            break L;
          }
        }
      }
      {
        if (true) {
          {
            v = "other";
            break L;
          }
        }
      }
    }
    return v;
  })();
}

export function main() {
  let first = null;
  let second = null;
  {
    const _0_0 = __dartRecord([1, 2], {});
    first = _0_0.$1;
    second = _0_0.$2;
  }
  __dartPrint("destructure " + __dartStr(first) + " " + __dartStr(second));
  __dartPrint(classify(4));
  __dartPrint(classify("dart"));
  __dartPrint(classify(__dartRecord([2, 3], {})));
  __dartPrint(classify(true));
}

main();
