const __dartRecordShape = Symbol("dart.recordShape");
function __dartIsRecord(value) {
  return value != null && typeof value === "object" && Array.isArray(value[__dartRecordShape]);
}
function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartAs(value, test, typeName) {
  if (test(value)) return value;
  throw new TypeError("Type cast failed: expected " + typeName);
}
function __dartIndexGet(receiver, index) {
  if (Array.isArray(receiver) || (ArrayBuffer.isView(receiver) && !(receiver instanceof DataView)) || typeof receiver === "string") return receiver[index];
  const op = receiver?.["[]"];
  if (typeof op === "function") return op.call(receiver, index);
  return receiver[index];
}
function __dartCompare(left, right, compare = null) {
  if (typeof compare === "function") return Number(compare(left, right));
  const compareTo = left?.compareTo;
  if (typeof compareTo === "function") return Number(compareTo.call(left, right));
  return left < right ? -1 : (left > right ? 1 : 0);
}
const __dartMapMissingKey = Symbol("dart.mapMissingKey");
function __dartMapKey(map, key) {
  if (map.__dartIdentityMap) return map.has(key) ? key : __dartMapMissingKey;
  if (map.__dartMapEquals != null) {
    if (map.__dartMapIsValidKey != null && !map.__dartMapIsValidKey(key)) return __dartMapMissingKey;
    for (const candidate of map.keys()) {
      if (map.__dartMapEquals(candidate, key)) return candidate;
    }
    return __dartMapMissingKey;
  }
  if (map.__dartSplayCompare !== undefined) {
    for (const candidate of map.keys()) {
      if (__dartCompare(candidate, key, map.__dartSplayCompare) === 0) return candidate;
    }
    return __dartMapMissingKey;
  }
  for (const candidate of map.keys()) {
    if (__dartEquals(candidate, key)) return candidate;
  }
  return __dartMapMissingKey;
}
function __dartMapContainsKey(map, key) {
  if (!(map instanceof Map) && map != null && typeof map.containsKey === "function") return map.containsKey(key);
  return __dartMapKey(map, key) !== __dartMapMissingKey;
}
function __dartMapGet(map, key) {
  if (!(map instanceof Map) && map != null && typeof map["[]"] === "function") return map["[]"](key);
  const actualKey = __dartMapKey(map, key);
  return actualKey === __dartMapMissingKey ? null : map.get(actualKey);
}
function __dartEquals(left, right) {
  if (left === right) return true;
  if (left == null || right == null) return false;
  if ((typeof left === "number" || left.__dartType === "double") && (typeof right === "number" || right.__dartType === "double")) return Number(left) === Number(right);
  if (__dartIsRecord(left) && __dartIsRecord(right)) {
    const leftShape = left[__dartRecordShape];
    const rightShape = right[__dartRecordShape];
    if (leftShape.length !== rightShape.length) return false;
    for (let i = 0; i < leftShape.length; i++) {
      const name = leftShape[i];
      if (name !== rightShape[i]) return false;
      if (!__dartEquals(left[name], right[name])) return false;
    }
    return true;
  }
  const equals = left["=="];
  return typeof equals === "function" ? equals.call(left, right) : false;
}
function __dartRecord(positional, named) {
  const record = {};
  const shape = [];
  for (let i = 0; i < positional.length; i++) {
    const name = "$" + (i + 1);
    shape.push(name);
    Object.defineProperty(record, name, { value: positional[i], enumerable: true });
  }
  for (const name of Object.keys(named).sort()) {
    shape.push(name);
    Object.defineProperty(record, name, { value: named[name], enumerable: true });
  }
  Object.defineProperty(record, __dartRecordShape, { value: Object.freeze(shape) });
  Object.defineProperty(record, "toString", {
    value() {
      return "(" + shape.map((name) => {
        const value = String(record[name]);
        return name.startsWith("$") ? value : name + ": " + value;
      }).join(", ") + ")";
    },
  });
  return Object.freeze(record);
}
const __dartConstValues = new Map();
function __dartConst(key, create) {
  if (!__dartConstValues.has(key)) {
    __dartConstValues.set(key, create());
  }
  return __dartConstValues.get(key);
}

// Generated by dart2esm.

export class Pair {
  constructor(left, right) {
    this.left = left;
    this.right = right;
  }
}

export function classify(value) {
  {
    const _0_0 = value;
    {
      let n = null;
      if (((typeof _0_0 === "number" && (() => { let v = n = _0_0; return true; })()) && (Math.trunc(n) % 2 === 0))) {
        {
          return "even " + __dartStr(n);
        }
      }
    }
  }
  return (() => {
    let v = null;
    const _1_0 = value;
    let _1_2 = null;
    let _1_2_isSet = false;
    let _1_3 = null;
    let _1_3_isSet = false;
    L:
    {
      {
        let s = null;
        if (typeof _1_0 === "string") {
          {
            s = _1_0;
            v = "string " + __dartStr(s);
            break L;
          }
        }
      }
      {
        let a = null;
        let b = null;
        if (((__dartIsRecord(_1_0) && _1_0[__dartRecordShape].length === 2 && _1_0[__dartRecordShape][0] === "$1" && _1_0[__dartRecordShape][1] === "$2" && (_1_0.$1 === null || _1_0.$1 != null) && (_1_0.$2 === null || _1_0.$2 != null) && (typeof (_1_2_isSet ? _1_2 : (() => { let v_1 = _1_2_isSet = true; return _1_2 = _1_0.$1; })()) === "number" && (() => { let v_2 = a = __dartAs((_1_2_isSet ? _1_2 : (() => { let v_3 = _1_2_isSet = true; return _1_2 = _1_0.$1; })()), value => typeof value === "number", "int"); return true; })())) && typeof (_1_3_isSet ? _1_3 : (() => { let v_4 = _1_3_isSet = true; return _1_3 = _1_0.$2; })()) === "number")) {
          {
            b = __dartAs((_1_3_isSet ? _1_3 : (() => { let v_5 = _1_3_isSet = true; return _1_3 = _1_0.$2; })()), value => typeof value === "number", "int");
            v = "record " + __dartStr((a + b));
            break L;
          }
        }
      }
      {
        if (true) {
          {
            v = "other";
            break L;
          }
        }
      }
    }
    return v;
  })();
}

export function shape(value) {
  return (() => {
    let v = null;
    const _0_0 = value;
    const _0_3 = 2;
    let _0_6 = null;
    let _0_6_isSet = false;
    let _0_7 = null;
    let _0_7_isSet = false;
    let _0_11 = null;
    let _0_11_isSet = false;
    const _0_9 = "name";
    let _0_14 = null;
    let _0_14_isSet = false;
    const _0_12 = "age";
    const _0_19 = 0;
    const _0_21 = 10;
    const _0_23 = null;
    L:
    {
      {
        let first = null;
        let second = null;
        if (((((Array.isArray(_0_0) || (ArrayBuffer.isView(_0_0) && !(_0_0 instanceof DataView))) && __dartEquals(_0_0.length, 2)) && (typeof (_0_6_isSet ? _0_6 : (() => { let v_1 = _0_6_isSet = true; return _0_6 = __dartIndexGet(_0_0, 0); })()) === "number" && (() => { let v_2 = first = __dartAs((_0_6_isSet ? _0_6 : (() => { let v_3 = _0_6_isSet = true; return _0_6 = __dartIndexGet(_0_0, 0); })()), value => typeof value === "number", "int"); return true; })())) && typeof (_0_7_isSet ? _0_7 : (() => { let v_4 = _0_7_isSet = true; return _0_7 = __dartIndexGet(_0_0, 1); })()) === "number")) {
          {
            second = __dartAs((_0_7_isSet ? _0_7 : (() => { let v_5 = _0_7_isSet = true; return _0_7 = __dartIndexGet(_0_0, 1); })()), value => typeof value === "number", "int");
            v = "list " + __dartStr((first + second));
            break L;
          }
        }
      }
      {
        let name = null;
        let age = null;
        if (((((_0_0 instanceof Map && (!(((_0_11_isSet ? _0_11 : (() => { let v_6 = _0_11_isSet = true; return _0_11 = __dartMapGet(_0_0, "name"); })()) === null)) || ((null === null || null != null) && __dartMapContainsKey(_0_0, "name")))) && (typeof (_0_11_isSet ? _0_11 : (() => { let v_7 = _0_11_isSet = true; return _0_11 = __dartMapGet(_0_0, "name"); })()) === "string" && (() => { let v_8 = name = __dartAs((_0_11_isSet ? _0_11 : (() => { let v_9 = _0_11_isSet = true; return _0_11 = __dartMapGet(_0_0, "name"); })()), value => typeof value === "string", "String"); return true; })())) && (!(((_0_14_isSet ? _0_14 : (() => { let v_10 = _0_14_isSet = true; return _0_14 = __dartMapGet(_0_0, "age"); })()) === null)) || ((null === null || null != null) && __dartMapContainsKey(_0_0, "age")))) && typeof (_0_14_isSet ? _0_14 : (() => { let v_11 = _0_14_isSet = true; return _0_14 = __dartMapGet(_0_0, "age"); })()) === "number")) {
          {
            age = __dartAs((_0_14_isSet ? _0_14 : (() => { let v_12 = _0_14_isSet = true; return _0_14 = __dartMapGet(_0_0, "age"); })()), value => typeof value === "number", "int");
            v = "map " + __dartStr(name) + " " + __dartStr(age);
            break L;
          }
        }
      }
      {
        let left = null;
        let right = null;
        if ((((_0_0 instanceof Pair && (() => { let v_13 = left = _0_0.left; return true; })()) && (() => { let v_14 = right = _0_0.right; return true; })()) && (left < right))) {
          {
            v = "pair " + __dartStr(left) + " " + __dartStr(right);
            break L;
          }
        }
      }
      {
        if (((typeof _0_0 === "number" && (_0_0 > 0)) && (_0_0 < 10))) {
          {
            v = "small number " + __dartStr(value);
            break L;
          }
        }
      }
      {
        if ((_0_0 === null)) {
          {
            v = "null";
            break L;
          }
        }
      }
      {
        if (true) {
          {
            v = "unknown";
            break L;
          }
        }
      }
    }
    return v;
  })();
}

export function main() {
  let first = null;
  let second = null;
  {
    const _0_0 = __dartRecord([1, 2], {});
    first = _0_0.$1;
    second = _0_0.$2;
  }
  __dartPrint("destructure " + __dartStr(first) + " " + __dartStr(second));
  __dartPrint(classify(4));
  __dartPrint(classify("dart"));
  __dartPrint(classify(__dartRecord([2, 3], {})));
  __dartPrint(classify(true));
  __dartPrint(shape([3, 4]));
  __dartPrint(shape(new Map([["name", "Ada"], ["age", 37]])));
  __dartPrint(shape(__dartConst("[\"instance\",\"class:Pair\",[\"field\",\"field:Pair.left\",[\"int\",\"1\"]],[\"field\",\"field:Pair.right\",[\"int\",\"2\"]]]", () => Object.freeze(Object.assign(Object.create(Pair.prototype), { left: 1, right: 2 })))));
  __dartPrint(shape(5));
  __dartPrint(shape(null));
  __dartPrint(shape("x"));
}

main();
