const __dartRecordShape = Symbol("dart.recordShape");
function __dartIsRecord(value) {
  return value != null && typeof value === "object" && Array.isArray(value[__dartRecordShape]);
}
function __dartStr(value) {
  if (value == null) return "null";
  if (Array.isArray(value)) {
    return "[" + value.map(__dartStr).join(", ") + "]";
  }
  if (value instanceof Set) {
    return "{" + Array.from(value).map(__dartStr).join(", ") + "}";
  }
  if (value instanceof Map) {
    return "{" + Array.from(value, ([key, entryValue]) => __dartStr(key) + ": " + __dartStr(entryValue)).join(", ") + "}";
  }
  if (typeof value === "object") {
    const toString = value.toString;
    if (typeof toString === "function" && toString !== Object.prototype.toString) {
      return String(toString.call(value));
    }
  }
  return String(value);
}
function __dartPrint(value) {
  console.log(__dartStr(value));
}
function __dartSetAdd(set, value) {
  const hadValue = set.has(value);
  set.add(value);
  return !hadValue;
}
function __dartRecord(positional, named) {
  const record = {};
  const shape = [];
  for (let i = 0; i < positional.length; i++) {
    const name = "$" + (i + 1);
    shape.push(name);
    Object.defineProperty(record, name, { value: positional[i], enumerable: true });
  }
  for (const name of Object.keys(named).sort()) {
    shape.push(name);
    Object.defineProperty(record, name, { value: named[name], enumerable: true });
  }
  Object.defineProperty(record, __dartRecordShape, { value: Object.freeze(shape) });
  Object.defineProperty(record, "toString", {
    value() {
      return "(" + shape.map((name) => {
        const value = String(record[name]);
        return name.startsWith("$") ? value : name + ": " + value;
      }).join(", ") + ")";
    },
  });
  return Object.freeze(record);
}

// Generated by dart2esm.

export function flags(value) {
  return __dartStr(value != null) + " " + __dartStr(value != null && typeof value !== "string" && !(value instanceof Map) && typeof value[Symbol.iterator] === "function") + " " + __dartStr((Array.isArray(value) || (ArrayBuffer.isView(value) && !(value instanceof DataView)))) + " " + __dartStr(value instanceof Set) + " " + __dartStr(value instanceof Map) + " " + __dartStr(typeof value === "function") + " " + __dartStr(__dartIsRecord(value)) + " " + __dartStr((value === null || typeof value === "string")) + " " + __dartStr(!(typeof value === "string"));
}

export function recordFlags(value) {
  return __dartStr(__dartIsRecord(value) && value[__dartRecordShape].length === 2 && value[__dartRecordShape][0] === "$1" && value[__dartRecordShape][1] === "label" && typeof value.$1 === "number" && typeof value.label === "string") + " " + __dartStr(__dartIsRecord(value) && value[__dartRecordShape].length === 2 && value[__dartRecordShape][0] === "$1" && value[__dartRecordShape][1] === "label" && typeof value.$1 === "string" && typeof value.label === "string") + " " + __dartStr(__dartIsRecord(value) && value[__dartRecordShape].length === 2 && value[__dartRecordShape][0] === "$1" && value[__dartRecordShape][1] === "other" && typeof value.$1 === "number" && typeof value.other === "string") + " " + __dartStr(__dartIsRecord(value) && value[__dartRecordShape].length === 2 && value[__dartRecordShape][0] === "$1" && value[__dartRecordShape][1] === "$2" && typeof value.$1 === "number" && typeof value.$2 === "number") + " " + __dartStr((value === null || __dartIsRecord(value)));
}

export function main() {
  __dartPrint(flags([1, 2]));
  __dartPrint(flags((() => {
    const v = new Set();
    __dartSetAdd(v, 1);
    __dartSetAdd(v, 2);
    return v;
  })()));
  __dartPrint(flags(new Map([["a", 1]])));
  __dartPrint(flags(function() { return 1; }));
  __dartPrint(flags(__dartRecord([1], { label: "one" })));
  __dartPrint(flags("x"));
  __dartPrint(flags(null));
  __dartPrint(recordFlags(__dartRecord([1], { label: "one" })));
  __dartPrint(recordFlags(null));
  __dartPrint(recordFlags([1]));
}

main();
