import 'dart:convert';

import '../ast/esm_ast.dart';

final class CodegenReturn {
  const CodegenReturn({required this.code, required this.diagnostics});

  final String code;
  final List<String> diagnostics;
}

final class Codegen {
  const Codegen();

  CodegenReturn generate(EsmModule module) {
    final printer = _EsmPrinter();
    return CodegenReturn(code: printer.print(module), diagnostics: const []);
  }
}

final class _EsmPrinter {
  final _buffer = StringBuffer();
  var _indent = 0;

  String print(EsmModule module) {
    _buffer.writeln('// Generated by dart2esm.');
    _buffer.writeln();
    for (var i = 0; i < module.items.length; i++) {
      _emitModuleItem(module.items[i]);
      if (i != module.items.length - 1 &&
          _needsBlankLineAfter(module.items[i])) {
        _buffer.writeln();
      }
    }
    return _buffer.toString();
  }

  bool _needsBlankLineAfter(EsmModuleItem item) {
    return item is EsmRawModuleItem || item is EsmClass || item is EsmFunction;
  }

  void _emitModuleItem(EsmModuleItem item) {
    switch (item) {
      case EsmRawModuleItem():
        _writeIndented(item.source.trimRight());
      case EsmClass():
        _emitClass(item);
      case EsmFunction():
        _emitFunction(item);
      case EsmStatement():
        _emitStatement(item);
    }
  }

  void _emitClass(EsmClass klass) {
    final exportPrefix = klass.export ? 'export ' : '';
    final superclass = klass.superclass == null
        ? ''
        : ' extends ${_emitExpression(klass.superclass!)}';
    _writeIndented('${exportPrefix}class ${klass.name}$superclass {');
    _indent++;
    final constructor = klass.constructor;
    if (constructor != null) {
      _writeIndented(
        'constructor(${constructor.parameters.map(_emitParameter).join(', ')}) {',
      );
      _indent++;
      for (final statement in constructor.body) {
        _emitStatement(statement);
      }
      _indent--;
      _writeIndented('}');
    }
    for (final method in klass.methods) {
      _emitClassMethod(method);
    }
    _indent--;
    _writeIndented('}');
  }

  void _emitClassMethod(EsmClassMethod method) {
    final staticPrefix = method.isStatic ? 'static ' : '';
    final prefix = switch (method.kind) {
      EsmClassMethodKind.method => '',
      EsmClassMethodKind.getter => 'get ',
      EsmClassMethodKind.setter => 'set ',
    };
    _writeIndented(
      '$staticPrefix$prefix${_emitPropertyKey(method.key)}(${method.parameters.map(_emitParameter).join(', ')}) {',
    );
    _indent++;
    for (final statement in method.body) {
      _emitStatement(statement);
    }
    _indent--;
    _writeIndented('}');
  }

  void _emitFunction(EsmFunction function) {
    final exportPrefix = function.export ? 'export ' : '';
    _writeIndented(
      '${exportPrefix}function ${function.name}(${function.parameters.map(_emitParameter).join(', ')}) {',
    );
    _indent++;
    for (final statement in function.body) {
      _emitStatement(statement);
    }
    _indent--;
    _writeIndented('}');
  }

  void _emitStatement(EsmStatement statement) {
    switch (statement) {
      case EsmExpressionStatement():
        _writeIndented('${_emitExpression(statement.expression)};');
      case EsmBlockStatement():
        _emitBlockStatement(statement);
      case EsmLabeledStatement():
        _emitLabeledStatement(statement);
      case EsmBreakStatement():
        final label = statement.label;
        _writeIndented(label == null ? 'break;' : 'break $label;');
      case EsmContinueStatement():
        final label = statement.label;
        _writeIndented(label == null ? 'continue;' : 'continue $label;');
      case EsmVariableDeclaration():
        final keyword = statement.mutable ? 'let' : 'const';
        final exportPrefix = statement.export ? 'export ' : '';
        final initializer = statement.initializer;
        final binding = _emitBinding(statement.binding);
        _writeIndented(
          initializer == null
              ? '$exportPrefix$keyword $binding;'
              : '$exportPrefix$keyword $binding = ${_emitExpression(initializer)};',
        );
      case EsmIfStatement():
        _emitIfStatement(statement);
      case EsmWhileStatement():
        _emitWhileStatement(statement);
      case EsmDoStatement():
        _emitDoStatement(statement);
      case EsmSwitchStatement():
        _emitSwitchStatement(statement);
      case EsmForStatement():
        _emitForStatement(statement);
      case EsmReturnStatement():
        final expression = statement.expression;
        _writeIndented(
          expression == null
              ? 'return;'
              : 'return ${_emitExpression(expression)};',
        );
      case EsmThrowStatement():
        _writeIndented('throw ${_emitExpression(statement.expression)};');
      case EsmTryStatement():
        _emitTryStatement(statement);
    }
  }

  void _emitBlockStatement(EsmBlockStatement statement) {
    _writeIndented('{');
    _indent++;
    for (final child in statement.body) {
      _emitStatement(child);
    }
    _indent--;
    _writeIndented('}');
  }

  void _emitLabeledStatement(EsmLabeledStatement statement) {
    final body = statement.statement;
    if (body is EsmBlockStatement) {
      _writeIndented('${statement.label}: {');
      _indent++;
      for (final child in body.body) {
        _emitStatement(child);
      }
      _indent--;
      _writeIndented('}');
      return;
    }
    if (body is EsmWhileStatement) {
      _emitWhileStatement(body, label: statement.label);
      return;
    }
    _writeIndented('${statement.label}:');
    _indent++;
    _emitStatement(body);
    _indent--;
  }

  void _emitIfStatement(EsmIfStatement statement) {
    _writeIndented('if (${_emitExpression(statement.condition)}) {');
    _indent++;
    for (final child in statement.thenBody) {
      _emitStatement(child);
    }
    _indent--;
    final otherwiseBody = statement.otherwiseBody;
    if (otherwiseBody == null) {
      _writeIndented('}');
      return;
    }
    _writeIndented('} else {');
    _indent++;
    for (final child in otherwiseBody) {
      _emitStatement(child);
    }
    _indent--;
    _writeIndented('}');
  }

  void _emitWhileStatement(EsmWhileStatement statement, {String? label}) {
    final prefix = label == null ? '' : '$label: ';
    _writeIndented(
      '${prefix}while (${_emitExpression(statement.condition)}) {',
    );
    _indent++;
    for (final child in statement.body) {
      _emitStatement(child);
    }
    _indent--;
    _writeIndented('}');
  }

  void _emitDoStatement(EsmDoStatement statement) {
    _writeIndented('do {');
    _indent++;
    for (final child in statement.body) {
      _emitStatement(child);
    }
    _indent--;
    _writeIndented('} while (${_emitExpression(statement.condition)});');
  }

  void _emitSwitchStatement(EsmSwitchStatement statement) {
    _writeIndented('switch (${_emitExpression(statement.expression)}) {');
    _indent++;
    for (final switchCase in statement.cases) {
      _emitSwitchCase(switchCase);
    }
    _indent--;
    _writeIndented('}');
  }

  void _emitSwitchCase(EsmSwitchCase switchCase) {
    for (final expression in switchCase.expressions) {
      _writeIndented('case ${_emitExpression(expression)}:');
    }
    if (switchCase.isDefault) {
      _writeIndented('default:');
    }
    _indent++;
    for (final child in switchCase.body) {
      _emitStatement(child);
    }
    _indent--;
  }

  void _emitTryStatement(EsmTryStatement statement) {
    _writeIndented('try {');
    _indent++;
    for (final child in statement.body) {
      _emitStatement(child);
    }
    _indent--;
    final catchBody = statement.catchBody;
    final finallyBody = statement.finallyBody;
    if (catchBody != null) {
      final catchParameter = statement.catchParameter;
      _writeIndented(
        catchParameter == null
            ? '} catch {'
            : '} catch (${_emitBindingPattern(catchParameter)}) {',
      );
      _indent++;
      for (final child in catchBody) {
        _emitStatement(child);
      }
      _indent--;
    }
    if (finallyBody != null) {
      _writeIndented('} finally {');
      _indent++;
      for (final child in finallyBody) {
        _emitStatement(child);
      }
      _indent--;
    }
    _writeIndented('}');
  }

  void _emitForStatement(EsmForStatement statement) {
    final initializer = _emitForInitializer(statement.initializers);
    final condition = statement.condition == null
        ? ''
        : _emitExpression(statement.condition!);
    final updates = statement.updates.map(_emitExpression).join(', ');
    _writeIndented('for ($initializer; $condition; $updates) {');
    _indent++;
    for (final child in statement.body) {
      _emitStatement(child);
    }
    _indent--;
    _writeIndented('}');
  }

  String _emitForInitializer(List<EsmVariableDeclaration> initializers) {
    if (initializers.isEmpty) {
      return '';
    }
    final mutable = initializers.first.mutable;
    final keyword = mutable ? 'let' : 'const';
    return '$keyword ${initializers.map(_emitForInitializerBinding).join(', ')}';
  }

  String _emitForInitializerBinding(EsmVariableDeclaration initializer) {
    final value = initializer.initializer;
    final binding = _emitBinding(initializer.binding);
    return value == null ? binding : '$binding = ${_emitExpression(value)}';
  }

  String _emitBinding(EsmBinding binding) {
    return switch (binding) {
      EsmIdentifierBinding() => binding.name,
      EsmObjectBindingPattern() =>
        '{ ${binding.bindings.map(_emitObjectPatternBinding).join(', ')} }',
      EsmArrayBindingPattern() =>
        '[${binding.elements.map(_emitBinding).join(', ')}]',
    };
  }

  String _emitParameter(EsmParameter parameter) {
    return switch (parameter) {
      EsmIdentifierParameter() =>
        parameter.defaultValue == null
            ? parameter.name
            : '${_emitBindingPattern(parameter)} = ${_emitExpression(parameter.defaultValue!)}',
      EsmObjectPatternParameter() => '${_emitBindingPattern(parameter)} = {}',
      EsmArrayPatternParameter() => _emitBindingPattern(parameter),
    };
  }

  String _emitBindingPattern(EsmParameter parameter) {
    return switch (parameter) {
      EsmIdentifierParameter() => parameter.name,
      EsmObjectPatternParameter() =>
        '{ ${parameter.bindings.map(_emitObjectPatternBinding).join(', ')} }',
      EsmArrayPatternParameter() =>
        '[${parameter.elements.map(_emitBindingPattern).join(', ')}]',
    };
  }

  String _emitObjectPatternBinding(EsmObjectPatternBinding binding) {
    final property = _emitObjectPropertyName(binding.property);
    final name = binding.property == binding.name ? '' : ': ${binding.name}';
    final defaultValue = binding.defaultValue == null
        ? ''
        : ' = ${_emitExpression(binding.defaultValue!)}';
    return '$property$name$defaultValue';
  }

  String _emitExpression(EsmExpression expression) {
    return switch (expression) {
      EsmIdentifier() => expression.name,
      EsmImportMeta() => 'import.meta',
      EsmStringLiteral() => jsonEncode(expression.value),
      EsmStringConcatenation() => _emitStringConcatenation(expression),
      EsmAssignment() =>
        '${_emitExpression(expression.target)} = ${_emitExpression(expression.value)}',
      EsmBinary() => _emitBinaryExpression(expression),
      EsmUnary() => _emitUnaryExpression(expression),
      EsmConditional() =>
        '(${_emitExpression(expression.condition)} ? ${_emitExpression(expression.thenExpression)} : ${_emitExpression(expression.otherwiseExpression)})',
      EsmNullishCoalesce() =>
        '(${_emitNullishOperand(expression.left)} ?? ${_emitNullishOperand(expression.right)})',
      EsmParenthesized() => '(${_emitExpression(expression.expression)})',
      EsmNumberLiteral() => _emitNumber(expression.value),
      EsmBooleanLiteral() => expression.value ? 'true' : 'false',
      EsmNullLiteral() => 'null',
      EsmArrayLiteral() =>
        '[${expression.elements.map(_emitExpression).join(', ')}]',
      EsmObjectLiteral() =>
        '{ ${expression.properties.map(_emitObjectLiteralProperty).join(', ')} }',
      EsmArrowFunction() =>
        '(${expression.parameters.map(_emitParameter).join(', ')}) => ${_emitExpression(expression.body)}',
      EsmFunctionExpression() => _emitFunctionExpression(expression),
      EsmArrowBlockFunction() => _emitArrowBlockFunction(expression),
      EsmCall() =>
        '${_emitCallCallee(expression.callee)}(${expression.arguments.map(_emitExpression).join(', ')})',
      EsmNew() =>
        'new ${_emitExpression(expression.callee)}(${expression.arguments.map(_emitExpression).join(', ')})',
      EsmPropertyAccess() =>
        '${_emitExpression(expression.receiver)}.${expression.property}',
      EsmComputedPropertyAccess() =>
        '${_emitExpression(expression.receiver)}[${_emitExpression(expression.property)}]',
      EsmOptionalPropertyAccess() =>
        '${_emitExpression(expression.receiver)}?.${expression.property}',
      EsmOptionalMethodCall() =>
        '${_emitExpression(expression.receiver)}?.${expression.property}(${expression.arguments.map(_emitExpression).join(', ')})',
      EsmThis() => 'this',
      EsmNewTarget() => 'new.target',
      EsmSuper() => 'super',
    };
  }

  String _emitBinaryExpression(EsmBinary expression) {
    final left = _emitBinaryOperand(
      expression.left,
      expression.operator,
      isRight: false,
    );
    final right = _emitBinaryOperand(
      expression.right,
      expression.operator,
      isRight: true,
    );
    return '$left ${_emitBinaryOperator(expression.operator)} $right';
  }

  String _emitBinaryOperand(
    EsmExpression operand,
    EsmBinaryOperator parentOperator, {
    required bool isRight,
  }) {
    final text = _emitExpression(operand);
    if (operand case EsmBinary(:final operator)) {
      final operandPrecedence = _binaryPrecedence(operator);
      final parentPrecedence = _binaryPrecedence(parentOperator);
      if (operandPrecedence < parentPrecedence ||
          (isRight &&
              operandPrecedence == parentPrecedence &&
              !_canFlattenRightBinary(parentOperator, operator))) {
        return '($text)';
      }
    }
    return text;
  }

  String _emitBinaryOperator(EsmBinaryOperator operator) {
    return switch (operator) {
      EsmBinaryOperator.multiply => '*',
      EsmBinaryOperator.divide => '/',
      EsmBinaryOperator.remainder => '%',
      EsmBinaryOperator.add => '+',
      EsmBinaryOperator.subtract => '-',
      EsmBinaryOperator.leftShift => '<<',
      EsmBinaryOperator.signedRightShift => '>>',
      EsmBinaryOperator.unsignedRightShift => '>>>',
      EsmBinaryOperator.lessThan => '<',
      EsmBinaryOperator.lessThanOrEqual => '<=',
      EsmBinaryOperator.greaterThan => '>',
      EsmBinaryOperator.greaterThanOrEqual => '>=',
      EsmBinaryOperator.instanceOf => 'instanceof',
      EsmBinaryOperator.inOperator => 'in',
      EsmBinaryOperator.looseEquals => '==',
      EsmBinaryOperator.looseNotEquals => '!=',
      EsmBinaryOperator.strictEquals => '===',
      EsmBinaryOperator.strictNotEquals => '!==',
      EsmBinaryOperator.bitAnd => '&',
      EsmBinaryOperator.bitXor => '^',
      EsmBinaryOperator.bitOr => '|',
      EsmBinaryOperator.logicalAnd => '&&',
      EsmBinaryOperator.logicalOr => '||',
    };
  }

  int _binaryPrecedence(EsmBinaryOperator operator) {
    return switch (operator) {
      EsmBinaryOperator.multiply ||
      EsmBinaryOperator.divide ||
      EsmBinaryOperator.remainder => 12,
      EsmBinaryOperator.add || EsmBinaryOperator.subtract => 11,
      EsmBinaryOperator.leftShift ||
      EsmBinaryOperator.signedRightShift ||
      EsmBinaryOperator.unsignedRightShift => 10,
      EsmBinaryOperator.lessThan ||
      EsmBinaryOperator.lessThanOrEqual ||
      EsmBinaryOperator.greaterThan ||
      EsmBinaryOperator.greaterThanOrEqual ||
      EsmBinaryOperator.instanceOf ||
      EsmBinaryOperator.inOperator => 9,
      EsmBinaryOperator.looseEquals ||
      EsmBinaryOperator.looseNotEquals ||
      EsmBinaryOperator.strictEquals ||
      EsmBinaryOperator.strictNotEquals => 8,
      EsmBinaryOperator.bitAnd => 7,
      EsmBinaryOperator.bitXor => 6,
      EsmBinaryOperator.bitOr => 5,
      EsmBinaryOperator.logicalAnd => 4,
      EsmBinaryOperator.logicalOr => 3,
    };
  }

  bool _canFlattenRightBinary(
    EsmBinaryOperator parentOperator,
    EsmBinaryOperator childOperator,
  ) {
    return parentOperator == childOperator &&
        (parentOperator == EsmBinaryOperator.multiply ||
            parentOperator == EsmBinaryOperator.logicalAnd ||
            parentOperator == EsmBinaryOperator.logicalOr ||
            parentOperator == EsmBinaryOperator.bitAnd ||
            parentOperator == EsmBinaryOperator.bitXor ||
            parentOperator == EsmBinaryOperator.bitOr);
  }

  String _emitUnaryExpression(EsmUnary expression) {
    final operand = _emitUnaryOperand(expression.operand);
    return switch (expression.operator) {
      EsmUnaryOperator.logicalNot => '!$operand',
      EsmUnaryOperator.negate => '-$operand',
      EsmUnaryOperator.bitNot => '~$operand',
      EsmUnaryOperator.typeOf => 'typeof $operand',
    };
  }

  String _emitCallCallee(EsmExpression expression) {
    return switch (expression) {
      EsmIdentifier() ||
      EsmImportMeta() ||
      EsmPropertyAccess() ||
      EsmComputedPropertyAccess() ||
      EsmOptionalPropertyAccess() ||
      EsmOptionalMethodCall() ||
      EsmCall() ||
      EsmNew() ||
      EsmThis() ||
      EsmSuper() ||
      EsmParenthesized() => _emitExpression(expression),
      _ => '(${_emitExpression(expression)})',
    };
  }

  String _emitUnaryOperand(EsmExpression expression) {
    return switch (expression) {
      EsmBinary() ||
      EsmAssignment() ||
      EsmConditional() => '(${_emitExpression(expression)})',
      _ => _emitExpression(expression),
    };
  }

  String _emitNullishOperand(EsmExpression expression) {
    return switch (expression) {
      EsmArrowFunction() ||
      EsmAssignment() ||
      EsmConditional() ||
      EsmNullishCoalesce() => '(${_emitExpression(expression)})',
      _ => _emitExpression(expression),
    };
  }

  String _emitObjectLiteralProperty(EsmObjectLiteralProperty property) {
    return '${_emitPropertyKey(property.key)}: ${_emitExpression(property.value)}';
  }

  String _emitPropertyKey(EsmPropertyKey key) {
    return switch (key) {
      EsmStaticPropertyKey() => _emitObjectPropertyName(key.value),
      EsmComputedPropertyKey() => '[${_emitExpression(key.expression)}]',
    };
  }

  String _emitFunctionExpression(EsmFunctionExpression expression) {
    final parameters = expression.parameters.map(_emitParameter).join(', ');
    if (expression.body.isEmpty) {
      return 'function($parameters) {}';
    }
    final bodyPrinter = _EsmPrinter().._indent = _indent + 1;
    for (final statement in expression.body) {
      bodyPrinter._emitStatement(statement);
    }
    final body = bodyPrinter._buffer.toString().trimRight();
    return 'function($parameters) {\n$body\n${'  ' * _indent}}';
  }

  String _emitArrowBlockFunction(EsmArrowBlockFunction expression) {
    final parameters = expression.parameters.map(_emitParameter).join(', ');
    if (expression.body.isEmpty) {
      return '($parameters) => {}';
    }
    final bodyPrinter = _EsmPrinter().._indent = _indent + 1;
    for (final statement in expression.body) {
      bodyPrinter._emitStatement(statement);
    }
    final body = bodyPrinter._buffer.toString().trimRight();
    return '($parameters) => {\n$body\n${'  ' * _indent}}';
  }

  String _emitObjectPropertyName(String name) {
    return RegExp(r'^[A-Za-z_$][\w$]*$').hasMatch(name)
        ? name
        : jsonEncode(name);
  }

  String _emitStringConcatenation(EsmStringConcatenation expression) {
    if (expression.expressions.isEmpty) {
      return '""';
    }
    final buffer = StringBuffer('`');
    for (final part in expression.expressions) {
      if (part case EsmStringLiteral()) {
        buffer.write(_escapeTemplateText(part.value));
      } else {
        buffer.write(r'${');
        buffer.write(_emitExpression(part));
        buffer.write('}');
      }
    }
    buffer.write('`');
    return buffer.toString();
  }

  String _escapeTemplateText(String value) {
    return value
        .replaceAll(r'\', r'\\')
        .replaceAll('`', r'\`')
        .replaceAll(r'${', r'\${');
  }

  String _emitNumber(num value) {
    if (value.isNaN) {
      return 'NaN';
    }
    if (value == double.infinity) {
      return 'Infinity';
    }
    if (value == double.negativeInfinity) {
      return '-Infinity';
    }
    return value.toString();
  }

  void _writeIndented(String line) {
    _buffer.write('  ' * _indent);
    _buffer.writeln(line);
  }
}
