import 'dart:convert';

import '../ast/esm_ast.dart';

part 'module_printer.dart';
part 'statement_printer.dart';
part 'binding_printer.dart';
part 'expression_printer.dart';
part 'literal_printer.dart';

final class CodegenReturn {
  const CodegenReturn({required this.code, required this.diagnostics});

  final String code;
  final List<String> diagnostics;
}

final class Codegen {
  const Codegen();

  CodegenReturn generate(EsmModule module) {
    final printer = _EsmPrinter();
    return CodegenReturn(code: printer.print(module), diagnostics: const []);
  }
}

final class _EsmPrinter {
  final _buffer = StringBuffer();
  var _indent = 0;

  String print(EsmModule module) {
    _buffer.writeln('// Generated by dart2esm.');
    _buffer.writeln();
    for (var i = 0; i < module.items.length; i++) {
      _emitModuleItem(module.items[i]);
      if (i != module.items.length - 1 &&
          _needsBlankLineAfter(module.items[i])) {
        _buffer.writeln();
      }
    }
    return _buffer.toString();
  }

  void _writeIndented(String line) {
    _buffer.write('  ' * _indent);
    _buffer.writeln(line);
  }
}
